/* Hands-on code challenges for Python, SQL, C# and C++ (graded by actually running the learner's code).
   Each is inserted into its lesson just before the Output Rush game (or before the reward screen). */
const CHALLENGES={
/* ---------------- Python ---------------- */
py1:{title:"Your first program",body:`<p>Print ${C("Hello, TypeMonkey!")} on one line, then let Python work out ${C("6 * 7")} on the next.</p>`,
  start:`# your code here\n`,use:[[/print/,"Use print() to show things."],[/6\s*\*\s*7/,"Let Python do the math: print(6 * 7)"]],out:["Hello, TypeMonkey!","42"],
  hint:`print("Hello, TypeMonkey!")\nprint(6 * 7)`},
py2:{title:"Banana sharing",body:`<p>Split the bananas equally between the monkeys (whole bananas only). Store it in ${C("share")} and print it.</p>`,
  start:`bananas = 12\nmonkeys = 4\n# make share, then print it\n`,use:[[/share\s*=/,"Make a variable called share."],[/\/\//,"Use // for whole-number division."]],out:["3"],variants:[[/bananas = 12/,"bananas = 22",["5"]]],
  hint:`bananas = 12\nmonkeys = 4\nshare = bananas // monkeys\nprint(share)`},
py3:{title:"Level badge",body:`<p>Use an f-string to print ${C("Mo is on level 7")}.</p>`,
  start:`name = "Mo"\nlevel = 7\n# print it with an f-string\n`,use:[[/f["']/,"Put f before the quotes: f\"...\""]],out:["Mo is on level 7"],variants:[[/level = 7/,"level = 12",["Mo is on level 12"]]],
  hint:`name = "Mo"\nlevel = 7\nprint(f"{name} is on level {level}")`},
py4:{title:"Movie length",body:`<p>Turn minutes into hours and minutes, printed like ${C("2 h 15 min")}.</p>`,
  start:`minutes = 135\n# use // and %\n`,use:[[/\/\//,"Use // to get whole hours."],[/%/,"Use % to get the leftover minutes."]],out:["2 h 15 min"],variants:[[/minutes = 135/,"minutes = 61",["1 h 1 min"]]],
  hint:`minutes = 135\nhours = minutes // 60\nleft = minutes % 60\nprint(f"{hours} h {left} min")`},
py5:{title:"Ticket check",body:`<p>Print ${C("True")} only if ${C("age")} is 13 or more <b>and</b> ${C("has_ticket")} is True. Otherwise it should print False.</p>`,
  start:`age = 15\nhas_ticket = True\n# print the check\n`,use:[[/\band\b/,"Use and to need both things."]],out:["True"],variants:[[/age = 15/,"age = 10",["False"]],[/has_ticket = True/,"has_ticket = False",["False"]]],
  hint:`age = 15\nhas_ticket = True\nprint(age >= 13 and has_ticket)`},
py6:{title:"Weather report",body:`<p>Above 25 print ${C("Hot")}. From 10 to 25 print ${C("Nice")}. Below 10 print ${C("Cold")}. I'll test a few temperatures.</p>`,
  start:`temp = 30\n# if / elif / else\n`,use:[[/\bif\b/,"Use an if."],[/\belif\b/,"Use elif for the middle case."]],out:["Hot"],
  variants:[[/temp = 30/,"temp = 18",["Nice"]],[/temp = 30/,"temp = 3",["Cold"]],[/temp = 30/,"temp = 25",["Nice"]],[/temp = 30/,"temp = 10",["Nice"]]],
  hint:`temp = 30\nif temp > 25:\n    print("Hot")\nelif temp >= 10:\n    print("Nice")\nelse:\n    print("Cold")`},
py8:{title:"Times table",body:`<p>Use a ${C("for")} loop with ${C("range")} to print the 5 times table: 5, 10, 15, 20, 25 (one per line).</p>`,
  start:`# your loop here\n`,use:[[/for\s+\w+\s+in\s+range/,"Use for ... in range(...)."]],out:["5","10","15","20","25"],
  hint:`for i in range(1, 6):\n    print(i * 5)`},
py9:{title:"Keep doubling",body:`<p>Keep doubling ${C("n")} while it's under 50, then print it.</p>`,
  start:`n = 1\n# your while loop here\n`,use:[[/\bwhile\b/,"Use a while loop."]],out:["64"],variants:[[/n = 1\b/,"n = 3",["96"]]],
  hint:`n = 1\nwhile n < 50:\n    n *= 2\nprint(n)`},
py10:{title:"FizzBuzz yourself",body:`<p>Now write FizzBuzz from 1 to 15 on your own. No peeking (unless you need to!).</p>`,
  start:`for i in range(1, 16):\n    # your if / elif chain\n    pass\n`,use:[[/%/,"Use % to check multiples."]],out:["1","2","Fizz","4","Buzz","Fizz","7","8","Fizz","Buzz","11","Fizz","13","14","FizzBuzz"],
  hint:`for i in range(1, 16):\n    if i % 15 == 0:\n        print("FizzBuzz")\n    elif i % 3 == 0:\n        print("Fizz")\n    elif i % 5 == 0:\n        print("Buzz")\n    else:\n        print(i)`},
py11:{title:"Double it",body:`<p>Write a function ${C("double(n)")} that <b>returns</b> n times 2.</p>`,
  start:`# define double here\n\nprint(double(4))\nprint(double(10))\n`,use:[[/def\s+double\s*\(/,"Define it with def double(n):"],[/\breturn\b/,"Use return to hand back the answer."]],out:["8","20"],
  hint:`def double(n):\n    return n * 2\n\nprint(double(4))\nprint(double(10))`},
py12:{title:"Friendly greeter",body:`<p>Write ${C("greet(name, greeting=\"Hi\")")} that <b>returns</b> text like ${C("Hi, Ava!")}.</p>`,
  start:`# define greet here\n\nprint(greet("Ava"))\nprint(greet("Leo", "Yo"))\n`,use:[[/def\s+greet\s*\(\s*name\s*,\s*greeting\s*=\s*["']Hi["']\s*\)/,"Give greeting a default: def greet(name, greeting=\"Hi\"):"],[/\breturn\b/,"Return the text instead of printing it."]],out:["Hi, Ava!","Yo, Leo!"],
  hint:`def greet(name, greeting="Hi"):\n    return f"{greeting}, {name}!"\n\nprint(greet("Ava"))\nprint(greet("Leo", "Yo"))`},
py14:{title:"High score",body:`<p>Print the biggest score, then how many scores there are.</p>`,
  start:`scores = [12, 7, 30, 1]\n`,use:[[/len\s*\(/,"Use len() to count the scores."]],out:["30","4"],variants:[[/\[12, 7, 30, 1\]/,"[5, 9]",["9","2"]]],
  hint:`scores = [12, 7, 30, 1]\nprint(max(scores))\nprint(len(scores))`},
py15:{title:"Even squares",body:`<p>Use one list comprehension to make the squares of only the <b>even</b> numbers, then print it.</p>`,
  start:`nums = [1, 2, 3, 4, 5, 6]\n`,use:[[/\[[^\]]*\bfor\b[^\]]*\bin\b[^\]]*\bif\b/,"Use [... for n in nums if ...] in one line."]],out:["[4, 16, 36]"],
  hint:`nums = [1, 2, 3, 4, 5, 6]\nsquares = [n * n for n in nums if n % 2 == 0]\nprint(squares)`},
py16:{title:"Restock the shop",body:`<p>Add ${C("\"kiwi\"")} with 7, add 5 more bananas, then print the whole dictionary.</p>`,
  start:`stock = {"banana": 12, "mango": 3}\n`,use:[[/stock\s*\[\s*["']kiwi["']\s*\]\s*=/,"Add kiwi with stock[\"kiwi\"] = 7"]],out:["{'banana': 17, 'mango': 3, 'kiwi': 7}"],
  hint:`stock = {"banana": 12, "mango": 3}\nstock["kiwi"] = 7\nstock["banana"] += 5\nprint(stock)`},
py18:{title:"Build a Counter",body:`<p>Make a class ${C("Counter")} whose ${C("count")} starts at 0, with an ${C("add()")} method that adds 1.</p>`,
  start:`# define the class here\n\nc = Counter()\nc.add()\nc.add()\nprint(c.count)\n`,use:[[/class\s+Counter/,"Start with class Counter:"],[/def\s+add\s*\(\s*self/,"Methods need self: def add(self):"]],out:["2"],
  hint:`class Counter:\n    def __init__(self):\n        self.count = 0\n\n    def add(self):\n        self.count += 1\n\nc = Counter()\nc.add()\nc.add()\nprint(c.count)`},
py19:{title:"Safe number",body:`<p>Try to turn ${C("text")} into an int and print it. If that fails, print ${C("Not a number")} instead.</p>`,
  start:`text = "12a"\n`,use:[[/\btry\s*:/,"Use try:"],[/\bexcept\b/,"Catch the error with except ValueError:"]],out:["Not a number"],variants:[[/"12a"/,'"12"',["12"]]],
  hint:`text = "12a"\ntry:\n    print(int(text))\nexcept ValueError:\n    print("Not a number")`},

/* ---------------- SQL ---------------- */
sql1:{title:"Names and ages",body:`<p>Get the ${C("name")} and ${C("age")} of every animal.</p>`,start:`-- your query here\n`,
  use:[[/\bselect\b/i,"Start with SELECT."],[/\bfrom\s+animals\b/i,"Get them FROM animals."]],out:["Mo | 4","Kiki | 12","Bao | 7","Zuri | 9","Pip | 2","Odo | 5"],
  hint:`SELECT name, age FROM animals;`},
sql2:{title:"Grown-ups only",body:`<p>Find the names of animals older than 6.</p>`,start:`SELECT name FROM animals\n`,
  use:[[/\bwhere\b/i,"Filter with WHERE."]],out:["Kiki","Bao","Zuri"],hint:`SELECT name FROM animals\nWHERE age > 6;`},
sql3:{title:"Z to A",body:`<p>List the keepers' names in reverse alphabetical order (Z first).</p>`,start:`-- your query here\n`,
  use:[[/order\s+by/i,"Sort with ORDER BY."],[/\bdesc\b/i,"Use DESC for Z to A."]],out:["Mia","Leo","Kai","Ava"],hint:`SELECT name FROM keepers\nORDER BY name DESC;`},
sql4:{title:"Banana count",body:`<p>Find the total ${C("qty")} of all banana snacks.</p>`,start:`-- your query here\n`,
  use:[[/\bsum\s*\(/i,"Add them up with SUM(qty)."]],out:["9"],hint:`SELECT SUM(qty) FROM snacks\nWHERE food = 'banana';`},
sql5:{title:"Species census",body:`<p>Count the animals of each species. Show the species and the count, biggest count first, then species A to Z.</p>`,start:`-- your query here\n`,
  use:[[/group\s+by/i,"Use GROUP BY species."]],out:["monkey | 2","giraffe | 1","owl | 1","panda | 1","parrot | 1"],
  hint:`SELECT species, COUNT(*) FROM animals\nGROUP BY species\nORDER BY COUNT(*) DESC, species;`},
sql6:{title:"Letter hunt",body:`<p>Find animals whose name contains the letter i (anywhere).</p>`,start:`SELECT name FROM animals\n`,
  use:[[/\blike\b/i,"Use LIKE with % on both sides."]],out:["Kiki","Zuri","Pip"],hint:`SELECT name FROM animals\nWHERE name LIKE '%i%';`},
sql7:{title:"Morning crew",body:`<p>List each animal's name with its keeper's name, only for keepers on the <b>morning</b> shift, sorted by animal name.</p>`,start:`-- your query here\n`,
  use:[[/\bjoin\b/i,"JOIN the animals and keepers tables."]],out:["Bao | Ava","Mo | Ava","Pip | Ava","Zuri | Kai"],
  hint:`SELECT a.name, k.name\nFROM animals a\nJOIN keepers k ON a.keeper_id = k.id\nWHERE k.shift = 'morning'\nORDER BY a.name;`},
sql8:{title:"Everyone counts",body:`<p>Show every keeper's name and how many animals they look after, <b>including</b> keepers with none. Order by keeper id.</p>`,start:`-- your query here\n`,
  use:[[/left\s+join/i,"Use a LEFT JOIN so Mia shows up too."]],out:["Ava | 3","Leo | 1","Kai | 1","Mia | 0"],
  hint:`SELECT k.name, COUNT(a.id)\nFROM keepers k\nLEFT JOIN animals a ON a.keeper_id = k.id\nGROUP BY k.id\nORDER BY k.id;`},
sql9:{title:"Your own report",body:`<p>For each <b>food</b>, show the total qty eaten by animals that <b>Ava</b> looks after, biggest total first.</p>`,start:`-- join snacks, animals and keepers\n`,
  use:[[/\bjoin\b/i,"You'll need two JOINs."],[/group\s+by/i,"Group by food."]],out:["bamboo | 20","banana | 9","mango | 2"],
  hint:`SELECT s.food, SUM(s.qty)\nFROM snacks s\nJOIN animals a ON s.animal_id = a.id\nJOIN keepers k ON a.keeper_id = k.id\nWHERE k.name = 'Ava'\nGROUP BY s.food\nORDER BY SUM(s.qty) DESC;`},
sql10:{title:"New hire",body:`<p>Add a keeper named ${C("Zed")} with id 5 on the night shift. Then show the names of all night keepers.</p>`,start:`-- INSERT first, then SELECT\n`,
  use:[[/insert\s+into/i,"Add the row with INSERT INTO."]],out:["Leo","Mia","Zed"],
  hint:`INSERT INTO keepers (id, name, shift) VALUES (5, 'Zed', 'night');\nSELECT name FROM keepers WHERE shift = 'night';`},
sql11:{title:"Monkey birthdays",body:`<p>Every monkey just had a birthday. Add 1 to the age of all monkeys, then show the monkeys' names and ages.</p>`,start:`-- UPDATE first, then SELECT\n`,
  use:[[/\bupdate\b/i,"Change the rows with UPDATE ... SET."],[/\bwhere\b/i,"Only update monkeys! Use WHERE."]],out:["Mo | 5","Pip | 3"],
  hint:`UPDATE animals SET age = age + 1 WHERE species = 'monkey';\nSELECT name, age FROM animals WHERE species = 'monkey';`},
sql12:{title:"Your own table",body:`<p>Create a table ${C("pets")} with an ${C("id")} and a ${C("name")}. Insert ${C("Rex")} and then ${C("Mittens")}, then select all the names.</p>`,start:`-- CREATE TABLE, INSERT, SELECT\n`,
  use:[[/create\s+table\s+pets/i,"Start with CREATE TABLE pets (...)."]],out:["Rex","Mittens"],
  hint:`CREATE TABLE pets (id INTEGER PRIMARY KEY, name TEXT);\nINSERT INTO pets (id, name) VALUES (1, 'Rex'), (2, 'Mittens');\nSELECT name FROM pets;`},

/* ---------------- C# ---------------- */
cs1:{title:"Your first program",body:`<p>Print ${C("Hello, C#!")} and then ${C("I can code!")} on two lines.</p>`,start:`// your code here\n`,
  use:[[/Console\.WriteLine/,"Use Console.WriteLine(...)."]],out:["Hello, C#!","I can code!"],hint:`Console.WriteLine("Hello, C#!");\nConsole.WriteLine("I can code!");`},
cs2:{title:"Apple sharing",body:`<p>Print how many whole apples each friend gets, then how many are left over.</p>`,start:`int apples = 7;\nint friends = 2;\n`,
  use:[[/\//,"Divide with /. Two ints give a whole number."],[/%/,"Use % for the leftovers."]],out:["3","1"],variants:[[/apples = 7/,"apples = 10",["5","0"]]],
  hint:`int apples = 7;\nint friends = 2;\nConsole.WriteLine(apples / friends);\nConsole.WriteLine(apples % friends);`},
cs3:{title:"Grade it",body:`<p>90 or more prints ${C("A")}, 80 or more ${C("B")}, 70 or more ${C("C")}, otherwise ${C("Try again")}. I'll test a few scores.</p>`,start:`int score = 72;\n`,
  use:[[/else\s+if/,"Use else if for the middle grades."]],out:["C"],variants:[[/score = 72/,"score = 95",["A"]],[/score = 72/,"score = 80",["B"]],[/score = 72/,"score = 50",["Try again"]]],
  hint:`int score = 72;\nif (score >= 90) {\n  Console.WriteLine("A");\n} else if (score >= 80) {\n  Console.WriteLine("B");\n} else if (score >= 70) {\n  Console.WriteLine("C");\n} else {\n  Console.WriteLine("Try again");\n}`},
cs4:{title:"Count down by twos",body:`<p>Use a loop to print 10, 8, 6, 4, 2 (one per line).</p>`,start:`// your loop here\n`,
  use:[[/\bfor\b|\bwhile\b/,"Use a loop."]],out:["10","8","6","4","2"],hint:`for (int i = 10; i > 0; i -= 2) {\n  Console.WriteLine(i);\n}`},
cs5:{title:"Triple it",body:`<p>Write ${C("static int Triple(int n)")} that returns n times 3.</p>`,start:`// write Triple here\n\nConsole.WriteLine(Triple(4));\nConsole.WriteLine(Triple(10));\n`,
  use:[[/static\s+int\s+Triple\s*\(/,"Start with static int Triple(int n)"],[/\breturn\b/,"Return the answer."]],out:["12","30"],
  hint:`static int Triple(int n) {\n  return n * 3;\n}\n\nConsole.WriteLine(Triple(4));\nConsole.WriteLine(Triple(10));`},
cs6:{title:"Replay the guesses",body:`<p>No typing in TypeMonkey yet, so here are the player's guesses. Loop through them: print ${C("Higher!")} if a guess is too low, ${C("Lower!")} if too high, and ${C("Got it!")} when it's right, then stop.</p>`,
  start:`int secret = 7;\nint[] guesses = { 3, 9, 7, 2 };\n`,use:[[/\bforeach\b|\bfor\b/,"Loop through the guesses."],[/\bbreak\b/,"Use break to stop once it's right."]],out:["Higher!","Lower!","Got it!"],variants:[[/secret = 7/,"secret = 9",["Higher!","Got it!"]]],
  hint:`int secret = 7;\nint[] guesses = { 3, 9, 7, 2 };\nforeach (int g in guesses) {\n  if (g < secret) Console.WriteLine("Higher!");\n  else if (g > secret) Console.WriteLine("Lower!");\n  else {\n    Console.WriteLine("Got it!");\n    break;\n  }\n}`},
cs7:{title:"Build a Robot",body:`<p>Below the code, write ${C("class Robot")} with a public ${C("string Name")} and a constructor ${C("Robot(string name)")} that stores it.</p>`,
  start:`Robot r = new Robot("Bolt");\nConsole.WriteLine(r.Name);\n\n// write the Robot class here\n`,use:[[/class\s+Robot/,"Write class Robot { ... }"],[/public\s+Robot\s*\(/,"Add a constructor: public Robot(string name)"]],out:["Bolt"],
  hint:`Robot r = new Robot("Bolt");\nConsole.WriteLine(r.Name);\n\nclass Robot {\n  public string Name;\n  public Robot(string name) {\n    Name = name;\n  }\n}`},
cs8:{title:"Score keeper",body:`<p>Write ${C("class Score")} with a ${C("Total")} property that only the class can change (${C("private set")}), and an ${C("Add(int points)")} method.</p>`,
  start:`Score s = new Score();\ns.Add(10);\ns.Add(5);\nConsole.WriteLine(s.Total);\n\n// write the Score class here\n`,use:[[/private\s+set/,"Use { get; private set; } for Total."],[/void\s+Add\s*\(/,"Add a method: public void Add(int points)"]],out:["15"],
  hint:`Score s = new Score();\ns.Add(10);\ns.Add(5);\nConsole.WriteLine(s.Total);\n\nclass Score {\n  public int Total { get; private set; }\n  public void Add(int points) { Total += points; }\n}`},
cs9:{title:"Feed the pet",body:`<p>Finish ${C("Feed()")}: it lowers Hunger by 2, but never below 0.</p>`,
  start:`VirtualPet pet = new VirtualPet();\npet.Feed();\npet.Feed();\npet.Feed();\nConsole.WriteLine(pet.Hunger);\n\nclass VirtualPet {\n  public int Hunger { get; private set; } = 5;\n  public void Feed() {\n    // your code here\n  }\n}\n`,
  use:[[/Hunger\s*-=\s*2|Hunger\s*=\s*Hunger\s*-\s*2/,"Lower Hunger by 2."]],out:["0"],variants:[[/= 5;/,"= 9;",["3"]]],
  hint:`VirtualPet pet = new VirtualPet();\npet.Feed();\npet.Feed();\npet.Feed();\nConsole.WriteLine(pet.Hunger);\n\nclass VirtualPet {\n  public int Hunger { get; private set; } = 5;\n  public void Feed() {\n    Hunger -= 2;\n    if (Hunger < 0) Hunger = 0;\n  }\n}`},
cs10:{title:"Squad changes",body:`<p>Add ${C("\"Kai\"")}, remove ${C("\"Ava\"")}, then print the count and then each name.</p>`,start:`var names = new List<string> { "Ava", "Leo" };\n`,
  use:[[/\.Add\s*\(/,"Use .Add()."],[/\.Remove\s*\(/,"Use .Remove()."],[/\bforeach\b/,"Print each name with foreach."]],out:["2","Leo","Kai"],
  hint:`var names = new List<string> { "Ava", "Leo" };\nnames.Add("Kai");\nnames.Remove("Ava");\nConsole.WriteLine(names.Count);\nforeach (string n in names) {\n  Console.WriteLine(n);\n}`},
cs11:{title:"Restock",body:`<p>Add 5 more bananas, add ${C("\"kiwi\"")} with 2, then print every item like ${C("banana: 8")}.</p>`,start:`var stock = new Dictionary<string, int> { ["banana"] = 3 };\n`,
  use:[[/\bforeach\b/,"Print the items with foreach."]],out:["banana: 8","kiwi: 2"],
  hint:`var stock = new Dictionary<string, int> { ["banana"] = 3 };\nstock["banana"] += 5;\nstock["kiwi"] = 2;\nforeach (var item in stock) {\n  Console.WriteLine($"{item.Key}: {item.Value}");\n}`},
cs12:{title:"Word counter",body:`<p>Count each word with a ${C("Dictionary&lt;string, int&gt;")}, then print each like ${C("ook: 3")} (in the order words first appear).</p>`,start:`string[] words = { "ook", "eek", "ook", "ook" };\n`,
  use:[[/Dictionary/,"Use a Dictionary<string, int> for the counts."]],out:["ook: 3","eek: 1"],
  hint:`string[] words = { "ook", "eek", "ook", "ook" };\nvar counts = new Dictionary<string, int>();\nforeach (string w in words) {\n  if (counts.ContainsKey(w)) counts[w]++;\n  else counts[w] = 1;\n}\nforeach (var kv in counts) {\n  Console.WriteLine($"{kv.Key}: {kv.Value}");\n}`},

/* ---------------- C++ ---------------- */
cpp1:{title:"Your first program",body:`<p>Print ${C("Hello, C++!")} on one line, then let C++ work out ${C("6 * 7")} on the next.</p>`,start:`// your code here\n`,
  use:[[/cout/,"Use std::cout <<"],[/6\s*\*\s*7/,"Let C++ do the math: 6 * 7"]],out:["Hello, C++!","42"],hint:`std::cout << "Hello, C++!" << "\\n";\nstd::cout << 6 * 7;`},
cpp2:{title:"Total cost",body:`<p>Print the total cost: price times qty.</p>`,start:`double price = 2.5;\nint qty = 4;\n`,
  use:[[/price\s*\*\s*qty|qty\s*\*\s*price/,"Multiply price by qty."]],out:["10"],variants:[[/qty = 4/,"qty = 3",["7.5"]]],hint:`double price = 2.5;\nint qty = 4;\nstd::cout << price * qty;`},
cpp3:{title:"Pizza party",body:`<p>Print how many whole slices each person gets, then the leftover slices on the next line.</p>`,start:`int pizzas = 2;\nint slices = 8;\nint people = 5;\n`,
  use:[[/\//,"Divide with /."],[/%/,"Use % for the leftovers."]],out:["3","1"],variants:[[/people = 5/,"people = 4",["4","0"]]],
  hint:`int pizzas = 2;\nint slices = 8;\nint people = 5;\nint total = pizzas * slices;\nstd::cout << total / people << "\\n";\nstd::cout << total % people;`},
cpp4:{title:"Liftoff",body:`<p>Count down from 5 to 1 with a loop, then print ${C("Liftoff!")} (one per line).</p>`,start:`// your loop here\n`,
  use:[[/\bfor\b|\bwhile\b/,"Use a loop."]],out:["5","4","3","2","1","Liftoff!"],hint:`for (int i = 5; i >= 1; i--) {\n  std::cout << i << "\\n";\n}\nstd::cout << "Liftoff!";`},
cpp5:{title:"The bigger one",body:`<p>Write ${C("int maxOf(int a, int b)")} above main that returns the bigger number.</p>`,
  start:`// write maxOf here\n\nint main() {\n  std::cout << maxOf(3, 9) << "\\n";\n  std::cout << maxOf(12, 4);\n}\n`,use:[[/int\s+maxOf\s*\(/,"Start with int maxOf(int a, int b)"],[/\breturn\b/,"Return the bigger number."]],out:["9","12"],
  hint:`int maxOf(int a, int b) {\n  if (a > b) return a;\n  return b;\n}\n\nint main() {\n  std::cout << maxOf(3, 9) << "\\n";\n  std::cout << maxOf(12, 4);\n}`},
cpp6:{title:"One row",body:`<p>Write ${C("void row(int n)")} that prints n, 2n, 3n, 4n and 5n with spaces between them.</p>`,
  start:`// write row here\n\nint main() {\n  row(3);\n}\n`,use:[[/\bfor\b/,"Use a for loop inside row."]],out:["3 6 9 12 15"],variants:[[/row\(3\);/,"row(4);",["4 8 12 16 20"]]],
  hint:`void row(int n) {\n  for (int i = 1; i <= 5; i++) {\n    std::cout << n * i << " ";\n  }\n}\n\nint main() {\n  row(3);\n}`},
cpp7:{title:"Power up",body:`<p>Write ${C("void addTen(int& x)")} that adds 10 to the caller's variable.</p>`,
  start:`// write addTen here\n\nint main() {\n  int score = 5;\n  addTen(score);\n  addTen(score);\n  std::cout << score;\n}\n`,use:[[/int\s*&\s*\w+/,"Take a reference: int& x"]],out:["25"],
  hint:`void addTen(int& x) {\n  x += 10;\n}\n\nint main() {\n  int score = 5;\n  addTen(score);\n  addTen(score);\n  std::cout << score;\n}`},
cpp8:{title:"Point and change",body:`<p>Make a pointer ${C("p")} that points at ${C("b")}, use it to set b to 100, then print b.</p>`,start:`int a = 3;\nint b = 8;\n`,
  use:[[/int\s*\*\s*p\s*=\s*&\s*b/,"Point at b: int* p = &b;"],[/\*\s*p\s*=/,"Change b through the pointer: *p = 100;"]],out:["100"],
  hint:`int a = 3;\nint b = 8;\nint* p = &b;\n*p = 100;\nstd::cout << b;`},
cpp9:{title:"Sort two",body:`<p>Write ${C("void sortTwo(int& a, int& b)")} so that afterward a holds the smaller number.</p>`,
  start:`// write sortTwo here\n\nint main() {\n  int x = 9, y = 4;\n  sortTwo(x, y);\n  std::cout << x << " " << y;\n}\n`,use:[[/int\s*&/,"Use references so you change the originals."]],out:["4 9"],variants:[[/x = 9, y = 4/,"x = 2, y = 7",["2 7"]]],
  hint:`void sortTwo(int& a, int& b) {\n  if (a > b) {\n    int t = a;\n    a = b;\n    b = t;\n  }\n}\n\nint main() {\n  int x = 9, y = 4;\n  sortTwo(x, y);\n  std::cout << x << " " << y;\n}`},
cpp10:{title:"Score list",body:`<p>Add 5 to the end of the vector, then print its size and the sum of all scores (two lines).</p>`,start:`std::vector<int> scores = {7, 3, 9};\n`,
  use:[[/push_back/,"Add with push_back."]],out:["4","24"],
  hint:`std::vector<int> scores = {7, 3, 9};\nscores.push_back(5);\nint sum = 0;\nfor (int s : scores) sum += s;\nstd::cout << scores.size() << "\\n" << sum;`},
cpp11:{title:"Woof",body:`<p>Write ${C("class Dog")} with a public ${C("std::string name")} and a ${C("bark()")} method that prints the name followed by ${C(" says woof")}.</p>`,
  start:`// write class Dog here\n\nint main() {\n  Dog d;\n  d.name = "Rex";\n  d.bark();\n}\n`,use:[[/class\s+Dog/,"Write class Dog { ... };"]],out:["Rex says woof"],variants:[[/"Rex"/,'"Bolt"',["Bolt says woof"]]],
  hint:`class Dog {\npublic:\n  std::string name;\n  void bark() {\n    std::cout << name << " says woof";\n  }\n};\n\nint main() {\n  Dog d;\n  d.name = "Rex";\n  d.bark();\n}`},
cpp12:{title:"Healing potion",body:`<p>Finish ${C("heal(int amount)")}: add amount to hp, but hp can never go over 30.</p>`,
  start:`class Hero {\npublic:\n  int hp = 20;\n  void heal(int amount) {\n    // your code here\n  }\n};\n\nint main() {\n  Hero h;\n  h.heal(5);\n  std::cout << h.hp << "\\n";\n  h.heal(50);\n  std::cout << h.hp;\n}\n`,
  use:[[/hp\s*\+=|hp\s*=\s*hp\s*\+/,"Add amount to hp."]],out:["25","30"],
  hint:`class Hero {\npublic:\n  int hp = 20;\n  void heal(int amount) {\n    hp += amount;\n    if (hp > 30) hp = 30;\n  }\n};\n\nint main() {\n  Hero h;\n  h.heal(5);\n  std::cout << h.hp << "\\n";\n  h.heal(50);\n  std::cout << h.hp;\n}`},
};

/* attach each challenge to its lesson */
for(const course of [COURSE_PY,COURSE_SQL,COURSE_CS,COURSE_CPP])for(const u of course.units)for(const l of u.lessons){
  const ch=CHALLENGES[l.id];if(!ch||!l.steps||l.steps.some(s=>s.challenge))continue;
  const at=l.steps.findIndex(s=>s.type==="game"||s.type==="done");
  l.steps.splice(at,0,{type:"code",challenge:true,...ch});
}
