/* C++ course. Units 2–4 live in cpp-units-2-4.js */
const COURSE_CPP={id:"cpp",name:"C++",blurb:"The speed-demon language behind game engines, browsers and robots. Unit 1 is free.",units:[
{name:"Hello, C++",free:true,lessons:[
{id:"cpp1",title:"Hello, C++",sub:"#include, main, std::cout",steps:[
 {type:"talk",title:"Meet C++",mood:"cheer",
  body:`<p>C++ is one of the fastest languages around. Game engines like Unreal, web browsers and robots use it. It gives you a lot of control, so it asks for a bit more care.</p>`,
  say:"Fast, powerful, and a little picky. Let's tame it."},
 {type:"talk",title:"Printing with cout",
  body:`<p>${C("#include &lt;iostream&gt;")} brings in input/output tools. Programs start in ${C("main()")}. You print by sending things into ${C("std::cout")} with ${C("&lt;&lt;")}.</p>`,
  demo:`#include <iostream>\n\nint main() {\n  std::cout << "Hello, world!" << std::endl;\n  std::cout << "I'm learning C++" << std::endl;\n  return 0;\n}`,
  say:"std::endl ends the line. return 0 tells the computer 'all good'."},
 {type:"talk",title:"Chaining output",mood:"think",
  body:`<p>You can chain as many ${C("&lt;&lt;")} as you want. ${C("\"\\n\"")} is a shorter way to end a line.</p>`,
  demo:`std::cout << "Level " << 3 << "\\n";\nstd::cout << 2 + 2 << "\\n";`,
  say:"Output:\nLevel 3\n4"},
 {type:"quiz",q:"Where does a C++ program start running?",opts:["main()","start()","the first line","#include"],a:0,mono:true,why:"Every C++ program begins in main."},
 {type:"fill",title:"Print it",body:`<p>Print Hi and end the line.</p>`,
  code:`std::[0] [1] "Hi" << std::endl;`,blanks:["cout","<<"],tokens:["cout","<<",">>","print"],why:"std::cout << sends things to the screen. >> is for reading input."},
 {type:"order",title:"Build a program",body:`<p>Put the lines in a working order.</p>`,
  lines:["#include <iostream>","int main() {","  std::cout << \"Ook!\";","  return 0;","}"],why:"Include first, then main wraps your code and returns 0."},
 {type:"quiz",q:"What does this print?",code:`std::cout << "A" << "B" << "\\n";\nstd::cout << "C";`,opts:["AB\nC","ABC","A B C"],a:0,mono:true,why:"\\n ends the first line after AB, then C goes on the next line."},
 {type:"game"},{type:"done"}],
 pool:[
  [`std::cout << "Hi" << "!";`,["Hi!","Hi !","Hi << !"]],
  [`std::cout << 3 + 4;`,["7","34","3 + 4"]],
  [`std::cout << "3" << 4;`,["34","7","Error"]],
  [`std::cout << "x\\n" << "y";`,["x y","xy","x\\ny"]],
  [`std::cout << 10 - 2 * 3;`,["4","24","6"]],
  [`std::cout << "a" << " " << "b";`,["a b","ab","a  b"]]
 ]},
{id:"cpp2",title:"Variables & types",sub:"int, double, std::string, bool, auto",steps:[
 {type:"talk",title:"Typed boxes",
  body:`<p>Like C#, every C++ variable has a type: ${C("int")}, ${C("double")}, ${C("bool")}, and ${C("std::string")} for text (which needs ${C("#include &lt;string&gt;")}).</p>`,
  demo:`int lives = 3;\ndouble price = 1.99;\nstd::string name = "Mo";\nbool hungry = true;\nstd::cout << name << " has " << lives << " lives";`,
  say:"Output: Mo has 3 lives"},
 {type:"talk",title:"bool prints as a number",mood:"oops",
  body:`<p>Surprise: by default, C++ prints ${C("true")} as ${C("1")} and ${C("false")} as ${C("0")}.</p>`,
  demo:`bool a = true;\nbool b = false;\nstd::cout << a << " " << b;`,
  say:"Output: 1 0. Computers love ones and zeros."},
 {type:"talk",title:"auto",mood:"think",
  body:`<p>${C("auto")} lets the compiler pick the type from the value, like ${C("var")} in C#.</p>`,
  demo:`auto score = 10;     // int\nauto ratio = 0.5;    // double\nscore = score + 5;\nstd::cout << score;  // 15`,
  say:"The type still never changes after it's decided."},
 {type:"quiz",q:"What does this print?",code:`bool ok = true;\nstd::cout << ok;`,opts:["1","true","True"],a:0,mono:true,why:"C++ prints booleans as 1 and 0 by default."},
 {type:"fill",title:"Pick the types",body:`<p>Match each value with its type.</p>`,
  code:`[0] coins = 50;\n[1] speed = 2.5;\n[2] name = "Kai";`,blanks:["int","double","std::string"],tokens:["int","double","std::string","bool"],why:"Whole → int, decimal → double, text → std::string."},
 {type:"quiz",q:"Which header do you need for std::string?",opts:["#include <string>","#include <text>","#include <iostream> only"],a:0,mono:true,why:"<string> brings in std::string."},
 {type:"game"},{type:"done"}],
 pool:[
  [`int a = 5;\na += 2;\nstd::cout << a;`,["7","52","5"]],
  [`bool b = false;\nstd::cout << b;`,["0","false","False"]],
  [`std::string s = "ook";\nstd::cout << s.length();`,["3","ook","2"]],
  [`int x = 4;\nint y = x;\nx = 10;\nstd::cout << y;`,["4","10","0"]],
  [`double d = 1.5;\nstd::cout << d + d;`,["3","1.51.5","2"]],
  [`auto n = 9;\nn--;\nstd::cout << n;`,["8","9","10"]]
 ]},
{id:"cpp3",title:"Math & decisions",sub:"integer division, %, if / else",steps:[
 {type:"talk",title:"Integer division",mood:"oops",
  body:`<p>${C("int")} divided by ${C("int")} drops the decimal in C++ too. Make one side a decimal to keep it.</p>`,
  demo:`std::cout << 7 / 2 << "\\n";    // 3\nstd::cout << 7.0 / 2 << "\\n";  // 3.5\nstd::cout << 7 % 2 << "\\n";    // 1`,
  say:"Same trap as C#. You're now immune."},
 {type:"talk",title:"if / else",
  body:`<p>Decisions use the same shape you already know: ${C("if")}, ${C("else if")}, ${C("else")}, plus ${C("==")}, ${C("&amp;&amp;")} and ${C("||")}.</p>`,
  demo:`int score = 84;\nif (score >= 90) {\n  std::cout << "A";\n} else if (score >= 80) {\n  std::cout << "B";\n} else {\n  std::cout << "Keep going";\n}`,
  say:"84 lands on B."},
 {type:"quiz",q:"What does this print?",code:`std::cout << 11 / 3;`,opts:["3","3.67","4"],a:0,mono:true,why:"11 / 3 is 3 with the decimal dropped."},
 {type:"fill",title:"Both must be true",body:`<p>Print "Go" only if ready AND fueled.</p>`,
  code:`bool ready = true;\nbool fueled = true;\nif (ready [0] fueled) {\n  std::cout << "Go";\n}`,blanks:["&&"],tokens:["&&","||","==","and"],why:"&& requires both sides to be true."},
 {type:"quiz",q:"What does this print?",code:`int x = 5;\nif (x = 0) {\n  std::cout << "zero";\n} else {\n  std::cout << "not zero";\n}`,opts:["not zero","zero","5"],a:0,mono:true,why:"Bug alert! x = 0 ASSIGNS 0 (which counts as false). You wanted x == 0. Classic C++ trap."},
 {type:"game"},{type:"done"}],
 pool:[
  [`std::cout << 9 / 2;`,["4","4.5","5"]],
  [`std::cout << 9.0 / 2;`,["4.5","4","5"]],
  [`std::cout << 9 % 4;`,["1","2","0"]],
  [`int a = 2;\nif (a > 1) std::cout << "big";\nelse std::cout << "small";`,["big","small","bigsmall"]],
  [`std::cout << (3 > 2 && 1 > 5);`,["0","1","false"]],
  [`std::cout << (4 == 4);`,["1","true","4"]]
 ]}
]},
CPP_UNIT2,CPP_UNIT3,CPP_UNIT4
]};
