/* deep-web: added units for HTML & CSS (Units 6 and 7, lessons web17–web26).
   Same schema as web.js: code steps are graded by gradeWebNow with
   checks:[{sel, msg, text?, count?, attr?, style?}] plus optional use:[[RegExp, msg]] source checks. */
COURSE_WEB.units.push({name:"Pages with substance",lessons:[
{id:"web17",title:"Tables",sub:"rows, columns, headers",steps:[
 {type:"talk",title:"Data in rows and columns",mood:"cheer",
  body:`<p>A ${C("&lt;table&gt;")} shows data in a grid. Each ${C("&lt;tr&gt;")} is a <b>table row</b>. Inside a row, ${C("&lt;th&gt;")} is a header cell and ${C("&lt;td&gt;")} is a normal data cell.</p>`,
  demo:`<table>\n  <tr>\n    <th>Monkey</th>\n    <th>Bananas</th>\n  </tr>\n  <tr>\n    <td>Mo</td>\n    <td>12</td>\n  </tr>\n  <tr>\n    <td>Kiki</td>\n    <td>9</td>\n  </tr>\n</table>`,
  say:"Header cells are bold and centered by default. Handy!"},
 {type:"talk",title:"thead, tbody and caption",mood:"think",
  body:`<p>Group the header row in ${C("&lt;thead&gt;")} and the data rows in ${C("&lt;tbody&gt;")}. A ${C("&lt;caption&gt;")} gives the table a title. In CSS, ${C("border-collapse: collapse")} merges the double borders into single neat lines.</p>`,
  demo:`<style>\n  table { border-collapse: collapse; }\n  th, td { border: 1px solid #ccc; padding: 6px 12px; }\n  th { background: #FFF4E5; }\n</style>\n<table>\n  <caption>Banana league</caption>\n  <thead>\n    <tr><th>Monkey</th><th>Bananas</th></tr>\n  </thead>\n  <tbody>\n    <tr><td>Mo</td><td>12</td></tr>\n    <tr><td>Kiki</td><td>9</td></tr>\n  </tbody>\n</table>`,
  say:"Try removing border-collapse to see the difference."},
 {type:"quiz",q:"Which tag makes a new ROW in a table?",opts:["<tr>","<td>","<row>"],a:0,mono:true,why:"tr = table row. td cells go inside it."},
 {type:"order",title:"Build a row",body:`<p>Put the tags in order to make one row with two cells.</p>`,lines:["<tr>","  <td>Bao</td>","  <td>7</td>","</tr>"],why:"Open the row, add cells, close the row.",noRun:true},
 {type:"code",title:"Snack table",
  body:`<p>Build a ${C("&lt;table&gt;")} with a header row of 2 ${C("&lt;th&gt;")} cells (${C("Snack")} and ${C("Price")}), then at least 2 more rows of ${C("&lt;td&gt;")} cells.</p>`,
  start:`<h2>Snack bar</h2>\n<!-- your table here -->\n`,
  checks:[{sel:"table th",count:2,msg:"Add a header row with 2 <th> cells."},{sel:"table th",text:/Snack/i,msg:"One header should say Snack."},{sel:"table th",text:/Price/i,msg:"One header should say Price."},{sel:"table tr",count:3,msg:"Add at least 2 data rows under the header row (3 <tr> in total)."},{sel:"table td",count:4,msg:"Each data row needs 2 <td> cells."}],
  hint:`<h2>Snack bar</h2>\n<table>\n  <tr><th>Snack</th><th>Price</th></tr>\n  <tr><td>Banana</td><td>$1</td></tr>\n  <tr><td>Mango</td><td>$2</td></tr>\n</table>`},
 {type:"fill",title:"Neat borders",body:`<p>Merge the table's borders into single lines.</p>`,code:`<style>\n  table { [0]: [1]; }\n</style>`,blanks:["border-collapse","collapse"],tokens:["border-collapse","collapse","merge","border-style"],why:"border-collapse: collapse joins neighboring cell borders."},
 {type:"code",title:"Style the table",
  body:`<p>Give the ${C("table")} ${C("border-collapse: collapse")}, and give every ${C("td")} a ${C("padding")} of ${C("8px")}.</p>`,
  start:`<style>\n  td, th { border: 1px solid #ccc; }\n</style>\n<table>\n  <thead><tr><th>Animal</th><th>Age</th></tr></thead>\n  <tbody>\n    <tr><td>Mo</td><td>4</td></tr>\n    <tr><td>Kiki</td><td>12</td></tr>\n  </tbody>\n</table>\n`,
  checks:[{sel:"table",style:{"border-collapse":"collapse"},msg:"Add border-collapse: collapse to the table."},{sel:"td",style:{"padding-top":"8px","padding-left":"8px"},msg:"Give td a padding of 8px."}],
  hint:`<style>\n  table { border-collapse: collapse; }\n  td, th { border: 1px solid #ccc; }\n  td { padding: 8px; }\n</style>\n<table>\n  <thead><tr><th>Animal</th><th>Age</th></tr></thead>\n  <tbody>\n    <tr><td>Mo</td><td>4</td></tr>\n    <tr><td>Kiki</td><td>12</td></tr>\n  </tbody>\n</table>`},
 {type:"quiz",q:"When should you use a table?",opts:["For data with rows and columns, like scores","To lay out a whole page","Whenever you want borders"],a:0,why:"Tables are for tabular data. Use flexbox or grid for page layout."},
 {type:"done"}]},
{id:"web18",title:"Forms, deeper",sub:"radio, textarea, required, fieldset",steps:[
 {type:"talk",title:"Choose one: radio buttons",
  body:`<p>${C("type=\"radio\"")} makes round buttons where you can pick only <b>one</b>. Radios that share the same ${C("name")} belong to the same group. A ${C("&lt;textarea&gt;")} is a big box for longer text.</p>`,
  demo:`<form>\n  <p>Favorite fruit:</p>\n  <label><input type="radio" name="fruit"> Banana</label><br>\n  <label><input type="radio" name="fruit"> Mango</label><br>\n  <label><input type="radio" name="fruit"> Kiwi</label>\n  <p><label for="msg">Tell us why</label></p>\n  <textarea id="msg" rows="3"></textarea>\n</form>`,
  say:"Click one radio, then another. Only one stays picked because they share a name."},
 {type:"talk",title:"required, fieldset and legend",mood:"think",
  body:`<p>Add ${C("required")} to an input and the browser won't submit the form while it's empty. ${C("&lt;fieldset&gt;")} draws a box around related fields, and ${C("&lt;legend&gt;")} is its title.</p>`,
  demo:`<form>\n  <fieldset>\n    <legend>Your details</legend>\n    <label for="nm">Name</label>\n    <input id="nm" required>\n    <button>Send</button>\n  </fieldset>\n</form>`,
  say:"Press Send with the box empty. The browser asks you to fill it in first."},
 {type:"quiz",q:"How do radio buttons know they're in the same group?",opts:["They share the same name","They share the same id","They sit next to each other"],a:0,why:"Same name means same group, so only one can be picked."},
 {type:"fill",title:"Must fill in",body:`<p>Make the email box required.</p>`,code:`<input type="email" [0]>`,blanks:["required"],tokens:["required","needed","must","important"],why:"The required attribute stops the form submitting while the field is empty."},
 {type:"code",title:"Pick a snack",
  body:`<p>Inside the form, add 3 radio inputs that all have ${C("name=\"snack\"")}. Wrap each one in a ${C("&lt;label&gt;")} with its snack name.</p>`,
  start:`<form>\n  <p>Pick your snack:</p>\n</form>\n`,
  checks:[{sel:"form input[type=radio][name=snack]",count:3,msg:"Add 3 <input type=\"radio\" name=\"snack\"> inside the form."},{sel:"form label input[type=radio]",count:3,msg:"Wrap each radio in a <label>."},{sel:"form label",text:/[A-Za-z]/,msg:"Give each label a snack name."}],
  hint:`<form>\n  <p>Pick your snack:</p>\n  <label><input type="radio" name="snack"> Banana</label><br>\n  <label><input type="radio" name="snack"> Mango</label><br>\n  <label><input type="radio" name="snack"> Kiwi</label>\n</form>`},
 {type:"code",title:"Feedback form",
  body:`<p>Build a form with a ${C("&lt;fieldset&gt;")} and a ${C("&lt;legend&gt;")}. Inside, add a ${C("required")} name input and a ${C("&lt;textarea&gt;")} for comments.</p>`,
  start:`<form>\n</form>\n`,
  checks:[{sel:"form fieldset",msg:"Add a <fieldset> inside the form."},{sel:"fieldset > legend",text:/\S/,msg:"Give the fieldset a <legend> with a title."},{sel:"fieldset input[required]",msg:"Add an input with the required attribute."},{sel:"fieldset textarea",msg:"Add a <textarea> for comments."}],
  hint:`<form>\n  <fieldset>\n    <legend>Feedback</legend>\n    <label for="nm">Name</label><br>\n    <input id="nm" required><br>\n    <label for="cm">Comments</label><br>\n    <textarea id="cm" rows="3"></textarea><br>\n    <button>Send</button>\n  </fieldset>\n</form>`},
 {type:"quiz",q:"Which element is best for a long message?",opts:["<textarea>","<input type=\"long\">","<p>"],a:0,mono:true,why:"textarea is a multi-line text box."},
 {type:"done"}]},
{id:"web19",title:"Images & accessibility",sub:"figure, good alt text, object-fit",steps:[
 {type:"talk",title:"figure and figcaption",
  body:`<p>Wrap an image in ${C("&lt;figure&gt;")} and add a ${C("&lt;figcaption&gt;")} to give it a caption everyone can see. The ${C("alt")} text is different: it describes the picture for people who can't see it.</p>`,
  demo:`<figure>\n  <img src="mo.png" alt="Mo the monkey hanging from a branch by one arm" width="160">\n  <figcaption>Mo practicing his morning stretch.</figcaption>\n</figure>`,
  say:"Caption: for everyone. Alt: for screen readers and broken images."},
 {type:"talk",title:"Writing good alt text",mood:"think",
  body:`<p>Good alt text says what matters in the picture, briefly. Skip "image of". If an image is only decoration, use an empty ${C("alt=\"\"")} so screen readers skip it. Buttons with only an icon need an ${C("aria-label")} so they have a name.</p>`,
  demo:`<img src="x.png" alt="Three ripe bananas on a wooden table" width="100">\n<img src="swirl.png" alt="">\n<p><button aria-label="Close">✖</button> This button has a name for screen readers.</p>`,
  say:"Ask yourself: what would I say about this picture over the phone?"},
 {type:"quiz",q:"Which is the best alt text for a photo of a monkey eating a banana?",opts:["A monkey eating a banana","image","monkey.png"],a:0,why:"Describe what's in the picture. File names and the word \"image\" don't help."},
 {type:"quiz",q:"A swirly line is just decoration. What alt should it have?",opts:["alt=\"\" (empty)","alt=\"swirly line decoration image\"","No alt at all"],a:0,mono:true,why:"Empty alt tells screen readers to skip it. Leaving alt out makes some read the file name."},
 {type:"code",title:"Captioned photo",
  body:`<p>Add a ${C("&lt;figure&gt;")} containing an ${C("&lt;img&gt;")} with real ${C("alt")} text (at least a few words) and a ${C("&lt;figcaption&gt;")}.</p>`,
  start:`<h2>My zoo trip</h2>\n`,
  checks:[{sel:"figure img",msg:"Put an <img> inside a <figure>."},{sel:"figure img",attr:["alt",/\S+\s+\S+\s+\S+/],msg:"Give the image alt text of at least 3 words describing it."},{sel:"figure figcaption",text:/\S/,msg:"Add a <figcaption> with a caption."}],
  hint:`<h2>My zoo trip</h2>\n<figure>\n  <img src="panda.png" alt="A panda munching bamboo in the sun">\n  <figcaption>Bao's lunch break.</figcaption>\n</figure>`},
 {type:"talk",title:"object-fit",mood:"think",
  body:`<p>When you set an image's ${C("width")} and ${C("height")}, it can get squished. ${C("object-fit: cover")} fills the box and crops the edges instead of stretching.</p>`,
  demo:`<style>\n  .thumb { width: 120px; height: 120px; object-fit: cover; border-radius: 50%; background: #FFD25C; }\n</style>\n<img class="thumb" src="mo.png" alt="Mo's profile photo">`,
  say:"Perfect for round profile pictures."},
 {type:"code",title:"Icon button and avatar",
  body:`<p>Give the icon-only button an ${C("aria-label")} of ${C("Search")}. Then style ${C(".avatar")} with ${C("object-fit: cover")} and ${C("border-radius: 50%")}.</p>`,
  start:`<style>\n  .avatar { width: 80px; height: 80px; }\n</style>\n<img class="avatar" src="me.png" alt="My smiling face">\n<button>🔍</button>\n`,
  checks:[{sel:"button[aria-label]",attr:["aria-label",/^search$/i],msg:"Add aria-label=\"Search\" to the button."},{sel:".avatar",style:{"object-fit":"cover"},msg:"Give .avatar object-fit: cover."},{sel:".avatar",style:{"border-top-left-radius":"50%"},msg:"Give .avatar border-radius: 50%."}],
  hint:`<style>\n  .avatar { width: 80px; height: 80px; object-fit: cover; border-radius: 50%; }\n</style>\n<img class="avatar" src="me.png" alt="My smiling face">\n<button aria-label="Search">🔍</button>`},
 {type:"done"}]},
{id:"web20",title:"Positioning",sub:"relative, absolute, sticky",steps:[
 {type:"talk",title:"position: relative and absolute",
  body:`<p>${C("position: absolute")} lifts an element out of the normal flow and places it with ${C("top")}, ${C("right")}, ${C("bottom")} and ${C("left")}. It measures from the nearest parent that has ${C("position: relative")}.</p>`,
  demo:`<style>\n  .card { position: relative; width: 180px; padding: 20px; background: #FFF4E5; border-radius: 12px; }\n  .badge { position: absolute; top: 8px; right: 8px; background: #FF7A1A; color: white; padding: 2px 8px; border-radius: 99px; font-size: 12px; }\n</style>\n<div class="card">\n  <span class="badge">NEW</span>\n  <b>Banana bread</b>\n  <p>Fresh from the oven.</p>\n</div>`,
  say:"Parent relative, child absolute. That's the classic pair."},
 {type:"talk",title:"position: sticky",mood:"think",
  body:`<p>${C("position: sticky")} with ${C("top: 0")} keeps an element in place while you scroll past it, like a header that follows you down the page.</p>`,
  demo:`<style>\n  .scroller { height: 140px; overflow: auto; border: 1px solid #ddd; }\n  .bar { position: sticky; top: 0; background: #14201B; color: white; padding: 6px 10px; }\n</style>\n<div class="scroller">\n  <div class="bar">🐒 I stick!</div>\n  <p>Scroll down...</p><p>Keep going...</p><p>Still here?</p><p>Bananas.</p><p>The end.</p>\n</div>`,
  say:"Scroll inside the box and watch the bar stay on top."},
 {type:"quiz",q:"An absolute element measures its top/left from...",opts:["The nearest parent with position set (like relative)","Always the very top of the page","Where it would have been"],a:0,why:"That's why we put position: relative on the parent."},
 {type:"fill",title:"Corner badge",body:`<p>Pin the badge to the top-right of its card.</p>`,code:`<style>\n  .card { position: [0]; }\n  .badge { position: [1]; top: 0; right: 0; }\n</style>`,blanks:["relative","absolute"],tokens:["relative","absolute","sticky","static"],why:"Parent relative, child absolute."},
 {type:"code",title:"Sale sticker",
  body:`<p>Make ${C(".product")} ${C("position: relative")}. Then make ${C(".sale")} ${C("position: absolute")} with ${C("top: 10px")} and ${C("right: 10px")}.</p>`,
  start:`<style>\n  .product { width: 200px; padding: 24px; background: #CDEFD9; border-radius: 12px; }\n  .sale { background: crimson; color: white; padding: 2px 8px; border-radius: 6px; }\n</style>\n<div class="product">\n  <span class="sale">-50%</span>\n  <h3>Mango</h3>\n</div>\n`,
  checks:[{sel:".product",style:{position:"relative"},msg:"Give .product position: relative."},{sel:".sale",style:{position:"absolute"},msg:"Give .sale position: absolute."},{sel:".sale",style:{top:"10px",right:"10px"},msg:"Place .sale with top: 10px and right: 10px."}],
  hint:`<style>\n  .product { position: relative; width: 200px; padding: 24px; background: #CDEFD9; border-radius: 12px; }\n  .sale { position: absolute; top: 10px; right: 10px; background: crimson; color: white; padding: 2px 8px; border-radius: 6px; }\n</style>\n<div class="product">\n  <span class="sale">-50%</span>\n  <h3>Mango</h3>\n</div>`},
 {type:"code",title:"Sticky header",
  body:`<p>Make the ${C("header")} stay at the top while scrolling: ${C("position: sticky")} and ${C("top: 0")}.</p>`,
  start:`<style>\n  .page { height: 160px; overflow: auto; }\n  header { background: #FF7A1A; color: white; padding: 8px; }\n</style>\n<div class="page">\n  <header>TypeMonkey</header>\n  <p>Line 1</p><p>Line 2</p><p>Line 3</p><p>Line 4</p><p>Line 5</p>\n</div>\n`,
  checks:[{sel:"header",style:{position:"sticky"},msg:"Give the header position: sticky."},{sel:"header",style:{top:"0px"},msg:"Add top: 0 to the header."}],
  hint:`<style>\n  .page { height: 160px; overflow: auto; }\n  header { position: sticky; top: 0; background: #FF7A1A; color: white; padding: 8px; }\n</style>\n<div class="page">\n  <header>TypeMonkey</header>\n  <p>Line 1</p><p>Line 2</p><p>Line 3</p><p>Line 4</p><p>Line 5</p>\n</div>`},
 {type:"done"}]},
{id:"web21",title:"Project: Recipe Card",sub:"semantic HTML + table + lists + position",project:true,steps:[
 {type:"talk",title:"TypeMonkey's banana smoothie",mood:"cheer",
  body:`<p>Recipe sites mix everything you've learned: headings, images with alt text, lists, tables and a little positioning. You'll build a recipe card for TypeMonkey's famous banana smoothie.</p>`,
  demo:`<style>\n  .recipe { position: relative; max-width: 300px; padding: 16px; background: #FFF4E5; border: 2px solid #FFB36B; border-radius: 16px; }\n  .time { position: absolute; top: 12px; right: 12px; background: #FF7A1A; color: white; padding: 2px 8px; border-radius: 99px; font-size: 12px; }\n  .recipe table { border-collapse: collapse; width: 100%; }\n  .recipe td { border-bottom: 1px solid #FFD8AD; padding: 4px; }\n</style>\n<article class="recipe">\n  <span class="time">5 min</span>\n  <h2>Banana Smoothie</h2>\n  <table>\n    <tr><td>Banana</td><td>2</td></tr>\n    <tr><td>Milk</td><td>1 cup</td></tr>\n    <tr><td>Honey</td><td>1 tsp</td></tr>\n  </table>\n  <ol><li>Peel the bananas.</li><li>Blend everything.</li><li>Enjoy!</li></ol>\n</article>`,
  say:"This is the goal. Let's build it in three steps."},
 {type:"code",title:"Step 1: the card",
  body:`<p>Make an ${C("&lt;article class=\"recipe\"&gt;")} with an ${C("&lt;h2&gt;")} recipe name and an ${C("&lt;ol&gt;")} of at least 3 steps.</p>`,
  start:`<!-- article.recipe with an h2 and an ol -->\n`,
  checks:[{sel:"article.recipe h2",text:/\S/,msg:"Add <article class=\"recipe\"> with an <h2> name."},{sel:"article.recipe ol > li",count:3,msg:"Add an <ol> with at least 3 <li> steps inside the article."}],
  hint:`<article class="recipe">\n  <h2>Banana Smoothie</h2>\n  <ol>\n    <li>Peel the bananas.</li>\n    <li>Blend everything.</li>\n    <li>Enjoy!</li>\n  </ol>\n</article>`},
 {type:"code",title:"Step 2: ingredients table",
  body:`<p>Add a ${C("&lt;table&gt;")} of ingredients inside the article with at least 3 rows of 2 ${C("&lt;td&gt;")} cells (ingredient and amount). Give the table ${C("border-collapse: collapse")}.</p>`,
  start:`<style>\n</style>\n<article class="recipe">\n  <h2>Banana Smoothie</h2>\n  <!-- ingredients table here -->\n  <ol><li>Peel.</li><li>Blend.</li><li>Enjoy!</li></ol>\n</article>\n`,
  checks:[{sel:".recipe table tr",count:3,msg:"Add a table with at least 3 rows inside the article."},{sel:".recipe table td",count:6,msg:"Give each row 2 <td> cells: ingredient and amount."},{sel:".recipe table",style:{"border-collapse":"collapse"},msg:"Give the table border-collapse: collapse."}],
  hint:`<style>\n  .recipe table { border-collapse: collapse; }\n  .recipe td { border-bottom: 1px solid #FFD8AD; padding: 4px; }\n</style>\n<article class="recipe">\n  <h2>Banana Smoothie</h2>\n  <table>\n    <tr><td>Banana</td><td>2</td></tr>\n    <tr><td>Milk</td><td>1 cup</td></tr>\n    <tr><td>Honey</td><td>1 tsp</td></tr>\n  </table>\n  <ol><li>Peel.</li><li>Blend.</li><li>Enjoy!</li></ol>\n</article>`},
 {type:"code",title:"Step 3: time badge",
  body:`<p>Add a ${C("&lt;span class=\"time\"&gt;")} inside the article. Make ${C(".recipe")} ${C("position: relative")} and pin ${C(".time")} with ${C("position: absolute")}, ${C("top: 12px")} and ${C("right: 12px")}.</p>`,
  start:`<style>\n  .recipe { padding: 16px; background: #FFF4E5; border-radius: 16px; }\n  .time { background: #FF7A1A; color: white; padding: 2px 8px; border-radius: 99px; }\n</style>\n<article class="recipe">\n  <h2>Banana Smoothie</h2>\n  <ol><li>Peel.</li><li>Blend.</li><li>Enjoy!</li></ol>\n</article>\n`,
  checks:[{sel:".recipe .time",text:/\S/,msg:"Add <span class=\"time\">5 min</span> inside the article."},{sel:".recipe",style:{position:"relative"},msg:"Give .recipe position: relative."},{sel:".time",style:{position:"absolute",top:"12px",right:"12px"},msg:"Give .time position: absolute, top: 12px and right: 12px."}],
  hint:`<style>\n  .recipe { position: relative; padding: 16px; background: #FFF4E5; border-radius: 16px; }\n  .time { position: absolute; top: 12px; right: 12px; background: #FF7A1A; color: white; padding: 2px 8px; border-radius: 99px; }\n</style>\n<article class="recipe">\n  <span class="time">5 min</span>\n  <h2>Banana Smoothie</h2>\n  <ol><li>Peel.</li><li>Blend.</li><li>Enjoy!</li></ol>\n</article>`},
 {type:"quiz",q:"Why use <article> for the recipe instead of <div>?",opts:["It says this is a complete piece of content that stands on its own","It makes the text bigger","Divs can't hold lists"],a:0,mono:true,why:"article is semantic: a blog post, a recipe, a news story."},
 {type:"talk",title:"Recipe complete!",mood:"cheer",
  body:`<p>You combined semantic HTML, a table, a list and absolute positioning into one real component. Try adding a ${C("&lt;figure&gt;")} with a photo and good alt text to make it even better.</p>`,
  say:"Chef TypeMonkey approves. 🍌"},
 {type:"done"}]}
]});

COURSE_WEB.units.push({name:"Layout like a pro",lessons:[
{id:"web22",title:"Flexbox, deeper",sub:"grow, columns, align-self",steps:[
 {type:"talk",title:"flex-grow: take the extra space",
  body:`<p>Give a flex item ${C("flex-grow: 1")} and it stretches to fill any leftover space in the row. Give two items ${C("1")} and ${C("2")} and the second takes twice as much of the extra space.</p>`,
  demo:`<style>\n  .bar { display: flex; gap: 6px; }\n  .bar div { background: #FFD25C; padding: 10px; border-radius: 8px; }\n  .search { flex-grow: 1; background: #FFF4E5 !important; }\n</style>\n<div class="bar">\n  <div>🐒</div>\n  <div class="search">Search...</div>\n  <div>👤</div>\n</div>`,
  say:"This is how search bars stretch across the top of a site."},
 {type:"talk",title:"Columns and align-self",mood:"think",
  body:`<p>${C("flex-direction: column")} stacks items top to bottom instead of left to right. ${C("align-self")} lets one item line up differently from the rest.</p>`,
  demo:`<style>\n  .chat { display: flex; flex-direction: column; gap: 6px; max-width: 260px; }\n  .msg { background: #E6E1FF; padding: 8px 12px; border-radius: 12px; align-self: flex-start; }\n  .me { background: #FFD25C; align-self: flex-end; }\n</style>\n<div class="chat">\n  <div class="msg">Hi Mo!</div>\n  <div class="msg me">Hey! Want a banana?</div>\n  <div class="msg">Always.</div>\n</div>`,
  say:"A chat app layout in a few lines: your messages on the right."},
 {type:"quiz",q:"Which property stacks flex items top to bottom?",opts:["flex-direction: column","flex-wrap: wrap","align-items: column"],a:0,mono:true,why:"flex-direction switches the main direction from row to column."},
 {type:"fill",title:"Stretch it",body:`<p>Make the middle item fill the leftover space.</p>`,code:`<style>\n  .middle { [0]: [1]; }\n</style>`,blanks:["flex-grow","1"],tokens:["flex-grow","1","grow","100"],why:"flex-grow: 1 lets an item take the free space."},
 {type:"code",title:"Stretchy search bar",
  body:`<p>The ${C(".top")} bar is already a flex row. Give ${C(".search")} ${C("flex-grow: 1")} so it fills the gap between the logo and the button.</p>`,
  start:`<style>\n  .top { display: flex; gap: 8px; align-items: center; }\n  .search { padding: 8px; }\n</style>\n<div class="top">\n  <b>🐒</b>\n  <input class="search" placeholder="Search lessons">\n  <button>Go</button>\n</div>\n`,
  checks:[{sel:".search",style:{"flex-grow":"1"},msg:"Give .search flex-grow: 1."}],
  hint:`<style>\n  .top { display: flex; gap: 8px; align-items: center; }\n  .search { padding: 8px; flex-grow: 1; }\n</style>\n<div class="top">\n  <b>🐒</b>\n  <input class="search" placeholder="Search lessons">\n  <button>Go</button>\n</div>`},
 {type:"code",title:"Chat bubbles",
  body:`<p>Make ${C(".chat")} a flex ${C("column")}. Then make ${C(".me")} sit on the right with ${C("align-self: flex-end")}.</p>`,
  start:`<style>\n  .chat { gap: 6px; }\n  .chat div { background: #E6E1FF; padding: 8px 12px; border-radius: 12px; }\n  .chat .me { background: #FFD25C; }\n</style>\n<div class="chat">\n  <div>Did you finish the lesson?</div>\n  <div class="me">Yes! Flexbox is fun.</div>\n</div>\n`,
  checks:[{sel:".chat",style:{display:"flex","flex-direction":"column"},msg:"Give .chat display: flex and flex-direction: column."},{sel:".me",style:{"align-self":"flex-end"},msg:"Give .me align-self: flex-end."}],
  hint:`<style>\n  .chat { display: flex; flex-direction: column; gap: 6px; }\n  .chat div { background: #E6E1FF; padding: 8px 12px; border-radius: 12px; align-self: flex-start; }\n  .chat .me { background: #FFD25C; align-self: flex-end; }\n</style>\n<div class="chat">\n  <div>Did you finish the lesson?</div>\n  <div class="me">Yes! Flexbox is fun.</div>\n</div>`},
 {type:"quiz",q:"Item A has flex-grow: 1 and item B has flex-grow: 2. Who gets more of the extra space?",opts:["B gets twice as much as A","A gets twice as much as B","They get the same"],a:0,why:"The numbers are shares of the leftover space."},
 {type:"done"}]},
{id:"web23",title:"Grid, deeper",sub:"spanning and named areas",steps:[
 {type:"talk",title:"Spanning columns",
  body:`<p>A grid item can stretch across several columns with ${C("grid-column: span 2")}. Rows work the same way with ${C("grid-row")}.</p>`,
  demo:`<style>\n  .g { display: grid; grid-template-columns: repeat(3, 1fr); gap: 6px; }\n  .g div { background: #CDEFD9; padding: 12px; border-radius: 8px; text-align: center; }\n  .wide { grid-column: span 2; background: #FFD25C !important; }\n</style>\n<div class="g">\n  <div class="wide">Featured (2 columns)</div>\n  <div>A</div>\n  <div>B</div><div>C</div><div>D</div>\n</div>`,
  say:"Great for a big featured item in a gallery."},
 {type:"talk",title:"grid-template-areas",mood:"think",
  body:`<p>Draw your layout with words! ${C("grid-template-areas")} names each cell, then each item picks its spot with ${C("grid-area")}. Each quoted string is one row.</p>`,
  demo:`<style>\n  .page { display: grid; gap: 6px;\n    grid-template-columns: 1fr 2fr;\n    grid-template-areas:\n      "head head"\n      "side main"\n      "foot foot"; }\n  .page > * { background: #E6E1FF; padding: 10px; border-radius: 8px; }\n  header { grid-area: head; }\n  aside { grid-area: side; }\n  main { grid-area: main; }\n  footer { grid-area: foot; }\n</style>\n<div class="page">\n  <header>Header</header>\n  <aside>Sidebar</aside>\n  <main>Main content</main>\n  <footer>Footer</footer>\n</div>`,
  say:"You can almost see the layout in the CSS. That's why people love it."},
 {type:"quiz",q:"In grid-template-areas, what does each quoted string stand for?",opts:["One row of the grid","One column of the grid","One item"],a:0,why:"\"head head\" is the first row, spanning both columns."},
 {type:"fill",title:"Go wide",body:`<p>Make the banner span 3 columns.</p>`,code:`<style>\n  .banner { grid-column: [0] 3; }\n</style>`,blanks:["span"],tokens:["span","stretch","across","wide"],why:"grid-column: span 3 covers three columns."},
 {type:"code",title:"Featured tile",
  body:`<p>The ${C(".tiles")} grid has 3 columns. Make ${C(".big")} span 2 columns with ${C("grid-column: span 2")}.</p>`,
  start:`<style>\n  .tiles { display: grid; grid-template-columns: repeat(3, 1fr); gap: 6px; }\n  .tiles div { background: #CDEFD9; padding: 14px; border-radius: 8px; }\n</style>\n<div class="tiles">\n  <div class="big">🍌 Banana of the day</div>\n  <div>🥭</div><div>🥝</div><div>🍍</div>\n</div>\n`,
  checks:[{sel:".big",style:{"grid-column-start":/span 2/},msg:"Give .big grid-column: span 2."}],
  hint:`<style>\n  .tiles { display: grid; grid-template-columns: repeat(3, 1fr); gap: 6px; }\n  .tiles div { background: #CDEFD9; padding: 14px; border-radius: 8px; }\n  .big { grid-column: span 2; }\n</style>\n<div class="tiles">\n  <div class="big">🍌 Banana of the day</div>\n  <div>🥭</div><div>🥝</div><div>🍍</div>\n</div>`},
 {type:"code",title:"Draw a layout",
  body:`<p>Give ${C(".app")} ${C("grid-template-areas: \"top top\" \"nav main\"")}. Then put ${C("header")} in ${C("top")}, ${C("nav")} in ${C("nav")} and ${C("main")} in ${C("main")} using ${C("grid-area")}.</p>`,
  start:`<style>\n  .app { display: grid; grid-template-columns: 1fr 3fr; gap: 6px; }\n  .app > * { background: #FFF4E5; padding: 10px; }\n</style>\n<div class="app">\n  <header>TypeMonkey</header>\n  <nav>Menu</nav>\n  <main>Lessons go here</main>\n</div>\n`,
  checks:[{sel:".app",style:{"grid-template-areas":/"top top"\s*"nav main"/},msg:"Set grid-template-areas: \"top top\" \"nav main\" on .app."},{sel:".app header",style:{"grid-row-start":"top"},msg:"Give header grid-area: top."},{sel:".app nav",style:{"grid-row-start":"nav"},msg:"Give nav grid-area: nav."},{sel:".app main",style:{"grid-row-start":"main"},msg:"Give main grid-area: main."}],
  hint:`<style>\n  .app { display: grid; grid-template-columns: 1fr 3fr; gap: 6px;\n    grid-template-areas: "top top" "nav main"; }\n  .app > * { background: #FFF4E5; padding: 10px; }\n  header { grid-area: top; }\n  nav { grid-area: nav; }\n  main { grid-area: main; }\n</style>\n<div class="app">\n  <header>TypeMonkey</header>\n  <nav>Menu</nav>\n  <main>Lessons go here</main>\n</div>`},
 {type:"done"}]},
{id:"web24",title:"Smarter selectors",sub:"descendants, nth-child, specificity",steps:[
 {type:"talk",title:"Combining selectors",
  body:`<p>${C(".menu a")} (with a space) means "any ${C("a")} inside ${C(".menu")}". ${C(".menu > a")} means only direct children. ${C("h1, h2")} (with a comma) styles both.</p>`,
  demo:`<style>\n  .menu a { color: #FF7A1A; font-weight: bold; }\n  h2, h3 { font-family: Georgia, serif; }\n</style>\n<h2>Menu</h2>\n<nav class="menu"><a href="#">Home</a> · <a href="#">Games</a></nav>\n<p><a href="#">This link is outside .menu, so it stays normal.</a></p>\n<h3>Same font as the h2</h3>`,
  say:"Selectors let you style exactly what you want, no extra classes needed."},
 {type:"talk",title:"nth-child and friends",mood:"think",
  body:`<p>Pseudo-classes pick elements by position: ${C(":first-child")}, ${C(":last-child")} and ${C(":nth-child(even)")} or ${C(":nth-child(3)")}. Perfect for striped lists and tables.</p>`,
  demo:`<style>\n  li { padding: 6px; }\n  li:nth-child(even) { background: #FFF4E5; }\n  li:first-child { font-weight: bold; }\n</style>\n<ul>\n  <li>Leaderboard</li>\n  <li>Mo</li>\n  <li>Kiki</li>\n  <li>Bao</li>\n  <li>Zuri</li>\n</ul>`,
  say:"Add a new item and the stripes update all by themselves."},
 {type:"talk",title:"Who wins? Specificity",mood:"think",
  body:`<p>When two rules disagree, the more <b>specific</b> one wins: an ${C("#id")} beats a ${C(".class")}, which beats a plain tag like ${C("p")}. If they tie, the rule written <b>later</b> wins.</p>`,
  demo:`<style>\n  p { color: gray; }\n  .note { color: teal; }\n  p { color: crimson; }\n</style>\n<p class="note">I'm teal: the class beats both tag rules.</p>\n<p>I'm crimson: the later tag rule wins the tie.</p>`,
  say:"Keep it simple: style with classes most of the time."},
 {type:"quiz",q:"Which selector styles only links INSIDE .footer?",opts:[".footer a",".footer, a","a.footer"],a:0,mono:true,why:"A space means \"inside\". A comma means \"and also\". a.footer is a link that has the class."},
 {type:"quiz",q:"<p class=\"tip\"> has two rules: p { color: red } and .tip { color: blue }. What color is it?",opts:["Blue","Red","Purple"],a:0,why:"A class selector is more specific than a tag selector."},
 {type:"code",title:"Striped list",
  body:`<p>Use ${C("li:nth-child(even)")} to give every even list item a ${C("background")} of ${C("lightyellow")}.</p>`,
  start:`<style>\n  li { padding: 6px; }\n</style>\n<ol>\n  <li>Mo</li>\n  <li>Kiki</li>\n  <li>Bao</li>\n  <li>Zuri</li>\n</ol>\n`,
  use:[[/:nth-child\(\s*(even|2n)\s*\)/,"Use li:nth-child(even) in your CSS."]],
  checks:[{sel:"li:nth-child(2)",style:{"background-color":"lightyellow"},msg:"Even items should get background: lightyellow."},{sel:"li:nth-child(1)",style:{"background-color":"rgba(0, 0, 0, 0)"},msg:"Odd items should stay plain. Only style the even ones."}],
  hint:`<style>\n  li { padding: 6px; }\n  li:nth-child(even) { background: lightyellow; }\n</style>\n<ol>\n  <li>Mo</li>\n  <li>Kiki</li>\n  <li>Bao</li>\n  <li>Zuri</li>\n</ol>`},
 {type:"code",title:"Only the nav links",
  body:`<p>Without adding any classes to the links, make the links inside ${C("nav")} ${C("orange")} using a descendant selector. The link in the footer should stay as it is.</p>`,
  start:`<style>\n</style>\n<nav><a href="#">Home</a> <a href="#">Learn</a></nav>\n<footer><a href="#">Privacy</a></footer>\n`,
  checks:[{sel:"nav a",style:{color:"orange"},msg:"Make links inside nav orange with a selector like: nav a { color: orange; }"},{sel:"footer a",style:{color:/^(?!rgb\(255, 165, 0\)).*/},msg:"Only the nav links should be orange, not the footer link."}],
  use:[[/nav\s+a\s*\{/,"Use the descendant selector nav a."]],
  hint:`<style>\n  nav a { color: orange; }\n</style>\n<nav><a href="#">Home</a> <a href="#">Learn</a></nav>\n<footer><a href="#">Privacy</a></footer>`},
 {type:"done"}]},
{id:"web25",title:"CSS animations",sub:"@keyframes and animation",steps:[
 {type:"talk",title:"Keyframes",mood:"cheer",
  body:`<p>Transitions animate between two states on hover. <b>Animations</b> can run on their own. First describe the steps with ${C("@keyframes")}, then attach it with ${C("animation: name duration")}.</p>`,
  demo:`<style>\n  @keyframes bounce {\n    from { transform: translateY(0); }\n    to { transform: translateY(-20px); }\n  }\n  .monkey { display: inline-block; font-size: 48px; animation: bounce 0.6s infinite alternate; }\n</style>\n<div class="monkey">🐒</div>`,
  say:"infinite repeats forever. alternate plays it backwards on every other round."},
 {type:"talk",title:"Percent steps",mood:"think",
  body:`<p>Use percentages for more than two steps. ${C("0%")} is the start and ${C("100%")} is the end. You can animate colors, sizes, rotation and more.</p>`,
  demo:`<style>\n  @keyframes party {\n    0% { background: #FFD25C; }\n    50% { background: #FF7A1A; transform: rotate(4deg); }\n    100% { background: #FFD25C; }\n  }\n  .banner { padding: 12px; border-radius: 10px; text-align: center; font-weight: bold; animation: party 2s infinite; }\n</style>\n<div class="banner">🎉 You leveled up! 🎉</div>`,
  say:"Use motion to celebrate, but don't overdo it. Some people find a lot of movement uncomfortable."},
 {type:"quiz",q:"Where do you describe the steps of an animation?",opts:["In @keyframes","In @media","In transition"],a:0,mono:true,why:"@keyframes name { ... } defines what changes over time."},
 {type:"fill",title:"Spin forever",body:`<p>Run the spin animation for 2 seconds, forever.</p>`,code:`<style>\n  .icon { animation: spin 2s [0]; }\n</style>`,blanks:["infinite"],tokens:["infinite","forever","loop","always"],why:"infinite makes the animation repeat without stopping."},
 {type:"code",title:"Wiggle!",
  body:`<p>Write a ${C("@keyframes wiggle")} that rotates from ${C("-10deg")} to ${C("10deg")}. Then give ${C(".bell")} ${C("animation: wiggle 0.5s infinite alternate")}.</p>`,
  start:`<style>\n  .bell { display: inline-block; font-size: 40px; }\n</style>\n<div class="bell">🔔</div>\n`,
  use:[[/@keyframes\s+wiggle\s*\{[\s\S]*rotate/,"Write @keyframes wiggle { ... } with rotate() inside."]],
  checks:[{sel:".bell",style:{"animation-name":"wiggle"},msg:"Attach the animation: animation: wiggle 0.5s infinite alternate;"},{sel:".bell",style:{"animation-duration":"0.5s"},msg:"Make the animation last 0.5s."},{sel:".bell",style:{"animation-iteration-count":"infinite"},msg:"Make it repeat with infinite."}],
  hint:`<style>\n  @keyframes wiggle {\n    from { transform: rotate(-10deg); }\n    to { transform: rotate(10deg); }\n  }\n  .bell { display: inline-block; font-size: 40px; animation: wiggle 0.5s infinite alternate; }\n</style>\n<div class="bell">🔔</div>`},
 {type:"talk",title:"Be kind with motion",mood:"think",
  body:`<p>Some people get dizzy from motion, so their devices ask for less of it. The ${C("prefers-reduced-motion")} media query lets you turn animations off for them.</p>`,
  demo:`<style>\n  @keyframes pulse { to { transform: scale(1.2); } }\n  .heart { display: inline-block; font-size: 40px; animation: pulse 0.8s infinite alternate; }\n  @media (prefers-reduced-motion: reduce) {\n    .heart { animation: none; }\n  }\n</style>\n<div class="heart">💛</div>`,
  say:"Good web developers think about everyone who uses their page."},
 {type:"code",title:"Fade in",
  body:`<p>Write ${C("@keyframes fadeIn")} that goes from ${C("opacity: 0")} to ${C("opacity: 1")}, and give ${C(".hello")} ${C("animation: fadeIn 1s")}.</p>`,
  start:`<style>\n</style>\n<h2 class="hello">Welcome back! 🍌</h2>\n`,
  use:[[/@keyframes\s+fadeIn\s*\{[\s\S]*opacity\s*:\s*0[\s\S]*opacity\s*:\s*1/,"Write @keyframes fadeIn going from opacity: 0 to opacity: 1."]],
  checks:[{sel:".hello",style:{"animation-name":"fadeIn","animation-duration":"1s"},msg:"Give .hello animation: fadeIn 1s;"}],
  hint:`<style>\n  @keyframes fadeIn {\n    from { opacity: 0; }\n    to { opacity: 1; }\n  }\n  .hello { animation: fadeIn 1s; }\n</style>\n<h2 class="hello">Welcome back! 🍌</h2>`},
 {type:"done"}]},
{id:"web26",title:"Project: TypeMonkey Fan Page",sub:"semantic layout + grid areas + animation + responsive",project:true,steps:[
 {type:"talk",title:"The ultimate fan page",mood:"cheer",
  body:`<p>Time to put Unit 7 together. You'll build a fan page for TypeMonkey with a named grid layout, theme variables, a bouncing mascot and a layout that stacks on phones.</p>`,
  demo:`<style>\n  .fan { --brand: #FF7A1A; display: grid; gap: 8px; grid-template-columns: 1fr 2fr;\n    grid-template-areas: "head head" "side main" "foot foot"; }\n  .fan > * { background: #FFF4E5; padding: 10px; border-radius: 10px; }\n  .fan header { grid-area: head; background: var(--brand); color: white; display: flex; align-items: center; gap: 10px; }\n  .fan aside { grid-area: side; }\n  .fan main { grid-area: main; }\n  .fan footer { grid-area: foot; text-align: center; font-size: 13px; }\n  @keyframes bounce { to { transform: translateY(-8px); } }\n  .mascot { display: inline-block; font-size: 32px; animation: bounce 0.6s infinite alternate; }\n  @media (max-width: 500px) { .fan { grid-template-columns: 1fr; grid-template-areas: "head" "main" "side" "foot"; } }\n</style>\n<div class="fan">\n  <header><span class="mascot">🐒</span><h2 style="margin:0">TypeMonkey Fans</h2></header>\n  <aside><b>Fun facts</b><ul><li>Loves bananas</li><li>Types 90 wpm</li></ul></aside>\n  <main><h3>Why we love TypeMonkey</h3><p>He makes coding feel like a game.</p></main>\n  <footer>Made with 🍌 by fans</footer>\n</div>`,
  say:"Here's the goal. Let's build it step by step."},
 {type:"code",title:"Step 1: semantic skeleton",
  body:`<p>Inside ${C(".fan")}, add a ${C("&lt;header&gt;")} with an ${C("&lt;h2&gt;")}, an ${C("&lt;aside&gt;")}, a ${C("&lt;main&gt;")} with a paragraph, and a ${C("&lt;footer&gt;")}.</p>`,
  start:`<div class="fan">\n</div>\n`,
  checks:[{sel:".fan > header h2",text:/\S/,msg:"Add a <header> with an <h2> inside .fan."},{sel:".fan > aside",msg:"Add an <aside> inside .fan."},{sel:".fan > main p",msg:"Add a <main> with a <p> inside .fan."},{sel:".fan > footer",msg:"Add a <footer> inside .fan."}],
  hint:`<div class="fan">\n  <header><h2>TypeMonkey Fans</h2></header>\n  <aside>Fun facts</aside>\n  <main><p>He makes coding feel like a game.</p></main>\n  <footer>Made with 🍌 by fans</footer>\n</div>`},
 {type:"code",title:"Step 2: grid areas and a theme",
  body:`<p>Define ${C("--brand: #FF7A1A")} on ${C(".fan")} and make it a grid with ${C("grid-template-areas: \"head head\" \"side main\" \"foot foot\"")}. Place each part with ${C("grid-area")}, and give the header ${C("background: var(--brand)")}.</p>`,
  start:`<style>\n  .fan { gap: 8px; grid-template-columns: 1fr 2fr; }\n</style>\n<div class="fan">\n  <header><h2>TypeMonkey Fans</h2></header>\n  <aside>Fun facts</aside>\n  <main><p>He makes coding feel like a game.</p></main>\n  <footer>Made with 🍌 by fans</footer>\n</div>\n`,
  use:[[/--brand\s*:\s*#FF7A1A/i,"Define --brand: #FF7A1A on .fan."],[/var\(\s*--brand\s*\)/,"Use var(--brand) for the header background."]],
  checks:[{sel:".fan",style:{display:"grid","grid-template-areas":/"head head"\s*"side main"\s*"foot foot"/},msg:"Make .fan display: grid with the three rows of grid-template-areas."},{sel:".fan > header",style:{"grid-row-start":"head","background-color":"rgb(255, 122, 26)"},msg:"Give the header grid-area: head and background: var(--brand)."},{sel:".fan > aside",style:{"grid-row-start":"side"},msg:"Give aside grid-area: side."},{sel:".fan > main",style:{"grid-row-start":"main"},msg:"Give main grid-area: main."},{sel:".fan > footer",style:{"grid-row-start":"foot"},msg:"Give footer grid-area: foot."}],
  hint:`<style>\n  .fan { --brand: #FF7A1A; display: grid; gap: 8px; grid-template-columns: 1fr 2fr;\n    grid-template-areas: "head head" "side main" "foot foot"; }\n  .fan header { grid-area: head; background: var(--brand); color: white; }\n  .fan aside { grid-area: side; }\n  .fan main { grid-area: main; }\n  .fan footer { grid-area: foot; }\n</style>\n<div class="fan">\n  <header><h2>TypeMonkey Fans</h2></header>\n  <aside>Fun facts</aside>\n  <main><p>He makes coding feel like a game.</p></main>\n  <footer>Made with 🍌 by fans</footer>\n</div>`},
 {type:"code",title:"Step 3: bouncing mascot",
  body:`<p>Add a ${C("&lt;span class=\"mascot\"&gt;🐒&lt;/span&gt;")} to the header. Write a ${C("@keyframes bounce")} and give ${C(".mascot")} ${C("animation: bounce 0.6s infinite alternate")}.</p>`,
  start:`<style>\n  .mascot { display: inline-block; font-size: 32px; }\n</style>\n<header><h2>TypeMonkey Fans</h2></header>\n`,
  use:[[/@keyframes\s+bounce\s*\{/,"Write @keyframes bounce { ... }."]],
  checks:[{sel:"header .mascot",msg:"Add <span class=\"mascot\">🐒</span> inside the header."},{sel:".mascot",style:{"animation-name":"bounce","animation-iteration-count":"infinite"},msg:"Give .mascot animation: bounce 0.6s infinite alternate;"}],
  hint:`<style>\n  @keyframes bounce {\n    from { transform: translateY(0); }\n    to { transform: translateY(-8px); }\n  }\n  .mascot { display: inline-block; font-size: 32px; animation: bounce 0.6s infinite alternate; }\n</style>\n<header><span class="mascot">🐒</span><h2>TypeMonkey Fans</h2></header>`},
 {type:"code",title:"Step 4: phone friendly",
  body:`<p>Add a ${C("@media (max-width: 500px)")} rule that switches ${C(".fan")} to one column: ${C("grid-template-columns: 1fr")}.</p>`,
  start:`<style>\n  .fan { display: grid; gap: 8px; grid-template-columns: 1fr 2fr; }\n  .fan > * { background: #FFF4E5; padding: 10px; }\n</style>\n<div class="fan">\n  <aside>Fun facts</aside>\n  <main>Why we love TypeMonkey</main>\n</div>\n`,
  use:[[/@media\s*\(\s*max-width\s*:\s*500px\s*\)\s*\{[\s\S]*\.fan\s*\{[^}]*grid-template-columns\s*:\s*1fr\s*;?\s*[^}]*\}/,"Inside @media (max-width: 500px), set .fan { grid-template-columns: 1fr; }"]],
  checks:[{sel:".fan > *",count:2,msg:"Keep the aside and main inside .fan."}],
  hint:`<style>\n  .fan { display: grid; gap: 8px; grid-template-columns: 1fr 2fr; }\n  .fan > * { background: #FFF4E5; padding: 10px; }\n  @media (max-width: 500px) {\n    .fan { grid-template-columns: 1fr; }\n  }\n</style>\n<div class="fan">\n  <aside>Fun facts</aside>\n  <main>Why we love TypeMonkey</main>\n</div>`},
 {type:"talk",title:"You're a layout pro!",mood:"cheer",
  body:`<p>Semantic HTML, named grid areas, CSS variables, keyframe animation and a responsive layout, all in one page. That's real front-end developer work. Tap ▶ Show page on the first step to see the full version, then make it your own.</p>`,
  say:"TypeMonkey is officially your biggest fan. 🐒🍌"},
 {type:"done"}]}
]});
