/* deep-game: launch depth units for Build a Game (Unit 5: shops, cards & scores; Unit 6: battles & bosses).
   Same step schema and arcade conventions as game.js. Randomness uses DICE (seeded roll()) so results can be checked. */
(() => {
const ATTACK_FN=`function attack(a, b) {\n  b.hp = Math.max(0, b.hp - a.power);\n  console.log(a.name + " hits " + b.name + " (" + b.hp + " hp left)");\n}\n`;
const HOL_TOP=`const deck = [5, 9, 2, 7, 3, 8];\nconst guesses = ["higher", "higher", "higher", "higher", "lower"];\nlet current = deck.shift();\nlet score = 0;\n`;
const BOSS_TOP=`const hero = { name: "Mo", hp: 10, maxHp: 10, power: 3 };\nconst boss = { name: "King Gorilla", hp: 12, maxHp: 12, power: 2 };\nconst moves = ["attack", "attack", "heal", "attack"];\nfor (const move of moves) {\n  if (move === "attack") {\n    boss.hp = Math.max(0, boss.hp - hero.power);\n    console.log("Mo attacks! King Gorilla: " + boss.hp + " hp");\n`;
const BOSS_HEAL=`  } else if (move === "heal") {\n    hero.hp = Math.min(hero.maxHp, hero.hp + 4);\n    console.log("Mo heals! Mo: " + hero.hp + " hp");\n  }\n`;
const BOSS_SMASH=`  if (boss.hp > 0) {\n    hero.hp = Math.max(0, hero.hp - boss.power);\n    console.log("King Gorilla smashes! Mo: " + hero.hp + " hp");\n  }\n}`;
const BOSS_RAGE=`    if (!boss.angry && boss.hp <= boss.maxHp / 2) {\n      boss.angry = true;\n      console.log("King Gorilla is ANGRY! Power up!");\n      boss.power *= 2;\n    }\n`;
const BOSS4_TOP=`const hero = { name: "Mo", hp: 10, maxHp: 10, power: 4 };\nconst boss = { name: "King Gorilla", hp: 12, maxHp: 12, power: 2 };\nconst moves = ["attack", "attack", "heal", "attack", "attack"];\nlet over = false;\nfor (const move of moves) {\n  if (move === "attack") {\n    boss.hp = Math.max(0, boss.hp - hero.power);\n    console.log("Mo attacks! King Gorilla: " + boss.hp + " hp");\n`+BOSS_RAGE+BOSS_HEAL;

COURSE_GAME.units.push(
{name:"Shops, cards & scores",lessons:[
{id:"g16",title:"Loot and shops",sub:"price lists and spending gold",steps:[
 {type:"talk",title:"Welcome to the market!",mood:"cheer",
  body:`<p>Lots of games have a shop. A shop is just a <b>price list</b>, and an object is perfect for that: each item's name points to its price.</p>`,
  demo:`const shop = { banana: 2, potion: 5, sword: 20 };\nconsole.log("🍌 banana: " + shop.banana + " gold");\nconsole.log("🧪 potion: " + shop.potion + " gold");`,
  say:"banana: 2 gold, potion: 5 gold. A tiny shop!"},
 {type:"talk",title:"Looking up a price",
  body:`<p>When the item's name is in a variable, use square brackets: ${C("shop[item]")}. It looks up whatever name ${C("item")} holds.</p>`,
  demo:`const shop = { banana: 2, potion: 5, sword: 20 };\nconst item = "sword";\nconsole.log(item + " costs " + shop[item] + " gold");`,
  say:"sword costs 20 gold. Change item to \"banana\" and try again!"},
 {type:"talk",title:"Can you afford it?",mood:"think",
  body:`<p>Before buying, check the gold with ${C("if (gold >= price)")}. If there's enough, take the price away with ${C("-=")}.</p>`,
  demo:`const shop = { banana: 2, potion: 5, sword: 20 };\nlet gold = 12;\nconst price = shop["potion"];\nif (gold >= price) {\n  gold -= price;\n  console.log("Bought a potion! Gold left: " + gold);\n} else {\n  console.log("Not enough gold");\n}`,
  say:"12 - 5 = 7. Bought a potion! Gold left: 7"},
 {type:"quiz",q:"What does this print?",code:`const shop = { apple: 3, cake: 8 };\nconsole.log(shop["cake"]);`,opts:["8","3","cake"],a:0,mono:true,why:"shop[\"cake\"] looks up the price of cake: 8."},
 {type:"fill",title:"Pay up",body:`<p>Take the price away from the gold.</p>`,code:`let gold = 10;\nconst price = 4;\ngold [0] price;\nconsole.log(gold);`,blanks:["-="],tokens:["-=","+=","=="],why:"-= takes away from what's already there: 10 - 4 = 6."},
 {type:"code",title:"Price tag",body:`<p>Print the price of ${C("item")} by looking it up with ${C("shop[item]")}. It should print ${C("potion costs 5 gold")}.</p>`,start:`const shop = { banana: 2, potion: 5, sword: 20 };\nconst item = "potion";\n// print: potion costs 5 gold\n`,
  use:[[/shop\[item\]/,"Look up the price with shop[item]."]],out:["potion costs 5 gold"],variants:[[/item = "potion"/,"item = \"sword\"",["sword costs 20 gold"]]],
  hint:`const shop = { banana: 2, potion: 5, sword: 20 };\nconst item = "potion";\nconsole.log(item + " costs " + shop[item] + " gold");`},
 {type:"code",title:"Buy it!",body:`<p>The ${C("if")} is ready. Fill in both parts: if there's enough gold, take ${C("price")} away from ${C("gold")} and print ${C("Bought sword! Gold left: 5")}. Otherwise print ${C("Not enough gold for sword")}.</p>`,start:`const shop = { banana: 2, potion: 5, sword: 20 };\nlet gold = 25;\nconst item = "sword";\nconst price = shop[item];\nif (gold >= price) {\n  // take away the price, then print what you bought\n} else {\n  // print the not-enough message\n}\n`,
  use:[[/-=|gold\s*=\s*gold\s*-/,"Take the price away from gold with -=."]],out:["Bought sword! Gold left: 5"],variants:[[/gold = 25/,"gold = 9",["Not enough gold for sword"]],[/item = "sword"/,"item = \"banana\"",["Bought banana! Gold left: 23"]]],
  hint:`const shop = { banana: 2, potion: 5, sword: 20 };\nlet gold = 25;\nconst item = "sword";\nconst price = shop[item];\nif (gold >= price) {\n  gold -= price;\n  console.log("Bought " + item + "! Gold left: " + gold);\n} else {\n  console.log("Not enough gold for " + item);\n}`},
 {type:"game"},{type:"done"}],
 pool:[
  [`const shop = { hat: 4 };\nconsole.log(shop.hat * 2);`,["8","4","hat2"]],
  [`let gold = 7;\ngold -= 3;\nconsole.log(gold);`,["4","10","7"]],
  [`const p = { a: 1, b: 2 };\nconst k = "b";\nconsole.log(p[k]);`,["2","1","b"]],
  [`const gold = 3;\nconsole.log(gold >= 5 ? "Buy" : "Too poor");`,["Too poor","Buy","3"]],
  [`const bag = ["key"];\nbag.push("map");\nconsole.log(bag.length);`,["2","1","3"]]
 ]},
{id:"g17",title:"Higher or lower",sub:"a card game with a deck",steps:[
 {type:"talk",title:"A deck of cards",mood:"cheer",
  body:`<p>Let's make a card game! A deck is just an array of numbers. The first one is the top card.</p>`,
  demo:`const deck = [7, 3, 9, 2];\nconsole.log("🃏 Top card: " + deck[0]);\nconsole.log("Cards in the deck: " + deck.length);`,
  say:"Top card: 7, and 4 cards in the deck."},
 {type:"talk",title:"Drawing a card",
  body:`<p>${C("deck.shift()")} takes the top card <b>off</b> the deck and gives it to you. The deck gets one card shorter.</p>`,
  demo:`const deck = [7, 3, 9];\nconst card = deck.shift();\nconsole.log("You drew a " + card);\nconsole.log("Cards left: " + deck.length);`,
  say:"You drew a 7, and 2 cards are left."},
 {type:"talk",title:"Higher or lower?",mood:"think",
  body:`<p>The game: look at the card you have, then guess if the next one is <b>higher</b> or <b>lower</b>. An ${C("if")} tells us which it was.</p>`,
  demo:`const current = 5;\nconst next = 8;\nif (next > current) console.log("It was higher!");\nelse if (next < current) console.log("It was lower!");\nelse console.log("Same card!");`,
  say:"8 is bigger than 5, so: It was higher!"},
 {type:"quiz",q:"What does this print?",code:`const deck = [6, 2, 8];\nconst c = deck.shift();\nconsole.log(c + " " + deck.length);`,opts:["6 2","8 2","6 3"],a:0,mono:true,why:"shift takes the 6 off the top, leaving 2 cards."},
 {type:"order",title:"Draw a card",body:`<p>Arrange the lines so the program prints ${C("Drew 5")}.</p>`,
  lines:["const deck = [5, 1, 4];","const card = deck.shift();","console.log(\"Drew \" + card);"],why:"Make the deck, draw the top card, then show it."},
 {type:"code",title:"Which way?",body:`<p>The ${C("higher")} part is done. Add an ${C("else if")} that prints ${C("It was lower!")}, and an ${C("else")} that prints ${C("Same card!")}. Here 4 is lower than 10, so it should print ${C("It was lower!")}.</p>`,start:`const current = 10;\nconst next = 4;\nif (next > current) {\n  console.log("It was higher!");\n}\n// add the lower case and the same-card case here\n`,
  use:[[/else/,"Add else if and else after the first if."]],out:["It was lower!"],variants:[[/next = 4/,"next = 12",["It was higher!"]],[/next = 4/,"next = 10",["Same card!"]]],
  hint:`const current = 10;\nconst next = 4;\nif (next > current) {\n  console.log("It was higher!");\n} else if (next < current) {\n  console.log("It was lower!");\n} else {\n  console.log("Same card!");\n}`},
 {type:"code",title:"Score the guesses",body:`<p>The loop already works out the ${C("actual")} answer for each card. Add an ${C("if")}: when ${C("guesses[i - 1]")} matches ${C("actual")}, add 1 to ${C("score")}. Three guesses are right, so it should print ${C("Score: 3")}.</p>`,start:`const deck = [5, 9, 2, 7, 3];\nconst guesses = ["higher", "higher", "higher", "lower"];\nlet score = 0;\nfor (let i = 1; i < deck.length; i++) {\n  const actual = deck[i] > deck[i - 1] ? "higher" : "lower";\n  // if the guess matches actual, add 1 to score\n}\nconsole.log("Score: " + score);\n`,
  use:[[/===/,"Compare the guess and actual with ===."]],out:["Score: 3"],variants:[[/"higher", "higher", "higher", "lower"/,"\"higher\", \"lower\", \"higher\", \"lower\"",["Score: 4"]],[/"higher", "higher", "higher", "lower"/,"\"lower\", \"higher\", \"lower\", \"higher\"",["Score: 0"]]],
  hint:`const deck = [5, 9, 2, 7, 3];\nconst guesses = ["higher", "higher", "higher", "lower"];\nlet score = 0;\nfor (let i = 1; i < deck.length; i++) {\n  const actual = deck[i] > deck[i - 1] ? "higher" : "lower";\n  if (guesses[i - 1] === actual) {\n    score++;\n  }\n}\nconsole.log("Score: " + score);`},
 {type:"game"},{type:"done"}],
 pool:[
  [`const d = [3, 8];\nconsole.log(d[1] > d[0] ? "higher" : "lower");`,["higher","lower","8"]],
  [`const d = [1, 2, 3];\nd.shift();\nconsole.log(d.length);`,["2","3","1"]],
  [`const d = [9, 4];\nconsole.log(d.shift());`,["9","4","2"]],
  [`let s = 0;\nfor (const g of ["hi", "lo", "hi"]) if (g === "hi") s++;\nconsole.log(s);`,["2","3","1"]],
  [`const d = [5, 5];\nconsole.log(d[0] === d[1] ? "Same card!" : "Different");`,["Same card!","Different","5"]]
 ]},
{id:"g18",title:"High scores",sub:"a leaderboard with objects and sort",steps:[
 {type:"talk",title:"Who's the best?",mood:"cheer",
  body:`<p>Every arcade has a high score table. Each entry has a name <b>and</b> a score, so we keep a list of objects.</p>`,
  demo:`const scores = [\n  { name: "Mo", score: 120 },\n  { name: "Kiki", score: 340 }\n];\nfor (const s of scores) console.log(s.name + ": " + s.score);`,
  say:"Mo: 120, Kiki: 340"},
 {type:"talk",title:"Adding a new score",
  body:`<p>When a game ends, ${C("push")} the new score onto the list.</p>`,
  demo:`const scores = [\n  { name: "Mo", score: 120 },\n  { name: "Kiki", score: 340 }\n];\nscores.push({ name: "Bao", score: 200 });\nconsole.log("Players: " + scores.length);`,
  say:"Players: 3"},
 {type:"talk",title:"Sorting the board",mood:"think",
  body:`<p>${C("scores.sort((a, b) => b.score - a.score)")} puts the <b>biggest</b> score first. (Swap ${C("a")} and ${C("b")} and it goes smallest first.)</p>`,
  demo:`const scores = [\n  { name: "Mo", score: 120 },\n  { name: "Kiki", score: 340 },\n  { name: "Bao", score: 200 }\n];\nscores.sort((a, b) => b.score - a.score);\nfor (const s of scores) console.log(s.name + " " + s.score);`,
  say:"Kiki 340, Bao 200, Mo 120. Best first!"},
 {type:"talk",title:"Only the top 3",
  body:`<p>${C("slice(0, 3)")} keeps the first three. ${C("forEach")} gives you each item <b>and</b> its position, so you can number them.</p>`,
  demo:`const board = ["Kiki", "Bao", "Mo", "Ana"];\nconst top = board.slice(0, 3);\ntop.forEach((name, i) => console.log((i + 1) + ". " + name));`,
  say:"1. Kiki, 2. Bao, 3. Mo. Sorry Ana!"},
 {type:"quiz",q:"What does this print?",code:`const s = [3, 9, 5];\ns.sort((a, b) => b - a);\nconsole.log(s.join(","));`,opts:["9,5,3","3,5,9","3,9,5"],a:0,mono:true,why:"b - a sorts biggest first."},
 {type:"fill",title:"Add your score",body:`<p>Put a new score on the list.</p>`,code:`const scores = [];\nscores.[0]({ name: "Mo", score: 50 });\nconsole.log(scores.length);`,blanks:["push"],tokens:["push","pop","shift"],why:"push adds to the end of the list."},
 {type:"code",title:"New player",body:`<p>Add Ivy with 275 points using ${C("scores.push(...)")}, then print how many players there are with ${C("scores.length")}. It should print ${C("Players: 3")}.</p>`,start:`const scores = [\n  { name: "Mo", score: 120 },\n  { name: "Kiki", score: 340 }\n];\n// add Ivy with 275 points\n\n// print how many players there are\n`,
  use:[[/scores\.push/,"Add Ivy with scores.push(...)."],[/scores\.length/,"Count the players with scores.length."]],out:["Players: 3"],
  hint:`const scores = [\n  { name: "Mo", score: 120 },\n  { name: "Kiki", score: 340 }\n];\nscores.push({ name: "Ivy", score: 275 });\nconsole.log("Players: " + scores.length);`},
 {type:"code",title:"Leaderboard",body:`<p>The printing part is done. Add one line that sorts ${C("scores")} biggest first. Then it prints ${C("1. Kiki 340")}, ${C("2. Ivy 275")}, ${C("3. Mo 120")}.</p>`,start:`const scores = [\n  { name: "Mo", score: 120 },\n  { name: "Kiki", score: 340 },\n  { name: "Ivy", score: 275 },\n  { name: "Bao", score: 90 }\n];\n// sort the scores here (biggest first)\n\nconst top = scores.slice(0, 3);\ntop.forEach((s, i) => console.log((i + 1) + ". " + s.name + " " + s.score));\n`,
  use:[[/\.sort\s*\(/,"Sort with scores.sort(...)."]],out:["1. Kiki 340","2. Ivy 275","3. Mo 120"],variants:[[/score: 90/,"score: 999",["1. Bao 999","2. Kiki 340","3. Ivy 275"]]],
  hint:`const scores = [\n  { name: "Mo", score: 120 },\n  { name: "Kiki", score: 340 },\n  { name: "Ivy", score: 275 },\n  { name: "Bao", score: 90 }\n];\nscores.sort((a, b) => b.score - a.score);\n\nconst top = scores.slice(0, 3);\ntop.forEach((s, i) => console.log((i + 1) + ". " + s.name + " " + s.score));`},
 {type:"game"},{type:"done"}],
 pool:[
  [`const s = [{ n: "A", p: 5 }];\nconsole.log(s[0].n + s[0].p);`,["A5","5A","A 5"]],
  [`const s = [4, 1, 7];\ns.sort((a, b) => b - a);\nconsole.log(s[0]);`,["7","1","4"]],
  [`console.log([5, 6, 7, 8].slice(0, 3).length);`,["3","4","2"]],
  [`const s = [];\ns.push(10);\ns.push(20);\nconsole.log(s.length);`,["2","20","1"]],
  [`["Mo", "Ivy"].forEach((n, i) => console.log((i + 1) + "." + n));`,["1.Mo 2.Ivy","0.Mo 1.Ivy","Mo Ivy"]]
 ]},
{id:"g19",title:"Project: Higher or Lower Showdown",sub:"a full card game with lives and a high score table",project:true,steps:[
 {type:"talk",title:"Showdown time",mood:"cheer",
  body:`<p>Let's build the whole card game in four small steps: deal the cards, score the guesses, add lives and game over, then save your score on the high score table.</p>`,
  say:"One small step at a time. You've got this!"},
 {type:"code",title:"Step 1: deal the cards",body:`<p>The loop draws each next card for you. Inside it, print how the card compared, like ${C("5 then 9: higher")} (or ${C("lower")}).</p>`,start:`const deck = [5, 9, 2, 7, 3];\nlet current = deck.shift();\nwhile (deck.length > 0) {\n  const next = deck.shift();\n  // print like: 5 then 9: higher\n\n  current = next;\n}\n`,
  use:[[/next\s*[<>]\s*current|current\s*[<>]\s*next/,"Compare next with current using > or <."]],out:["5 then 9: higher","9 then 2: lower","2 then 7: higher","7 then 3: lower"],variants:[[/\[5, 9, 2, 7, 3\]/,"[1, 4, 6]",["1 then 4: higher","4 then 6: higher"]]],
  hint:`const deck = [5, 9, 2, 7, 3];\nlet current = deck.shift();\nwhile (deck.length > 0) {\n  const next = deck.shift();\n  const word = next > current ? "higher" : "lower";\n  console.log(current + " then " + next + ": " + word);\n  current = next;\n}`},
 {type:"code",title:"Step 2: right or wrong",body:`<p>Now the player guesses. Fill in both parts: a right guess adds 1 to ${C("score")} and prints ${C("Right! Score: 1")}. A wrong guess takes away a life and prints ${C("Wrong! Lives: 2")}.</p>`,start:HOL_TOP+`let lives = 3;\nfor (const guess of guesses) {\n  const next = deck.shift();\n  const actual = next > current ? "higher" : "lower";\n  if (guess === actual) {\n    // add 1 to score, then print: Right! Score: N\n  } else {\n    // take away a life, then print: Wrong! Lives: N\n  }\n  current = next;\n}\nconsole.log("Final score: " + score);\n`,
  use:[[/score\+\+|score\s*\+=\s*1/,"Add 1 to score with score++."],[/lives--|lives\s*-=\s*1/,"Take away a life with lives--."]],out:["Right! Score: 1","Wrong! Lives: 2","Right! Score: 2","Wrong! Lives: 1","Wrong! Lives: 0","Final score: 2"],variants:[[/"higher", "higher", "higher", "higher", "lower"/,"\"higher\", \"lower\", \"higher\", \"lower\", \"higher\"",["Right! Score: 1","Right! Score: 2","Right! Score: 3","Right! Score: 4","Right! Score: 5","Final score: 5"]]],
  hint:HOL_TOP+`let lives = 3;\nfor (const guess of guesses) {\n  const next = deck.shift();\n  const actual = next > current ? "higher" : "lower";\n  if (guess === actual) {\n    score++;\n    console.log("Right! Score: " + score);\n  } else {\n    lives--;\n    console.log("Wrong! Lives: " + lives);\n  }\n  current = next;\n}\nconsole.log("Final score: " + score);`},
 {type:"code",title:"Step 3: game over",body:`<p>Now there are only 2 lives. After losing a life, check: if ${C("lives")} is 0, print ${C("Game over!")} and stop the loop with ${C("break")}.</p>`,start:HOL_TOP+`let lives = 2;\nfor (const guess of guesses) {\n  const next = deck.shift();\n  const actual = next > current ? "higher" : "lower";\n  if (guess === actual) {\n    score++;\n    console.log("Right! Score: " + score);\n  } else {\n    lives--;\n    console.log("Wrong! Lives: " + lives);\n    // if lives is 0: print Game over! and break\n  }\n  current = next;\n}\nconsole.log("Final score: " + score);\n`,
  use:[[/\bbreak\b/,"Stop the loop with break."]],out:["Right! Score: 1","Wrong! Lives: 1","Right! Score: 2","Wrong! Lives: 0","Game over!","Final score: 2"],variants:[[/lives = 2/,"lives = 5",["Right! Score: 1","Wrong! Lives: 4","Right! Score: 2","Wrong! Lives: 3","Wrong! Lives: 2","Final score: 2"]]],
  hint:HOL_TOP+`let lives = 2;\nfor (const guess of guesses) {\n  const next = deck.shift();\n  const actual = next > current ? "higher" : "lower";\n  if (guess === actual) {\n    score++;\n    console.log("Right! Score: " + score);\n  } else {\n    lives--;\n    console.log("Wrong! Lives: " + lives);\n    if (lives === 0) {\n      console.log("Game over!");\n      break;\n    }\n  }\n  current = next;\n}\nconsole.log("Final score: " + score);`},
 {type:"code",title:"Step 4: the high score table",body:`<p>You scored ${C("myScore")}! Add ${C("{ name: \"You\", score: myScore }")} to ${C("scores")}, then sort biggest first. The table prints itself, starting ${C("1. You 5")}.</p>`,start:`const scores = [\n  { name: "Kiki", score: 4 },\n  { name: "Mo", score: 1 },\n  { name: "Bao", score: 3 }\n];\nconst myScore = 5;\n// 1. add your score to the list\n\n// 2. sort biggest first\n\nconsole.log("🏆 HIGH SCORES 🏆");\nscores.slice(0, 3).forEach((s, i) => console.log((i + 1) + ". " + s.name + " " + s.score));\n`,
  use:[[/scores\.push/,"Add your score with scores.push(...)."],[/\.sort\s*\(/,"Sort with scores.sort(...)."]],out:["🏆 HIGH SCORES 🏆","1. You 5","2. Kiki 4","3. Bao 3"],variants:[[/myScore = 5/,"myScore = 2",["🏆 HIGH SCORES 🏆","1. Kiki 4","2. Bao 3","3. You 2"]]],
  hint:`const scores = [\n  { name: "Kiki", score: 4 },\n  { name: "Mo", score: 1 },\n  { name: "Bao", score: 3 }\n];\nconst myScore = 5;\nscores.push({ name: "You", score: myScore });\nscores.sort((a, b) => b.score - a.score);\n\nconsole.log("🏆 HIGH SCORES 🏆");\nscores.slice(0, 3).forEach((s, i) => console.log((i + 1) + ". " + s.name + " " + s.score));`},
 {type:"done"}]}
]},
{name:"Battles & bosses",lessons:[
{id:"g20",title:"Turn-based battles",sub:"taking turns to attack",steps:[
 {type:"talk",title:"Your turn, my turn",mood:"cheer",
  body:`<p>In a turn-based battle, the hero attacks, then the monster attacks back. Each one is an object with ${C("hp")} and ${C("power")}.</p>`,
  demo:`const mo = { name: "Mo", hp: 10, power: 3 };\nconst slime = { name: "Slime", hp: 6, power: 1 };\nslime.hp -= mo.power;\nconsole.log("Mo hits Slime! Slime hp: " + slime.hp);\nmo.hp -= slime.power;\nconsole.log("Slime hits Mo! Mo hp: " + mo.hp);`,
  say:"Slime drops to 3, Mo drops to 9."},
 {type:"talk",title:"One function for every attack",
  body:`<p>Instead of writing every hit by hand, make ${C("attack(a, b)")}: ${C("a")} hits ${C("b")}. ${C("Math.max(0, ...)")} stops hp going below 0.</p>`,
  demo:ATTACK_FN+`\nconst mo = { name: "Mo", hp: 10, power: 4 };\nconst bat = { name: "Bat", hp: 7, power: 2 };\nattack(mo, bat);\nattack(bat, mo);`,
  say:"Mo hits Bat (3 hp left), Bat hits Mo (8 hp left)."},
 {type:"talk",title:"Fight until someone falls",mood:"think",
  body:`<p>Put the turns in a ${C("while")} loop that keeps going while <b>both</b> still have hp (${C("&&")}). The monster only hits back if it's still standing.</p>`,
  demo:ATTACK_FN+`\nconst mo = { name: "Mo", hp: 10, power: 4 };\nconst bat = { name: "Bat", hp: 7, power: 2 };\nwhile (mo.hp > 0 && bat.hp > 0) {\n  attack(mo, bat);\n  if (bat.hp > 0) attack(bat, mo);\n}\nconsole.log(mo.hp > 0 ? "You win!" : "You lose!");`,
  say:"Two hits from Mo and the bat is done. You win!"},
 {type:"quiz",q:"What does this print?",code:`const foe = { hp: 5 };\nfoe.hp = Math.max(0, foe.hp - 8);\nconsole.log(foe.hp);`,opts:["0","-3","5"],a:0,mono:true,why:"5 - 8 is -3, and Math.max(0, -3) picks 0."},
 {type:"fill",title:"Both still standing",body:`<p>Keep fighting while <b>both</b> have hp.</p>`,code:`let a = 5, b = 4;\nwhile (a > 0 [0] b > 0) {\n  b -= 2;\n  a -= 1;\n}\nconsole.log(a, b);`,blanks:["&&"],tokens:["&&","||","!"],why:"&& means \"and\": both must be true to keep going."},
 {type:"code",title:"Strike!",body:`<p>Inside ${C("attack")}, add one line that lowers ${C("b.hp")} by ${C("a.power")}, but never below 0. It should print ${C("Mo hits Bat (3 hp left)")} then ${C("Mo hits Bat (0 hp left)")}.</p>`,start:`function attack(a, b) {\n  // lower b.hp by a.power (but not below 0)\n\n  console.log(a.name + " hits " + b.name + " (" + b.hp + " hp left)");\n}\n\nconst mo = { name: "Mo", hp: 10, power: 4 };\nconst bat = { name: "Bat", hp: 7, power: 2 };\nattack(mo, bat);\nattack(mo, bat);\n`,
  use:[[/Math\.max|if\s*\(/,"Use Math.max(0, ...) so hp never goes below 0."]],out:["Mo hits Bat (3 hp left)","Mo hits Bat (0 hp left)"],variants:[[/power: 4/,"power: 2",["Mo hits Bat (5 hp left)","Mo hits Bat (3 hp left)"]]],
  hint:`function attack(a, b) {\n  b.hp = Math.max(0, b.hp - a.power);\n  console.log(a.name + " hits " + b.name + " (" + b.hp + " hp left)");\n}\n\nconst mo = { name: "Mo", hp: 10, power: 4 };\nconst bat = { name: "Bat", hp: 7, power: 2 };\nattack(mo, bat);\nattack(mo, bat);`},
 {type:"code",title:"Battle loop",body:`<p>Wrap the two attack lines in a ${C("while")} loop that runs while ${C("mo.hp > 0 && bat.hp > 0")}. The fight should end with ${C("You win!")}.</p>`,start:ATTACK_FN+`\nconst mo = { name: "Mo", hp: 10, power: 4 };\nconst bat = { name: "Bat", hp: 7, power: 3 };\n// put these two lines inside a while loop\nattack(mo, bat);\nif (bat.hp > 0) attack(bat, mo);\n\nconsole.log(mo.hp > 0 ? "You win!" : "You lose!");\n`,
  use:[[/while\s*\(/,"Wrap the attacks in a while loop."]],out:["Mo hits Bat (3 hp left)","Bat hits Mo (7 hp left)","Mo hits Bat (0 hp left)","You win!"],variants:[[/hp: 7, power: 3/,"hp: 20, power: 3",["Mo hits Bat (16 hp left)","Bat hits Mo (7 hp left)","Mo hits Bat (12 hp left)","Bat hits Mo (4 hp left)","Mo hits Bat (8 hp left)","Bat hits Mo (1 hp left)","Mo hits Bat (4 hp left)","Bat hits Mo (0 hp left)","You lose!"]]],
  hint:ATTACK_FN+`\nconst mo = { name: "Mo", hp: 10, power: 4 };\nconst bat = { name: "Bat", hp: 7, power: 3 };\nwhile (mo.hp > 0 && bat.hp > 0) {\n  attack(mo, bat);\n  if (bat.hp > 0) attack(bat, mo);\n}\n\nconsole.log(mo.hp > 0 ? "You win!" : "You lose!");`},
 {type:"game"},{type:"done"}],
 pool:[
  [`const b = { hp: 9 };\nb.hp -= 4;\nconsole.log(b.hp);`,["5","13","9"]],
  [`let a = 3, b = 0;\nconsole.log(a > 0 && b > 0);`,["false","true","0"]],
  [`const m = { name: "Mo", power: 2 };\nconsole.log(m.name + " x" + m.power);`,["Mo x2","Mo2","Mo x 2"]],
  [`let hp = 5, t = 0;\nwhile (hp > 0) { hp -= 2; t++; }\nconsole.log(t);`,["3","2","5"]],
  [`const hp = 0;\nconsole.log(hp > 0 ? "You win!" : "You lose!");`,["You lose!","You win!","0"]]
 ]},
{id:"g21",title:"Lucky hits",sub:"dice for damage, crits and misses",steps:[
 {type:"talk",title:"Rolling for damage",mood:"cheer",
  body:`<p>Battles are more exciting when damage is a bit random. Use TypeMonkey's ${C("roll()")} from the dice lesson: it gives 1 to 6, the same every time for the same seed.</p>`,
  demo:`let seed = 42;\nconst dmg = roll();\nconsole.log("⚔️ Mo hits for " + dmg + " damage!");\n\n`+DICE,
  say:"Seed 42 rolls a 6 first. Mo hits for 6!"},
 {type:"talk",title:"Critical hit!",mood:"think",
  body:`<p>Many games have <b>critical hits</b>: a lucky roll does double damage. Here, rolling a 6 is a crit.</p>`,
  demo:`let seed = 42;\nfor (let i = 0; i < 3; i++) {\n  const r = roll();\n  if (r === 6) console.log("💥 CRITICAL! " + (r * 2) + " damage");\n  else console.log("Hit for " + r);\n}\n\n`+DICE,
  say:"6 is a crit (12 damage), then a 5, then another crit."},
 {type:"talk",title:"Whoosh, a miss",mood:"oops",
  body:`<p>And unlucky rolls can miss. Here, rolling a 1 means the attack misses completely.</p>`,
  demo:`let seed = 99;\nfor (let i = 0; i < 2; i++) {\n  const r = roll();\n  if (r === 1) console.log("Whoosh... a miss!");\n  else console.log("Hit for " + r);\n}\n\n`+DICE,
  say:"Seed 99 rolls a 1 (miss!), then a 3."},
 {type:"quiz",q:"What does this print?",code:`const r = 6;\nconsole.log(r === 6 ? r * 2 : r);`,opts:["12","6","66"],a:0,mono:true,why:"r is 6, so it prints r * 2 = 12."},
 {type:"quiz",q:"Why do the challenges give you a seed for roll()?",opts:["So the same fight happens every time and can be checked","So the dice are fairer","So the numbers never repeat"],a:0,why:"Same seed, same rolls. That's how TypeMonkey can check your game."},
 {type:"fill",title:"Double it",body:`<p>Double the damage on a 6.</p>`,code:`const r = 6;\nlet dmg = r;\nif (r [0] 6) dmg = r * 2;\nconsole.log(dmg);`,blanks:["==="],tokens:["===","=","!=="],why:"=== checks if two things are equal. A single = would change r instead."},
 {type:"code",title:"Crit or not?",body:`<p>${C("r")} is already rolled. If it's 6, print ${C("CRITICAL! 12 damage")} (double the roll). Otherwise print ${C("Hit for 3")} with the roll. Seed 42 rolls a 6.</p>`,start:`let seed = 42;\nconst r = roll();\n// if r is 6: print CRITICAL! and double damage\n// otherwise: print Hit for r\n\n`+DICE,
  use:[[/===\s*6|6\s*===/,"Check for a 6 with r === 6."]],out:["CRITICAL! 12 damage"],variants:[[/seed = 42/,"seed = 7",["Hit for 3"]]],
  hint:`let seed = 42;\nconst r = roll();\nif (r === 6) {\n  console.log("CRITICAL! " + (r * 2) + " damage");\n} else {\n  console.log("Hit for " + r);\n}\n\n`+DICE},
 {type:"code",title:"Three swings",body:`<p>The miss is done. Fill in the other two parts: on a 6, add ${C("r * 2")} to ${C("total")} and print ${C("CRITICAL! 12")}. Otherwise add ${C("r")} and print ${C("Hit for N")}. With seed 42 it ends with ${C("Total damage: 29")}.</p>`,start:`let seed = 42;\nlet total = 0;\nfor (let i = 0; i < 3; i++) {\n  const r = roll();\n  if (r === 1) {\n    console.log("Miss!");\n  } else if (r === 6) {\n    // add r * 2 to total, then print: CRITICAL! 12\n  } else {\n    // add r to total, then print: Hit for r\n  }\n}\nconsole.log("Total damage: " + total);\n\n`+DICE,
  use:[[/total\s*\+=/,"Add the damage to total with +=."]],out:["CRITICAL! 12","Hit for 5","CRITICAL! 12","Total damage: 29"],variants:[[/seed = 42/,"seed = 99",["Miss!","Hit for 3","Hit for 2","Total damage: 5"]]],
  hint:`let seed = 42;\nlet total = 0;\nfor (let i = 0; i < 3; i++) {\n  const r = roll();\n  if (r === 1) {\n    console.log("Miss!");\n  } else if (r === 6) {\n    total += r * 2;\n    console.log("CRITICAL! " + (r * 2));\n  } else {\n    total += r;\n    console.log("Hit for " + r);\n  }\n}\nconsole.log("Total damage: " + total);\n\n`+DICE},
 {type:"game"},{type:"done"}],
 pool:[
  [`const r = 1;\nconsole.log(r === 1 ? "Miss!" : "Hit");`,["Miss!","Hit","1"]],
  [`let t = 0;\nfor (const r of [2, 6, 3]) t += r === 6 ? 12 : r;\nconsole.log(t);`,["17","11","12"]],
  [`console.log(Math.floor(0.2 * 6) + 1);`,["2","1","3"]],
  [`const dmg = 4;\nconsole.log("Hit for " + dmg * 2);`,["Hit for 8","Hit for 42","Hit for 4"]],
  [`let hp = 10;\nfor (const d of [3, 4]) hp -= d;\nconsole.log(hp);`,["3","7","10"]]
 ]},
{id:"g22",title:"Quiz show",sub:"questions, answers and streak bonuses",steps:[
 {type:"talk",title:"A quiz is a game too!",mood:"cheer",
  body:`<p>Quiz games are easy to build: each question is an object with the question ${C("q")} and the answer ${C("a")}.</p>`,
  demo:`const quiz = [\n  { q: "What color is a banana?", a: "yellow" },\n  { q: "How many legs does a spider have?", a: "8" }\n];\nfor (const item of quiz) console.log("❓ " + item.q);`,
  say:"Two questions on the game screen."},
 {type:"talk",title:"Checking answers",mood:"think",
  body:`<p>Players might type ${C("YELLOW")} or ${C("Yellow")}. ${C(".toLowerCase()")} turns everything into small letters, so all of them count as right.</p>`,
  demo:`const correct = "yellow";\nconst typed = "YELLOW";\nconsole.log(typed.toLowerCase());\nconsole.log(typed.toLowerCase() === correct ? "✅ Correct!" : "❌ Nope");`,
  say:"yellow, then ✅ Correct!"},
 {type:"talk",title:"Streak bonus",
  body:`<p>Reward players for answers in a row! The ${C("streak")} counts right answers in a row, and each one is worth ${C("10 * streak")}. A wrong answer resets the streak to 0.</p>`,
  demo:`const results = [true, true, false, true];\nlet score = 0;\nlet streak = 0;\nfor (const ok of results) {\n  if (ok) {\n    streak++;\n    score += 10 * streak;\n  } else {\n    streak = 0;\n  }\n}\nconsole.log("Score: " + score);`,
  say:"10 + 20, then a miss, then 10 again: Score: 40"},
 {type:"quiz",q:"What does this print?",code:`console.log("MoNKEY".toLowerCase());`,opts:["monkey","MONKEY","MoNKEY"],a:0,mono:true,why:"toLowerCase makes every letter small."},
 {type:"fill",title:"Any capitals are fine",body:`<p>Make the check work however the answer was typed.</p>`,code:`const answer = "paris";\nconst typed = "Paris";\nconsole.log(typed.[0]() === answer);`,blanks:["toLowerCase"],tokens:["toLowerCase","toUpperCase","length"],why:"\"Paris\" becomes \"paris\", which matches."},
 {type:"code",title:"Mark the answers",body:`<p>Inside the loop, add an ${C("if")}: when ${C("answers[i].toLowerCase()")} matches ${C("quiz[i].a")}, add 1 to ${C("score")}. Two answers are right, so it should print ${C("You got 2 out of 3!")}.</p>`,start:`const quiz = [\n  { q: "What color is a banana?", a: "yellow" },\n  { q: "How many legs does a spider have?", a: "8" },\n  { q: "What do bees make?", a: "honey" }\n];\nconst answers = ["Yellow", "6", "HONEY"];\nlet score = 0;\nfor (let i = 0; i < quiz.length; i++) {\n  // if the answer matches, add 1 to score\n}\nconsole.log("You got " + score + " out of " + quiz.length + "!");\n`,
  use:[[/toLowerCase/,"Use .toLowerCase() so YELLOW and Yellow both count."]],out:["You got 2 out of 3!"],variants:[[/"6"/,"\"8\"",["You got 3 out of 3!"]]],
  hint:`const quiz = [\n  { q: "What color is a banana?", a: "yellow" },\n  { q: "How many legs does a spider have?", a: "8" },\n  { q: "What do bees make?", a: "honey" }\n];\nconst answers = ["Yellow", "6", "HONEY"];\nlet score = 0;\nfor (let i = 0; i < quiz.length; i++) {\n  if (answers[i].toLowerCase() === quiz[i].a) {\n    score++;\n  }\n}\nconsole.log("You got " + score + " out of " + quiz.length + "!");`},
 {type:"code",title:"Streak bonus",body:`<p>Fill in both parts: a right answer adds 1 to ${C("streak")}, then adds ${C("10 * streak")} to ${C("score")}. A wrong answer sets ${C("streak")} back to 0. It should print ${C("Score: 70")}.</p>`,start:`const results = [true, true, true, false, true];\nlet score = 0;\nlet streak = 0;\nfor (const ok of results) {\n  if (ok) {\n    // add 1 to streak, then add 10 * streak to score\n  } else {\n    // reset the streak to 0\n  }\n}\nconsole.log("Score: " + score);\n`,
  use:[[/streak\s*=\s*0[\s\S]*streak\s*=\s*0/,"Reset the streak with streak = 0 when the answer is wrong."]],out:["Score: 70"],variants:[[/true, true, true, false, true/,"true, false, true, true, false",["Score: 40"]]],
  hint:`const results = [true, true, true, false, true];\nlet score = 0;\nlet streak = 0;\nfor (const ok of results) {\n  if (ok) {\n    streak++;\n    score += 10 * streak;\n  } else {\n    streak = 0;\n  }\n}\nconsole.log("Score: " + score);`},
 {type:"game"},{type:"done"}],
 pool:[
  [`console.log("Yes".toLowerCase() === "yes");`,["true","false","yes"]],
  [`const q = { q: "2+2?", a: "4" };\nconsole.log(q.a);`,["4","2+2?","q"]],
  [`let s = 0, k = 0;\nfor (const ok of [true, true]) { k++; s += 10 * k; }\nconsole.log(s);`,["30","20","10"]],
  [`const quiz = [1, 2, 3];\nconsole.log("Question " + quiz.length);`,["Question 3","Question 2","Question 1,2,3"]],
  [`let streak = 4;\nstreak = 0;\nconsole.log(streak);`,["0","4","40"]]
 ]},
{id:"g23",title:"Project: Boss Battle",sub:"the grand finale: a boss with a rage mode",project:true,steps:[
 {type:"talk",title:"The King Gorilla awaits",mood:"cheer",
  body:`<p>Time for the final boss! You'll build it in four small steps: health bars, a turn with attack and heal, a <b>rage mode</b> when the boss gets hurt, and finally winning or losing.</p>`,
  say:"Big boss, small steps. Let's go!"},
 {type:"code",title:"Step 1: health bars",body:`<p>Finish ${C("bar(p)")}: return the name, a space, then ${C("♥")} for each point of ${C("hp")} and ${C("♡")} for each missing point. Mo's bar should look like ${C("Mo ♥♥♥♥♥♥♥♥♡♡")}.</p>`,start:`const hero = { name: "Mo", hp: 8, maxHp: 10 };\nconst boss = { name: "King Gorilla", hp: 12, maxHp: 12 };\n\nfunction bar(p) {\n  // return the name, a space, then the hearts\n}\n\nconsole.log(bar(hero));\nconsole.log(bar(boss));\n`,
  use:[[/return/,"Give the bar back with return."],[/repeat/,"Draw the hearts with .repeat()."]],out:["Mo ♥♥♥♥♥♥♥♥♡♡","King Gorilla ♥♥♥♥♥♥♥♥♥♥♥♥"],variants:[[/hp: 8/,"hp: 2",["Mo ♥♥♡♡♡♡♡♡♡♡","King Gorilla ♥♥♥♥♥♥♥♥♥♥♥♥"]]],
  hint:`const hero = { name: "Mo", hp: 8, maxHp: 10 };\nconst boss = { name: "King Gorilla", hp: 12, maxHp: 12 };\n\nfunction bar(p) {\n  return p.name + " " + "♥".repeat(p.hp) + "♡".repeat(p.maxHp - p.hp);\n}\n\nconsole.log(bar(hero));\nconsole.log(bar(boss));`},
 {type:"code",title:"Step 2: attack and heal",body:`<p>Attacking and the boss's smash are done. Fill in the ${C("heal")} part: add 4 to Mo's hp (not past ${C("maxHp")}), then print ${C("Mo heals! Mo: 8 hp")}.</p>`,start:`const hero = { name: "Mo", hp: 6, maxHp: 10, power: 3 };\nconst boss = { name: "King Gorilla", hp: 12, maxHp: 12, power: 2 };\nconst moves = ["attack", "heal", "attack"];\nfor (const move of moves) {\n  if (move === "attack") {\n    boss.hp = Math.max(0, boss.hp - hero.power);\n    console.log("Mo attacks! King Gorilla: " + boss.hp + " hp");\n  } else if (move === "heal") {\n    // heal Mo by 4 (not past maxHp), then print: Mo heals! Mo: N hp\n  }\n`+BOSS_SMASH+`\n`,
  use:[[/Math\.min/,"Use Math.min so Mo can't heal past maxHp."]],out:["Mo attacks! King Gorilla: 9 hp","King Gorilla smashes! Mo: 4 hp","Mo heals! Mo: 8 hp","King Gorilla smashes! Mo: 6 hp","Mo attacks! King Gorilla: 6 hp","King Gorilla smashes! Mo: 4 hp"],variants:[[/hp: 6, maxHp/,"hp: 9, maxHp",["Mo attacks! King Gorilla: 9 hp","King Gorilla smashes! Mo: 7 hp","Mo heals! Mo: 10 hp","King Gorilla smashes! Mo: 8 hp","Mo attacks! King Gorilla: 6 hp","King Gorilla smashes! Mo: 6 hp"]]],
  hint:`const hero = { name: "Mo", hp: 6, maxHp: 10, power: 3 };\nconst boss = { name: "King Gorilla", hp: 12, maxHp: 12, power: 2 };\nconst moves = ["attack", "heal", "attack"];\nfor (const move of moves) {\n  if (move === "attack") {\n    boss.hp = Math.max(0, boss.hp - hero.power);\n    console.log("Mo attacks! King Gorilla: " + boss.hp + " hp");\n`+BOSS_HEAL+BOSS_SMASH},
 {type:"code",title:"Step 3: rage mode!",body:`<p>When the boss drops to half its hp, it gets angry. The check is ready: inside it, print ${C("King Gorilla is ANGRY! Power up!")} and double ${C("boss.power")} with ${C("*= 2")}. Watch Mo take bigger hits after that!</p>`,start:BOSS_TOP+`    if (!boss.angry && boss.hp <= boss.maxHp / 2) {\n      boss.angry = true;\n      // print: King Gorilla is ANGRY! Power up!\n      // then double boss.power\n    }\n`+BOSS_HEAL+BOSS_SMASH+`\n`,
  use:[[/power\s*\*=\s*2|power\s*=\s*boss\.power\s*\*\s*2/,"Double the power with boss.power *= 2."]],out:["Mo attacks! King Gorilla: 9 hp","King Gorilla smashes! Mo: 8 hp","Mo attacks! King Gorilla: 6 hp","King Gorilla is ANGRY! Power up!","King Gorilla smashes! Mo: 4 hp","Mo heals! Mo: 8 hp","King Gorilla smashes! Mo: 4 hp","Mo attacks! King Gorilla: 3 hp","King Gorilla smashes! Mo: 0 hp"],variants:[[/hp: 12, maxHp: 12, power: 2/,"hp: 12, maxHp: 12, power: 1",["Mo attacks! King Gorilla: 9 hp","King Gorilla smashes! Mo: 9 hp","Mo attacks! King Gorilla: 6 hp","King Gorilla is ANGRY! Power up!","King Gorilla smashes! Mo: 7 hp","Mo heals! Mo: 10 hp","King Gorilla smashes! Mo: 8 hp","Mo attacks! King Gorilla: 3 hp","King Gorilla smashes! Mo: 6 hp"]]],
  hint:BOSS_TOP+BOSS_RAGE+BOSS_HEAL+BOSS_SMASH},
 {type:"code",title:"Step 4: win or lose",body:`<p>Last step! Mo is stronger now (power 4). Fill in the two ${C("if")}s: when the boss reaches 0 hp, print ${C("You win! King Gorilla gives up!")}, set ${C("over = true")} and ${C("break")}. When Mo reaches 0 hp, print ${C("Game over! Mo needs a nap.")}, set ${C("over = true")} and ${C("break")}.</p>`,start:BOSS4_TOP+`  if (boss.hp === 0) {\n    // print the win message, set over to true, then break\n  }\n  hero.hp = Math.max(0, hero.hp - boss.power);\n  console.log("King Gorilla smashes! Mo: " + hero.hp + " hp");\n  if (hero.hp === 0) {\n    // print the game over message, set over to true, then break\n  }\n}\nif (!over) console.log("The battle goes on...");\n`,
  use:[[/\bbreak\b/,"Stop the battle with break."],[/over\s*=\s*true/,"Set over = true when the battle ends."]],out:["Mo attacks! King Gorilla: 8 hp","King Gorilla smashes! Mo: 8 hp","Mo attacks! King Gorilla: 4 hp","King Gorilla is ANGRY! Power up!","King Gorilla smashes! Mo: 4 hp","Mo heals! Mo: 8 hp","King Gorilla smashes! Mo: 4 hp","Mo attacks! King Gorilla: 0 hp","You win! King Gorilla gives up!"],variants:[[/hp: 10, maxHp: 10, power: 4/,"hp: 10, maxHp: 10, power: 3",["Mo attacks! King Gorilla: 9 hp","King Gorilla smashes! Mo: 8 hp","Mo attacks! King Gorilla: 6 hp","King Gorilla is ANGRY! Power up!","King Gorilla smashes! Mo: 4 hp","Mo heals! Mo: 8 hp","King Gorilla smashes! Mo: 4 hp","Mo attacks! King Gorilla: 3 hp","King Gorilla smashes! Mo: 0 hp","Game over! Mo needs a nap."]],[/"attack", "attack", "heal", "attack", "attack"/,"\"attack\", \"heal\"",["Mo attacks! King Gorilla: 8 hp","King Gorilla smashes! Mo: 8 hp","Mo heals! Mo: 10 hp","King Gorilla smashes! Mo: 8 hp","The battle goes on..."]]],
  hint:BOSS4_TOP+`  if (boss.hp === 0) {\n    console.log("You win! King Gorilla gives up!");\n    over = true;\n    break;\n  }\n  hero.hp = Math.max(0, hero.hp - boss.power);\n  console.log("King Gorilla smashes! Mo: " + hero.hp + " hp");\n  if (hero.hp === 0) {\n    console.log("Game over! Mo needs a nap.");\n    over = true;\n    break;\n  }\n}\nif (!over) console.log("The battle goes on...");`},
 {type:"done"}]}
]}
);
})();
