/* deep-web: launch depth units. HTML & CSS Unit 6 (page building blocks) and Unit 7 (layout & motion). */
COURSE_WEB.units.push({name:"Page building blocks",lessons:[
{id:"web17",title:"Warm-up: quotes & highlights",sub:"mark, blockquote, hr",steps:[
 {type:"talk",title:"Welcome back!",mood:"cheer",
  body:`<p>Let's start easy. A few small tags make text clearer. ${C("&lt;mark&gt;")} highlights words, just like a highlighter pen.</p>`,
  demo:`<p>Remember: <mark>save your work</mark> before you close the tab.</p>`,
  say:"Tap ▶ Show page. See the yellow highlight? That's mark."},
 {type:"talk",title:"Quotes and dividers",mood:"think",
  body:`<p>${C("&lt;blockquote&gt;")} is for a quote from someone. ${C("&lt;hr&gt;")} draws a divider line between sections. Like ${C("&lt;br&gt;")}, it doesn't need a closing tag.</p>`,
  demo:`<h2>Words of wisdom</h2>\n<blockquote>A banana a day keeps the bugs away.</blockquote>\n<hr>\n<h2>Next section</h2>\n<p>The line above splits the page in two.</p>`,
  say:"Browsers indent blockquotes a little so they stand out."},
 {type:"quiz",q:"Which tag highlights text like a marker pen?",opts:["<mark>","<hr>","<blockquote>"],a:0,mono:true,why:"mark highlights. hr is a line. blockquote is a quote."},
 {type:"code",title:"Highlight a word",
  body:`<p>Wrap the word ${C("bananas")} in ${C("&lt;mark&gt;")} and ${C("&lt;/mark&gt;")}. When you show the page, that word gets a yellow background.</p>`,
  start:`<p>TypeMonkey's favorite snack is bananas.</p>\n`,
  checks:[{sel:"p mark",text:/banana/i,msg:"Put <mark> before bananas and </mark> after it."}],
  hint:`<p>TypeMonkey's favorite snack is <mark>bananas</mark>.</p>`},
 {type:"fill",title:"Make a quote",body:`<p>Turn this sentence into a quote.</p>`,code:`<[0]>Practice a little every day.</[1]>`,blanks:["blockquote","blockquote"],tokens:["blockquote","blockquote","mark","quote"],why:"The opening and closing tags must both be blockquote."},
 {type:"code",title:"Add a quote",
  body:`<p>Under the heading, add a ${C("&lt;blockquote&gt;")} with any quote you like inside it. Most of the page is already there, so you only add one line. It will show up indented.</p>`,
  start:`<h2>Quote of the day</h2>\n<!-- add your blockquote on the next line -->\n\n`,
  checks:[{sel:"blockquote",text:/\S/,msg:"Add <blockquote>Your quote here</blockquote> under the heading."}],
  hint:`<h2>Quote of the day</h2>\n<!-- add your blockquote on the next line -->\n<blockquote>Every expert was once a beginner.</blockquote>`},
 {type:"done"}]},
{id:"web18",title:"Tables",sub:"table, tr, th, td",steps:[
 {type:"talk",title:"Rows and columns",
  body:`<p>Tables show data in rows and columns, like a score chart. ${C("&lt;table&gt;")} holds everything. Each ${C("&lt;tr&gt;")} is a <b>t</b>able <b>r</b>ow. Inside a row, ${C("&lt;td&gt;")} is a cell and ${C("&lt;th&gt;")} is a heading cell.</p>`,
  demo:`<table>\n  <tr><th>Name</th><th>Age</th></tr>\n  <tr><td>Mo</td><td>4</td></tr>\n  <tr><td>Bao</td><td>7</td></tr>\n</table>`,
  say:"Heading cells are bold and centered by default."},
 {type:"talk",title:"Tidy borders",mood:"think",
  body:`<p>Give the cells a ${C("border")} and some ${C("padding")}. Then add ${C("border-collapse: collapse")} to the table so neighboring borders merge into one neat line.</p>`,
  demo:`<style>\n  table { border-collapse: collapse; }\n  th, td { border: 1px solid #ccc; padding: 6px 10px; }\n  th { background: #FFF4E5; }\n</style>\n<table>\n  <tr><th>Snack</th><th>Price</th></tr>\n  <tr><td>Banana</td><td>$1</td></tr>\n  <tr><td>Mango</td><td>$2</td></tr>\n</table>`,
  say:"Delete the border-collapse line and show the page again to see the double borders."},
 {type:"quiz",q:"What does <tr> stand for?",opts:["Table row","Text right","Top row"],a:0,mono:true,why:"Each tr is one row of the table."},
 {type:"order",title:"Build a row",body:`<p>Put the lines in order to make one table row.</p>`,lines:["<tr>","  <td>Kiki</td>","  <td>12</td>","</tr>"],why:"Open the row, add the cells, close the row.",noRun:true},
 {type:"code",title:"Add a row",
  body:`<p>Add one more row for ${C("Kiki")}, who is ${C("12")}. Copy the Mo row and change the words. You should see a third row in the table.</p>`,
  start:`<table>\n  <tr><th>Name</th><th>Age</th></tr>\n  <tr><td>Mo</td><td>4</td></tr>\n  <!-- add a row for Kiki here -->\n</table>\n`,
  checks:[{sel:"tr",count:3,msg:"Add a new <tr> row, so the table has 3 rows."},{sel:"td",text:/Kiki/,msg:"Put Kiki in a <td> cell in your new row."}],
  hint:`<table>\n  <tr><th>Name</th><th>Age</th></tr>\n  <tr><td>Mo</td><td>4</td></tr>\n  <tr><td>Kiki</td><td>12</td></tr>\n</table>`},
 {type:"fill",title:"A heading cell",body:`<p>Make a bold heading cell for the Name column.</p>`,code:`<tr><[0]>Name</[1]></tr>`,blanks:["th","th"],tokens:["th","th","td","head"],why:"th is a heading cell. td is a normal cell."},
 {type:"code",title:"Neat borders",
  body:`<p>The cells already have borders. Inside the ${C("table")} rule, add ${C("border-collapse: collapse;")} so the double lines become single lines.</p>`,
  start:`<style>\n  table {\n    /* add border-collapse here */\n  }\n  th, td { border: 1px solid #ccc; padding: 6px; }\n</style>\n<table>\n  <tr><th>Game</th><th>Score</th></tr>\n  <tr><td>Banana Rush</td><td>120</td></tr>\n</table>\n`,
  checks:[{sel:"table",style:{"border-collapse":"collapse"},msg:"Inside table { }, write border-collapse: collapse;"}],
  hint:`<style>\n  table {\n    border-collapse: collapse;\n  }\n  th, td { border: 1px solid #ccc; padding: 6px; }\n</style>\n<table>\n  <tr><th>Game</th><th>Score</th></tr>\n  <tr><td>Banana Rush</td><td>120</td></tr>\n</table>`},
 {type:"done"}]},
{id:"web19",title:"More form fields",sub:"textarea, radio buttons, required",steps:[
 {type:"talk",title:"Big text boxes",
  body:`<p>An ${C("&lt;input&gt;")} holds one line. For longer messages, use ${C("&lt;textarea&gt;")}. It has a closing tag, and ${C("rows")} sets how tall it starts.</p>`,
  demo:`<form>\n  <label for="note">Note to TypeMonkey</label><br>\n  <textarea id="note" rows="3" placeholder="Write anything..."></textarea>\n</form>`,
  say:"Type a few lines in the box. It holds as much as you like."},
 {type:"code",title:"A message box",
  body:`<p>The label is ready. Add a ${C("&lt;textarea id=\"msg\"&gt;&lt;/textarea&gt;")} where the comment is. You should see a big empty box.</p>`,
  start:`<form>\n  <label for="msg">Message</label><br>\n  <!-- add a textarea with id="msg" here -->\n</form>\n`,
  checks:[{sel:"form textarea#msg",msg:"Add <textarea id=\"msg\"></textarea> inside the form."}],
  hint:`<form>\n  <label for="msg">Message</label><br>\n  <textarea id="msg" rows="3"></textarea>\n</form>`},
 {type:"talk",title:"Radio buttons",mood:"think",
  body:`<p>Radio buttons let you pick <b>one</b> choice. Give every option the same ${C("name")} and they become a group: choosing one un-chooses the others.</p>`,
  demo:`<p>Pick a snack:</p>\n<label><input type="radio" name="snack"> Banana</label><br>\n<label><input type="radio" name="snack"> Mango</label><br>\n<label><input type="radio" name="snack"> Kiwi</label>`,
  say:"Try clicking different ones. Only one can be picked at a time."},
 {type:"quiz",q:"How do radio buttons know they're in the same group?",opts:["They share the same name","They are next to each other","They share the same id"],a:0,why:"Same name = same group. ids must be unique."},
 {type:"code",title:"Pick a snack",
  body:`<p>One radio button is done. Add a second one for ${C("Mango")} with the same ${C("name=\"snack\"")}. You should see two choices, and only one can be picked.</p>`,
  start:`<p>Pick a snack:</p>\n<label><input type="radio" name="snack"> Banana</label><br>\n<!-- add a Mango radio button here -->\n`,
  checks:[{sel:"input[type=radio][name=snack]",count:2,msg:"Add a second <input type=\"radio\" name=\"snack\">."}],
  hint:`<p>Pick a snack:</p>\n<label><input type="radio" name="snack"> Banana</label><br>\n<label><input type="radio" name="snack"> Mango</label>`},
 {type:"talk",title:"Required fields",
  body:`<p>Add the word ${C("required")} to an input and the form won't send until it's filled in. The browser shows a friendly warning for you.</p>`,
  demo:`<form>\n  <label for="nick">Nickname</label>\n  <input id="nick" required>\n  <button>Send</button>\n</form>`,
  say:"Tap Send with the box empty. The browser stops you!"},
 {type:"fill",title:"Must fill in",body:`<p>Make the email field required.</p>`,code:`<input type="email" [0]>`,blanks:["required"],tokens:["required","needed","must","important"],why:"required is an attribute with no value needed."},
 {type:"code",title:"Make it required",
  body:`<p>Add ${C("required")} inside the email ${C("&lt;input&gt;")} tag, like ${C("&lt;input id=\"email\" type=\"email\" required&gt;")}. The page looks the same, but now the form won't send while it's empty.</p>`,
  start:`<form>\n  <label for="email">Email</label>\n  <input id="email" type="email">\n  <button>Join</button>\n</form>\n`,
  checks:[{sel:"input#email[required]",msg:"Add the word required inside the <input> tag."}],
  hint:`<form>\n  <label for="email">Email</label>\n  <input id="email" type="email" required>\n  <button>Join</button>\n</form>`},
 {type:"done"}]},
{id:"web20",title:"Images & accessibility",sub:"alt text, figure, aria-label",steps:[
 {type:"talk",title:"Good alt text",
  body:`<p>Alt text is read aloud to people who can't see the image. Good alt text says what matters in the picture, in a short sentence. Skip words like "image of".</p>`,
  demo:`<img src="mo.png" alt="Mo the monkey high-fiving a parrot">\n<p>The image file is missing, so the alt text shows instead. It still tells you what's going on!</p>`,
  say:"Imagine describing the photo to a friend over the phone."},
 {type:"quiz",q:"Which is the best alt text for a photo of a monkey eating a banana?",opts:["A monkey eating a banana","image.png","photo"],a:0,why:"Describe what's in the picture. File names and \"photo\" don't help anyone."},
 {type:"code",title:"Write alt text",
  body:`<p>This image has no ${C("alt")}. Add ${C("alt=\"...\"")} inside the ${C("&lt;img&gt;")} tag with a few words describing it, like ${C("alt=\"A parrot on a branch\"")}. The alt text will show where the picture would be.</p>`,
  start:`<img src="kiki.png">\n`,
  checks:[{sel:"img",attr:["alt",/\w{3}/],msg:"Add alt=\"...\" with a short description inside the <img> tag."}],
  hint:`<img src="kiki.png" alt="A green parrot sitting on a branch">`},
 {type:"talk",title:"Captions",mood:"think",
  body:`<p>Wrap an image in ${C("&lt;figure&gt;")} and add a ${C("&lt;figcaption&gt;")} to give it a caption everyone can read. The caption belongs to the picture.</p>`,
  demo:`<figure>\n  <img src="bao.png" alt="A panda chewing bamboo" width="120">\n  <figcaption>Bao at lunch time</figcaption>\n</figure>`,
  say:"Alt text is for when you can't see the image. A caption is extra info for everyone."},
 {type:"code",title:"Add a caption",
  body:`<p>Inside the ${C("&lt;figure&gt;")}, under the image, add ${C("&lt;figcaption&gt;Kiki says hi&lt;/figcaption&gt;")} (or your own words). The caption appears under the picture.</p>`,
  start:`<figure>\n  <img src="kiki.png" alt="A green parrot on a branch">\n  <!-- add a figcaption here -->\n</figure>\n`,
  checks:[{sel:"figure figcaption",text:/\S/,msg:"Add <figcaption>Your caption</figcaption> inside the figure."}],
  hint:`<figure>\n  <img src="kiki.png" alt="A green parrot on a branch">\n  <figcaption>Kiki says hi</figcaption>\n</figure>`},
 {type:"talk",title:"Name your icon buttons",
  body:`<p>A button that only shows an emoji or icon has no words for a screen reader to say. Add ${C("aria-label")} to give it a name.</p>`,
  demo:`<button aria-label="Play">▶</button>\n<button aria-label="Settings">⚙️</button>\n<p>They look the same, but now a screen reader says "Play" and "Settings".</p>`,
  say:"Small detail, big help for people using screen readers."},
 {type:"fill",title:"Describe the cat",body:`<p>Give the image a description.</p>`,code:`<img src="cat.png" [0]="A sleepy cat">`,blanks:["alt"],tokens:["alt","title","src","name"],why:"alt holds the description."},
 {type:"code",title:"Name the search button",
  body:`<p>Add ${C("aria-label=\"Search\"")} inside the ${C("&lt;button&gt;")} tag. It still shows 🔍, but now it has a name.</p>`,
  start:`<button>🔍</button>\n`,
  checks:[{sel:"button",attr:["aria-label",/\S/],msg:"Add aria-label=\"Search\" inside the <button> tag."}],
  hint:`<button aria-label="Search">🔍</button>`},
 {type:"done"}]},
{id:"web21",title:"Project: Recipe Card",sub:"image, lists, table and style",project:true,steps:[
 {type:"talk",title:"Cook up a recipe card",mood:"cheer",
  body:`<p>Recipe sites use everything you've learned: a picture with alt text, lists, a little table and a tidy card style. Here's the goal. You'll build it one small piece at a time.</p>`,
  demo:`<style>\n  .recipe { max-width: 280px; padding: 16px; border-radius: 16px; background: #FFF4E5; border: 2px solid #FFB36B; }\n  .recipe h2 { margin-top: 0; color: #E05E08; }\n  .recipe table { border-collapse: collapse; }\n  .recipe th, .recipe td { border: 1px solid #FFB36B; padding: 4px 8px; }\n</style>\n<div class="recipe">\n  <h2>🍌 Banana Smoothie</h2>\n  <img src="smoothie.png" alt="A tall glass of yellow banana smoothie">\n  <h3>Ingredients</h3>\n  <ul><li>1 banana</li><li>1 cup milk</li><li>2 ice cubes</li></ul>\n  <h3>Steps</h3>\n  <ol><li>Peel the banana</li><li>Put everything in a blender</li><li>Blend and enjoy</li></ol>\n  <table>\n    <tr><th>Time</th><td>5 min</td></tr>\n    <tr><th>Serves</th><td>2</td></tr>\n  </table>\n</div>`,
  say:"Yum. Let's build it!"},
 {type:"code",title:"Step 1: name and picture",
  body:`<p>Inside ${C(".recipe")}, add an ${C("&lt;h2&gt;")} with your recipe's name, and an ${C("&lt;img&gt;")} with ${C("alt")} text describing the food.</p>`,
  start:`<div class="recipe">\n  <!-- 1. an h2 with the recipe name -->\n  <!-- 2. an img with alt text -->\n</div>\n`,
  checks:[{sel:".recipe h2",text:/\S/,msg:"Add an <h2> with the recipe name inside .recipe."},{sel:".recipe img",attr:["alt",/\w{3}/],msg:"Add an <img> with alt text describing the food."}],
  hint:`<div class="recipe">\n  <h2>Banana Smoothie</h2>\n  <img src="smoothie.png" alt="A tall glass of banana smoothie">\n</div>`},
 {type:"code",title:"Step 2: ingredients",
  body:`<p>Under the Ingredients heading, add a ${C("&lt;ul&gt;")} with at least 3 ${C("&lt;li&gt;")} items. You'll see a bulleted list.</p>`,
  start:`<div class="recipe">\n  <h2>Banana Smoothie</h2>\n  <h3>Ingredients</h3>\n  <!-- a ul with 3 li items -->\n</div>\n`,
  checks:[{sel:".recipe ul li",count:3,msg:"Add a <ul> with at least 3 <li> items."}],
  hint:`<div class="recipe">\n  <h2>Banana Smoothie</h2>\n  <h3>Ingredients</h3>\n  <ul>\n    <li>1 banana</li>\n    <li>1 cup milk</li>\n    <li>2 ice cubes</li>\n  </ul>\n</div>`},
 {type:"code",title:"Step 3: the steps",
  body:`<p>Steps happen in order, so use a <b>numbered</b> list: an ${C("&lt;ol&gt;")} with at least 3 ${C("&lt;li&gt;")} items.</p>`,
  start:`<div class="recipe">\n  <h2>Banana Smoothie</h2>\n  <h3>Steps</h3>\n  <!-- an ol with 3 li items -->\n</div>\n`,
  checks:[{sel:".recipe ol li",count:3,msg:"Add an <ol> with at least 3 <li> items."}],
  hint:`<div class="recipe">\n  <h2>Banana Smoothie</h2>\n  <h3>Steps</h3>\n  <ol>\n    <li>Peel the banana</li>\n    <li>Put everything in a blender</li>\n    <li>Blend and enjoy</li>\n  </ol>\n</div>`},
 {type:"code",title:"Step 4: quick facts",
  body:`<p>The table has a Time row. Add a second row with a ${C("&lt;th&gt;Serves&lt;/th&gt;")} and a ${C("&lt;td&gt;")} with a number.</p>`,
  start:`<div class="recipe">\n  <table>\n    <tr><th>Time</th><td>5 min</td></tr>\n    <!-- add a Serves row here -->\n  </table>\n</div>\n`,
  checks:[{sel:".recipe tr",count:2,msg:"Add a second <tr> row to the table."},{sel:".recipe th",text:/Serves/i,msg:"Put <th>Serves</th> in the new row."}],
  hint:`<div class="recipe">\n  <table>\n    <tr><th>Time</th><td>5 min</td></tr>\n    <tr><th>Serves</th><td>2</td></tr>\n  </table>\n</div>`},
 {type:"code",title:"Step 5: card style",
  body:`<p>Make it look like a card. In the ${C(".recipe")} rule, add ${C("padding: 16px;")} and ${C("border-radius: 16px;")}. The background is already there.</p>`,
  start:`<style>\n  .recipe {\n    background: #FFF4E5;\n    /* add padding and border-radius */\n  }\n</style>\n<div class="recipe">\n  <h2>Banana Smoothie</h2>\n  <p>Sweet, cold and ready in 5 minutes.</p>\n</div>\n`,
  checks:[{sel:".recipe",style:{"padding-top":"16px"},msg:"Add padding: 16px; to .recipe."},{sel:".recipe",style:{"border-top-left-radius":"16px"},msg:"Add border-radius: 16px; to .recipe."}],
  hint:`<style>\n  .recipe {\n    background: #FFF4E5;\n    padding: 16px;\n    border-radius: 16px;\n  }\n</style>\n<div class="recipe">\n  <h2>Banana Smoothie</h2>\n  <p>Sweet, cold and ready in 5 minutes.</p>\n</div>`},
 {type:"talk",title:"Your recipe card",mood:"cheer",
  body:`<p>Here it is all together. Tap ▶ Show page, then make it yours: a different recipe, new colors, more steps.</p>`,
  demo:`<style>\n  .recipe { max-width: 280px; padding: 16px; border-radius: 16px; background: #FFF4E5; border: 2px solid #FFB36B; }\n  .recipe h2 { margin-top: 0; color: #E05E08; }\n  .recipe table { border-collapse: collapse; }\n  .recipe th, .recipe td { border: 1px solid #FFB36B; padding: 4px 8px; }\n</style>\n<div class="recipe">\n  <h2>🍌 Banana Smoothie</h2>\n  <img src="smoothie.png" alt="A tall glass of banana smoothie">\n  <h3>Ingredients</h3>\n  <ul><li>1 banana</li><li>1 cup milk</li><li>2 ice cubes</li></ul>\n  <h3>Steps</h3>\n  <ol><li>Peel the banana</li><li>Put everything in a blender</li><li>Blend and enjoy</li></ol>\n  <table>\n    <tr><th>Time</th><td>5 min</td></tr>\n    <tr><th>Serves</th><td>2</td></tr>\n  </table>\n</div>`,
  say:"A real recipe card, built by you. Chef TypeMonkey approves!"},
 {type:"done"}]}
]});

COURSE_WEB.units.push({name:"Layout & motion",lessons:[
{id:"web22",title:"Warm-up: centering",sub:"text-align, margin auto, flex center",steps:[
 {type:"talk",title:"Center the text",mood:"cheer",
  body:`<p>Centering things is one of the most common jobs in CSS. Let's start with the easiest kind: ${C("text-align: center")} centers the text inside a box.</p>`,
  demo:`<style>\n  h1 { text-align: center; }\n</style>\n<h1>Banana Party</h1>\n<p>This paragraph stays on the left.</p>`,
  say:"One line of CSS. Nice and easy!"},
 {type:"code",title:"Center the title",
  body:`<p>Inside the ${C("h1")} rule, write ${C("text-align: center;")}. The heading should move to the middle of the page.</p>`,
  start:`<style>\n  h1 {\n    /* center me */\n  }\n</style>\n<h1>Banana Party</h1>\n`,
  checks:[{sel:"h1",style:{"text-align":"center"},msg:"Write text-align: center; inside h1 { }."}],
  hint:`<style>\n  h1 {\n    text-align: center;\n  }\n</style>\n<h1>Banana Party</h1>`},
 {type:"talk",title:"Center a box",mood:"think",
  body:`<p>To center a whole box, give it a ${C("max-width")} and ${C("margin: 0 auto")}. ${C("auto")} shares the leftover space equally on the left and right.</p>`,
  demo:`<style>\n  .card { max-width: 180px; margin: 0 auto; background: #FFF4E5; padding: 12px; border-radius: 12px; }\n</style>\n<div class="card">I'm in the middle!</div>`,
  say:"0 is the top and bottom margin. auto is left and right."},
 {type:"quiz",q:"What does margin: 0 auto do to a box with a max-width?",opts:["Centers it left to right","Removes it from the page","Makes it full width"],a:0,mono:true,why:"auto splits the leftover space evenly on both sides."},
 {type:"code",title:"Center the card",
  body:`<p>The card already has a ${C("max-width")}. Add ${C("margin: 0 auto;")} where the comment is, and the card will slide to the middle.</p>`,
  start:`<style>\n  .card {\n    max-width: 200px;\n    background: #FFF4E5;\n    padding: 12px;\n    /* add margin here */\n  }\n</style>\n<div class="card">🍌 Center me!</div>\n`,
  checks:[{sel:".card",style:{"margin-left":/^[1-9][\d.]*px$/},msg:"Add margin: 0 auto; inside .card { }."}],
  hint:`<style>\n  .card {\n    max-width: 200px;\n    background: #FFF4E5;\n    padding: 12px;\n    margin: 0 auto;\n  }\n</style>\n<div class="card">🍌 Center me!</div>`},
 {type:"talk",title:"Dead center with flexbox",
  body:`<p>Flexbox can center in <b>both</b> directions. On the container: ${C("display: flex")}, then ${C("justify-content: center")} (left to right) and ${C("align-items: center")} (top to bottom).</p>`,
  demo:`<style>\n  .stage { display: flex; justify-content: center; align-items: center; height: 120px; background: #CDEFD9; border-radius: 12px; font-size: 40px; }\n</style>\n<div class="stage">🐒</div>`,
  say:"This is the trick pros use all the time."},
 {type:"fill",title:"Both ways",body:`<p>Center the item in both directions.</p>`,code:`<style>\n  .stage { display: flex; justify-content: [0]; align-items: [1]; }\n</style>`,blanks:["center","center"],tokens:["center","center","middle","top"],why:"Both properties use the value center."},
 {type:"code",title:"Center the monkey",
  body:`<p>${C(".stage")} is already a flex box. Add ${C("justify-content: center;")} and ${C("align-items: center;")} and the monkey moves to the exact middle.</p>`,
  start:`<style>\n  .stage {\n    display: flex;\n    height: 120px;\n    background: #CDEFD9;\n    font-size: 40px;\n    /* center both ways */\n  }\n</style>\n<div class="stage">🐒</div>\n`,
  checks:[{sel:".stage",style:{"justify-content":"center"},msg:"Add justify-content: center; to .stage."},{sel:".stage",style:{"align-items":"center"},msg:"Add align-items: center; to .stage."}],
  hint:`<style>\n  .stage {\n    display: flex;\n    height: 120px;\n    background: #CDEFD9;\n    font-size: 40px;\n    justify-content: center;\n    align-items: center;\n  }\n</style>\n<div class="stage">🐒</div>`},
 {type:"done"}]},
{id:"web23",title:"Flexbox deeper",sub:"flex: 1 and flex-direction",steps:[
 {type:"talk",title:"Grow to fill",
  body:`<p>Put ${C("flex: 1")} on a flex item and it grows to fill all the space that's left over. Perfect for search bars.</p>`,
  demo:`<style>\n  .bar { display: flex; gap: 6px; }\n  .bar input { flex: 1; padding: 8px; }\n</style>\n<div class="bar">\n  <input placeholder="Search bananas...">\n  <button>Go</button>\n</div>`,
  say:"The button stays small, and the input takes the rest."},
 {type:"code",title:"Stretch the search box",
  body:`<p>In the ${C(".bar input")} rule, add ${C("flex: 1;")}. The input should stretch all the way to the button.</p>`,
  start:`<style>\n  .bar { display: flex; gap: 6px; }\n  .bar input {\n    /* make me grow */\n  }\n</style>\n<div class="bar">\n  <input placeholder="Search...">\n  <button>Go</button>\n</div>\n`,
  checks:[{sel:".bar input",style:{"flex-grow":"1"},msg:"Add flex: 1; inside .bar input { }."}],
  hint:`<style>\n  .bar { display: flex; gap: 6px; }\n  .bar input {\n    flex: 1;\n  }\n</style>\n<div class="bar">\n  <input placeholder="Search...">\n  <button>Go</button>\n</div>`},
 {type:"talk",title:"Rows or columns",mood:"think",
  body:`<p>Flex items line up in a row by default. ${C("flex-direction: column")} stacks them top to bottom instead, and ${C("gap")} still works.</p>`,
  demo:`<style>\n  .menu { display: flex; flex-direction: column; gap: 6px; max-width: 160px; }\n  .menu a { background: #FFF4E5; padding: 8px; border-radius: 8px; }\n</style>\n<nav class="menu">\n  <a href="#">Learn</a>\n  <a href="#">Play</a>\n  <a href="#">Shop</a>\n</nav>`,
  say:"Phone menus are often a column like this."},
 {type:"quiz",q:"What does flex-direction: column do?",opts:["Stacks the items top to bottom","Makes columns wider","Turns off flexbox"],a:0,mono:true,why:"column switches the direction from across to down."},
 {type:"code",title:"Stack the menu",
  body:`<p>Add ${C("flex-direction: column;")} to ${C(".menu")}. The three links should stack into a column.</p>`,
  start:`<style>\n  .menu {\n    display: flex;\n    gap: 6px;\n    /* stack us */\n  }\n  .menu a { background: #FFF4E5; padding: 8px; }\n</style>\n<nav class="menu">\n  <a href="#">Learn</a>\n  <a href="#">Play</a>\n  <a href="#">Shop</a>\n</nav>\n`,
  checks:[{sel:".menu",style:{"flex-direction":"column"},msg:"Add flex-direction: column; to .menu."}],
  hint:`<style>\n  .menu {\n    display: flex;\n    gap: 6px;\n    flex-direction: column;\n  }\n  .menu a { background: #FFF4E5; padding: 8px; }\n</style>\n<nav class="menu">\n  <a href="#">Learn</a>\n  <a href="#">Play</a>\n  <a href="#">Shop</a>\n</nav>`},
 {type:"talk",title:"Sharing space",
  body:`<p>The number in ${C("flex")} is a share. ${C("flex: 2")} gets twice as much space as ${C("flex: 1")}. Great for a main area next to a sidebar.</p>`,
  demo:`<style>\n  .page { display: flex; gap: 8px; }\n  .main { flex: 2; background: #CDEFD9; padding: 12px; border-radius: 8px; }\n  .side { flex: 1; background: #E6E1FF; padding: 12px; border-radius: 8px; }\n</style>\n<div class="page">\n  <div class="main">Main (2 shares)</div>\n  <div class="side">Side (1 share)</div>\n</div>`,
  say:"Change 2 to 3 and watch the main area grow."},
 {type:"fill",title:"Twice as wide",body:`<p>Make the main area twice as wide as the sidebar.</p>`,code:`<style>\n  .main { flex: [0]; }\n  .side { flex: [1]; }\n</style>`,blanks:["2","1"],tokens:["2","1","0","10"],why:"2 shares versus 1 share means twice as wide."},
 {type:"done"}]},
{id:"web24",title:"Grid deeper",sub:"span and grid areas",steps:[
 {type:"talk",title:"Big tiles",
  body:`<p>In a grid, ${C("grid-column: span 2")} makes one item stretch across 2 columns. Great for a big featured tile.</p>`,
  demo:`<style>\n  .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; }\n  .grid div { background: #FFD25C; padding: 14px; border-radius: 8px; text-align: center; }\n  .big { grid-column: span 2; }\n</style>\n<div class="grid">\n  <div class="big">⭐ Featured</div>\n  <div>🐒</div>\n  <div>🦜</div><div>🐼</div><div>🦒</div>\n</div>`,
  say:"The other items flow around the big one automatically."},
 {type:"code",title:"Make a big tile",
  body:`<p>In the ${C(".big")} rule, add ${C("grid-column: span 2;")}. The first tile should become twice as wide.</p>`,
  start:`<style>\n  .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; }\n  .grid div { background: #FFD25C; padding: 14px; }\n  .big {\n    /* span 2 columns */\n  }\n</style>\n<div class="grid">\n  <div class="big">⭐</div>\n  <div>🐒</div>\n  <div>🦜</div>\n  <div>🐼</div>\n</div>\n`,
  checks:[{sel:".big",style:{"grid-column":/span 2/},msg:"Add grid-column: span 2; inside .big { }."}],
  hint:`<style>\n  .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; }\n  .grid div { background: #FFD25C; padding: 14px; }\n  .big {\n    grid-column: span 2;\n  }\n</style>\n<div class="grid">\n  <div class="big">⭐</div>\n  <div>🐒</div>\n  <div>🦜</div>\n  <div>🐼</div>\n</div>`},
 {type:"talk",title:"Draw a map of your page",mood:"think",
  body:`<p>${C("grid-template-areas")} lets you draw your layout with words. Each quoted string is a row. Then put an item in a spot with ${C("grid-area: name")}.</p>`,
  demo:`<style>\n  .page {\n    display: grid;\n    grid-template-columns: 1fr 2fr;\n    grid-template-areas:\n      "head head"\n      "side main";\n    gap: 8px;\n  }\n  .page > div { padding: 12px; border-radius: 8px; background: #E6E1FF; }\n  .head { grid-area: head; background: #FFD25C !important; }\n  .side { grid-area: side; }\n  .main { grid-area: main; }\n</style>\n<div class="page">\n  <div class="head">Header</div>\n  <div class="side">Sidebar</div>\n  <div class="main">Main content</div>\n</div>`,
  say:"Writing head twice makes the header stretch across both columns."},
 {type:"quiz",q:"In grid-template-areas, what does the row \"head head\" do?",opts:["The head area fills both columns","It makes two headers","It hides the header"],a:0,why:"Repeating a name makes that area cover those cells."},
 {type:"fill",title:"Put it in place",body:`<p>Put .top in the head area.</p>`,code:`<style>\n  .top { [0]: head; }\n</style>`,blanks:["grid-area"],tokens:["grid-area","area","grid-name","place"],why:"grid-area puts an item into a named area."},
 {type:"code",title:"Place the sidebar",
  body:`<p>The map is drawn and the header and main are placed. In the ${C(".side")} rule, add ${C("grid-area: side;")}. The sidebar should move to the left of the main area.</p>`,
  start:`<style>\n  .page {\n    display: grid;\n    grid-template-columns: 1fr 2fr;\n    grid-template-areas:\n      "head head"\n      "side main";\n    gap: 8px;\n  }\n  .page > div { padding: 12px; background: #E6E1FF; }\n  .head { grid-area: head; }\n  .main { grid-area: main; }\n  .side {\n    /* put me in the side area */\n  }\n</style>\n<div class="page">\n  <div class="head">Header</div>\n  <div class="main">Main content</div>\n  <div class="side">Sidebar</div>\n</div>\n`,
  checks:[{sel:".side",style:{"grid-column-start":"side"},msg:"Add grid-area: side; inside .side { }."}],
  hint:`<style>\n  .page {\n    display: grid;\n    grid-template-columns: 1fr 2fr;\n    grid-template-areas:\n      "head head"\n      "side main";\n    gap: 8px;\n  }\n  .page > div { padding: 12px; background: #E6E1FF; }\n  .head { grid-area: head; }\n  .main { grid-area: main; }\n  .side {\n    grid-area: side;\n  }\n</style>\n<div class="page">\n  <div class="head">Header</div>\n  <div class="main">Main content</div>\n  <div class="side">Sidebar</div>\n</div>`},
 {type:"done"}]},
{id:"web25",title:"Animations",sub:"@keyframes and animation",steps:[
 {type:"talk",title:"Make it move",mood:"cheer",
  body:`<p>Animations play all by themselves, no hover needed. First, ${C("@keyframes")} describes the movement from start (${C("from")}) to end (${C("to")}). Then ${C("animation")} plays it on an element.</p>`,
  demo:`<style>\n  @keyframes bounce {\n    from { transform: translateY(0); }\n    to { transform: translateY(-20px); }\n  }\n  .monkey { display: inline-block; font-size: 48px; animation: bounce 0.6s infinite alternate; }\n</style>\n<div class="monkey">🐒</div>`,
  say:"Boing boing! TypeMonkey loves this one."},
 {type:"talk",title:"Reading the animation line",mood:"think",
  body:`<p>${C("animation: bounce 0.6s infinite alternate")} means: play <b>bounce</b>, take <b>0.6 seconds</b>, repeat <b>forever</b>, and go back and forth (<b>alternate</b>) instead of jumping back to the start.</p>`,
  demo:`<style>\n  @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }\n  .sun { display: inline-block; font-size: 40px; animation: spin 3s linear infinite; }\n</style>\n<div class="sun">🌞</div>`,
  say:"linear keeps the speed steady, which looks best for spinning."},
 {type:"quiz",q:"Which part describes the steps of an animation?",opts:["@keyframes","animation-play","@media"],a:0,mono:true,why:"@keyframes holds the steps. The animation property plays them."},
 {type:"code",title:"Play the animation",
  body:`<p>The ${C("wiggle")} keyframes are ready. In the ${C(".monkey")} rule, add ${C("animation: wiggle 1s infinite;")} and the monkey starts wiggling.</p>`,
  start:`<style>\n  @keyframes wiggle {\n    0% { transform: rotate(-10deg); }\n    50% { transform: rotate(10deg); }\n    100% { transform: rotate(-10deg); }\n  }\n  .monkey {\n    display: inline-block;\n    font-size: 48px;\n    /* play wiggle here */\n  }\n</style>\n<div class="monkey">🐒</div>\n`,
  checks:[{sel:".monkey",style:{"animation-name":"wiggle"},msg:"Add animation: wiggle 1s infinite; inside .monkey { }."},{sel:".monkey",style:{"animation-iteration-count":"infinite"},msg:"Add infinite so it keeps going: animation: wiggle 1s infinite;"}],
  hint:`<style>\n  @keyframes wiggle {\n    0% { transform: rotate(-10deg); }\n    50% { transform: rotate(10deg); }\n    100% { transform: rotate(-10deg); }\n  }\n  .monkey {\n    display: inline-block;\n    font-size: 48px;\n    animation: wiggle 1s infinite;\n  }\n</style>\n<div class="monkey">🐒</div>`},
 {type:"fill",title:"Forever and ever",body:`<p>Make the spin repeat forever.</p>`,code:`<style>\n  .sun { animation: spin 2s [0]; }\n</style>`,blanks:["infinite"],tokens:["infinite","forever","loop","always"],why:"infinite repeats the animation with no end."},
 {type:"code",title:"Make it pulse",
  body:`<p>The heart is already playing ${C("pulse")}, but the keyframes only have a ${C("from")} step. Add a ${C("to")} step that grows it: ${C("to { transform: scale(1.3); }")}. The heart should beat!</p>`,
  start:`<style>\n  @keyframes pulse {\n    from { transform: scale(1); }\n    /* add the to step here */\n  }\n  .heart { display: inline-block; font-size: 48px; animation: pulse 0.8s infinite alternate; }\n</style>\n<div class="heart">🧡</div>\n`,
  use:[[/\bto\s*\{[^}]*transform\s*:\s*scale\(/,"Add a to step inside @keyframes pulse: to { transform: scale(1.3); }"]],
  checks:[{sel:".heart",style:{"animation-name":"pulse"},msg:"Keep the .heart rule playing pulse."}],
  hint:`<style>\n  @keyframes pulse {\n    from { transform: scale(1); }\n    to { transform: scale(1.3); }\n  }\n  .heart { display: inline-block; font-size: 48px; animation: pulse 0.8s infinite alternate; }\n</style>\n<div class="heart">🧡</div>`},
 {type:"talk",title:"Be kind with motion",
  body:`<p>A little motion is fun, but too much can make some people feel dizzy. Keep animations small, and you can switch them off for people who ask for less motion with ${C("@media (prefers-reduced-motion: reduce)")}.</p>`,
  demo:`<style>\n  @keyframes bob { to { transform: translateY(-6px); } }\n  .tip { display: inline-block; animation: bob 1s infinite alternate; }\n  @media (prefers-reduced-motion: reduce) {\n    .tip { animation: none; }\n  }\n</style>\n<p><span class="tip">🍌</span> A gentle bob, switched off if you prefer less motion.</p>`,
  say:"Good animation is like seasoning. A little goes a long way."},
 {type:"done"}]},
{id:"web26",title:"Project: TypeMonkey Fan Page",sub:"layout, flexbox, grid, theme and animation",project:true,steps:[
 {type:"talk",title:"Build a fan page",mood:"cheer",
  body:`<p>Final project for this unit: a fan page for TypeMonkey! It has a header with a nav bar, a grid of fun facts, a theme color and a bouncing mascot. You'll build it in five small steps.</p>`,
  demo:`<style>\n  .fan { --monkey: #FF7A1A; }\n  .fan header { display: flex; justify-content: space-between; align-items: center; background: #14201B; color: white; padding: 8px 12px; border-radius: 10px; }\n  .fan header h1 { font-size: 18px; margin: 0; color: var(--monkey); }\n  .fan nav a { color: #FFD25C; margin-left: 8px; }\n  @keyframes bounce { to { transform: translateY(-12px); } }\n  .mascot { text-align: center; font-size: 56px; }\n  .mascot span { display: inline-block; animation: bounce 0.6s infinite alternate; }\n  .facts { display: grid; grid-template-columns: repeat(2, 1fr); gap: 8px; }\n  .fact { background: #FFF4E5; padding: 10px; border-radius: 10px; }\n  .fan footer { text-align: center; color: gray; margin-top: 12px; }\n</style>\n<div class="fan">\n  <header><h1>🐒 TypeMonkey Fans</h1><nav><a href="#">Facts</a><a href="#">Join</a></nav></header>\n  <main>\n    <div class="mascot"><span>🐒</span></div>\n    <div class="facts">\n      <div class="fact">🍌 Eats 3 bananas a day</div>\n      <div class="fact">⌨️ Types super fast</div>\n      <div class="fact">🧡 Favorite color: orange</div>\n      <div class="fact">🎓 Teaches coding</div>\n    </div>\n  </main>\n  <footer>Made by a TypeMonkey fan</footer>\n</div>`,
  say:"Here's the goal. One small step at a time!"},
 {type:"code",title:"Step 1: the page skeleton",
  body:`<p>The header is done. Add a ${C("&lt;main&gt;")} with a ${C("&lt;p&gt;")} inside it, and then a ${C("&lt;footer&gt;")} with any text.</p>`,
  start:`<header>\n  <h1>🐒 TypeMonkey Fans</h1>\n</header>\n<!-- 1. a main with a p inside -->\n<!-- 2. a footer -->\n`,
  checks:[{sel:"main p",text:/\S/,msg:"Add <main><p>Some text</p></main> under the header."},{sel:"footer",text:/\S/,msg:"Add a <footer> with some text at the bottom."}],
  hint:`<header>\n  <h1>🐒 TypeMonkey Fans</h1>\n</header>\n<main>\n  <p>Welcome, fellow fans!</p>\n</main>\n<footer>Made by a TypeMonkey fan</footer>`},
 {type:"code",title:"Step 2: the nav bar",
  body:`<p>Turn the header into a nav bar. In the ${C("header")} rule, add ${C("display: flex;")} and ${C("justify-content: space-between;")}. The title goes left and the links go right.</p>`,
  start:`<style>\n  header {\n    background: #14201B;\n    color: white;\n    padding: 8px 12px;\n    /* add flex here */\n  }\n  header h1 { font-size: 18px; margin: 0; }\n  header a { color: #FFD25C; margin-left: 8px; }\n</style>\n<header>\n  <h1>🐒 Fans</h1>\n  <nav><a href="#">Facts</a><a href="#">Join</a></nav>\n</header>\n`,
  checks:[{sel:"header",style:{display:"flex"},msg:"Add display: flex; to header."},{sel:"header",style:{"justify-content":"space-between"},msg:"Add justify-content: space-between; to header."}],
  hint:`<style>\n  header {\n    background: #14201B;\n    color: white;\n    padding: 8px 12px;\n    display: flex;\n    justify-content: space-between;\n  }\n  header h1 { font-size: 18px; margin: 0; }\n  header a { color: #FFD25C; margin-left: 8px; }\n</style>\n<header>\n  <h1>🐒 Fans</h1>\n  <nav><a href="#">Facts</a><a href="#">Join</a></nav>\n</header>`},
 {type:"code",title:"Step 3: fun facts grid",
  body:`<p>Make ${C(".facts")} a grid with 2 columns: ${C("display: grid;")} and ${C("grid-template-columns: repeat(2, 1fr);")}. The four facts become a 2 by 2 square.</p>`,
  start:`<style>\n  .facts {\n    gap: 8px;\n    /* make a 2-column grid */\n  }\n  .fact { background: #FFF4E5; padding: 10px; border-radius: 10px; }\n</style>\n<div class="facts">\n  <div class="fact">🍌 Eats 3 bananas a day</div>\n  <div class="fact">⌨️ Types super fast</div>\n  <div class="fact">🧡 Loves orange</div>\n  <div class="fact">🎓 Teaches coding</div>\n</div>\n`,
  checks:[{sel:".facts",style:{display:"grid"},msg:"Add display: grid; to .facts."},{sel:".facts",style:{"grid-template-columns":/^\S+\s+\S+$/},msg:"Add grid-template-columns: repeat(2, 1fr); to .facts."}],
  hint:`<style>\n  .facts {\n    gap: 8px;\n    display: grid;\n    grid-template-columns: repeat(2, 1fr);\n  }\n  .fact { background: #FFF4E5; padding: 10px; border-radius: 10px; }\n</style>\n<div class="facts">\n  <div class="fact">🍌 Eats 3 bananas a day</div>\n  <div class="fact">⌨️ Types super fast</div>\n  <div class="fact">🧡 Loves orange</div>\n  <div class="fact">🎓 Teaches coding</div>\n</div>`},
 {type:"code",title:"Step 4: the theme color",
  body:`<p>Give the page a theme color. On ${C(".fan")}, define ${C("--monkey: #FF7A1A;")}. Then in the ${C(".fan h1")} rule, use it: ${C("color: var(--monkey);")}. The title turns TypeMonkey orange.</p>`,
  start:`<style>\n  .fan {\n    /* 1. define --monkey here */\n  }\n  .fan h1 {\n    /* 2. use var(--monkey) for the color */\n  }\n</style>\n<div class="fan">\n  <h1>🐒 TypeMonkey Fans</h1>\n  <p>The best coding buddy around.</p>\n</div>\n`,
  use:[[/--monkey\s*:\s*#FF7A1A/i,"Define --monkey: #FF7A1A; inside .fan { }."],[/color\s*:\s*var\(\s*--monkey\s*\)/,"Use color: var(--monkey); inside .fan h1 { }."]],
  checks:[{sel:".fan h1",style:{color:"#FF7A1A"},msg:"The h1 should end up orange through var(--monkey)."}],
  hint:`<style>\n  .fan {\n    --monkey: #FF7A1A;\n  }\n  .fan h1 {\n    color: var(--monkey);\n  }\n</style>\n<div class="fan">\n  <h1>🐒 TypeMonkey Fans</h1>\n  <p>The best coding buddy around.</p>\n</div>`},
 {type:"code",title:"Step 5: the bouncing mascot",
  body:`<p>Last step! The ${C("bounce")} keyframes are ready. In the ${C(".mascot")} rule, add ${C("animation: bounce 0.6s infinite alternate;")} and watch TypeMonkey jump.</p>`,
  start:`<style>\n  @keyframes bounce {\n    from { transform: translateY(0); }\n    to { transform: translateY(-12px); }\n  }\n  .mascot {\n    display: inline-block;\n    font-size: 56px;\n    /* add the animation here */\n  }\n</style>\n<div class="mascot">🐒</div>\n`,
  checks:[{sel:".mascot",style:{"animation-name":"bounce"},msg:"Add animation: bounce 0.6s infinite alternate; to .mascot."}],
  hint:`<style>\n  @keyframes bounce {\n    from { transform: translateY(0); }\n    to { transform: translateY(-12px); }\n  }\n  .mascot {\n    display: inline-block;\n    font-size: 56px;\n    animation: bounce 0.6s infinite alternate;\n  }\n</style>\n<div class="mascot">🐒</div>`},
 {type:"talk",title:"The finished fan page",mood:"cheer",
  body:`<p>All five steps, together on one page. Tap ▶ Show page, then make it your own: add facts, change the theme color, or add a ${C("@media")} rule so the facts stack into one column on phones.</p>`,
  demo:`<style>\n  .fan { --monkey: #FF7A1A; }\n  .fan header { display: flex; justify-content: space-between; align-items: center; background: #14201B; color: white; padding: 8px 12px; border-radius: 10px; }\n  .fan header h1 { font-size: 18px; margin: 0; color: var(--monkey); }\n  .fan nav a { color: #FFD25C; margin-left: 8px; }\n  @keyframes bounce { to { transform: translateY(-12px); } }\n  .mascot { text-align: center; font-size: 56px; }\n  .mascot span { display: inline-block; animation: bounce 0.6s infinite alternate; }\n  .facts { display: grid; grid-template-columns: repeat(2, 1fr); gap: 8px; }\n  .fact { background: #FFF4E5; padding: 10px; border-radius: 10px; }\n  .fan footer { text-align: center; color: gray; margin-top: 12px; }\n  @media (max-width: 400px) { .facts { grid-template-columns: 1fr; } }\n</style>\n<div class="fan">\n  <header><h1>🐒 TypeMonkey Fans</h1><nav><a href="#">Facts</a><a href="#">Join</a></nav></header>\n  <main>\n    <div class="mascot"><span>🐒</span></div>\n    <div class="facts">\n      <div class="fact">🍌 Eats 3 bananas a day</div>\n      <div class="fact">⌨️ Types super fast</div>\n      <div class="fact">🧡 Favorite color: orange</div>\n      <div class="fact">🎓 Teaches coding</div>\n    </div>\n  </main>\n  <footer>Made by a TypeMonkey fan</footer>\n</div>`,
  say:"You built a whole fan page. TypeMonkey is blushing!"},
 {type:"done"}]}
]});
