/* Launch depth for C# and C++: two hands-on units each (practice lab + interactive programs).
   Every lesson has real code challenges. Starters already hold most of the code; learners fill in one small piece.
   Challenges with `tests` read typed input (Console.ReadLine / std::cin): each test types its `input` and expects `out`. */

/* ======================= C# ======================= */
COURSE_CS.units.push({name:"C# Practice Lab",lessons:[
{id:"cs16",title:"Warm-up: methods",sub:"give a method values, get an answer back",steps:[
 {type:"talk",title:"Welcome to the lab!",mood:"cheer",
  body:`<p>This unit is all about <b>practice</b>. Every lesson has real code for you to write, and the starter code already does most of the work. You just fill in the missing piece.</p><p>First, a quick refresher. A method takes values in (its <b>parameters</b>) and can hand one value back with ${C("return")}.</p>`,
  demo:`static int Add(int a, int b) {\n  return a + b;\n}\n\nConsole.WriteLine(Add(2, 3));\nConsole.WriteLine(Add(10, 5));`,
  say:"Output:\n5\n15\n\nPress ▶ Run to see it for yourself."},
 {type:"code",title:"Fill in the return",body:`<p>${C("Square")} should give back n times n. Change the line ${C("return 0;")} to ${C("return n * n;")}</p><p>The output should be ${C("16")} and then ${C("49")}.</p>`,
  start:`static int Square(int n) {\n  return 0; // change this line\n}\n\nConsole.WriteLine(Square(4));\nConsole.WriteLine(Square(7));\n`,
  out:["16","49"],
  hint:`static int Square(int n) {\n  return n * n;\n}\n\nConsole.WriteLine(Square(4));\nConsole.WriteLine(Square(7));`},
 {type:"talk",title:"Text in, text out",mood:"think",
  body:`<p>Methods can return text too. The return type is ${C("string")}, and ${C("$\"...\"")} builds the text.</p>`,
  demo:`static string Greet(string name) {\n  return $"Hi, {name}!";\n}\n\nConsole.WriteLine(Greet("Ava"));\nConsole.WriteLine(Greet("Leo"));`,
  say:"Output:\nHi, Ava!\nHi, Leo!"},
 {type:"code",title:"Make a cheer",body:`<p>Finish ${C("Cheer")} so it returns ${C("Go")}, a space, the team name and an ${C("!")}. Tip: ${C("return $\"Go {team}!\";")}</p><p>The output should be ${C("Go Monkeys!")} and then ${C("Go Tigers!")}.</p>`,
  start:`static string Cheer(string team) {\n  return ""; // change this line\n}\n\nConsole.WriteLine(Cheer("Monkeys"));\nConsole.WriteLine(Cheer("Tigers"));\n`,
  out:["Go Monkeys!","Go Tigers!"],
  hint:`static string Cheer(string team) {\n  return $"Go {team}!";\n}\n\nConsole.WriteLine(Cheer("Monkeys"));\nConsole.WriteLine(Cheer("Tigers"));`},
 {type:"quiz",q:"What does this print?",code:`static int Half(int n) {\n  return n / 2;\n}\n\nConsole.WriteLine(Half(7));`,opts:["3","3.5","4"],a:0,mono:true,why:"n is an int, so 7 / 2 drops the decimal and gives 3."},
 {type:"fill",title:"Pick the return type",body:`<p>This method answers yes or no. What type does it return?</p>`,
  code:`static [0] IsBig(int n) {\n  return n > 100;\n}`,blanks:["bool"],tokens:["bool","int","string","void"],why:"n > 100 is true or false, so the method returns a bool."},
 {type:"game"},{type:"done"}],
 pool:[
  [`static int Add(int a, int b) => a + b;\n\nConsole.WriteLine(Add(4, 4));`,["8","44","4"]],
  [`static string Hi(string n) => "Hi " + n;\n\nConsole.WriteLine(Hi("Mo"));`,["Hi Mo","Hi n","HiMo"]],
  [`static int Square(int n) => n * n;\n\nConsole.WriteLine(Square(3) + 1);`,["10","16","7"]],
  [`static bool IsBig(int n) => n > 100;\n\nConsole.WriteLine(IsBig(50));`,["False","True","50"]],
  [`static int Half(int n) => n / 2;\n\nConsole.WriteLine(Half(9));`,["4","4.5","5"]]
 ]},
{id:"cs17",title:"Lists in action",sub:"Add, Count, foreach and totals",steps:[
 {type:"talk",title:"A quick list refresher",
  body:`<p>A ${C("List&lt;T&gt;")} holds many values and can grow. ${C(".Add()")} puts a new item on the end, ${C(".Count")} says how many there are, and ${C("foreach")} visits each one.</p>`,
  demo:`var snacks = new List<string> { "banana", "mango" };\nsnacks.Add("kiwi");\nConsole.WriteLine(snacks.Count);\nforeach (string s in snacks) {\n  Console.WriteLine(s);\n}`,
  say:"Output:\n3\nbanana\nmango\nkiwi"},
 {type:"code",title:"Add one more",body:`<p>On the empty line, add ${C("\"kiwi\"")} to the list with ${C("snacks.Add(\"kiwi\");")}</p><p>The output should be ${C("banana")}, ${C("mango")} and ${C("kiwi")}, one per line.</p>`,
  start:`var snacks = new List<string> { "banana", "mango" };\n// add kiwi on this line\n\nforeach (string s in snacks) {\n  Console.WriteLine(s);\n}\n`,
  use:[[/snacks\.Add\s*\(/,"Use snacks.Add(\"kiwi\"); to add it."]],out:["banana","mango","kiwi"],
  hint:`var snacks = new List<string> { "banana", "mango" };\nsnacks.Add("kiwi");\n\nforeach (string s in snacks) {\n  Console.WriteLine(s);\n}`},
 {type:"talk",title:"Adding up a list",mood:"think",
  body:`<p>To total a list, start a variable at 0. Then add each item to it inside a ${C("foreach")}. Print it <b>after</b> the loop is done.</p>`,
  demo:`var coins = new List<int> { 3, 4, 5 };\nint total = 0;\nforeach (int c in coins) {\n  total += c;\n}\nConsole.WriteLine(total);`,
  say:"Output: 12. Round by round, total goes 3, 7, 12."},
 {type:"code",title:"Total the scores",body:`<p>Inside the loop, add each score to ${C("total")} with ${C("total += n;")}</p><p>The output should be ${C("25")}.</p>`,
  start:`var scores = new List<int> { 5, 10, 10 };\nint total = 0;\nforeach (int n in scores) {\n  // add n to total here\n}\nConsole.WriteLine(total);\n`,
  use:[[/total\s*\+=\s*n|total\s*=\s*total\s*\+\s*n/,"Inside the loop, write total += n;"]],out:["25"],variants:[[/\{ 5, 10, 10 \}/,"{ 1, 2, 3 }",["6"]]],
  hint:`var scores = new List<int> { 5, 10, 10 };\nint total = 0;\nforeach (int n in scores) {\n  total += n;\n}\nConsole.WriteLine(total);`},
 {type:"quiz",q:"What does this print?",code:`var l = new List<int> { 4, 6 };\nl.Add(5);\nConsole.WriteLine(l.Count);`,opts:["3","2","15"],a:0,mono:true,why:"Two items to start, plus one more: 3 items. Count is how many, not the total."},
 {type:"code",title:"Numbered list",body:`<p>This loop uses a counter ${C("i")}, so ${C("snacks[i]")} is the item at that spot. Print each item with its number in front, like ${C("1. banana")}. Tip: ${C("Console.WriteLine($\"{i + 1}. {snacks[i]}\");")}</p><p>The output should be ${C("1. banana")}, ${C("2. mango")}, ${C("3. kiwi")}.</p>`,
  start:`var snacks = new List<string> { "banana", "mango", "kiwi" };\nfor (int i = 0; i < snacks.Count; i++) {\n  // print the number and the snack here\n}\n`,
  out:["1. banana","2. mango","3. kiwi"],
  hint:`var snacks = new List<string> { "banana", "mango", "kiwi" };\nfor (int i = 0; i < snacks.Count; i++) {\n  Console.WriteLine($"{i + 1}. {snacks[i]}");\n}`},
 {type:"fill",title:"How many?",body:`<p>Print how many items the list has.</p>`,
  code:`var pets = new List<string> { "cat", "owl" };\nConsole.WriteLine(pets.[0]);`,blanks:["Count"],tokens:["Count","Length","Size","Total"],why:"Lists use .Count. Arrays use .Length."},
 {type:"game"},{type:"done"}],
 pool:[
  [`var l = new List<string> { "a" };\nl.Add("b");\nConsole.WriteLine(l.Count);`,["2","1","ab"]],
  [`var l = new List<int> { 2, 3 };\nint t = 0;\nforeach (int n in l) t += n;\nConsole.WriteLine(t);`,["5","23","2"]],
  [`var l = new List<string> { "x", "y", "z" };\nConsole.WriteLine(l[1]);`,["y","x","z"]],
  [`var l = new List<int>();\nl.Add(7);\nl.Add(7);\nConsole.WriteLine(l.Count);`,["2","7","14"]],
  [`var l = new List<string> { "ook", "eek" };\nforeach (string s in l) Console.Write(s);`,["ookeek","ook eek","eekook"]]
 ]},
{id:"cs18",title:"Dictionaries in action",sub:"look up, update and count",steps:[
 {type:"talk",title:"Look it up",
  body:`<p>A ${C("Dictionary")} finds a value by its <b>key</b>. Put the key in square brackets to read it.</p>`,
  demo:`var prices = new Dictionary<string, int> { ["banana"] = 2, ["mango"] = 5 };\nConsole.WriteLine(prices["mango"]);\nConsole.WriteLine(prices["banana"]);`,
  say:"Output:\n5\n2"},
 {type:"code",title:"Price check",body:`<p>Print the price of a ${C("coconut")}, then the price of a ${C("banana")}. Tip: ${C("Console.WriteLine(prices[\"coconut\"]);")}</p><p>The output should be ${C("8")} and then ${C("2")}.</p>`,
  start:`var prices = new Dictionary<string, int> { ["banana"] = 2, ["coconut"] = 8 };\n// print the two prices here\n`,
  use:[[/prices\s*\[\s*"coconut"\s*\]/,"Read the price with prices[\"coconut\"]."]],out:["8","2"],
  hint:`var prices = new Dictionary<string, int> { ["banana"] = 2, ["coconut"] = 8 };\nConsole.WriteLine(prices["coconut"]);\nConsole.WriteLine(prices["banana"]);`},
 {type:"talk",title:"Change and add",mood:"think",
  body:`<p>${C("prices[\"mango\"] += 3;")} changes a value that's already there. ${C("prices[\"kiwi\"] = 4;")} adds a brand new key.</p>`,
  demo:`var prices = new Dictionary<string, int> { ["mango"] = 5 };\nprices["mango"] += 3;\nprices["kiwi"] = 4;\nforeach (var p in prices) {\n  Console.WriteLine($"{p.Key}: {p.Value}");\n}`,
  say:"Output:\nmango: 8\nkiwi: 4"},
 {type:"code",title:"Price change",body:`<p>Make bananas cost 1 more, and add ${C("\"kiwi\"")} with a price of 4. The loop that prints everything is already there.</p><p>The output should be ${C("banana: 3")}, ${C("mango: 5")}, ${C("kiwi: 4")}.</p>`,
  start:`var prices = new Dictionary<string, int> { ["banana"] = 2, ["mango"] = 5 };\n// make banana cost 1 more\n// add kiwi with a price of 4\n\nforeach (var p in prices) {\n  Console.WriteLine($"{p.Key}: {p.Value}");\n}\n`,
  use:[[/\["kiwi"\]/,"Add the new key with prices[\"kiwi\"] = 4;"]],out:["banana: 3","mango: 5","kiwi: 4"],
  hint:`var prices = new Dictionary<string, int> { ["banana"] = 2, ["mango"] = 5 };\nprices["banana"] += 1;\nprices["kiwi"] = 4;\n\nforeach (var p in prices) {\n  Console.WriteLine($"{p.Key}: {p.Value}");\n}`},
 {type:"talk",title:"Counting votes",mood:"cheer",
  body:`<p>Dictionaries are great for counting. If the key is already there, add 1. If not, start it at 1.</p>`,
  demo:`string[] votes = { "pizza", "tacos", "pizza" };\nvar counts = new Dictionary<string, int>();\nforeach (string v in votes) {\n  if (counts.ContainsKey(v)) {\n    counts[v]++;\n  } else {\n    counts[v] = 1;\n  }\n}\nConsole.WriteLine(counts["pizza"]);`,
  say:"Output: 2"},
 {type:"code",title:"Snack poll",body:`<p>The counting code is ready except for one line. In the ${C("else")} part, start a new snack at 1: ${C("counts[s] = 1;")}</p><p>The output should be ${C("banana: 3")}, ${C("mango: 1")}, ${C("kiwi: 1")}.</p>`,
  start:`string[] picks = { "banana", "mango", "banana", "kiwi", "banana" };\nvar counts = new Dictionary<string, int>();\nforeach (string s in picks) {\n  if (counts.ContainsKey(s)) {\n    counts[s]++;\n  } else {\n    // start this snack at 1\n  }\n}\nforeach (var c in counts) {\n  Console.WriteLine($"{c.Key}: {c.Value}");\n}\n`,
  out:["banana: 3","mango: 1","kiwi: 1"],
  hint:`string[] picks = { "banana", "mango", "banana", "kiwi", "banana" };\nvar counts = new Dictionary<string, int>();\nforeach (string s in picks) {\n  if (counts.ContainsKey(s)) {\n    counts[s]++;\n  } else {\n    counts[s] = 1;\n  }\n}\nforeach (var c in counts) {\n  Console.WriteLine($"{c.Key}: {c.Value}");\n}`},
 {type:"quiz",q:"What does this print?",code:`var d = new Dictionary<string, int> { ["a"] = 1 };\nConsole.WriteLine(d.ContainsKey("b"));`,opts:["False","True","0"],a:0,mono:true,why:"There's no key \"b\", so ContainsKey says False."},
 {type:"game"},{type:"done"}],
 pool:[
  [`var d = new Dictionary<string, int> { ["x"] = 3 };\nd["x"] += 2;\nConsole.WriteLine(d["x"]);`,["5","3","2"]],
  [`var d = new Dictionary<string, int>();\nd["a"] = 1;\nd["b"] = 1;\nConsole.WriteLine(d.Count);`,["2","1","0"]],
  [`var d = new Dictionary<string, int> { ["hp"] = 9 };\nConsole.WriteLine(d.ContainsKey("hp"));`,["True","False","9"]],
  [`var d = new Dictionary<string, string> { ["cat"] = "meow" };\nConsole.WriteLine(d["cat"]);`,["meow","cat","cat: meow"]],
  [`var d = new Dictionary<string, int> { ["a"] = 1, ["b"] = 2 };\nforeach (var p in d) Console.Write(p.Value);`,["12","ab","3"]]
 ]},
{id:"cs19",title:"LINQ: ask your list",sub:"Max, Sum, Where, Select, OrderBy",steps:[
 {type:"talk",title:"Questions instead of loops",mood:"cheer",
  body:`<p><b>LINQ</b> lets you ask a list a question in one short line. What's the biggest? What's the total? It comes from ${C("using System.Linq;")}, which modern C# includes for you.</p>`,
  demo:`var scores = new List<int> { 70, 95, 82, 60 };\nConsole.WriteLine(scores.Max());\nConsole.WriteLine(scores.Min());\nConsole.WriteLine(scores.Sum());\nConsole.WriteLine(scores.Average());`,
  say:"Output:\n95\n60\n307\n76.75\n\nNo loops needed!"},
 {type:"code",title:"Best and total",body:`<p>Print the highest score with ${C("scores.Max()")}, then the total with ${C("scores.Sum()")}.</p><p>The output should be ${C("95")} and then ${C("307")}.</p>`,
  start:`var scores = new List<int> { 70, 95, 82, 60 };\n// print the highest score\n// print the total\n`,
  use:[[/\.Max\s*\(/,"Use scores.Max() for the highest."],[/\.Sum\s*\(/,"Use scores.Sum() for the total."]],out:["95","307"],
  hint:`var scores = new List<int> { 70, 95, 82, 60 };\nConsole.WriteLine(scores.Max());\nConsole.WriteLine(scores.Sum());`},
 {type:"talk",title:"Where: keep some",mood:"think",
  body:`<p>${C("Where")} keeps only the items that pass a test. The test ${C("s =&gt; s &gt;= 80")} is a tiny method called a <b>lambda</b>. Read it as \"for each s, keep it if s is 80 or more\".</p>`,
  demo:`var scores = new List<int> { 70, 95, 82, 60 };\nvar great = scores.Where(s => s >= 80).ToList();\nConsole.WriteLine(string.Join(", ", great));`,
  say:"Output: 95, 82"},
 {type:"code",title:"Keep the big ones",body:`<p>Right now the test keeps every number above 0. Change the ${C("0")} to ${C("10")} so only numbers bigger than 10 are kept.</p><p>The output should be ${C("12, 40, 11")}.</p>`,
  start:`var nums = new List<int> { 3, 12, 40, 7, 11 };\nvar big = nums.Where(n => n > 0).ToList();\nConsole.WriteLine(string.Join(", ", big));\n`,
  out:["12, 40, 11"],
  hint:`var nums = new List<int> { 3, 12, 40, 7, 11 };\nvar big = nums.Where(n => n > 10).ToList();\nConsole.WriteLine(string.Join(", ", big));`},
 {type:"talk",title:"Select and OrderBy",
  body:`<p>${C("Select")} changes every item. ${C("OrderBy")} sorts them, smallest first (or A to Z for text).</p>`,
  demo:`var nums = new List<int> { 3, 1, 2 };\nConsole.WriteLine(string.Join(", ", nums.Select(n => n * 10)));\nConsole.WriteLine(string.Join(", ", nums.OrderBy(n => n)));`,
  say:"Output:\n30, 10, 20\n1, 2, 3"},
 {type:"code",title:"Sort the names",body:`<p>Sort the names from A to Z. Change ${C("names")} on the second line to ${C("names.OrderBy(n =&gt; n)")}</p><p>The output should be ${C("Ava, Kai, Leo, Zoe")}.</p>`,
  start:`var names = new List<string> { "Zoe", "Ava", "Leo", "Kai" };\nvar sorted = names;\nConsole.WriteLine(string.Join(", ", sorted));\n`,
  use:[[/OrderBy/,"Use names.OrderBy(n => n) to sort."]],out:["Ava, Kai, Leo, Zoe"],
  hint:`var names = new List<string> { "Zoe", "Ava", "Leo", "Kai" };\nvar sorted = names.OrderBy(n => n);\nConsole.WriteLine(string.Join(", ", sorted));`},
 {type:"quiz",q:"What does this print?",code:`var l = new List<int> { 1, 2, 3, 4 };\nConsole.WriteLine(l.Count(n => n % 2 == 0));`,opts:["2","4","6"],a:0,mono:true,why:"Count with a test counts only the items that pass. 2 and 4 are even."},
 {type:"game"},{type:"done"}],
 pool:[
  [`var l = new List<int> { 4, 9, 2 };\nConsole.WriteLine(l.Max());`,["9","4","2"]],
  [`var l = new List<int> { 4, 9, 2 };\nConsole.WriteLine(l.Sum());`,["15","3","942"]],
  [`var l = new List<int> { 2, 4 };\nConsole.WriteLine(l.Average());`,["3","6","2"]],
  [`var l = new List<int> { 1, 5, 8 };\nConsole.WriteLine(string.Join(",", l.Where(n => n > 4)));`,["5,8","1","1,5,8"]],
  [`var l = new List<int> { 1, 2 };\nConsole.WriteLine(string.Join(",", l.Select(n => n + 1)));`,["2,3","1,2","3"]],
  [`var l = new List<string> { "b", "c", "a" };\nConsole.WriteLine(string.Join("", l.OrderBy(s => s)));`,["abc","bca","cba"]]
 ]},
{id:"cs20",title:"Project: Grade Book",sub:"lists + methods + LINQ",project:true,steps:[
 {type:"talk",title:"Build a grade book",mood:"cheer",
  body:`<p>Teachers keep a grade book: a list of scores, the class average, the best score, and a letter for each one. You'll build it in four small steps.</p>`,
  say:"One small piece at a time. You've got this!"},
 {type:"code",title:"Step 1: store the scores",body:`<p>Add the scores ${C("88")}, ${C("92")} and ${C("75")} to the list, one ${C(".Add()")} each.</p><p>The output should be ${C("3")}.</p>`,
  start:`var scores = new List<int>();\n// add 88, 92 and 75 here\n\nConsole.WriteLine(scores.Count);\n`,
  use:[[/\.Add\s*\(/,"Use scores.Add(88); and so on."]],out:["3"],
  hint:`var scores = new List<int>();\nscores.Add(88);\nscores.Add(92);\nscores.Add(75);\n\nConsole.WriteLine(scores.Count);`},
 {type:"code",title:"Step 2: the average",body:`<p>Change ${C("double avg = 0;")} so it uses ${C("scores.Average()")}. The ${C(":F1")} shows one decimal place.</p><p>The output should be ${C("Average: 85.0")}.</p>`,
  start:`var scores = new List<int> { 88, 92, 75 };\ndouble avg = 0; // use scores.Average()\nConsole.WriteLine($"Average: {avg:F1}");\n`,
  use:[[/\.Average\s*\(/,"Use scores.Average()."]],out:["Average: 85.0"],
  hint:`var scores = new List<int> { 88, 92, 75 };\ndouble avg = scores.Average();\nConsole.WriteLine($"Average: {avg:F1}");`},
 {type:"code",title:"Step 3: letter grades",body:`<p>${C("Letter")} already gives an ${C("A")} for 90 or more. Add two lines: 80 or more returns ${C("\"B\"")}, and 70 or more returns ${C("\"C\"")}.</p><p>The output should be ${C("88: B")}, ${C("92: A")}, ${C("75: C")}.</p>`,
  start:`static string Letter(int score) {\n  if (score >= 90) return "A";\n  // add the B line here\n  // add the C line here\n  return "Keep going";\n}\n\nvar scores = new List<int> { 88, 92, 75 };\nforeach (int s in scores) {\n  Console.WriteLine($"{s}: {Letter(s)}");\n}\n`,
  out:["88: B","92: A","75: C"],
  hint:`static string Letter(int score) {\n  if (score >= 90) return "A";\n  if (score >= 80) return "B";\n  if (score >= 70) return "C";\n  return "Keep going";\n}\n\nvar scores = new List<int> { 88, 92, 75 };\nforeach (int s in scores) {\n  Console.WriteLine($"{s}: {Letter(s)}");\n}`},
 {type:"quiz",q:"With that Letter method, what does Letter(80) return?",opts:["B","A","C"],a:0,why:"80 isn't 90 or more, but it is 80 or more, so it's a B."},
 {type:"code",title:"Step 4: the full report",body:`<p>Everything is in place. Add one last line at the bottom that prints ${C("Best:")} and the highest score, using ${C("scores.Max()")}.</p><p>The last line should be ${C("Best: 92")}.</p>`,
  start:`static string Letter(int score) {\n  if (score >= 90) return "A";\n  if (score >= 80) return "B";\n  if (score >= 70) return "C";\n  return "Keep going";\n}\n\nvar scores = new List<int> { 88, 92, 75 };\nforeach (int s in scores) {\n  Console.WriteLine($"{s}: {Letter(s)}");\n}\nConsole.WriteLine($"Average: {scores.Average():F1}");\n// print the best score here\n`,
  use:[[/\.Max\s*\(/,"Use scores.Max() for the best score."]],out:["88: B","92: A","75: C","Average: 85.0","Best: 92"],
  hint:`static string Letter(int score) {\n  if (score >= 90) return "A";\n  if (score >= 80) return "B";\n  if (score >= 70) return "C";\n  return "Keep going";\n}\n\nvar scores = new List<int> { 88, 92, 75 };\nforeach (int s in scores) {\n  Console.WriteLine($"{s}: {Letter(s)}");\n}\nConsole.WriteLine($"Average: {scores.Average():F1}");\nConsole.WriteLine($"Best: {scores.Max()}");`},
 {type:"talk",title:"The finished grade book",mood:"cheer",
  body:`<p>Here's the whole thing, now reading the scores from the ⌨️ Input box. Press ▶ Run, then change the numbers and run it again!</p>`,
  input:"88\n92\n75",demo:`static string Letter(int score) {\n  if (score >= 90) return "A";\n  if (score >= 80) return "B";\n  if (score >= 70) return "C";\n  return "Keep going";\n}\n\nvar scores = new List<int>();\nfor (int i = 0; i < 3; i++) {\n  scores.Add(int.Parse(Console.ReadLine()));\n}\nforeach (int s in scores) {\n  Console.WriteLine($"{s}: {Letter(s)}");\n}\nConsole.WriteLine($"Average: {scores.Average():F1}");\nConsole.WriteLine($"Best: {scores.Max()}");`,
  say:"You built a real tool with lists, methods and LINQ. Next up: programs that talk to the player!"},
 {type:"done"}]}
]});

COURSE_CS.units.push({name:"Interactive C#",lessons:[
{id:"cs21",title:"Warm-up: talking to the player",sub:"Console.ReadLine",steps:[
 {type:"talk",title:"Your program can listen",mood:"cheer",
  body:`<p>${C("Console.ReadLine()")} waits for the player to type a line, then gives it back as a ${C("string")}.</p><p>In TypeMonkey, whatever is in the ⌨️ <b>Input</b> box under the code gets typed in for you. Press ▶ Run, then change the name and run it again.</p>`,
  input:"Mo",demo:`Console.WriteLine("What's your name?");\nstring name = Console.ReadLine();\nConsole.WriteLine($"Nice to meet you, {name}!");`,
  say:"The player typed Mo, so it prints:\nNice to meet you, Mo!"},
 {type:"code",title:"Say hi back",body:`<p>The name is already read for you. Add one line that prints ${C("Hi,")} the name and ${C("!")}. Tip: ${C("Console.WriteLine($\"Hi, {name}!\");")}</p><p>If the player types ${C("Ava")}, the output should be ${C("What's your name?")} and then ${C("Hi, Ava!")}.</p>`,
  start:`Console.WriteLine("What's your name?");\nstring name = Console.ReadLine();\n// print the greeting here\n`,
  tests:[{input:"Ava",out:["What's your name?","Hi, Ava!"]},{input:"Leo",out:["What's your name?","Hi, Leo!"]}],
  hint:`Console.WriteLine("What's your name?");\nstring name = Console.ReadLine();\nConsole.WriteLine($"Hi, {name}!");`},
 {type:"talk",title:"One question at a time",mood:"think",
  body:`<p>Each ${C("ReadLine()")} reads the <b>next</b> line. So in the Input box, put each answer on its own line.</p>`,
  input:"Mo\nblue",demo:`Console.WriteLine("Name?");\nstring name = Console.ReadLine();\nConsole.WriteLine("Favorite color?");\nstring color = Console.ReadLine();\nConsole.WriteLine($"{name} likes {color}.");`,
  say:"Output ends with: Mo likes blue."},
 {type:"code",title:"Two questions",body:`<p>The name is read for you. Read the food the same way (${C("string food = Console.ReadLine();")}), then print the name, ${C("loves")} and the food, like ${C("Ava loves pizza!")}</p>`,
  start:`Console.WriteLine("Name?");\nstring name = Console.ReadLine();\nConsole.WriteLine("Favorite food?");\n// read the food here\n// print the sentence here\n`,
  tests:[{input:"Ava\npizza",out:["Name?","Favorite food?","Ava loves pizza!"]},{input:"Leo\nmangoes",out:["Name?","Favorite food?","Leo loves mangoes!"]}],
  hint:`Console.WriteLine("Name?");\nstring name = Console.ReadLine();\nConsole.WriteLine("Favorite food?");\nstring food = Console.ReadLine();\nConsole.WriteLine($"{name} loves {food}!");`},
 {type:"quiz",q:"What type of value does Console.ReadLine() give back?",opts:["string","int","bool"],a:0,mono:true,why:"It's always text, even if the player types a number. The next lesson shows how to turn it into a number."},
 {type:"fill",title:"Read a line",body:`<p>Read what the player types into ${C("pet")}.</p>`,
  code:`string pet = Console.[0]();`,blanks:["ReadLine"],tokens:["ReadLine","WriteLine","Read","Input"],why:"ReadLine reads; WriteLine prints."},
 {type:"game"},{type:"done"}],
 pool:[
  [`string name = "Mo";\nConsole.WriteLine($"Hi, {name}!");`,["Hi, Mo!","Hi, {name}!","Hi, name!"]],
  [`string a = "Ava";\nstring f = "figs";\nConsole.WriteLine($"{a} loves {f}");`,["Ava loves figs","a loves f","Avalovesfigs"]],
  [`string s = "ook";\nConsole.WriteLine(s + "!");`,["ook!","ook !","s!"]],
  [`string s = "5";\nConsole.WriteLine(s + s);`,["55","10","5 5"]],
  [`string s = "Mo";\nConsole.WriteLine(s.Length);`,["2","Mo","1"]]
 ]},
{id:"cs22",title:"Numbers from the keyboard",sub:"int.Parse and math on input",steps:[
 {type:"talk",title:"Text isn't a number (yet)",mood:"oops",
  body:`<p>${C("ReadLine()")} always gives text. Add ${C("\"5\" + \"5\"")} and you get ${C("\"55\"")}, not 10!</p><p>${C("int.Parse()")} turns text like ${C("\"7\"")} into the number 7 so you can do math with it.</p>`,
  input:"7",demo:`Console.WriteLine("How old are you?");\nint age = int.Parse(Console.ReadLine());\nConsole.WriteLine($"Next year you'll be {age + 1}!");`,
  say:"The player typed 7, so it prints:\nNext year you'll be 8!"},
 {type:"code",title:"Double it",body:`<p>The number is already read for you. Print it doubled with ${C("Console.WriteLine(n * 2);")}</p><p>If the player types ${C("4")}, the output should be ${C("Pick a number:")} and then ${C("8")}.</p>`,
  start:`Console.WriteLine("Pick a number:");\nint n = int.Parse(Console.ReadLine());\n// print n doubled here\n`,
  tests:[{input:"4",out:["Pick a number:","8"]},{input:"21",out:["Pick a number:","42"]}],
  hint:`Console.WriteLine("Pick a number:");\nint n = int.Parse(Console.ReadLine());\nConsole.WriteLine(n * 2);`},
 {type:"talk",title:"Decide with input",mood:"think",
  body:`<p>Once it's a number, you can use it in an ${C("if")}, just like any other number.</p>`,
  input:"15",demo:`int age = int.Parse(Console.ReadLine());\nif (age >= 13) {\n  Console.WriteLine("You can join the club!");\n} else {\n  Console.WriteLine("Come back soon!");\n}`,
  say:"15 is 13 or more, so: You can join the club!"},
 {type:"code",title:"Ride check",body:`<p>The ${C("if")} part is done. Add an ${C("else")} that prints ${C("Not yet!")} for anyone shorter than 120.</p><p>If the player types ${C("130")}, it prints ${C("You can ride!")}. If they type ${C("100")}, it prints ${C("Not yet!")}</p>`,
  start:`int height = int.Parse(Console.ReadLine());\nif (height >= 120) {\n  Console.WriteLine("You can ride!");\n}\n// add the else here\n`,
  use:[[/\belse\b/,"Add an else { ... } after the if."]],tests:[{input:"130",out:["You can ride!"]},{input:"100",out:["Not yet!"]},{input:"120",out:["You can ride!"]}],
  hint:`int height = int.Parse(Console.ReadLine());\nif (height >= 120) {\n  Console.WriteLine("You can ride!");\n} else {\n  Console.WriteLine("Not yet!");\n}`},
 {type:"quiz",q:"What does this print?",code:`string a = "5";\nstring b = "5";\nConsole.WriteLine(a + b);`,opts:["55","10","5 + 5"],a:0,mono:true,why:"a and b are text, so + glues them together. That's why we use int.Parse first."},
 {type:"code",title:"Mini calculator",body:`<p>The first number is read for you. Read the second one into ${C("b")} the same way, then print ${C("a + b")}.</p><p>If the player types ${C("3")} and ${C("4")}, the output should be ${C("7")}.</p>`,
  start:`int a = int.Parse(Console.ReadLine());\n// read b here\n// print a + b here\n`,
  tests:[{input:"3\n4",out:["7"]},{input:"10\n25",out:["35"]}],
  hint:`int a = int.Parse(Console.ReadLine());\nint b = int.Parse(Console.ReadLine());\nConsole.WriteLine(a + b);`},
 {type:"game"},{type:"done"}],
 pool:[
  [`int n = int.Parse("7");\nConsole.WriteLine(n + 1);`,["8","71","7"]],
  [`string s = "7";\nConsole.WriteLine(s + 1);`,["71","8","7"]],
  [`int a = int.Parse("3");\nint b = int.Parse("4");\nConsole.WriteLine(a * b);`,["12","34","7"]],
  [`int h = int.Parse("110");\nif (h >= 120) Console.WriteLine("ride");\nelse Console.WriteLine("wait");`,["wait","ride","110"]],
  [`int n = int.Parse("10");\nConsole.WriteLine(n / 4);`,["2","2.5","3"]]
 ]},
{id:"cs23",title:"Loops that listen",sub:"keep asking until the player is done",steps:[
 {type:"talk",title:"Ask again and again",
  body:`<p>Put ${C("ReadLine()")} inside a loop to keep listening. ${C("while (true)")} loops forever, so we ${C("break")} out when the player types ${C("quit")}.</p><p>If the Input box runs out of lines, ${C("ReadLine()")} gives ${C("null")} (nothing at all). Checking for it too keeps the loop safe.</p>`,
  input:"hello\nbananas\nquit",demo:`while (true) {\n  string word = Console.ReadLine();\n  if (word == null || word == "quit") break;\n  Console.WriteLine($"You said: {word}");\n}\nConsole.WriteLine("Bye!");`,
  say:"Output:\nYou said: hello\nYou said: bananas\nBye!"},
 {type:"code",title:"Echo bot",body:`<p>The loop is ready. Add one line inside it that prints the word in capitals: ${C("Console.WriteLine(word.ToUpper());")}</p><p>If the player types ${C("hi")}, ${C("ook")}, ${C("quit")}, the output should be ${C("HI")} and ${C("OOK")}.</p>`,
  start:`while (true) {\n  string word = Console.ReadLine();\n  if (word == null || word == "quit") break;\n  // print the word in capitals here\n}\n`,
  use:[[/ToUpper/,"Use word.ToUpper()."]],tests:[{input:"hi\nook\nquit",out:["HI","OOK"]},{input:"banana\nquit",out:["BANANA"]}],
  hint:`while (true) {\n  string word = Console.ReadLine();\n  if (word == null || word == "quit") break;\n  Console.WriteLine(word.ToUpper());\n}`},
 {type:"talk",title:"Keep a running total",mood:"think",
  body:`<p>A loop can add up everything the player types. Here, typing ${C("0")} means \"I'm done\".</p>`,
  input:"5\n10\n0",demo:`int total = 0;\nwhile (true) {\n  int n = int.Parse(Console.ReadLine());\n  if (n == 0) break;\n  total += n;\n}\nConsole.WriteLine($"Total: {total}");`,
  say:"5 + 10 = 15, so: Total: 15"},
 {type:"code",title:"Banana counter",body:`<p>Each number is how many bananas the monkey picked. The loop reads until ${C("0")}. Add one line inside the loop so the number gets added to ${C("total")}: ${C("total += n;")}</p><p>If the player types ${C("3")}, ${C("4")}, ${C("0")}, the output should be ${C("Bananas: 7")}.</p>`,
  start:`int total = 0;\nwhile (true) {\n  int n = int.Parse(Console.ReadLine());\n  if (n == 0) break;\n  // add n to total here\n}\nConsole.WriteLine($"Bananas: {total}");\n`,
  tests:[{input:"3\n4\n0",out:["Bananas: 7"]},{input:"10\n0",out:["Bananas: 10"]},{input:"0",out:["Bananas: 0"]}],
  hint:`int total = 0;\nwhile (true) {\n  int n = int.Parse(Console.ReadLine());\n  if (n == 0) break;\n  total += n;\n}\nConsole.WriteLine($"Bananas: {total}");`},
 {type:"talk",title:"Menus with switch",
  body:`<p>A ${C("switch")} picks one path based on a value. It's a tidy way to handle menu choices. Each ${C("case")} ends with ${C("break;")}, and ${C("default")} catches everything else.</p>`,
  input:"2",demo:`Console.WriteLine("1) Play  2) Help");\nstring choice = Console.ReadLine();\nswitch (choice) {\n  case "1":\n    Console.WriteLine("Let's go!");\n    break;\n  case "2":\n    Console.WriteLine("Type 1 to play.");\n    break;\n  default:\n    Console.WriteLine("Pick 1 or 2.");\n    break;\n}`,
  say:"The player typed 2, so: Type 1 to play."},
 {type:"code",title:"Snack menu",body:`<p>Case ${C("\"1\"")} is done. Add ${C("case \"2\":")} that prints ${C("Mango")}, then a ${C("default:")} that prints ${C("Not on the menu")}. Remember ${C("break;")} after each one.</p>`,
  start:`string choice = Console.ReadLine();\nswitch (choice) {\n  case "1":\n    Console.WriteLine("Banana");\n    break;\n  // add case "2" here\n  // add default here\n}\n`,
  use:[[/default\s*:/,"Add a default: case for anything else."]],tests:[{input:"1",out:["Banana"]},{input:"2",out:["Mango"]},{input:"9",out:["Not on the menu"]}],
  hint:`string choice = Console.ReadLine();\nswitch (choice) {\n  case "1":\n    Console.WriteLine("Banana");\n    break;\n  case "2":\n    Console.WriteLine("Mango");\n    break;\n  default:\n    Console.WriteLine("Not on the menu");\n    break;\n}`},
 {type:"quiz",q:"What does break do inside while (true)?",opts:["Leaves the loop","Skips to the next round","Stops the whole program with an error"],a:0,why:"break jumps out of the loop. The code after the loop keeps running."},
 {type:"game"},{type:"done"}],
 pool:[
  [`int t = 0;\nforeach (int n in new[] { 2, 3, 0, 9 }) {\n  if (n == 0) break;\n  t += n;\n}\nConsole.WriteLine(t);`,["5","14","0"]],
  [`string c = "2";\nswitch (c) {\n  case "1": Console.WriteLine("A"); break;\n  case "2": Console.WriteLine("B"); break;\n  default: Console.WriteLine("?"); break;\n}`,["B","A","?"]],
  [`string c = "7";\nswitch (c) {\n  case "1": Console.WriteLine("A"); break;\n  default: Console.WriteLine("?"); break;\n}`,["?","A","7"]],
  [`int i = 0;\nwhile (true) {\n  i++;\n  if (i == 3) break;\n}\nConsole.WriteLine(i);`,["3","2","4"]],
  [`Console.WriteLine("ook".ToUpper());`,["OOK","ook","Ook"]]
 ]},
{id:"cs24",title:"Objects in action",sub:"methods, lists inside classes, ToString",steps:[
 {type:"talk",title:"A class refresher",
  body:`<p>A class bundles data and the methods that work on it. Methods inside the class can change the object's own values.</p>`,
  demo:`Player p = new Player("Mo");\np.AddPoints(10);\np.AddPoints(5);\nConsole.WriteLine(p.Score);\n\nclass Player {\n  public string Name;\n  public int Score;\n  public Player(string name) { Name = name; }\n  public void AddPoints(int pts) { Score += pts; }\n}`,
  say:"Output: 15"},
 {type:"code",title:"Lose a life",body:`<p>Finish ${C("Hit()")} so it takes 1 away from ${C("Lives")}. Tip: ${C("Lives -= 1;")} or ${C("Lives--;")}</p><p>The hero starts with 3 lives and gets hit twice, so the output should be ${C("1")}.</p>`,
  start:`Hero h = new Hero();\nh.Hit();\nh.Hit();\nConsole.WriteLine(h.Lives);\n\nclass Hero {\n  public int Lives = 3;\n  public void Hit() {\n    // take away one life here\n  }\n}\n`,
  out:["1"],
  hint:`Hero h = new Hero();\nh.Hit();\nh.Hit();\nConsole.WriteLine(h.Lives);\n\nclass Hero {\n  public int Lives = 3;\n  public void Hit() {\n    Lives--;\n  }\n}`},
 {type:"talk",title:"A class with a list inside",mood:"think",
  body:`<p>A field can be a whole ${C("List")}. Here a backpack keeps its items in a list, and ${C("Pack()")} adds to it.</p>`,
  demo:`Backpack bag = new Backpack();\nbag.Pack("rope");\nbag.Pack("map");\nConsole.WriteLine(bag.Items.Count);\n\nclass Backpack {\n  public List<string> Items = new List<string>();\n  public void Pack(string item) {\n    Items.Add(item);\n  }\n}`,
  say:"Output: 2"},
 {type:"code",title:"Pack it",body:`<p>Finish ${C("Pack()")} so it adds the item to ${C("Items")}: ${C("Items.Add(item);")}</p><p>The output should be ${C("3")}, then ${C("rope")}, ${C("map")}, ${C("banana")}.</p>`,
  start:`Backpack bag = new Backpack();\nbag.Pack("rope");\nbag.Pack("map");\nbag.Pack("banana");\nConsole.WriteLine(bag.Items.Count);\nforeach (string it in bag.Items) {\n  Console.WriteLine(it);\n}\n\nclass Backpack {\n  public List<string> Items = new List<string>();\n  public void Pack(string item) {\n    // add item to Items here\n  }\n}\n`,
  use:[[/Items\.Add\s*\(/,"Use Items.Add(item);"]],out:["3","rope","map","banana"],
  hint:`Backpack bag = new Backpack();\nbag.Pack("rope");\nbag.Pack("map");\nbag.Pack("banana");\nConsole.WriteLine(bag.Items.Count);\nforeach (string it in bag.Items) {\n  Console.WriteLine(it);\n}\n\nclass Backpack {\n  public List<string> Items = new List<string>();\n  public void Pack(string item) {\n    Items.Add(item);\n  }\n}`},
 {type:"talk",title:"ToString: how an object prints",mood:"cheer",
  body:`<p>When you print an object, C# calls its ${C("ToString()")} method. Write your own with ${C("public override string ToString()")} and you decide what it looks like.</p>`,
  demo:`Pet p = new Pet("Bitsy", 3);\nConsole.WriteLine(p);\n\nclass Pet {\n  public string Name;\n  public int Age;\n  public Pet(string name, int age) { Name = name; Age = age; }\n  public override string ToString() => $"{Name} is {Age}";\n}`,
  say:"Output: Bitsy is 3"},
 {type:"code",title:"Show the score",body:`<p>Change the ${C("ToString")} line so it returns the name, a colon, the score and ${C("points")}. Tip: ${C("$\"{Name}: {Score} points\"")}</p><p>The output should be ${C("Mo: 30 points")}.</p>`,
  start:`Player p = new Player("Mo", 30);\nConsole.WriteLine(p);\n\nclass Player {\n  public string Name;\n  public int Score;\n  public Player(string name, int score) { Name = name; Score = score; }\n  public override string ToString() => "?"; // change this\n}\n`,
  out:["Mo: 30 points"],
  hint:`Player p = new Player("Mo", 30);\nConsole.WriteLine(p);\n\nclass Player {\n  public string Name;\n  public int Score;\n  public Player(string name, int score) { Name = name; Score = score; }\n  public override string ToString() => $"{Name}: {Score} points";\n}`},
 {type:"quiz",q:"What does this print?",code:`Bag b = new Bag();\nb.Items.Add("key");\nb.Items.Add("map");\nConsole.WriteLine(b.Items.Count);\n\nclass Bag {\n  public List<string> Items = new List<string>();\n}`,opts:["2","0","key"],a:0,mono:true,why:"Two items were added to the bag's list."},
 {type:"game"},{type:"done"}],
 pool:[
  [`Hero h = new Hero();\nh.Lives--;\nConsole.WriteLine(h.Lives);\n\nclass Hero {\n  public int Lives = 3;\n}`,["2","3","4"]],
  [`Pet p = new Pet();\nConsole.WriteLine(p);\n\nclass Pet {\n  public override string ToString() => "ook";\n}`,["ook","Pet","p"]],
  [`Bag b = new Bag();\nConsole.WriteLine(b.Items.Count);\n\nclass Bag {\n  public List<string> Items = new List<string>();\n}`,["0","1","null"]],
  [`Player p = new Player();\np.Add(4);\np.Add(4);\nConsole.WriteLine(p.Score);\n\nclass Player {\n  public int Score;\n  public void Add(int n) { Score += n; }\n}`,["8","4","0"]],
  [`Box a = new Box();\nBox b = a;\nb.N = 5;\nConsole.WriteLine(a.N);\n\nclass Box {\n  public int N;\n}`,["5","0","null"]]
 ]},
{id:"cs25",title:"Project: Text Adventure",sub:"input + loops + methods",project:true,steps:[
 {type:"talk",title:"Escape the temple!",mood:"cheer",
  body:`<p>You'll build a tiny text adventure. The player starts in a dusty <b>hall</b>. North is a <b>kitchen</b> with a banana. East is the <b>garden</b> and freedom, but a monkey guard won't let you pass without a banana!</p><p>The player types commands like ${C("north")}, ${C("south")}, ${C("take")} and ${C("east")} in the ⌨️ Input box.</p>`,
  say:"Four small steps. Let's build it!"},
 {type:"code",title:"Step 1: describe the rooms",body:`<p>${C("Describe")} returns the text for each room. The hall and garden are done. Add a ${C("case \"kitchen\":")} that returns ${C("You are in the kitchen. A banana sits on the table.")}</p>`,
  start:`Console.WriteLine(Describe("hall"));\nConsole.WriteLine(Describe("kitchen"));\n\nstatic string Describe(string room) {\n  switch (room) {\n    case "hall": return "You are in a dusty hall. Doors lead north and east.";\n    // add the kitchen case here\n    case "garden": return "Sunshine! You found the garden. You escaped!";\n    default: return "You are lost.";\n  }\n}\n`,
  out:["You are in a dusty hall. Doors lead north and east.","You are in the kitchen. A banana sits on the table."],
  hint:`Console.WriteLine(Describe("hall"));\nConsole.WriteLine(Describe("kitchen"));\n\nstatic string Describe(string room) {\n  switch (room) {\n    case "hall": return "You are in a dusty hall. Doors lead north and east.";\n    case "kitchen": return "You are in the kitchen. A banana sits on the table.";\n    case "garden": return "Sunshine! You found the garden. You escaped!";\n    default: return "You are lost.";\n  }\n}`},
 {type:"code",title:"Step 2: walking around",body:`<p>The game loop reads one command each round. Going ${C("north")} from the hall already works. Add an ${C("else if")} so going ${C("south")} from the kitchen sets ${C("room = \"hall\";")} and prints ${C("Describe(room)")}.</p>`,
  start:`string room = "hall";\nConsole.WriteLine(Describe(room));\nwhile (room != "garden") {\n  string cmd = Console.ReadLine();\n  if (cmd == null || cmd == "quit") break;\n  if (room == "hall" && cmd == "north") {\n    room = "kitchen";\n    Console.WriteLine(Describe(room));\n  }\n  // add: else if room is kitchen and cmd is south\n  else {\n    Console.WriteLine("You can't do that here.");\n  }\n}\n\nstatic string Describe(string room) {\n  switch (room) {\n    case "hall": return "You are in a dusty hall. Doors lead north and east.";\n    case "kitchen": return "You are in the kitchen. A banana sits on the table.";\n    case "garden": return "Sunshine! You found the garden. You escaped!";\n    default: return "You are lost.";\n  }\n}\n`,
  tests:[{input:"north\nsouth\nquit",out:["You are in a dusty hall. Doors lead north and east.","You are in the kitchen. A banana sits on the table.","You are in a dusty hall. Doors lead north and east."]},
         {input:"south\nquit",out:["You are in a dusty hall. Doors lead north and east.","You can't do that here."]}],
  hint:`string room = "hall";\nConsole.WriteLine(Describe(room));\nwhile (room != "garden") {\n  string cmd = Console.ReadLine();\n  if (cmd == null || cmd == "quit") break;\n  if (room == "hall" && cmd == "north") {\n    room = "kitchen";\n    Console.WriteLine(Describe(room));\n  }\n  else if (room == "kitchen" && cmd == "south") {\n    room = "hall";\n    Console.WriteLine(Describe(room));\n  }\n  else {\n    Console.WriteLine("You can't do that here.");\n  }\n}\n\nstatic string Describe(string room) {\n  switch (room) {\n    case "hall": return "You are in a dusty hall. Doors lead north and east.";\n    case "kitchen": return "You are in the kitchen. A banana sits on the table.";\n    case "garden": return "Sunshine! You found the garden. You escaped!";\n    default: return "You are lost.";\n  }\n}`},
 {type:"code",title:"Step 3: grab the banana",body:`<p>Now add a ${C("take")} command. Fill in the empty ${C("else if")}: set ${C("hasBanana = true;")} and print ${C("You take the banana.")}</p>`,
  start:`string room = "hall";\nbool hasBanana = false;\nConsole.WriteLine(Describe(room));\nwhile (room != "garden") {\n  string cmd = Console.ReadLine();\n  if (cmd == null || cmd == "quit") break;\n  if (room == "hall" && cmd == "north") {\n    room = "kitchen";\n    Console.WriteLine(Describe(room));\n  } else if (room == "kitchen" && cmd == "south") {\n    room = "hall";\n    Console.WriteLine(Describe(room));\n  } else if (room == "kitchen" && cmd == "take") {\n    // grab the banana here (two lines)\n  } else {\n    Console.WriteLine("You can't do that here.");\n  }\n}\nConsole.WriteLine($"Banana: {hasBanana}");\n\nstatic string Describe(string room) {\n  switch (room) {\n    case "hall": return "You are in a dusty hall. Doors lead north and east.";\n    case "kitchen": return "You are in the kitchen. A banana sits on the table.";\n    case "garden": return "Sunshine! You found the garden. You escaped!";\n    default: return "You are lost.";\n  }\n}\n`,
  tests:[{input:"north\ntake\nquit",out:["You are in a dusty hall. Doors lead north and east.","You are in the kitchen. A banana sits on the table.","You take the banana.","Banana: True"]},
         {input:"take\nquit",out:["You are in a dusty hall. Doors lead north and east.","You can't do that here.","Banana: False"]}],
  hint:`string room = "hall";\nbool hasBanana = false;\nConsole.WriteLine(Describe(room));\nwhile (room != "garden") {\n  string cmd = Console.ReadLine();\n  if (cmd == null || cmd == "quit") break;\n  if (room == "hall" && cmd == "north") {\n    room = "kitchen";\n    Console.WriteLine(Describe(room));\n  } else if (room == "kitchen" && cmd == "south") {\n    room = "hall";\n    Console.WriteLine(Describe(room));\n  } else if (room == "kitchen" && cmd == "take") {\n    hasBanana = true;\n    Console.WriteLine("You take the banana.");\n  } else {\n    Console.WriteLine("You can't do that here.");\n  }\n}\nConsole.WriteLine($"Banana: {hasBanana}");\n\nstatic string Describe(string room) {\n  switch (room) {\n    case "hall": return "You are in a dusty hall. Doors lead north and east.";\n    case "kitchen": return "You are in the kitchen. A banana sits on the table.";\n    case "garden": return "Sunshine! You found the garden. You escaped!";\n    default: return "You are lost.";\n  }\n}`},
 {type:"code",title:"Step 4: the monkey guard",body:`<p>Last piece! Going ${C("east")} from the hall: if ${C("hasBanana")} is true, set ${C("room = \"garden\";")} and print ${C("Describe(room)")}. Otherwise print ${C("The monkey guard wants a banana!")}</p>`,
  start:`string room = "hall";\nbool hasBanana = false;\nConsole.WriteLine(Describe(room));\nwhile (room != "garden") {\n  string cmd = Console.ReadLine();\n  if (cmd == null || cmd == "quit") break;\n  if (room == "hall" && cmd == "north") {\n    room = "kitchen";\n    Console.WriteLine(Describe(room));\n  } else if (room == "kitchen" && cmd == "south") {\n    room = "hall";\n    Console.WriteLine(Describe(room));\n  } else if (room == "kitchen" && cmd == "take") {\n    hasBanana = true;\n    Console.WriteLine("You take the banana.");\n  } else if (room == "hall" && cmd == "east") {\n    // if hasBanana: go to the garden and describe it\n    // else: print the guard's line\n  } else {\n    Console.WriteLine("You can't do that here.");\n  }\n}\n\nstatic string Describe(string room) {\n  switch (room) {\n    case "hall": return "You are in a dusty hall. Doors lead north and east.";\n    case "kitchen": return "You are in the kitchen. A banana sits on the table.";\n    case "garden": return "Sunshine! You found the garden. You escaped!";\n    default: return "You are lost.";\n  }\n}\n`,
  tests:[{input:"east\nquit",out:["You are in a dusty hall. Doors lead north and east.","The monkey guard wants a banana!"]},
         {input:"north\ntake\nsouth\neast",out:["You are in a dusty hall. Doors lead north and east.","You are in the kitchen. A banana sits on the table.","You take the banana.","You are in a dusty hall. Doors lead north and east.","Sunshine! You found the garden. You escaped!"]}],
  hint:`string room = "hall";\nbool hasBanana = false;\nConsole.WriteLine(Describe(room));\nwhile (room != "garden") {\n  string cmd = Console.ReadLine();\n  if (cmd == null || cmd == "quit") break;\n  if (room == "hall" && cmd == "north") {\n    room = "kitchen";\n    Console.WriteLine(Describe(room));\n  } else if (room == "kitchen" && cmd == "south") {\n    room = "hall";\n    Console.WriteLine(Describe(room));\n  } else if (room == "kitchen" && cmd == "take") {\n    hasBanana = true;\n    Console.WriteLine("You take the banana.");\n  } else if (room == "hall" && cmd == "east") {\n    if (hasBanana) {\n      room = "garden";\n      Console.WriteLine(Describe(room));\n    } else {\n      Console.WriteLine("The monkey guard wants a banana!");\n    }\n  } else {\n    Console.WriteLine("You can't do that here.");\n  }\n}\n\nstatic string Describe(string room) {\n  switch (room) {\n    case "hall": return "You are in a dusty hall. Doors lead north and east.";\n    case "kitchen": return "You are in the kitchen. A banana sits on the table.";\n    case "garden": return "Sunshine! You found the garden. You escaped!";\n    default: return "You are lost.";\n  }\n}`},
 {type:"quiz",q:"The player types east, north, take, south, east. How does the game end?",opts:["They escape to the garden","The guard stops them","They're stuck in the kitchen"],a:0,why:"The first east fails (no banana yet), but after taking the banana and walking back south, east works."},
 {type:"talk",title:"Play your game!",mood:"cheer",
  body:`<p>Here's the finished adventure. Press ▶ Run to play with the moves in the ⌨️ Input box, then try your own. Can you add a new room?</p>`,
  input:"east\nnorth\ntake\nsouth\neast",demo:`string room = "hall";\nbool hasBanana = false;\nConsole.WriteLine(Describe(room));\nwhile (room != "garden") {\n  string cmd = Console.ReadLine();\n  if (cmd == null || cmd == "quit") break;\n  if (room == "hall" && cmd == "north") {\n    room = "kitchen";\n    Console.WriteLine(Describe(room));\n  } else if (room == "kitchen" && cmd == "south") {\n    room = "hall";\n    Console.WriteLine(Describe(room));\n  } else if (room == "kitchen" && cmd == "take") {\n    hasBanana = true;\n    Console.WriteLine("You take the banana.");\n  } else if (room == "hall" && cmd == "east") {\n    if (hasBanana) {\n      room = "garden";\n      Console.WriteLine(Describe(room));\n    } else {\n      Console.WriteLine("The monkey guard wants a banana!");\n    }\n  } else {\n    Console.WriteLine("You can't do that here.");\n  }\n}\n\nstatic string Describe(string room) {\n  switch (room) {\n    case "hall": return "You are in a dusty hall. Doors lead north and east.";\n    case "kitchen": return "You are in the kitchen. A banana sits on the table.";\n    case "garden": return "Sunshine! You found the garden. You escaped!";\n    default: return "You are lost.";\n  }\n}`,
  say:"You made a real game that listens to the player. Amazing work!"},
 {type:"done"}]}
]});

/* ======================= C++ =======================
   Like cpp-units-2-4.js: snippets without int main() are the inside of main; snippets with functions,
   structs or std::map show the full program. */
COURSE_CPP.units.push({name:"C++ Practice Lab",lessons:[
{id:"cpp16",title:"Warm-up: functions",sub:"values in, answers out",steps:[
 {type:"talk",title:"Welcome to the lab!",mood:"cheer",
  body:`<p>This unit is all about <b>practice</b>. Every lesson has real code for you to write, and the starter code already does most of the work. You just fill in the missing piece.</p><p>Quick refresher: a function lists its return type, its name, and its typed parameters. ${C("return")} hands an answer back.</p>`,
  demo:`#include <iostream>\n\nint add(int a, int b) {\n  return a + b;\n}\n\nint main() {\n  std::cout << add(2, 3) << "\\n";\n  std::cout << add(10, 5);\n}`,
  say:"Output:\n5\n15\n\nPress ▶ Run to see it for yourself."},
 {type:"code",title:"Fill in the return",body:`<p>${C("square")} should give back n times n. Change the line ${C("return 0;")} to ${C("return n * n;")}</p><p>The output should be ${C("16")} and then ${C("49")}.</p>`,
  start:`int square(int n) {\n  return 0; // change this line\n}\n\nint main() {\n  std::cout << square(4) << "\\n";\n  std::cout << square(7);\n}\n`,
  out:["16","49"],
  hint:`int square(int n) {\n  return n * n;\n}\n\nint main() {\n  std::cout << square(4) << "\\n";\n  std::cout << square(7);\n}`},
 {type:"talk",title:"Text in, text out",mood:"think",
  body:`<p>Functions can return a ${C("std::string")} too. The ${C("+")} sign glues pieces of text together.</p>`,
  demo:`#include <iostream>\n#include <string>\n\nstd::string greet(std::string name) {\n  return "Hi, " + name + "!";\n}\n\nint main() {\n  std::cout << greet("Ava") << "\\n";\n  std::cout << greet("Leo");\n}`,
  say:"Output:\nHi, Ava!\nHi, Leo!"},
 {type:"code",title:"Make a cheer",body:`<p>Finish ${C("cheer")} so it returns ${C("Go")}, a space, the team and an ${C("!")}. Tip: ${C("return \"Go \" + team + \"!\";")}</p><p>The output should be ${C("Go Monkeys!")} and then ${C("Go Tigers!")}.</p>`,
  start:`std::string cheer(std::string team) {\n  return ""; // change this line\n}\n\nint main() {\n  std::cout << cheer("Monkeys") << "\\n";\n  std::cout << cheer("Tigers");\n}\n`,
  out:["Go Monkeys!","Go Tigers!"],
  hint:`std::string cheer(std::string team) {\n  return "Go " + team + "!";\n}\n\nint main() {\n  std::cout << cheer("Monkeys") << "\\n";\n  std::cout << cheer("Tigers");\n}`},
 {type:"talk",title:"Remember the &?",mood:"oops",
  body:`<p>A normal parameter is a <b>copy</b>, so changing it doesn't change the caller's variable. Add ${C("&amp;")} to make it a <b>reference</b> to the real thing.</p>`,
  demo:`#include <iostream>\n\nvoid addPoints(int& score, int pts) {\n  score += pts;\n}\n\nint main() {\n  int score = 0;\n  addPoints(score, 5);\n  addPoints(score, 5);\n  std::cout << score;\n}`,
  say:"Output: 10. Without the & it would still be 0."},
 {type:"code",title:"Heal for real",body:`<p>${C("heal")} only changes a copy right now, so the hero stays at 10. Add one ${C("&amp;")} so ${C("hp")} is a reference: ${C("int&amp; hp")}</p><p>The output should be ${C("15")}.</p>`,
  start:`void heal(int hp, int amount) {\n  hp += amount;\n}\n\nint main() {\n  int hp = 10;\n  heal(hp, 5);\n  std::cout << hp;\n}\n`,
  use:[[/int\s*&\s*hp/,"Make hp a reference: int& hp"]],out:["15"],
  hint:`void heal(int& hp, int amount) {\n  hp += amount;\n}\n\nint main() {\n  int hp = 10;\n  heal(hp, 5);\n  std::cout << hp;\n}`},
 {type:"quiz",q:"What does this print?",code:`int half(int n) {\n  return n / 2;\n}\n\nint main() {\n  std::cout << half(9);\n}`,opts:["4","4.5","5"],a:0,mono:true,why:"n is an int, so 9 / 2 drops the decimal and gives 4."},
 {type:"game"},{type:"done"}],
 pool:[
  [`int add(int a, int b) {\n  return a + b;\n}\nint main() {\n  std::cout << add(4, 4);\n}`,["8","44","4"]],
  [`std::string hi(std::string n) {\n  return "Hi " + n;\n}\nint main() {\n  std::cout << hi("Mo");\n}`,["Hi Mo","Hi n","HiMo"]],
  [`int sq(int n) {\n  return n * n;\n}\nint main() {\n  std::cout << sq(3) + 1;\n}`,["10","16","7"]],
  [`void up(int& x) {\n  x++;\n}\nint main() {\n  int a = 1;\n  up(a);\n  std::cout << a;\n}`,["2","1","0"]],
  [`void up(int x) {\n  x++;\n}\nint main() {\n  int a = 1;\n  up(a);\n  std::cout << a;\n}`,["1","2","0"]]
 ]},
{id:"cpp17",title:"Vectors in action",sub:"push_back, totals and the biggest",steps:[
 {type:"talk",title:"A quick vector refresher",
  body:`<p>A ${C("std::vector")} holds many values and can grow. ${C(".push_back()")} adds to the end, ${C(".size()")} counts, and a range-for visits each item.</p>`,
  demo:`std::vector<std::string> snacks = {"banana", "mango"};\nsnacks.push_back("kiwi");\nstd::cout << snacks.size() << "\\n";\nfor (std::string s : snacks) {\n  std::cout << s << "\\n";\n}`,
  say:"Output:\n3\nbanana\nmango\nkiwi"},
 {type:"code",title:"Add one more",body:`<p>On the empty line, add ${C("\"kiwi\"")} with ${C("snacks.push_back(\"kiwi\");")}</p><p>The output should be ${C("banana")}, ${C("mango")} and ${C("kiwi")}, one per line.</p>`,
  start:`std::vector<std::string> snacks = {"banana", "mango"};\n// add kiwi on this line\n\nfor (std::string s : snacks) {\n  std::cout << s << "\\n";\n}\n`,
  use:[[/push_back\s*\(/,"Use snacks.push_back(\"kiwi\");"]],out:["banana","mango","kiwi"],
  hint:`std::vector<std::string> snacks = {"banana", "mango"};\nsnacks.push_back("kiwi");\n\nfor (std::string s : snacks) {\n  std::cout << s << "\\n";\n}`},
 {type:"talk",title:"Adding up a vector",mood:"think",
  body:`<p>Start a total at 0, add each item inside the loop, and print it <b>after</b> the loop.</p>`,
  demo:`std::vector<int> coins = {3, 4, 5};\nint total = 0;\nfor (int c : coins) {\n  total += c;\n}\nstd::cout << total;`,
  say:"Output: 12. Round by round, total goes 3, 7, 12."},
 {type:"code",title:"Total the scores",body:`<p>Inside the loop, add each score to ${C("total")} with ${C("total += n;")}</p><p>The output should be ${C("25")}.</p>`,
  start:`std::vector<int> scores = {5, 10, 10};\nint total = 0;\nfor (int n : scores) {\n  // add n to total here\n}\nstd::cout << total;\n`,
  use:[[/total\s*\+=\s*n|total\s*=\s*total\s*\+\s*n/,"Inside the loop, write total += n;"]],out:["25"],variants:[[/\{5, 10, 10\}/,"{1, 2, 3}",["6"]]],
  hint:`std::vector<int> scores = {5, 10, 10};\nint total = 0;\nfor (int n : scores) {\n  total += n;\n}\nstd::cout << total;`},
 {type:"talk",title:"Finding the biggest",
  body:`<p>To find the biggest, remember the best one so far. Start with the first item, then swap in any item that beats it.</p>`,
  demo:`std::vector<int> v = {4, 9, 2};\nint best = v.front();\nfor (int n : v) {\n  if (n > best) best = n;\n}\nstd::cout << best;`,
  say:"Output: 9. front() is the first item, just like v[0]."},
 {type:"code",title:"Find the biggest",body:`<p>Inside the loop, add: ${C("if (n &gt; best) best = n;")}</p><p>The output should be ${C("42")}.</p>`,
  start:`std::vector<int> nums = {7, 42, 3, 19};\nint best = nums.front();\nfor (int n : nums) {\n  // if n is bigger than best, store it in best\n}\nstd::cout << best;\n`,
  out:["42"],variants:[[/\{7, 42, 3, 19\}/,"{50, 2, 60}",["60"]]],
  hint:`std::vector<int> nums = {7, 42, 3, 19};\nint best = nums.front();\nfor (int n : nums) {\n  if (n > best) best = n;\n}\nstd::cout << best;`},
 {type:"quiz",q:"What does this print?",code:`std::vector<int> v = {1, 2};\nv.push_back(3);\nstd::cout << v.size();`,opts:["3","2","6"],a:0,mono:true,why:"Two items to start, plus one more. size() counts items, it doesn't add them up."},
 {type:"game"},{type:"done"}],
 pool:[
  [`std::vector<int> v = {2, 3};\nv.push_back(4);\nstd::cout << v.size();`,["3","2","9"]],
  [`std::vector<int> v = {2, 3, 4};\nint t = 0;\nfor (int n : v) t += n;\nstd::cout << t;`,["9","234","3"]],
  [`std::vector<int> v = {5, 1, 8};\nint b = v.front();\nfor (int n : v) if (n > b) b = n;\nstd::cout << b;`,["8","5","1"]],
  [`std::vector<std::string> v = {"x", "y"};\nstd::cout << v.back();`,["y","x","xy"]],
  [`std::vector<std::string> v = {"ook", "eek"};\nfor (std::string s : v) std::cout << s;`,["ookeek","ook eek","eekook"]]
 ]},
{id:"cpp18",title:"String toolkit",sub:"substr, find, to_string, toupper",steps:[
 {type:"talk",title:"Slicing strings",
  body:`<p>${C("s.length()")} counts the letters. ${C("s.substr(start, count)")} cuts out a piece: start at a position (counting from 0) and take that many letters.</p>`,
  demo:`std::string w = "Banana";\nstd::cout << w.length() << "\\n";\nstd::cout << w.substr(0, 3) << "\\n";\nstd::cout << w.substr(2, 4);`,
  say:"Output:\n6\nBan\nnana"},
 {type:"code",title:"First three letters",body:`<p>Print the first three letters of ${C("word")} with ${C("word.substr(0, 3)")}</p><p>The output should be ${C("Mon")}.</p>`,
  start:`std::string word = "Monkey";\n// print the first three letters here\n`,
  use:[[/substr\s*\(/,"Use word.substr(0, 3)."]],out:["Mon"],variants:[[/"Monkey"/,'"Banana"',["Ban"]]],
  hint:`std::string word = "Monkey";\nstd::cout << word.substr(0, 3);`},
 {type:"talk",title:"Numbers into text",mood:"think",
  body:`<p>You can't glue a number straight onto a string with ${C("+")}. ${C("std::to_string(7)")} turns the number into the text ${C("\"7\"")} first.</p>`,
  demo:`int score = 120;\nstd::string msg = "Score: " + std::to_string(score);\nstd::cout << msg;`,
  say:"Output: Score: 120"},
 {type:"code",title:"Build a label",body:`<p>Finish the label: change the second line to ${C("std::string label = \"Level \" + std::to_string(level);")}</p><p>The output should be ${C("Level 7")}.</p>`,
  start:`int level = 7;\nstd::string label = "Level ";\nstd::cout << label;\n`,
  use:[[/to_string\s*\(/,"Use std::to_string(level)."]],out:["Level 7"],variants:[[/level = 7/,"level = 12",["Level 12"]]],
  hint:`int level = 7;\nstd::string label = "Level " + std::to_string(level);\nstd::cout << label;`},
 {type:"talk",title:"Changing letters",mood:"cheer",
  body:`<p>${C("word[i]")} is the letter at position i, and you can change it. ${C("toupper")} turns a letter into a capital.</p>`,
  demo:`std::string w = "ook";\nw[0] = toupper(w[0]);\nstd::cout << w;`,
  say:"Output: Ook"},
 {type:"code",title:"Shout it",body:`<p>The loop visits every position. Inside it, make each letter a capital: ${C("word[i] = toupper(word[i]);")}</p><p>The output should be ${C("BANANA")}.</p>`,
  start:`std::string word = "banana";\nfor (int i = 0; i < word.length(); i++) {\n  // make word[i] a capital here\n}\nstd::cout << word;\n`,
  use:[[/toupper/,"Use toupper(word[i])."]],out:["BANANA"],
  hint:`std::string word = "banana";\nfor (int i = 0; i < word.length(); i++) {\n  word[i] = toupper(word[i]);\n}\nstd::cout << word;`},
 {type:"quiz",q:"What does this print?",code:`std::string s = "ook eek";\nstd::cout << s.find("eek");`,opts:["4","5","3"],a:0,mono:true,why:"find gives the position where \"eek\" starts. Counting from 0: o=0, o=1, k=2, space=3, e=4."},
 {type:"game"},{type:"done"}],
 pool:[
  [`std::string s = "monkey";\nstd::cout << s.substr(0, 4);`,["monk","mon","monke"]],
  [`std::string s = "hello";\nstd::cout << s.length();`,["5","4","6"]],
  [`std::string s = "a" + std::to_string(5);\nstd::cout << s;`,["a5","a 5","5"]],
  [`std::string s = "ook";\ns[0] = 'b';\nstd::cout << s;`,["bok","ook","b"]],
  [`std::string s = "banana";\nstd::cout << s.find("n");`,["2","1","3"]]
 ]},
{id:"cpp19",title:"std::map",sub:"look things up by key",steps:[
 {type:"talk",title:"A dictionary for C++",
  body:`<p>A ${C("std::map")} (from ${C("#include &lt;map&gt;")}) stores values you find by a <b>key</b>. ${C("std::map&lt;std::string, int&gt;")} means text keys and int values.</p>`,
  demo:`#include <iostream>\n#include <map>\n#include <string>\n\nint main() {\n  std::map<std::string, int> prices;\n  prices["banana"] = 2;\n  prices["mango"] = 5;\n  std::cout << prices["mango"] << "\\n";\n  std::cout << prices.size();\n}`,
  say:"Output:\n5\n2"},
 {type:"code",title:"Price check",body:`<p>Print the price of a ${C("coconut")}, then a ${C("banana")}, each on its own line. Tip: ${C("std::cout &lt;&lt; prices[\"coconut\"] &lt;&lt; \"\\n\";")}</p><p>The output should be ${C("8")} and then ${C("2")}.</p>`,
  start:`#include <iostream>\n#include <map>\n#include <string>\n\nint main() {\n  std::map<std::string, int> prices = {{"banana", 2}, {"coconut", 8}};\n  // print the two prices here\n}\n`,
  use:[[/prices\s*\[\s*"coconut"\s*\]/,"Read the price with prices[\"coconut\"]."]],out:["8","2"],
  hint:`#include <iostream>\n#include <map>\n#include <string>\n\nint main() {\n  std::map<std::string, int> prices = {{"banana", 2}, {"coconut", 8}};\n  std::cout << prices["coconut"] << "\\n";\n  std::cout << prices["banana"];\n}`},
 {type:"talk",title:"Looping in order",mood:"think",
  body:`<p>Loop over a map and each item is a pair: ${C(".first")} is the key and ${C(".second")} is the value. A ${C("std::map")} always keeps its keys <b>sorted</b>, A to Z.</p>`,
  demo:`#include <iostream>\n#include <map>\n#include <string>\n\nint main() {\n  std::map<std::string, int> prices;\n  prices["mango"] = 5;\n  prices["banana"] = 2;\n  for (const auto& p : prices) {\n    std::cout << p.first << ": " << p.second << "\\n";\n  }\n}`,
  say:"Output:\nbanana: 2\nmango: 5\n\nBanana comes first even though it was added second!"},
 {type:"code",title:"Price list",body:`<p>Add ${C("\"kiwi\"")} with a price of 4 on the empty line: ${C("prices[\"kiwi\"] = 4;")} The loop prints everything.</p><p>The output should be ${C("banana: 2")}, ${C("kiwi: 4")}, ${C("mango: 5")} (sorted!).</p>`,
  start:`#include <iostream>\n#include <map>\n#include <string>\n\nint main() {\n  std::map<std::string, int> prices = {{"banana", 2}, {"mango", 5}};\n  // add kiwi here\n\n  for (const auto& p : prices) {\n    std::cout << p.first << ": " << p.second << "\\n";\n  }\n}\n`,
  use:[[/\["kiwi"\]/,"Add it with prices[\"kiwi\"] = 4;"]],out:["banana: 2","kiwi: 4","mango: 5"],
  hint:`#include <iostream>\n#include <map>\n#include <string>\n\nint main() {\n  std::map<std::string, int> prices = {{"banana", 2}, {"mango", 5}};\n  prices["kiwi"] = 4;\n\n  for (const auto& p : prices) {\n    std::cout << p.first << ": " << p.second << "\\n";\n  }\n}`},
 {type:"talk",title:"Counting made easy",mood:"cheer",
  body:`<p>Here's a handy C++ trick: reading a key that isn't there yet creates it with the value 0. So ${C("counts[v]++")} works even the first time!</p>`,
  demo:`#include <iostream>\n#include <map>\n#include <string>\n\nint main() {\n  std::map<std::string, int> counts;\n  counts["pizza"]++;\n  counts["pizza"]++;\n  counts["tacos"]++;\n  std::cout << counts["pizza"] << " " << counts["tacos"];\n}`,
  say:"Output: 2 1"},
 {type:"code",title:"Snack poll",body:`<p>Inside the first loop, count each pick with ${C("counts[s]++;")}</p><p>The output should be ${C("banana: 3")}, ${C("kiwi: 1")}, ${C("mango: 1")}.</p>`,
  start:`#include <iostream>\n#include <map>\n#include <string>\n#include <vector>\n\nint main() {\n  std::vector<std::string> picks = {"banana", "mango", "banana", "kiwi", "banana"};\n  std::map<std::string, int> counts;\n  for (std::string s : picks) {\n    // count this pick here\n  }\n  for (const auto& c : counts) {\n    std::cout << c.first << ": " << c.second << "\\n";\n  }\n}\n`,
  out:["banana: 3","kiwi: 1","mango: 1"],
  hint:`#include <iostream>\n#include <map>\n#include <string>\n#include <vector>\n\nint main() {\n  std::vector<std::string> picks = {"banana", "mango", "banana", "kiwi", "banana"};\n  std::map<std::string, int> counts;\n  for (std::string s : picks) {\n    counts[s]++;\n  }\n  for (const auto& c : counts) {\n    std::cout << c.first << ": " << c.second << "\\n";\n  }\n}`},
 {type:"quiz",q:"What does this print?",code:`#include <iostream>\n#include <map>\n#include <string>\n\nint main() {\n  std::map<std::string, int> m;\n  m["a"] = 1;\n  std::cout << m.count("a") << m.count("z");\n}`,opts:["10","11","1"],a:0,mono:true,why:"count is 1 if the key is there and 0 if it isn't. It's a safe way to check without creating the key."},
 {type:"game"},{type:"done"}],
 pool:[
  [`#include <iostream>\n#include <map>\n#include <string>\nint main() {\n  std::map<std::string, int> m;\n  m["x"] = 3;\n  m["x"] += 2;\n  std::cout << m["x"];\n}`,["5","3","2"]],
  [`#include <iostream>\n#include <map>\n#include <string>\nint main() {\n  std::map<std::string, int> m;\n  m["b"] = 1;\n  m["a"] = 2;\n  for (const auto& p : m) std::cout << p.first;\n}`,["ab","ba","12"]],
  [`#include <iostream>\n#include <map>\n#include <string>\nint main() {\n  std::map<std::string, int> m;\n  m["hp"]++;\n  std::cout << m["hp"];\n}`,["1","0","hp"]],
  [`#include <iostream>\n#include <map>\n#include <string>\nint main() {\n  std::map<std::string, int> m;\n  m["a"] = 1;\n  m["a"] = 5;\n  std::cout << m.size();\n}`,["1","2","5"]],
  [`#include <iostream>\n#include <map>\n#include <string>\nint main() {\n  std::map<std::string, int> m;\n  std::cout << m.count("cat");\n}`,["0","1","cat"]]
 ]},
{id:"cpp20",title:"Project: Grade Book",sub:"structs + vectors + functions",project:true,steps:[
 {type:"talk",title:"Build a grade book",mood:"cheer",
  body:`<p>You'll build a grade book that stores each student's name and score, then works out the class average, letter grades and the top student.</p><p>A ${C("struct")} bundles the two pieces of each student together:</p>`,
  demo:`#include <iostream>\n#include <string>\n\nstruct Student {\n  std::string name;\n  int score;\n};\n\nint main() {\n  Student s = {"Ava", 88};\n  std::cout << s.name << ": " << s.score;\n}`,
  say:"Output: Ava: 88. Four small steps from here!"},
 {type:"code",title:"Step 1: the class list",body:`<p>Ava and Ben are already in the list. Add Kai with a score of 75: ${C("students.push_back({\"Kai\", 75});")}</p><p>The output should be ${C("Ava: 88")}, ${C("Ben: 92")}, ${C("Kai: 75")}.</p>`,
  start:`struct Student {\n  std::string name;\n  int score;\n};\n\nint main() {\n  std::vector<Student> students = {{"Ava", 88}, {"Ben", 92}};\n  // add Kai here\n\n  for (const Student& s : students) {\n    std::cout << s.name << ": " << s.score << "\\n";\n  }\n}\n`,
  use:[[/push_back/,"Use students.push_back({\"Kai\", 75});"]],out:["Ava: 88","Ben: 92","Kai: 75"],
  hint:`struct Student {\n  std::string name;\n  int score;\n};\n\nint main() {\n  std::vector<Student> students = {{"Ava", 88}, {"Ben", 92}};\n  students.push_back({"Kai", 75});\n\n  for (const Student& s : students) {\n    std::cout << s.name << ": " << s.score << "\\n";\n  }\n}`},
 {type:"code",title:"Step 2: the average",body:`<p>Inside the loop, add each student's score to the total: ${C("total += s.score;")} The average line is already written.</p><p>The output should be ${C("Average: 85")}.</p>`,
  start:`struct Student {\n  std::string name;\n  int score;\n};\n\nint main() {\n  std::vector<Student> students = {{"Ava", 88}, {"Ben", 92}, {"Kai", 75}};\n  int total = 0;\n  for (const Student& s : students) {\n    // add s.score to total here\n  }\n  std::cout << "Average: " << (double)total / students.size();\n}\n`,
  use:[[/total\s*\+=\s*s\.score|total\s*=\s*total\s*\+\s*s\.score/,"Inside the loop, write total += s.score;"]],out:["Average: 85"],
  hint:`struct Student {\n  std::string name;\n  int score;\n};\n\nint main() {\n  std::vector<Student> students = {{"Ava", 88}, {"Ben", 92}, {"Kai", 75}};\n  int total = 0;\n  for (const Student& s : students) {\n    total += s.score;\n  }\n  std::cout << "Average: " << (double)total / students.size();\n}`},
 {type:"code",title:"Step 3: letter grades",body:`<p>${C("letter")} already gives an ${C("A")} for 90 or more. Add two lines: 80 or more returns ${C("\"B\"")}, and 70 or more returns ${C("\"C\"")}.</p><p>The output should be ${C("Ava: B")}, ${C("Ben: A")}, ${C("Kai: C")}.</p>`,
  start:`struct Student {\n  std::string name;\n  int score;\n};\n\nstd::string letter(int score) {\n  if (score >= 90) return "A";\n  // add the B line here\n  // add the C line here\n  return "Keep going";\n}\n\nint main() {\n  std::vector<Student> students = {{"Ava", 88}, {"Ben", 92}, {"Kai", 75}};\n  for (const Student& s : students) {\n    std::cout << s.name << ": " << letter(s.score) << "\\n";\n  }\n}\n`,
  out:["Ava: B","Ben: A","Kai: C"],
  hint:`struct Student {\n  std::string name;\n  int score;\n};\n\nstd::string letter(int score) {\n  if (score >= 90) return "A";\n  if (score >= 80) return "B";\n  if (score >= 70) return "C";\n  return "Keep going";\n}\n\nint main() {\n  std::vector<Student> students = {{"Ava", 88}, {"Ben", 92}, {"Kai", 75}};\n  for (const Student& s : students) {\n    std::cout << s.name << ": " << letter(s.score) << "\\n";\n  }\n}`},
 {type:"code",title:"Step 4: top student",body:`<p>${C("best")} starts as the first student. Inside the loop, swap in anyone with a higher score: ${C("if (s.score &gt; best.score) best = s;")}</p><p>The output should be ${C("Top: Ben with 92")}.</p>`,
  start:`struct Student {\n  std::string name;\n  int score;\n};\n\nint main() {\n  std::vector<Student> students = {{"Ava", 88}, {"Ben", 92}, {"Kai", 75}};\n  Student best = students.front();\n  for (const Student& s : students) {\n    // if s has a higher score than best, set best = s\n  }\n  std::cout << "Top: " << best.name << " with " << best.score;\n}\n`,
  out:["Top: Ben with 92"],variants:[[/\{"Kai", 75\}/,'{"Kai", 99}',["Top: Kai with 99"]]],
  hint:`struct Student {\n  std::string name;\n  int score;\n};\n\nint main() {\n  std::vector<Student> students = {{"Ava", 88}, {"Ben", 92}, {"Kai", 75}};\n  Student best = students.front();\n  for (const Student& s : students) {\n    if (s.score > best.score) best = s;\n  }\n  std::cout << "Top: " << best.name << " with " << best.score;\n}`},
 {type:"quiz",q:"Why does the loop use const Student& s instead of Student s?",opts:["It reads each student without making a copy","It lets the loop change the scores","It's the only way to loop over structs"],a:0,why:"& skips the copy, and const promises not to change anything. Both versions work, this one is just faster."},
 {type:"talk",title:"The finished grade book",mood:"cheer",
  body:`<p>All four steps together in one program.</p>`,
  demo:`#include <iostream>\n#include <string>\n#include <vector>\n\nstruct Student {\n  std::string name;\n  int score;\n};\n\nstd::string letter(int score) {\n  if (score >= 90) return "A";\n  if (score >= 80) return "B";\n  if (score >= 70) return "C";\n  return "Keep going";\n}\n\nint main() {\n  std::vector<Student> students = {{"Ava", 88}, {"Ben", 92}, {"Kai", 75}};\n  int total = 0;\n  Student best = students.front();\n  for (const Student& s : students) {\n    std::cout << s.name << ": " << s.score << " (" << letter(s.score) << ")\\n";\n    total += s.score;\n    if (s.score > best.score) best = s;\n  }\n  std::cout << "Average: " << (double)total / students.size() << "\\n";\n  std::cout << "Top: " << best.name << " with " << best.score;\n}`,
  say:"Output:\nAva: 88 (B)\nBen: 92 (A)\nKai: 75 (C)\nAverage: 85\nTop: Ben with 92\n\nNext up: programs that talk to the player!"},
 {type:"done"}]}
]});

COURSE_CPP.units.push({name:"Interactive C++",lessons:[
{id:"cpp21",title:"Warm-up: std::cin",sub:"reading what the player types",steps:[
 {type:"talk",title:"Your program can listen",mood:"cheer",
  body:`<p>${C("std::cout &lt;&lt;")} sends text <b>out</b>. ${C("std::cin &gt;&gt;")} brings what the player types <b>in</b>. Notice the arrows point the way the data flows.</p><p>In TypeMonkey, whatever is in the ⌨️ <b>Input</b> box under the code gets typed in for you. Press ▶ Run, then change the name and run it again.</p>`,
  input:"Mo",demo:`std::string name;\nstd::cout << "What's your name?\\n";\nstd::cin >> name;\nstd::cout << "Nice to meet you, " << name << "!";`,
  say:"The player typed Mo, so it ends with:\nNice to meet you, Mo!"},
 {type:"code",title:"Say hi back",body:`<p>The name is already read for you. Add one line that prints ${C("Hi,")} the name and ${C("!")}. Tip: ${C("std::cout &lt;&lt; \"Hi, \" &lt;&lt; name &lt;&lt; \"!\";")}</p><p>If the player types ${C("Ava")}, the output should be ${C("What's your name?")} and then ${C("Hi, Ava!")}.</p>`,
  start:`std::string name;\nstd::cout << "What's your name?\\n";\nstd::cin >> name;\n// print the greeting here\n`,
  tests:[{input:"Ava",out:["What's your name?","Hi, Ava!"]},{input:"Leo",out:["What's your name?","Hi, Leo!"]}],
  hint:`std::string name;\nstd::cout << "What's your name?\\n";\nstd::cin >> name;\nstd::cout << "Hi, " << name << "!";`},
 {type:"talk",title:"Reading numbers",mood:"think",
  body:`<p>If the variable is an ${C("int")}, ${C("std::cin")} reads a number into it, ready for math. No converting needed!</p>`,
  input:"7",demo:`int age;\nstd::cout << "How old are you?\\n";\nstd::cin >> age;\nstd::cout << "In 10 years you'll be " << age + 10;`,
  say:"The player typed 7, so it ends with:\nIn 10 years you'll be 17"},
 {type:"code",title:"Next year",body:`<p>The age is read for you. Print ${C("Next year you'll be")} and the age plus 1. Tip: ${C("std::cout &lt;&lt; \"Next year you'll be \" &lt;&lt; age + 1;")}</p><p>If the player types ${C("7")}, the output should be ${C("Next year you'll be 8")}.</p>`,
  start:`int age;\nstd::cin >> age;\n// print the message here\n`,
  tests:[{input:"7",out:["Next year you'll be 8"]},{input:"12",out:["Next year you'll be 13"]}],
  hint:`int age;\nstd::cin >> age;\nstd::cout << "Next year you'll be " << age + 1;`},
 {type:"quiz",q:"name is a std::string. The player types Mo Monkey. What does std::cin >> name put in name?",opts:["Mo","Mo Monkey","Monkey"],a:0,mono:true,why:"cin >> reads one word and stops at the space. The next lesson shows how to read a whole line."},
 {type:"fill",title:"Read it in",body:`<p>Read the player's number into ${C("age")}.</p>`,
  code:`int age;\nstd::cin [0] age;`,blanks:[">>"],tokens:[">>","<<","=","->"],why:"cin >> brings data in. cout << sends it out."},
 {type:"game"},{type:"done"}],
 pool:[
  [`std::string name = "Mo";\nstd::cout << "Hi, " << name << "!";`,["Hi, Mo!","Hi, name!","Hi,Mo!"]],
  [`int age = 7;\nstd::cout << age + 1;`,["8","71","7"]],
  [`std::string a = "ook";\nstd::cout << a + "!";`,["ook!","ook !","a!"]],
  [`int x = 4;\nstd::cout << "x=" << x * 2;`,["x=8","x=4","8"]],
  [`std::string s = "Mo";\nstd::cout << s.length();`,["2","1","Mo"]]
 ]},
{id:"cpp22",title:"Decisions from input",sub:"if/else, two numbers, getline",steps:[
 {type:"talk",title:"Decide with what they typed",
  body:`<p>Once a number is read in, you can use it in an ${C("if")} like any other number.</p>`,
  input:"7",demo:`int n;\nstd::cin >> n;\nif (n > 5) {\n  std::cout << "Big number!";\n} else {\n  std::cout << "Small number!";\n}`,
  say:"7 is more than 5, so: Big number!"},
 {type:"code",title:"Even or odd",body:`<p>The ${C("if")} part prints ${C("even")}. Add an ${C("else")} that prints ${C("odd")}.</p><p>If the player types ${C("4")}, it prints ${C("even")}. If they type ${C("7")}, it prints ${C("odd")}.</p>`,
  start:`int n;\nstd::cin >> n;\nif (n % 2 == 0) {\n  std::cout << "even";\n}\n// add the else here\n`,
  use:[[/\belse\b/,"Add an else { ... } after the if."]],tests:[{input:"4",out:["even"]},{input:"7",out:["odd"]}],
  hint:`int n;\nstd::cin >> n;\nif (n % 2 == 0) {\n  std::cout << "even";\n} else {\n  std::cout << "odd";\n}`},
 {type:"talk",title:"Two at once",mood:"think",
  body:`<p>Chain ${C("&gt;&gt;")} to read two values. The player can type them on one line with a space, or on two lines.</p>`,
  input:"3 9",demo:`int a, b;\nstd::cin >> a >> b;\nstd::cout << a << " + " << b << " = " << a + b;`,
  say:"Output: 3 + 9 = 12"},
 {type:"code",title:"The bigger one",body:`<p>Both numbers are read for you. If ${C("a")} is bigger it prints a. In the ${C("else")}, print ${C("b")}.</p><p>If the player types ${C("3 9")}, the output should be ${C("9")}.</p>`,
  start:`int a, b;\nstd::cin >> a >> b;\nif (a > b) {\n  std::cout << a;\n} else {\n  // print b here\n}\n`,
  tests:[{input:"3 9",out:["9"]},{input:"12 4",out:["12"]}],
  hint:`int a, b;\nstd::cin >> a >> b;\nif (a > b) {\n  std::cout << a;\n} else {\n  std::cout << b;\n}`},
 {type:"talk",title:"Reading a whole line",
  body:`<p>${C("std::cin &gt;&gt;")} stops at a space. To read a whole line, spaces and all, use ${C("std::getline(std::cin, line);")}</p>`,
  input:"I love bananas",demo:`std::string line;\nstd::getline(std::cin, line);\nstd::cout << "You said: " << line;`,
  say:"Output: You said: I love bananas"},
 {type:"code",title:"Full name",body:`<p>Read the whole line into ${C("full")} with ${C("std::getline(std::cin, full);")}. The welcome line is already there.</p><p>If the player types ${C("Mo Monkey")}, the output should be ${C("Welcome, Mo Monkey!")}</p>`,
  start:`std::string full;\n// read the whole line here\nstd::cout << "Welcome, " << full << "!";\n`,
  use:[[/getline/,"Use std::getline(std::cin, full);"]],tests:[{input:"Mo Monkey",out:["Welcome, Mo Monkey!"]},{input:"Ava Lee",out:["Welcome, Ava Lee!"]}],
  hint:`std::string full;\nstd::getline(std::cin, full);\nstd::cout << "Welcome, " << full << "!";`},
 {type:"quiz",q:"Which one reads a whole line, spaces and all?",opts:["std::getline(std::cin, s)","std::cin >> s","std::cout << s"],a:0,mono:true,why:"getline reads up to the end of the line. cin >> stops at the first space."},
 {type:"game"},{type:"done"}],
 pool:[
  [`int n = 7;\nif (n % 2 == 0) std::cout << "even";\nelse std::cout << "odd";`,["odd","even","7"]],
  [`int a = 3, b = 9;\nif (a > b) std::cout << a;\nelse std::cout << b;`,["9","3","39"]],
  [`int a = 3, b = 9;\nstd::cout << a + b;`,["12","39","3 9"]],
  [`int n = 12;\nstd::cout << (n > 10);`,["1","true","12"]],
  [`std::string s = "Mo Monkey";\nstd::cout << s.length();`,["9","8","2"]]
 ]},
{id:"cpp23",title:"Loops that listen",sub:"keep reading until the player is done",steps:[
 {type:"talk",title:"Keep reading",
  body:`<p>${C("while (std::cin &gt;&gt; n)")} reads a number each round and stops when the input runs out. You can also ${C("break")} when the player types a special stop value, like ${C("0")}.</p>`,
  input:"5\n10\n0",demo:`int total = 0;\nint n;\nwhile (std::cin >> n) {\n  if (n == 0) break;\n  total += n;\n}\nstd::cout << "Total: " << total;`,
  say:"5 + 10 = 15, so: Total: 15"},
 {type:"code",title:"Banana counter",body:`<p>Each number is how many bananas the monkey picked. Add one line inside the loop so the number gets added to ${C("total")}: ${C("total += n;")}</p><p>If the player types ${C("3")}, ${C("4")}, ${C("0")}, the output should be ${C("Bananas: 7")}.</p>`,
  start:`int total = 0;\nint n;\nwhile (std::cin >> n) {\n  if (n == 0) break;\n  // add n to total here\n}\nstd::cout << "Bananas: " << total;\n`,
  tests:[{input:"3\n4\n0",out:["Bananas: 7"]},{input:"10\n0",out:["Bananas: 10"]},{input:"0",out:["Bananas: 0"]}],
  hint:`int total = 0;\nint n;\nwhile (std::cin >> n) {\n  if (n == 0) break;\n  total += n;\n}\nstd::cout << "Bananas: " << total;`},
 {type:"talk",title:"Counting words",mood:"think",
  body:`<p>${C("std::cin &gt;&gt; word")} reads one word at a time. Loop until the input runs out and you can count every word the player typed.</p>`,
  input:"ook eek ook",demo:`std::string word;\nwhile (std::cin >> word) {\n  std::cout << "[" << word << "] ";\n}`,
  say:"Output: [ook] [eek] [ook]"},
 {type:"code",title:"Word counter",body:`<p>Inside the loop, add 1 to ${C("count")} for each word: ${C("count++;")}</p><p>If the player types ${C("the monkey ate a banana")}, the output should be ${C("Words: 5")}.</p>`,
  start:`std::string word;\nint count = 0;\nwhile (std::cin >> word) {\n  // count this word here\n}\nstd::cout << "Words: " << count;\n`,
  tests:[{input:"the monkey ate a banana",out:["Words: 5"]},{input:"ook",out:["Words: 1"]}],
  hint:`std::string word;\nint count = 0;\nwhile (std::cin >> word) {\n  count++;\n}\nstd::cout << "Words: " << count;`},
 {type:"code",title:"Pick and eat",body:`<p>The monkey starts with 3 bananas. The loop reads commands until ${C("quit")}. ${C("eat")} already takes one away. Add ${C("else if (cmd == \"pick\") bananas++;")} so picking adds one.</p><p>If the player types ${C("pick")}, ${C("pick")}, ${C("eat")}, ${C("quit")}, the output should be ${C("Bananas left: 4")}.</p>`,
  start:`std::string cmd;\nint bananas = 3;\nwhile (std::cin >> cmd) {\n  if (cmd == "quit") break;\n  if (cmd == "eat") bananas--;\n  // add the pick command here\n}\nstd::cout << "Bananas left: " << bananas;\n`,
  tests:[{input:"pick\npick\neat\nquit",out:["Bananas left: 4"]},{input:"eat\nquit",out:["Bananas left: 2"]},{input:"pick\nquit\npick",out:["Bananas left: 4"]}],
  hint:`std::string cmd;\nint bananas = 3;\nwhile (std::cin >> cmd) {\n  if (cmd == "quit") break;\n  if (cmd == "eat") bananas--;\n  else if (cmd == "pick") bananas++;\n}\nstd::cout << "Bananas left: " << bananas;`},
 {type:"quiz",q:"When does while (std::cin >> word) stop on its own?",opts:["When there's nothing left to read","After 10 words","When the word is empty"],a:0,why:"cin >> counts as false once the input runs out, so the loop ends."},
 {type:"game"},{type:"done"}],
 pool:[
  [`std::vector<int> v = {2, 3, 0, 9};\nint t = 0;\nfor (int n : v) {\n  if (n == 0) break;\n  t += n;\n}\nstd::cout << t;`,["5","14","0"]],
  [`std::vector<std::string> v = {"a", "b", "c"};\nint c = 0;\nfor (std::string w : v) c++;\nstd::cout << c;`,["3","0","abc"]],
  [`int b = 3;\nb--;\nb++;\nb++;\nstd::cout << b;`,["4","3","5"]],
  [`int i = 0;\nwhile (true) {\n  i++;\n  if (i == 3) break;\n}\nstd::cout << i;`,["3","2","4"]],
  [`std::string cmd = "eat";\nif (cmd == "pick") std::cout << "+1";\nelse std::cout << "-1";`,["-1","+1","eat"]]
 ]},
{id:"cpp24",title:"Structs in action",sub:"bundle data and pass it around",steps:[
 {type:"talk",title:"A struct refresher",
  body:`<p>A ${C("struct")} groups related values into one thing. A ${C("std::vector")} of structs makes a handy list, like a shop menu.</p>`,
  demo:`#include <iostream>\n#include <string>\n#include <vector>\n\nstruct Item {\n  std::string name;\n  int price;\n};\n\nint main() {\n  std::vector<Item> menu = {{"banana", 2}, {"mango", 5}};\n  for (const Item& it : menu) {\n    std::cout << it.name << ": " << it.price << "\\n";\n  }\n}`,
  say:"Output:\nbanana: 2\nmango: 5"},
 {type:"code",title:"Grow the menu",body:`<p>Add a coconut that costs 8 on the empty line: ${C("menu.push_back({\"coconut\", 8});")}</p><p>The output should be ${C("banana: 2")}, ${C("mango: 5")}, ${C("coconut: 8")}.</p>`,
  start:`struct Item {\n  std::string name;\n  int price;\n};\n\nint main() {\n  std::vector<Item> menu = {{"banana", 2}, {"mango", 5}};\n  // add the coconut here\n\n  for (const Item& it : menu) {\n    std::cout << it.name << ": " << it.price << "\\n";\n  }\n}\n`,
  use:[[/push_back/,"Use menu.push_back({\"coconut\", 8});"]],out:["banana: 2","mango: 5","coconut: 8"],
  hint:`struct Item {\n  std::string name;\n  int price;\n};\n\nint main() {\n  std::vector<Item> menu = {{"banana", 2}, {"mango", 5}};\n  menu.push_back({"coconut", 8});\n\n  for (const Item& it : menu) {\n    std::cout << it.name << ": " << it.price << "\\n";\n  }\n}`},
 {type:"talk",title:"Structs into functions",mood:"think",
  body:`<p>Pass a struct to a function as ${C("const Item&amp;")}. The ${C("&amp;")} skips making a copy, and ${C("const")} promises the function only reads it.</p>`,
  demo:`#include <iostream>\n#include <string>\n\nstruct Item {\n  std::string name;\n  int price;\n};\n\nvoid show(const Item& it) {\n  std::cout << "A " << it.name << " costs " << it.price << " coins\\n";\n}\n\nint main() {\n  Item a = {"banana", 2};\n  show(a);\n}`,
  say:"Output: A banana costs 2 coins"},
 {type:"code",title:"Price tag",body:`<p>Finish ${C("tag")}: print the name, ${C(" - ")}, then the price. Tip: ${C("std::cout &lt;&lt; it.name &lt;&lt; \" - \" &lt;&lt; it.price &lt;&lt; \"\\n\";")}</p><p>The output should be ${C("banana - 2")} and then ${C("mango - 5")}.</p>`,
  start:`struct Item {\n  std::string name;\n  int price;\n};\n\nvoid tag(const Item& it) {\n  // print the name, " - ", the price and a new line\n}\n\nint main() {\n  Item a = {"banana", 2};\n  Item b = {"mango", 5};\n  tag(a);\n  tag(b);\n}\n`,
  use:[[/it\.name/,"Use it.name and it.price."]],out:["banana - 2","mango - 5"],
  hint:`struct Item {\n  std::string name;\n  int price;\n};\n\nvoid tag(const Item& it) {\n  std::cout << it.name << " - " << it.price << "\\n";\n}\n\nint main() {\n  Item a = {"banana", 2};\n  Item b = {"mango", 5};\n  tag(a);\n  tag(b);\n}`},
 {type:"talk",title:"Changing through a reference",mood:"oops",
  body:`<p>To let a function <b>change</b> a struct, drop the ${C("const")} and keep the ${C("&amp;")}. Without the ${C("&amp;")}, it would only change a copy.</p>`,
  demo:`#include <iostream>\n#include <string>\n\nstruct Item {\n  std::string name;\n  int price;\n};\n\nvoid doublePrice(Item& it) {\n  it.price *= 2;\n}\n\nint main() {\n  Item m = {"mango", 5};\n  doublePrice(m);\n  std::cout << m.price;\n}`,
  say:"Output: 10"},
 {type:"code",title:"Sale!",body:`<p>${C("sale")} takes 1 coin off the price, but it only changes a copy right now. Add one ${C("&amp;")} so the parameter is ${C("Item&amp; it")}</p><p>The output should be ${C("mango costs 4")}.</p>`,
  start:`struct Item {\n  std::string name;\n  int price;\n};\n\nvoid sale(Item it) {\n  it.price -= 1;\n}\n\nint main() {\n  Item m = {"mango", 5};\n  sale(m);\n  std::cout << m.name << " costs " << m.price;\n}\n`,
  use:[[/Item\s*&\s*it/,"Make it a reference: Item& it"]],out:["mango costs 4"],
  hint:`struct Item {\n  std::string name;\n  int price;\n};\n\nvoid sale(Item& it) {\n  it.price -= 1;\n}\n\nint main() {\n  Item m = {"mango", 5};\n  sale(m);\n  std::cout << m.name << " costs " << m.price;\n}`},
 {type:"quiz",q:"What does this print?",code:`struct P {\n  int x;\n};\n\nvoid move(P p) {\n  p.x += 10;\n}\n\nint main() {\n  P a = {1};\n  move(a);\n  std::cout << a.x;\n}`,opts:["1","11","10"],a:0,mono:true,why:"move gets a copy (no &), so the real a.x stays 1."},
 {type:"game"},{type:"done"}],
 pool:[
  [`struct P {\n  int x, y;\n};\nint main() {\n  P p = {2, 3};\n  std::cout << p.x * p.y;\n}`,["6","5","23"]],
  [`struct I {\n  std::string n;\n  int c;\n};\nint main() {\n  std::vector<I> v = {{"a", 1}, {"b", 2}};\n  std::cout << v.size();\n}`,["2","4","1"]],
  [`struct I {\n  int c;\n};\nvoid up(I& i) {\n  i.c++;\n}\nint main() {\n  I a = {5};\n  up(a);\n  std::cout << a.c;\n}`,["6","5","0"]],
  [`struct I {\n  int c;\n};\nint main() {\n  I a = {5};\n  I b = a;\n  b.c = 9;\n  std::cout << a.c;\n}`,["5","9","0"]],
  [`struct I {\n  std::string n;\n};\nint main() {\n  I a = {"ook"};\n  std::cout << a.n << "!";\n}`,["ook!","n!","ook"]]
 ]},
{id:"cpp25",title:"Project: Banana Shop",sub:"maps + input + loops",project:true,steps:[
 {type:"talk",title:"Open a shop!",mood:"cheer",
  body:`<p>You'll build a shop the player can actually use. It shows a price list, then the player types what they want to buy. The shop takes their coins, says no to things it doesn't sell, and refuses if they can't afford it.</p><p>The prices live in a ${C("std::map")}, and the player starts with 10 coins.</p>`,
  say:"Four small steps. Let's open for business!"},
 {type:"code",title:"Step 1: the price list",body:`<p>The loop visits every item in the map. Inside it, print the name, a colon, the price and ${C(" coins")}, like ${C("banana: 2 coins")}. Tip: ${C("std::cout &lt;&lt; p.first &lt;&lt; \": \" &lt;&lt; p.second &lt;&lt; \" coins\\n\";")}</p>`,
  start:`#include <iostream>\n#include <map>\n#include <string>\n\nint main() {\n  std::map<std::string, int> prices = {{"banana", 2}, {"mango", 5}, {"coconut", 8}};\n  std::cout << "Welcome to the Banana Shop!\\n";\n  for (const auto& p : prices) {\n    // print the name and price here\n  }\n}\n`,
  out:["Welcome to the Banana Shop!","banana: 2 coins","coconut: 8 coins","mango: 5 coins"],
  hint:`#include <iostream>\n#include <map>\n#include <string>\n\nint main() {\n  std::map<std::string, int> prices = {{"banana", 2}, {"mango", 5}, {"coconut", 8}};\n  std::cout << "Welcome to the Banana Shop!\\n";\n  for (const auto& p : prices) {\n    std::cout << p.first << ": " << p.second << " coins\\n";\n  }\n}`},
 {type:"code",title:"Step 2: buy one thing",body:`<p>The player's choice is read into ${C("item")}. Take its price away from the coins: ${C("coins -= prices[item];")}</p><p>If the player types ${C("banana")}, the output should be ${C("You bought a banana. Coins left: 8")}</p>`,
  start:`#include <iostream>\n#include <map>\n#include <string>\n\nint main() {\n  std::map<std::string, int> prices = {{"banana", 2}, {"mango", 5}, {"coconut", 8}};\n  int coins = 10;\n  std::string item;\n  std::cin >> item;\n  // take the price away from coins here\n  std::cout << "You bought a " << item << ". Coins left: " << coins;\n}\n`,
  tests:[{input:"banana",out:["You bought a banana. Coins left: 8"]},{input:"mango",out:["You bought a mango. Coins left: 5"]}],
  hint:`#include <iostream>\n#include <map>\n#include <string>\n\nint main() {\n  std::map<std::string, int> prices = {{"banana", 2}, {"mango", 5}, {"coconut", 8}};\n  int coins = 10;\n  std::string item;\n  std::cin >> item;\n  coins -= prices[item];\n  std::cout << "You bought a " << item << ". Coins left: " << coins;\n}`},
 {type:"code",title:"Step 3: keep shopping",body:`<p>Now the shop loops until the player types ${C("done")}. It needs to say no to things it doesn't sell. Change ${C("false")} in the ${C("if")} to ${C("prices.count(item) == 0")}</p><p>If the player types ${C("kiwi")}, ${C("banana")}, ${C("done")}, the shop says it doesn't sell kiwi, then sells the banana.</p>`,
  start:`#include <iostream>\n#include <map>\n#include <string>\n\nint main() {\n  std::map<std::string, int> prices = {{"banana", 2}, {"mango", 5}, {"coconut", 8}};\n  int coins = 10;\n  std::string item;\n  while (std::cin >> item) {\n    if (item == "done") break;\n    if (false) { // change false: is the item missing from prices?\n      std::cout << "We don't sell " << item << ".\\n";\n    } else {\n      coins -= prices[item];\n      std::cout << "You bought a " << item << ". Coins left: " << coins << "\\n";\n    }\n  }\n  std::cout << "Thanks for shopping! You have " << coins << " coins.";\n}\n`,
  use:[[/prices\.count\s*\(/,"Use prices.count(item) == 0 to spot items the shop doesn't sell."]],
  tests:[{input:"kiwi\nbanana\ndone",out:["We don't sell kiwi.","You bought a banana. Coins left: 8","Thanks for shopping! You have 8 coins."]},
         {input:"mango\ndone",out:["You bought a mango. Coins left: 5","Thanks for shopping! You have 5 coins."]}],
  hint:`#include <iostream>\n#include <map>\n#include <string>\n\nint main() {\n  std::map<std::string, int> prices = {{"banana", 2}, {"mango", 5}, {"coconut", 8}};\n  int coins = 10;\n  std::string item;\n  while (std::cin >> item) {\n    if (item == "done") break;\n    if (prices.count(item) == 0) {\n      std::cout << "We don't sell " << item << ".\\n";\n    } else {\n      coins -= prices[item];\n      std::cout << "You bought a " << item << ". Coins left: " << coins << "\\n";\n    }\n  }\n  std::cout << "Thanks for shopping! You have " << coins << " coins.";\n}`},
 {type:"code",title:"Step 4: no money, no banana",body:`<p>Last piece! When the price is more than the player's coins, the shop must refuse. Fill in the empty ${C("else if")}: print ${C("Not enough coins for a")}, the item and ${C("!")}, then a new line.</p><p>Tip: ${C("std::cout &lt;&lt; \"Not enough coins for a \" &lt;&lt; item &lt;&lt; \"!\\n\";")}</p>`,
  start:`#include <iostream>\n#include <map>\n#include <string>\n\nint main() {\n  std::map<std::string, int> prices = {{"banana", 2}, {"mango", 5}, {"coconut", 8}};\n  int coins = 10;\n  std::string item;\n  while (std::cin >> item) {\n    if (item == "done") break;\n    if (prices.count(item) == 0) {\n      std::cout << "We don't sell " << item << ".\\n";\n    } else if (prices[item] > coins) {\n      // print the "not enough coins" message here\n    } else {\n      coins -= prices[item];\n      std::cout << "You bought a " << item << ". Coins left: " << coins << "\\n";\n    }\n  }\n  std::cout << "Thanks for shopping! You have " << coins << " coins.";\n}\n`,
  tests:[{input:"coconut\ncoconut\ndone",out:["You bought a coconut. Coins left: 2","Not enough coins for a coconut!","Thanks for shopping! You have 2 coins."]},
         {input:"banana\nmango\nmango\ndone",out:["You bought a banana. Coins left: 8","You bought a mango. Coins left: 3","Not enough coins for a mango!","Thanks for shopping! You have 3 coins."]}],
  hint:`#include <iostream>\n#include <map>\n#include <string>\n\nint main() {\n  std::map<std::string, int> prices = {{"banana", 2}, {"mango", 5}, {"coconut", 8}};\n  int coins = 10;\n  std::string item;\n  while (std::cin >> item) {\n    if (item == "done") break;\n    if (prices.count(item) == 0) {\n      std::cout << "We don't sell " << item << ".\\n";\n    } else if (prices[item] > coins) {\n      std::cout << "Not enough coins for a " << item << "!\\n";\n    } else {\n      coins -= prices[item];\n      std::cout << "You bought a " << item << ". Coins left: " << coins << "\\n";\n    }\n  }\n  std::cout << "Thanks for shopping! You have " << coins << " coins.";\n}`},
 {type:"quiz",q:"The player has 10 coins and types mango, mango, banana, done. How many coins are left at the end?",opts:["0","2","8"],a:0,why:"Two mangoes cost 5 + 5 = 10, leaving 0. The banana costs 2, which is more than 0, so the shop refuses."},
 {type:"talk",title:"Open for business!",mood:"cheer",
  body:`<p>Here's the whole shop with the price list on top. Press ▶ Run, then change the shopping list in the ⌨️ Input box. Can you add a new item to the shop?</p>`,
  input:"kiwi\nbanana\nmango\ncoconut\ndone",demo:`#include <iostream>\n#include <map>\n#include <string>\n\nint main() {\n  std::map<std::string, int> prices = {{"banana", 2}, {"mango", 5}, {"coconut", 8}};\n  int coins = 10;\n  std::cout << "Welcome to the Banana Shop!\\n";\n  for (const auto& p : prices) {\n    std::cout << p.first << ": " << p.second << " coins\\n";\n  }\n  std::string item;\n  while (std::cin >> item) {\n    if (item == "done") break;\n    if (prices.count(item) == 0) {\n      std::cout << "We don't sell " << item << ".\\n";\n    } else if (prices[item] > coins) {\n      std::cout << "Not enough coins for a " << item << "!\\n";\n    } else {\n      coins -= prices[item];\n      std::cout << "You bought a " << item << ". Coins left: " << coins << "\\n";\n    }\n  }\n  std::cout << "Thanks for shopping! You have " << coins << " coins.";\n}`,
  say:"You built a real interactive program with maps, loops and input. You're a C++ coder now!"},
 {type:"done"}]}
]});
