/* deep-sql: launch depth units for SQL (Units 6 and 7).
   Unit 6 "Sharper questions": gentle practice on filters, sorting and groups, plus the Banana Shop project.
   Unit 7 "Data detective": joins, WITH (CTEs), CASE reports, safe changes, plus the Missing Bananas project.
   Adds one table, sales (the zoo's banana shop). Verified with SQLite by tests/verify_compiled.py sql. */
ZOO_TABLES.sales={cols:["id","day","item","price","qty"],rows:[
  [1,1,"banana",2,5],[2,1,"smoothie",4,2],[3,2,"banana",2,8],[4,2,"banana bread",3,1],
  [5,3,"smoothie",4,3],[6,3,"banana",2,4],[7,3,"banana bread",3,2],[8,3,"banana split",5,1]]};

COURSE_SQL.units.push({name:"Sharper questions",lessons:[
{id:"sql16",title:"Warm-up: back to the zoo",sub:"SELECT, WHERE and ORDER BY again",steps:[
 {type:"talk",title:"Welcome back!",mood:"cheer",
  body:`<p>This unit is all about practice. Every challenge gives you most of the query already. You only fill in the missing piece, marked ${C("___")}.</p><p>Here's the ${C("animals")} table again:</p>`,
  show:["animals"],say:"Take it slow. If you get stuck, tap 💡 Help and I'll give you a clue."},
 {type:"talk",title:"The three-part recipe",mood:"think",
  body:`<p>Most questions follow the same recipe: ${C("SELECT")} which columns, ${C("FROM")} which table, ${C("WHERE")} which rows.</p>`,
  demo:`SELECT name, age\nFROM animals\nWHERE species = 'monkey';`,
  say:"Result: Mo | 4 and Pip | 2. Only the monkeys!"},
 {type:"code",title:"Just the names",body:`<p>Replace the ${C("___")} with the column ${C("name")} so you get every keeper's name.</p><p>You should see 4 rows: <b>Ava, Leo, Kai, Mia</b>.</p>`,
  start:`SELECT ___\nFROM keepers;\n`,
  use:[[/select\s+name\b/i,"Put the word name right after SELECT."],[/from\s+keepers/i,"Keep FROM keepers."]],out:["Ava","Leo","Kai","Mia"],
  hint:`SELECT name\nFROM keepers;`},
 {type:"quiz",q:"In SELECT name FROM keepers, which part picks the table?",opts:["FROM keepers","SELECT name","The semicolon"],a:0,why:"FROM names the table. SELECT names the columns."},
 {type:"code",title:"Old timers",body:`<p>Replace the ${C("___")} with a condition so only animals <b>older than 8</b> show up. (Older means ${C("&gt;")}.)</p><p>You should see 2 rows: <b>Kiki | 12</b> and <b>Zuri | 9</b>.</p>`,
  start:`SELECT name, age\nFROM animals\nWHERE ___;\n`,
  use:[[/where\s+age\s*>\s*8/i,"Write the condition as age > 8."]],out:["Kiki | 12","Zuri | 9"],
  hint:`SELECT name, age\nFROM animals\nWHERE age > 8;`},
 {type:"fill",title:"A to Z",body:`<p>Sort the keepers' names alphabetically.</p>`,
  code:`SELECT name FROM keepers [0] name;`,blanks:["ORDER BY"],tokens:["ORDER BY","GROUP BY","SORT","WHERE"],why:"ORDER BY sorts. A to Z is the default.",out:"Ava\nKai\nLeo\nMia"},
 {type:"code",title:"Youngest first",body:`<p>Replace the comment line with ${C("ORDER BY age")} so the youngest animal comes first.</p><p>You should see 6 rows, starting with <b>Pip | 2</b> and ending with <b>Kiki | 12</b>.</p>`,
  start:`SELECT name, age\nFROM animals\n-- put ORDER BY age on this line\n;\n`,
  use:[[/order\s+by\s+age/i,"Add the line ORDER BY age before the semicolon."]],out:["Pip | 2","Mo | 4","Odo | 5","Bao | 7","Zuri | 9","Kiki | 12"],
  hint:`SELECT name, age\nFROM animals\nORDER BY age;`},
 {type:"game"},{type:"done"}],
 pool:[
  [`SELECT species FROM animals WHERE name = 'Bao';`,["panda","Bao","monkey"]],
  [`SELECT name FROM animals WHERE age < 5 ORDER BY age;`,["Pip\nMo","Mo\nPip","Pip"]],
  [`SELECT name FROM keepers WHERE shift = 'night' ORDER BY name DESC;`,["Mia\nLeo","Leo\nMia","Mia"]],
  [`SELECT food, qty FROM snacks WHERE qty > 10 ORDER BY qty;`,["leaves | 15\nbamboo | 20","bamboo | 20\nleaves | 15","bamboo | 20"]],
  [`SELECT name FROM animals ORDER BY age DESC LIMIT 1;`,["Kiki","Pip","Zuri"]]
 ]},
{id:"sql17",title:"Smarter filters",sub:"AND, OR, IN, BETWEEN and LIKE",steps:[
 {type:"talk",title:"AND and OR",
  body:`<p>${C("AND")} needs <b>both</b> conditions to be true. ${C("OR")} needs <b>at least one</b>. Use brackets to group them, just like in math.</p>`,
  demo:`SELECT name FROM animals\nWHERE (species = 'monkey' OR species = 'owl') AND age > 3\nORDER BY id;`,show:["animals"],
  say:"Result: Mo and Odo. Pip is a monkey, but only 2, so AND kicks him out."},
 {type:"code",title:"Young monkeys",body:`<p>Replace the ${C("___")} with ${C("AND")} so you find animals that are monkeys <b>and</b> younger than 3.</p><p>You should see 1 row: <b>Pip</b>.</p>`,
  start:`SELECT name FROM animals\nWHERE species = 'monkey' ___ age < 3;\n`,
  use:[[/'monkey'\s+and\s+age/i,"Put AND between the two conditions."]],out:["Pip"],
  hint:`SELECT name FROM animals\nWHERE species = 'monkey' AND age < 3;`},
 {type:"talk",title:"IN: a shortcut for lots of ORs",mood:"think",
  body:`<p>Instead of ${C("food = 'banana' OR food = 'mango'")}, write ${C("food IN ('banana', 'mango')")}. Same answer, less typing.</p>`,
  demo:`SELECT name FROM animals\nWHERE species IN ('parrot', 'owl');`,
  say:"Result: Kiki and Odo. Both birds!"},
 {type:"code",title:"Fruit snacks",body:`<p>Replace the ${C("___")} with the two foods ${C("'banana', 'mango'")} so you get only the fruit snacks.</p><p>You should see 3 rows: <b>1 | banana</b>, <b>2 | banana</b>, <b>5 | mango</b>.</p>`,
  start:`SELECT id, food FROM snacks\nWHERE food IN (___);\n`,
  use:[[/in\s*\(\s*'(banana|mango)'\s*,\s*'(banana|mango)'\s*\)/i,"Inside the brackets write 'banana', 'mango' (each in quotes, with a comma between)."]],out:["1 | banana","2 | banana","5 | mango"],
  hint:`SELECT id, food FROM snacks\nWHERE food IN ('banana', 'mango');`},
 {type:"talk",title:"BETWEEN and LIKE",
  body:`<p>${C("BETWEEN 3 AND 6")} means 3 to 6, including both ends. In ${C("LIKE")}, ${C("%")} matches any number of letters and ${C("_")} matches exactly one.</p>`,
  demo:`SELECT name FROM animals\nWHERE name LIKE '_i%';`,
  say:"Result: Kiki and Pip. Both have i as their second letter."},
 {type:"quiz",q:"What does this return?",code:`SELECT name FROM animals\nWHERE age BETWEEN 5 AND 9\nORDER BY age;`,opts:["Odo\nBao\nZuri","Bao","Odo\nBao"],a:0,mono:true,why:"Odo is 5, Bao is 7 and Zuri is 9. BETWEEN includes both ends."},
 {type:"code",title:"Medium snacks",body:`<p>Replace the ${C("___")} with ${C("BETWEEN 3 AND 6")} to find snacks with a qty from 3 to 6.</p><p>You should see 3 rows: <b>banana | 6</b>, <b>banana | 3</b>, <b>seeds | 4</b>.</p>`,
  start:`SELECT food, qty FROM snacks\nWHERE qty ___;\n`,
  use:[[/between\s+3\s+and\s+6/i,"Write BETWEEN 3 AND 6 after qty."]],out:["banana | 6","banana | 3","seeds | 4"],
  hint:`SELECT food, qty FROM snacks\nWHERE qty BETWEEN 3 AND 6;`},
 {type:"fill",title:"K names",body:`<p>Find keepers whose name starts with K.</p>`,
  code:`SELECT name FROM keepers WHERE name [0] 'K%';`,blanks:["LIKE"],tokens:["LIKE","=","IN","IS"],why:"LIKE does pattern matching. 'K%' means K, then anything.",out:"Kai"},
 {type:"game"},{type:"done"}],
 pool:[
  [`SELECT name FROM animals WHERE species = 'monkey' OR age > 10 ORDER BY id;`,["Mo\nKiki\nPip","Mo\nPip","Kiki"]],
  [`SELECT name FROM keepers WHERE id IN (2, 4);`,["Leo\nMia","Ava\nKai","Leo"]],
  [`SELECT food FROM snacks WHERE qty BETWEEN 10 AND 20 ORDER BY qty;`,["leaves\nbamboo","bamboo\nleaves","leaves"]],
  [`SELECT name FROM animals WHERE name LIKE '%u%';`,["Zuri","Mo\nZuri","(no rows)"]],
  [`SELECT COUNT(*) FROM animals WHERE species NOT IN ('monkey');`,["4","2","6"]]
 ]},
{id:"sql18",title:"Group practice",sub:"GROUP BY, HAVING and rounding",steps:[
 {type:"talk",title:"Totals for each group",
  body:`<p>Quick refresher: ${C("GROUP BY food")} makes one group per food, and ${C("SUM(qty)")} adds up each group. ${C("AS total")} gives the column a name you can sort by.</p>`,
  demo:`SELECT food, SUM(qty) AS total\nFROM snacks\nGROUP BY food\nORDER BY total DESC;`,show:["snacks"],
  say:"Result: bamboo 20, leaves 15, banana 9, seeds 4, mango 2"},
 {type:"code",title:"Keepers per shift",body:`<p>Replace the comment with ${C("GROUP BY shift")} to count how many keepers work each shift.</p><p>You should see 2 rows: <b>morning | 2</b> and <b>night | 2</b>.</p>`,
  start:`SELECT shift, COUNT(*)\nFROM keepers\n-- put GROUP BY shift on this line\nORDER BY shift;\n`,
  use:[[/group\s+by\s+shift/i,"Add the line GROUP BY shift (above ORDER BY)."]],out:["morning | 2","night | 2"],
  hint:`SELECT shift, COUNT(*)\nFROM keepers\nGROUP BY shift\nORDER BY shift;`},
 {type:"talk",title:"Tidy averages",mood:"think",
  body:`<p>Averages can have lots of decimals. ${C("ROUND(value, 1)")} keeps just 1 decimal place.</p>`,
  demo:`SELECT species, ROUND(AVG(age), 1) AS avg_age\nFROM animals\nGROUP BY species\nORDER BY avg_age DESC;`,
  say:"Result: parrot 12.0, giraffe 9.0, panda 7.0, owl 5.0, monkey 3.0"},
 {type:"quiz",q:"What does this return?",code:`SELECT ROUND(AVG(qty), 1) FROM snacks\nWHERE food = 'banana';`,opts:["4.5","9","4"],a:0,mono:true,why:"The banana snacks are 6 and 3. (6 + 3) / 2 = 4.5."},
 {type:"talk",title:"HAVING keeps some groups",
  body:`<p>${C("WHERE")} throws away <b>rows</b> before grouping. ${C("HAVING")} throws away <b>groups</b> after grouping, so it can check totals.</p>`,
  demo:`SELECT animal_id, COUNT(*) AS meals\nFROM snacks\nGROUP BY animal_id\nHAVING COUNT(*) >= 2;`,
  say:"Result: 1 | 2. Only Mo (animal 1) had two meals."},
 {type:"code",title:"Big foods",body:`<p>Replace the comment with ${C("HAVING SUM(qty) &gt; 10")} so only foods with a total over 10 stay.</p><p>You should see 2 rows: <b>bamboo | 20</b> and <b>leaves | 15</b>.</p>`,
  start:`SELECT food, SUM(qty) AS total\nFROM snacks\nGROUP BY food\n-- put HAVING here\nORDER BY total DESC;\n`,
  use:[[/having\s+(sum\s*\(\s*qty\s*\)|total)\s*>\s*10/i,"Add HAVING SUM(qty) > 10 after GROUP BY."]],out:["bamboo | 20","leaves | 15"],
  hint:`SELECT food, SUM(qty) AS total\nFROM snacks\nGROUP BY food\nHAVING SUM(qty) > 10\nORDER BY total DESC;`},
 {type:"code",title:"No tiny snacks",body:`<p>Skip the small snacks <b>before</b> grouping: replace the ${C("___")} with ${C("qty &gt;= 4")}.</p><p>You should see 4 rows: <b>bamboo | 20</b>, <b>banana | 6</b>, <b>leaves | 15</b>, <b>seeds | 4</b>.</p>`,
  start:`SELECT food, SUM(qty)\nFROM snacks\nWHERE ___\nGROUP BY food\nORDER BY food;\n`,
  use:[[/where\s+qty\s*>=\s*4/i,"Write WHERE qty >= 4."]],out:["bamboo | 20","banana | 6","leaves | 15","seeds | 4"],
  hint:`SELECT food, SUM(qty)\nFROM snacks\nWHERE qty >= 4\nGROUP BY food\nORDER BY food;`},
 {type:"order",title:"Put it in order",body:`<p>Arrange the clauses in the order SQL needs.</p>`,
  lines:["SELECT food, SUM(qty)","FROM snacks","WHERE qty > 2","GROUP BY food","HAVING SUM(qty) > 5","ORDER BY food;"],why:"SELECT, FROM, WHERE, GROUP BY, HAVING, ORDER BY. WHERE always comes before GROUP BY, and HAVING right after it.",out:"bamboo | 20\nbanana | 9\nleaves | 15"},
 {type:"game"},{type:"done"}],
 pool:[
  [`SELECT species, COUNT(*) FROM animals GROUP BY species HAVING COUNT(*) >= 2;`,["monkey | 2","monkey | 1","2"]],
  [`SELECT ROUND(AVG(age), 1) FROM animals WHERE species = 'monkey';`,["3.0","3","6"]],
  [`SELECT keeper_id, COUNT(*) FROM animals WHERE keeper_id IS NOT NULL GROUP BY keeper_id HAVING COUNT(*) = 1 ORDER BY keeper_id;`,["2 | 1\n3 | 1","1 | 3","2 | 1"]],
  [`SELECT COUNT(*) FROM snacks WHERE qty >= 4;`,["4","6","3"]],
  [`SELECT shift, MIN(name) FROM keepers GROUP BY shift ORDER BY shift;`,["morning | Ava\nnight | Leo","morning | Kai\nnight | Mia","Ava\nLeo"]]
 ]},
{id:"sql19",title:"Project: Banana Shop",sub:"sales analytics, one step at a time",project:true,steps:[
 {type:"talk",title:"The zoo opened a shop!",mood:"cheer",
  body:`<p>The zoo now sells banana treats. Every sale goes into a new table called ${C("sales")}: which ${C("day")} it happened, the ${C("item")}, the ${C("price")} of one, and how many (${C("qty")}).</p><p>The manager wants to know how the shop is doing. Let's find out, one small step at a time.</p>`,
  show:["sales"],say:"Each row is one sale. Look at the table for a moment before you start."},
 {type:"code",title:"Step 1: day 3",body:`<p>Replace the ${C("___")} with ${C("day = 3")} to see what sold on day 3.</p><p>You should see 4 rows: <b>smoothie | 3</b>, <b>banana | 4</b>, <b>banana bread | 2</b>, <b>banana split | 1</b>.</p>`,
  start:`SELECT item, qty\nFROM sales\nWHERE ___;\n`,
  use:[[/where\s+day\s*=\s*3/i,"Write WHERE day = 3."]],out:["smoothie | 3","banana | 4","banana bread | 2","banana split | 1"],
  hint:`SELECT item, qty\nFROM sales\nWHERE day = 3;`},
 {type:"talk",title:"Money math",mood:"think",
  body:`<p>How much money did a sale make? Multiply: ${C("price * qty")}. Name the new column with ${C("AS")}.</p>`,
  demo:`SELECT item, price * qty AS money\nFROM sales\nWHERE day = 1;`,
  say:"Result: banana | 10 (2 × 5) and smoothie | 8 (4 × 2)"},
 {type:"code",title:"Step 2: biggest sales",body:`<p>Replace the ${C("___")} with ${C("price * qty")} to find the 3 sales that made the most money.</p><p>You should see 3 rows: <b>3 | 16</b>, <b>5 | 12</b>, <b>1 | 10</b>.</p>`,
  start:`SELECT id, ___ AS money\nFROM sales\nORDER BY money DESC\nLIMIT 3;\n`,
  use:[[/price\s*\*\s*qty|qty\s*\*\s*price/i,"Multiply price * qty."]],out:["3 | 16","5 | 12","1 | 10"],
  hint:`SELECT id, price * qty AS money\nFROM sales\nORDER BY money DESC\nLIMIT 3;`},
 {type:"code",title:"Step 3: money per day",body:`<p>Replace the comment with ${C("GROUP BY day")} to total the money for each day.</p><p>You should see 3 rows: <b>1 | 18</b>, <b>2 | 19</b>, <b>3 | 31</b>.</p>`,
  start:`SELECT day, SUM(price * qty) AS money\nFROM sales\n-- put GROUP BY day here\nORDER BY day;\n`,
  use:[[/group\s+by\s+day/i,"Add GROUP BY day above ORDER BY."]],out:["1 | 18","2 | 19","3 | 31"],
  hint:`SELECT day, SUM(price * qty) AS money\nFROM sales\nGROUP BY day\nORDER BY day;`},
 {type:"quiz",q:"Which day made the most money?",opts:["Day 3","Day 1","Day 2"],a:0,why:"Day 3 made 31, more than 18 and 19."},
 {type:"code",title:"Step 4: best seller",body:`<p>Which item sold the most? Replace the ${C("___")} with ${C("sold DESC")} so the biggest total comes first.</p><p>You should see 1 row: <b>banana | 17</b>.</p>`,
  start:`SELECT item, SUM(qty) AS sold\nFROM sales\nGROUP BY item\nORDER BY ___\nLIMIT 1;\n`,
  use:[[/order\s+by\s+(sold|sum\s*\(\s*qty\s*\))\s+desc/i,"Write ORDER BY sold DESC."]],out:["banana | 17"],
  hint:`SELECT item, SUM(qty) AS sold\nFROM sales\nGROUP BY item\nORDER BY sold DESC\nLIMIT 1;`},
 {type:"talk",title:"The finished report",mood:"cheer",
  body:`<p>Put the pieces together and you get the full report for the manager: every item, how many sold, and how much money it made.</p>`,
  demo:`SELECT item,\n       SUM(qty) AS sold,\n       SUM(price * qty) AS money\nFROM sales\nGROUP BY item\nORDER BY money DESC;`,
  say:"Result:\nbanana | 17 | 34\nsmoothie | 5 | 20\nbanana bread | 3 | 9\nbanana split | 1 | 5\n\nBananas are the star of the shop. Great analysis! 🍌"},
 {type:"done"}]}
]});

COURSE_SQL.units.push({name:"Data detective",lessons:[
{id:"sql20",title:"Warm-up: joins again",sub:"matching rows across tables",steps:[
 {type:"talk",title:"Welcome, detective!",mood:"cheer",
  body:`<p>In this unit you'll combine tables, name the steps of big queries, and make careful changes. First, a gentle refresher on ${C("JOIN")}.</p><p>Remember: ${C("animals.keeper_id")} points at ${C("keepers.id")}.</p>`,
  show:["animals","keepers"],say:"Mo has keeper_id 1, and keeper 1 is Ava. A JOIN does that matching for every row."},
 {type:"talk",title:"JOIN … ON",mood:"think",
  body:`<p>${C("JOIN keepers k")} brings in the keepers table with the short name ${C("k")}. ${C("ON")} says which columns must match.</p>`,
  demo:`SELECT a.name, k.name\nFROM animals a\nJOIN keepers k ON a.keeper_id = k.id\nWHERE a.species = 'monkey'\nORDER BY a.id;`,
  say:"Result: Mo | Ava and Pip | Ava"},
 {type:"code",title:"Kiki's keeper",body:`<p>Replace the ${C("___")} with ${C("k.id")} to finish the match, so you find who looks after Kiki.</p><p>You should see 1 row: <b>Leo</b>.</p>`,
  start:`SELECT k.name\nFROM animals a\nJOIN keepers k ON a.keeper_id = ___\nWHERE a.name = 'Kiki';\n`,
  use:[[/a\.keeper_id\s*=\s*k\.id|k\.id\s*=\s*a\.keeper_id/i,"Match a.keeper_id = k.id."]],out:["Leo"],
  hint:`SELECT k.name\nFROM animals a\nJOIN keepers k ON a.keeper_id = k.id\nWHERE a.name = 'Kiki';`},
 {type:"quiz",q:"In JOIN keepers k, what is k?",opts:["A short nickname (alias) for keepers","A new column","A keeper called k"],a:0,why:"Aliases save typing: k.name means keepers.name."},
 {type:"code",title:"Who eats bananas?",body:`<p>Snacks point at animals with ${C("animal_id")}. Replace the ${C("___")} with ${C("s.food = 'banana'")}.</p><p>You should see 2 rows: <b>Mo | 6</b> and <b>Pip | 3</b>.</p>`,
  start:`SELECT a.name, s.qty\nFROM snacks s\nJOIN animals a ON s.animal_id = a.id\nWHERE ___\nORDER BY s.qty DESC;\n`,
  use:[[/food\s*=\s*'banana'/i,"Write s.food = 'banana'."]],out:["Mo | 6","Pip | 3"],
  hint:`SELECT a.name, s.qty\nFROM snacks s\nJOIN animals a ON s.animal_id = a.id\nWHERE s.food = 'banana'\nORDER BY s.qty DESC;`},
 {type:"fill",title:"Don't forget Odo",body:`<p>Odo has no keeper. Keep him in the results anyway.</p>`,
  code:`SELECT a.name, k.name FROM animals a\n[0] JOIN keepers k ON a.keeper_id = k.id\nWHERE a.name = 'Odo';`,blanks:["LEFT"],tokens:["LEFT","INNER","OUTSIDE","ALL"],why:"LEFT JOIN keeps every animal. The missing keeper shows as NULL.",out:"Odo | NULL"},
 {type:"code",title:"Animals per keeper",body:`<p>Replace the comment with ${C("GROUP BY k.name")} to count each keeper's animals.</p><p>You should see 3 rows: <b>Ava | 3</b>, <b>Kai | 1</b>, <b>Leo | 1</b>.</p>`,
  start:`SELECT k.name, COUNT(*)\nFROM animals a\nJOIN keepers k ON a.keeper_id = k.id\n-- put GROUP BY k.name here\nORDER BY k.name;\n`,
  use:[[/group\s+by\s+k\.(name|id)/i,"Add GROUP BY k.name above ORDER BY."]],out:["Ava | 3","Kai | 1","Leo | 1"],
  hint:`SELECT k.name, COUNT(*)\nFROM animals a\nJOIN keepers k ON a.keeper_id = k.id\nGROUP BY k.name\nORDER BY k.name;`},
 {type:"game"},{type:"done"}],
 pool:[
  [`SELECT k.shift FROM animals a JOIN keepers k ON a.keeper_id = k.id WHERE a.name = 'Zuri';`,["morning","night","Kai"]],
  [`SELECT a.name FROM animals a JOIN keepers k ON a.keeper_id = k.id WHERE k.shift = 'night';`,["Kiki","Kiki\nOdo","(no rows)"]],
  [`SELECT COUNT(*) FROM snacks s JOIN animals a ON s.animal_id = a.id WHERE a.species = 'monkey';`,["3","2","1"]],
  [`SELECT a.name, s.food FROM snacks s JOIN animals a ON s.animal_id = a.id WHERE s.qty < 3;`,["Mo | mango","Pip | banana","mango"]],
  [`SELECT COUNT(*) FROM animals a LEFT JOIN keepers k ON a.keeper_id = k.id WHERE k.id IS NULL;`,["1","0","6"]]
 ]},
{id:"sql21",title:"WITH: name your steps",sub:"CTEs make big queries readable",steps:[
 {type:"talk",title:"Give a query a name",
  body:`<p>${C("WITH name AS (SELECT ...)")} saves a query under a name. Then the main query can use that name like a table. This is called a <b>CTE</b> (common table expression).</p>`,
  demo:`WITH monkeys AS (\n  SELECT * FROM animals WHERE species = 'monkey'\n)\nSELECT name, age FROM monkeys ORDER BY age;`,
  say:"Result: Pip | 2, Mo | 4. First we made a mini-table of monkeys, then asked it a question."},
 {type:"quiz",q:"What is a CTE most like?",opts:["A named mini-table that lasts for one query","A new table saved forever","A comment"],a:0,why:"It only exists while that one query runs, so nothing in the database changes."},
 {type:"code",title:"Night crew",body:`<p>Replace the ${C("___")} with ${C("shift = 'night'")} so the ${C("night")} mini-table holds only night keepers.</p><p>You should see 2 rows: <b>Leo</b> and <b>Mia</b>.</p>`,
  start:`WITH night AS (\n  SELECT * FROM keepers WHERE ___\n)\nSELECT name FROM night ORDER BY name;\n`,
  use:[[/shift\s*=\s*'night'/i,"Write shift = 'night' inside the brackets."]],out:["Leo","Mia"],
  hint:`WITH night AS (\n  SELECT * FROM keepers WHERE shift = 'night'\n)\nSELECT name FROM night ORDER BY name;`},
 {type:"talk",title:"Totals first, questions second",mood:"think",
  body:`<p>CTEs shine when you need two steps: first work out totals, then ask about them.</p>`,
  demo:`WITH totals AS (\n  SELECT animal_id, SUM(qty) AS eaten\n  FROM snacks\n  GROUP BY animal_id\n)\nSELECT animal_id, eaten\nFROM totals\nWHERE eaten > 5\nORDER BY eaten DESC;`,
  say:"Result: 3 | 20, 4 | 15, 1 | 8"},
 {type:"code",title:"Names for the totals",body:`<p>The totals only have ids. Join them to ${C("animals")} to get names: replace the ${C("___")} with ${C("a.id = t.animal_id")}.</p><p>You should see 5 rows, starting with <b>Bao | 20</b> and ending with <b>Pip | 3</b>.</p>`,
  start:`WITH totals AS (\n  SELECT animal_id, SUM(qty) AS eaten\n  FROM snacks\n  GROUP BY animal_id\n)\nSELECT a.name, t.eaten\nFROM totals t\nJOIN animals a ON ___\nORDER BY t.eaten DESC;\n`,
  use:[[/a\.id\s*=\s*t\.animal_id|t\.animal_id\s*=\s*a\.id/i,"Match a.id = t.animal_id."]],out:["Bao | 20","Zuri | 15","Mo | 8","Kiki | 4","Pip | 3"],
  hint:`WITH totals AS (\n  SELECT animal_id, SUM(qty) AS eaten\n  FROM snacks\n  GROUP BY animal_id\n)\nSELECT a.name, t.eaten\nFROM totals t\nJOIN animals a ON a.id = t.animal_id\nORDER BY t.eaten DESC;`},
 {type:"fill",title:"Start with WITH",body:`<p>Count the animals older than 6.</p>`,
  code:`[0] old AS (SELECT * FROM animals WHERE age > 6)\nSELECT COUNT(*) FROM old;`,blanks:["WITH"],tokens:["WITH","LET","FROM","NAME"],why:"Every CTE starts with WITH name AS (...).",out:"3"},
 {type:"code",title:"Who never ate?",body:`<p>The ${C("fed")} mini-table lists every animal that got a snack. Replace the ${C("___")} with ${C("NOT IN")} to find the animal that is <b>not</b> in it.</p><p>You should see 1 row: <b>Odo</b>.</p>`,
  start:`WITH fed AS (\n  SELECT DISTINCT animal_id FROM snacks\n)\nSELECT name FROM animals\nWHERE id ___ (SELECT animal_id FROM fed);\n`,
  use:[[/not\s+in/i,"Write NOT IN before the brackets."]],out:["Odo"],
  hint:`WITH fed AS (\n  SELECT DISTINCT animal_id FROM snacks\n)\nSELECT name FROM animals\nWHERE id NOT IN (SELECT animal_id FROM fed);`},
 {type:"game"},{type:"done"}],
 pool:[
  [`WITH old AS (SELECT * FROM animals WHERE age > 8) SELECT name FROM old ORDER BY name;`,["Kiki\nZuri","Zuri","Bao\nKiki\nZuri"]],
  [`WITH m AS (SELECT * FROM keepers WHERE shift = 'morning') SELECT COUNT(*) FROM m;`,["2","4","1"]],
  [`WITH big AS (SELECT * FROM snacks WHERE qty > 5) SELECT SUM(qty) FROM big;`,["41","50","35"]],
  [`WITH t AS (SELECT food, SUM(qty) AS n FROM snacks GROUP BY food) SELECT food FROM t ORDER BY n LIMIT 1;`,["mango","bamboo","seeds"]]
 ]},
{id:"sql22",title:"CASE for reports",sub:"labels, counts and custom sorting",steps:[
 {type:"talk",title:"Labels with CASE",
  body:`<p>Remember ${C("CASE")}? It's SQL's if/else. ${C("WHEN")} a condition is true, ${C("THEN")} use this value, ${C("ELSE")} use that one, then ${C("END")}.</p>`,
  demo:`SELECT name,\n  CASE WHEN shift = 'morning' THEN 'early bird'\n       ELSE 'night owl' END AS type\nFROM keepers\nORDER BY id;`,show:["keepers"],
  say:"Result: Ava early bird, Leo night owl, Kai early bird, Mia night owl"},
 {type:"code",title:"Feast or nibble",body:`<p>Replace the ${C("___")} with ${C("ELSE")} so small snacks are labelled ${C("nibble")}.</p><p>You should see 6 rows. The bamboo and leaves rows say <b>feast</b>; all the others say <b>nibble</b>.</p>`,
  start:`SELECT food, qty,\n  CASE WHEN qty >= 10 THEN 'feast' ___ 'nibble' END AS size\nFROM snacks\nORDER BY id;\n`,
  use:[[/\belse\s+'nibble'/i,"Write ELSE before 'nibble'."]],out:["banana | 6 | nibble","banana | 3 | nibble","bamboo | 20 | feast","seeds | 4 | nibble","mango | 2 | nibble","leaves | 15 | feast"],
  hint:`SELECT food, qty,\n  CASE WHEN qty >= 10 THEN 'feast' ELSE 'nibble' END AS size\nFROM snacks\nORDER BY id;`},
 {type:"talk",title:"Counting with CASE",mood:"think",
  body:`<p>Here's a pro trick: make CASE give ${C("1")} or ${C("0")}, then ${C("SUM")} it. You get several counts side by side in one row.</p>`,
  demo:`SELECT\n  SUM(CASE WHEN age < 5 THEN 1 ELSE 0 END) AS young,\n  SUM(CASE WHEN age >= 5 THEN 1 ELSE 0 END) AS grown\nFROM animals;`,
  say:"Result: 2 | 4. Two young animals, four grown-ups."},
 {type:"quiz",q:"What does this return?",code:`SELECT SUM(CASE WHEN shift = 'night' THEN 1 ELSE 0 END)\nFROM keepers;`,opts:["2","4","night"],a:0,mono:true,why:"Leo and Mia each add 1. Ava and Kai add 0."},
 {type:"code",title:"Bananas vs the rest",body:`<p>The first column adds up banana qty. Replace the ${C("___")} with ${C("&lt;&gt;")} (not equal) so the second column adds up everything else.</p><p>You should see 1 row: <b>9 | 41</b>.</p>`,
  start:`SELECT\n  SUM(CASE WHEN food = 'banana' THEN qty ELSE 0 END) AS bananas,\n  SUM(CASE WHEN food ___ 'banana' THEN qty ELSE 0 END) AS other\nFROM snacks;\n`,
  use:[[/food\s*(<>|!=)\s*'banana'/i,"Use <> to mean not equal."]],out:["9 | 41"],
  hint:`SELECT\n  SUM(CASE WHEN food = 'banana' THEN qty ELSE 0 END) AS bananas,\n  SUM(CASE WHEN food <> 'banana' THEN qty ELSE 0 END) AS other\nFROM snacks;`},
 {type:"talk",title:"Your own sort order",
  body:`<p>CASE works in ${C("ORDER BY")} too. Give the rows you want first a ${C("0")} and everything else a ${C("1")}.</p>`,
  demo:`SELECT name, species FROM animals\nORDER BY CASE WHEN species = 'monkey' THEN 0 ELSE 1 END, name;`,
  say:"Result: Mo, Pip, then everyone else A to Z: Bao, Kiki, Odo, Zuri. Monkeys first!"},
 {type:"code",title:"Night shift first",body:`<p>Replace the ${C("___")} with ${C("'night'")} so night keepers come first, then everyone A to Z.</p><p>You should see: <b>Leo | night</b>, <b>Mia | night</b>, <b>Ava | morning</b>, <b>Kai | morning</b>.</p>`,
  start:`SELECT name, shift FROM keepers\nORDER BY CASE WHEN shift = ___ THEN 0 ELSE 1 END, name;\n`,
  use:[[/shift\s*=\s*'night'/i,"Write 'night' in quotes."]],out:["Leo | night","Mia | night","Ava | morning","Kai | morning"],
  hint:`SELECT name, shift FROM keepers\nORDER BY CASE WHEN shift = 'night' THEN 0 ELSE 1 END, name;`},
 {type:"game"},{type:"done"}],
 pool:[
  [`SELECT CASE WHEN age > 10 THEN 'old' ELSE 'young' END FROM animals WHERE name = 'Kiki';`,["old","young","12"]],
  [`SELECT SUM(CASE WHEN food = 'banana' THEN 1 ELSE 0 END) FROM snacks;`,["2","9","1"]],
  [`SELECT name FROM keepers ORDER BY CASE WHEN name = 'Mia' THEN 0 ELSE 1 END, name LIMIT 2;`,["Mia\nAva","Ava\nKai","Mia"]],
  [`SELECT CASE WHEN keeper_id IS NULL THEN 'none' ELSE 'yes' END FROM animals WHERE name = 'Odo';`,["none","yes","NULL"]]
 ]},
{id:"sql23",title:"Safe changes",sub:"look with SELECT, then UPDATE or DELETE",steps:[
 {type:"talk",title:"Look before you leap",mood:"oops",
  body:`<p>${C("UPDATE")} and ${C("DELETE")} change data for real. Pros always run a ${C("SELECT")} with the <b>same WHERE</b> first, to see exactly which rows will be hit.</p>`,
  demo:`SELECT * FROM snacks WHERE food = 'banana';`,show:["snacks"],
  say:"Result: 2 rows. Now we know a change WHERE food = 'banana' would touch exactly those two."},
 {type:"code",title:"Preview first",body:`<p>Which snacks are small? Replace the ${C("___")} with ${C("qty &lt; 5")} to preview them.</p><p>You should see 3 rows: <b>2 | 3</b>, <b>4 | 4</b>, <b>5 | 2</b>.</p>`,
  start:`SELECT id, qty FROM snacks\nWHERE ___;\n`,
  use:[[/where\s+qty\s*<\s*5/i,"Write WHERE qty < 5."]],out:["2 | 3","4 | 4","5 | 2"],
  hint:`SELECT id, qty FROM snacks\nWHERE qty < 5;`},
 {type:"code",title:"Now delete them",body:`<p>The preview looked right, so use the same condition to delete them. Replace the ${C("___")} with ${C("qty &lt; 5")}. The SELECT underneath shows what's left.</p><p>You should see 3 rows: <b>banana</b>, <b>bamboo</b>, <b>leaves</b>.</p>`,
  start:`DELETE FROM snacks\nWHERE ___;\nSELECT food FROM snacks ORDER BY id;\n`,
  use:[[/delete\s+from\s+snacks\s+where\s+qty\s*<\s*5/i,"Keep the WHERE! Write WHERE qty < 5 after DELETE FROM snacks."]],out:["banana","bamboo","leaves"],
  hint:`DELETE FROM snacks\nWHERE qty < 5;\nSELECT food FROM snacks ORDER BY id;`},
 {type:"quiz",q:"Why run a SELECT before a DELETE?",opts:["To check exactly which rows the WHERE will hit","Because DELETE needs a SELECT to work","To make the query faster"],a:0,why:"A quick preview catches mistakes before any data is gone."},
 {type:"talk",title:"UPDATE with math",
  body:`<p>${C("SET")} can use the old value. ${C("qty = qty + 5")} adds 5 to whatever was there.</p>`,
  demo:`UPDATE snacks SET qty = qty + 5 WHERE food = 'banana';\nSELECT food, qty FROM snacks WHERE food = 'banana';`,
  say:"Result: banana | 11 and banana | 8"},
 {type:"code",title:"Leo's new shift",body:`<p>Leo is moving to mornings. Replace the ${C("___")} with ${C("'morning'")}.</p><p>You should see 3 rows: <b>Ava</b>, <b>Kai</b>, <b>Leo</b>.</p>`,
  start:`UPDATE keepers\nSET shift = ___\nWHERE name = 'Leo';\nSELECT name FROM keepers WHERE shift = 'morning' ORDER BY name;\n`,
  use:[[/set\s+shift\s*=\s*'morning'/i,"Write SET shift = 'morning'."],[/where\s+name\s*=\s*'Leo'/i,"Keep WHERE name = 'Leo' so only Leo changes."]],out:["Ava","Kai","Leo"],
  hint:`UPDATE keepers\nSET shift = 'morning'\nWHERE name = 'Leo';\nSELECT name FROM keepers WHERE shift = 'morning' ORDER BY name;`},
 {type:"code",title:"A keeper for Odo",body:`<p>You can look up a value with a subquery inside ${C("SET")}. Replace the ${C("___")} with ${C("'Kai'")} so Odo gets Kai's id.</p><p>You should see 1 row: <b>Odo | Kai</b>.</p>`,
  start:`UPDATE animals\nSET keeper_id = (SELECT id FROM keepers WHERE name = ___)\nWHERE name = 'Odo';\nSELECT a.name, k.name FROM animals a\nJOIN keepers k ON a.keeper_id = k.id\nWHERE a.name = 'Odo';\n`,
  use:[[/name\s*=\s*'Kai'/i,"Write 'Kai' in quotes inside the subquery."]],out:["Odo | Kai"],
  hint:`UPDATE animals\nSET keeper_id = (SELECT id FROM keepers WHERE name = 'Kai')\nWHERE name = 'Odo';\nSELECT a.name, k.name FROM animals a\nJOIN keepers k ON a.keeper_id = k.id\nWHERE a.name = 'Odo';`},
 {type:"game"},{type:"done"}],
 pool:[
  [`UPDATE snacks SET qty = qty - 1 WHERE id = 3;\nSELECT qty FROM snacks WHERE id = 3;`,["19","20","21"]],
  [`DELETE FROM snacks WHERE food = 'banana';\nSELECT COUNT(*) FROM snacks;`,["4","6","2"]],
  [`UPDATE keepers SET shift = 'night' WHERE name = 'Ava';\nSELECT COUNT(*) FROM keepers WHERE shift = 'night';`,["3","2","1"]],
  [`DELETE FROM animals WHERE age > 100;\nSELECT COUNT(*) FROM animals;`,["6","0","5"]]
 ]},
{id:"sql24",title:"Project: The Missing Bananas",sub:"solve a mystery with queries",project:true,steps:[
 {type:"talk",title:"A zoo mystery!",mood:"cheer",
  body:`<p>The zoo has a rule: <b>no animal gets more than 5 bananas in one snack</b>. But the banana crate is emptier than it should be! Someone broke the rule.</p><p>Follow the clues, one small query at a time, to crack the case.</p>`,
  show:["snacks","animals"],say:"Every good detective starts by looking at the evidence."},
 {type:"code",title:"Clue 1: the banana snacks",body:`<p>Replace the ${C("___")} with ${C("'banana'")} to list every banana snack.</p><p>You should see 2 rows: <b>1 | 6</b> and <b>5 | 3</b> (animal_id | qty).</p>`,
  start:`SELECT animal_id, qty FROM snacks\nWHERE food = ___;\n`,
  use:[[/food\s*=\s*'banana'/i,"Write 'banana' in quotes."]],out:["1 | 6","5 | 3"],
  hint:`SELECT animal_id, qty FROM snacks\nWHERE food = 'banana';`},
 {type:"code",title:"Clue 2: who are they?",body:`<p>Ids aren't names. Join to ${C("animals")}: replace the ${C("___")} with ${C("s.animal_id = a.id")}.</p><p>You should see 2 rows: <b>Mo | monkey | 6</b> and <b>Pip | monkey | 3</b>.</p>`,
  start:`SELECT a.name, a.species, s.qty\nFROM snacks s\nJOIN animals a ON ___\nWHERE s.food = 'banana'\nORDER BY s.qty DESC;\n`,
  use:[[/s\.animal_id\s*=\s*a\.id|a\.id\s*=\s*s\.animal_id/i,"Match s.animal_id = a.id."]],out:["Mo | monkey | 6","Pip | monkey | 3"],
  hint:`SELECT a.name, a.species, s.qty\nFROM snacks s\nJOIN animals a ON s.animal_id = a.id\nWHERE s.food = 'banana'\nORDER BY s.qty DESC;`},
 {type:"code",title:"Clue 3: rule breakers",body:`<p>Label each banana snack. Replace the ${C("___")} with ${C("&gt;")} so snacks over 5 say ${C("too many")}.</p><p>You should see: <b>Mo | 6 | too many</b> and <b>Pip | 3 | ok</b>.</p>`,
  start:`SELECT a.name, s.qty,\n  CASE WHEN s.qty ___ 5 THEN 'too many' ELSE 'ok' END AS verdict\nFROM snacks s\nJOIN animals a ON s.animal_id = a.id\nWHERE s.food = 'banana'\nORDER BY s.qty DESC;\n`,
  use:[[/s\.qty\s*>\s*5/i,"Write s.qty > 5."]],out:["Mo | 6 | too many","Pip | 3 | ok"],
  hint:`SELECT a.name, s.qty,\n  CASE WHEN s.qty > 5 THEN 'too many' ELSE 'ok' END AS verdict\nFROM snacks s\nJOIN animals a ON s.animal_id = a.id\nWHERE s.food = 'banana'\nORDER BY s.qty DESC;`},
 {type:"quiz",q:"Who got too many bananas?",opts:["Mo","Pip","Kiki"],a:0,why:"Mo's banana snack was 6, one over the limit of 5."},
 {type:"code",title:"Clue 4: who was on duty?",body:`<p>Which keeper looks after the rule breaker? The ${C("culprit")} mini-table holds Mo. Replace the ${C("___")} with ${C("c.keeper_id = k.id")}.</p><p>You should see 1 row: <b>Mo | Ava | morning</b>.</p>`,
  start:`WITH culprit AS (\n  SELECT a.name, a.keeper_id\n  FROM snacks s\n  JOIN animals a ON s.animal_id = a.id\n  WHERE s.food = 'banana' AND s.qty > 5\n)\nSELECT c.name, k.name, k.shift\nFROM culprit c\nJOIN keepers k ON ___;\n`,
  use:[[/c\.keeper_id\s*=\s*k\.id|k\.id\s*=\s*c\.keeper_id/i,"Match c.keeper_id = k.id."]],out:["Mo | Ava | morning"],
  hint:`WITH culprit AS (\n  SELECT a.name, a.keeper_id\n  FROM snacks s\n  JOIN animals a ON s.animal_id = a.id\n  WHERE s.food = 'banana' AND s.qty > 5\n)\nSELECT c.name, k.name, k.shift\nFROM culprit c\nJOIN keepers k ON c.keeper_id = k.id;`},
 {type:"code",title:"Case closed: fix the record",body:`<p>Ava agrees Mo should only get 5. Replace the ${C("___")} with ${C("5")} to fix snack 1, then the SELECT checks the new banana total.</p><p>You should see 1 row: <b>8</b>.</p>`,
  start:`UPDATE snacks SET qty = ___ WHERE id = 1;\nSELECT SUM(qty) FROM snacks WHERE food = 'banana';\n`,
  use:[[/set\s+qty\s*=\s*5\b/i,"Write SET qty = 5."],[/where\s+id\s*=\s*1\b/i,"Keep WHERE id = 1 so only Mo's snack changes."]],out:["8"],
  hint:`UPDATE snacks SET qty = 5 WHERE id = 1;\nSELECT SUM(qty) FROM snacks WHERE food = 'banana';`},
 {type:"talk",title:"The detective's report",mood:"cheer",
  body:`<p>Here's the whole investigation in one query: a CTE finds the banana snacks, a JOIN adds keepers, and CASE gives the verdict.</p>`,
  demo:`WITH bananas AS (\n  SELECT a.name, a.keeper_id, s.qty\n  FROM snacks s\n  JOIN animals a ON s.animal_id = a.id\n  WHERE s.food = 'banana'\n)\nSELECT b.name, k.name AS keeper, b.qty,\n  CASE WHEN b.qty > 5 THEN 'too many' ELSE 'ok' END AS verdict\nFROM bananas b\nJOIN keepers k ON b.keeper_id = k.id\nORDER BY b.qty DESC;`,
  say:"Result:\nMo | Ava | 6 | too many\nPip | Ava | 3 | ok\n\nMystery solved, detective! You used joins, WITH, CASE and UPDATE like a real data analyst. 🕵️"},
 {type:"done"}]}
]});
