/* Build a Game: a JavaScript track where every lesson builds part of a real (console) game.
   Runs in the same JavaScript runner as the JS course. Randomness uses a seeded generator so results
   can be checked; tests/verify_course.py runs every snippet. */
const RAND_FN=`function makeRandom(seed) {\n  return function () {\n    seed = (seed * 9301 + 49297) % 233280;\n    return seed / 233280;\n  };\n}\n`;

const COURSE_GAME={id:"game",name:"Build a Game",blurb:"Make real games in JavaScript: dice duels, treasure maps, hangman, tic-tac-toe and a dungeon crawler. Best after JavaScript Units 1–3. Unit 1 is free.",units:[
{name:"Game basics",free:true,lessons:[
{id:"g1",title:"Game state",sub:"the numbers that make a game",steps:[
 {type:"talk",title:"Every game is just numbers",mood:"cheer",
  body:`<p>Under the hood, every game is a bunch of values that change: health, score, level, position. Those values are the <b>game state</b>. Your job is to keep them right and show them to the player.</p>`,
  demo:`let hp = 10;\nlet score = 0;\nlet level = 1;\nconsole.log("HP: " + hp + " | Score: " + score + " | Level: " + level);\nscore += 50;\nhp -= 3;\nconsole.log("HP: " + hp + " | Score: " + score + " | Level: " + level);`,
  say:"This is a status bar, the same thing you see at the top of most games."},
 {type:"talk",title:"Drawing a health bar",
  body:`<p>${C('"♥".repeat(n)')} repeats a piece of text. Use it to draw bars: full hearts for the health you have, empty ones for what's missing.</p>`,
  demo:`const maxHp = 5;\nlet hp = 3;\nconsole.log("♥".repeat(hp) + "♡".repeat(maxHp - hp));\nhp = 5;\nconsole.log("♥".repeat(hp) + "♡".repeat(maxHp - hp));`,
  say:"♥♥♥♡♡, then ♥♥♥♥♥."},
 {type:"talk",title:"Keeping values in range",mood:"think",
  body:`<p>Health shouldn't go below 0 or above the max. ${C("Math.max")} and ${C("Math.min")} <b>clamp</b> a value into range.</p>`,
  demo:`const maxHp = 10;\nlet hp = 8;\nhp = Math.min(maxHp, hp + 5);   // heal, but not past max\nconsole.log(hp);\nhp = Math.max(0, hp - 25);      // big hit, but not below 0\nconsole.log(hp);`,
  say:"10, then 0."},
 {type:"talk",title:"Grouping state in an object",
  body:`<p>Once there's lots of state, keep it together in one object. Then a function can take the whole player.</p>`,
  demo:`const player = { name: "Mo", hp: 10, coins: 0 };\n\nfunction status(p) {\n  return p.name + " ♥" + p.hp + " 🪙" + p.coins;\n}\n\nplayer.coins += 3;\nconsole.log(status(player));`,
  say:"Mo ♥10 🪙3"},
 {type:"quiz",q:"What does this print?",code:`let hp = 4;\nhp = Math.max(0, hp - 9);\nconsole.log(hp);`,opts:["0","-5","4"],a:0,mono:true,why:"Math.max(0, -5) picks the bigger one: 0."},
 {type:"quiz",q:"What does this print?",code:`console.log("=".repeat(3) + "|");`,opts:["===|","=3|","= = =|"],a:0,mono:true,why:"repeat(3) makes three copies."},
 {type:"fill",title:"Heal, but not too much",body:`<p>Heal by 4 without going past the max.</p>`,code:`const maxHp = 10;\nlet hp = 9;\nhp = Math.[0](maxHp, hp + 4);\nconsole.log(hp);`,blanks:["min"],tokens:["min","max","round","abs"],why:"min picks the smaller value, so it can never pass maxHp."},
 {type:"code",title:"Health bar",body:`<p>Print the bar with ${C("#")} for each point of ${C("hp")} and ${C("-")} for each missing point, inside square brackets. With 3 of 8 it looks like ${C("[###-----]")}.</p>`,start:`const maxHp = 8;\nlet hp = 3;\n// print the bar\n`,
  use:[[/repeat/,"Use .repeat() to draw the pieces."]],out:["[###-----]"],variants:[[/hp = 3/,"hp = 6",["[######--]"]]],
  hint:`const maxHp = 8;\nlet hp = 3;\nconsole.log("[" + "#".repeat(hp) + "-".repeat(maxHp - hp) + "]");`},
 {type:"code",title:"Damage and healing",body:`<p>Finish ${C("hit")} and ${C("heal")} so hp always stays between 0 and ${C("player.maxHp")}.</p>`,start:`const player = { hp: 10, maxHp: 10 };\n\nfunction hit(p, dmg) {\n  // your code here\n}\nfunction heal(p, amount) {\n  // your code here\n}\n\nhit(player, 4);\nconsole.log(player.hp);\nheal(player, 99);\nconsole.log(player.hp);\nhit(player, 50);\nconsole.log(player.hp);\n`,
  use:[[/Math\.max|Math\.min|if\s*\(/,"Clamp with Math.max/Math.min (or an if)."]],out:["6","10","0"],
  hint:`const player = { hp: 10, maxHp: 10 };\n\nfunction hit(p, dmg) {\n  p.hp = Math.max(0, p.hp - dmg);\n}\nfunction heal(p, amount) {\n  p.hp = Math.min(p.maxHp, p.hp + amount);\n}\n\nhit(player, 4);\nconsole.log(player.hp);\nheal(player, 99);\nconsole.log(player.hp);\nhit(player, 50);\nconsole.log(player.hp);`},
 {type:"game"},{type:"done"}],
 pool:[
  [`let s = 0;\ns += 10;\ns *= 3;\nconsole.log(s);`,["30","13","10"]],
  [`console.log("♥".repeat(2) + "♡");`,["♥♥♡","♥♡♡","♥2♡"]],
  [`console.log(Math.min(5, 12));`,["5","12","17"]],
  [`const p = { hp: 3 };\np.hp--;\nconsole.log(p.hp);`,["2","3","4"]],
  [`let hp = 7;\nhp = Math.min(10, hp + 6);\nconsole.log(hp);`,["10","13","7"]],
  [`const p = { name: "Bao", lvl: 1 };\np.lvl++;\nconsole.log(p.name + p.lvl);`,["Bao2","Bao1","3"]]
 ]},
{id:"g2",title:"The game loop",sub:"turns, rounds and game over",steps:[
 {type:"talk",title:"Loop until game over",
  body:`<p>Games run in a <b>loop</b>: take a turn, update the state, check if the game is over, repeat. A ${C("while")} loop with a game-over condition is the heart of every game.</p>`,
  demo:`let monsterHp = 10;\nlet turn = 0;\nwhile (monsterHp > 0) {\n  turn++;\n  monsterHp -= 3;\n  console.log("Turn " + turn + ": monster has " + Math.max(0, monsterHp) + " hp");\n}\nconsole.log("You win in " + turn + " turns!");`,
  say:"4 turns: 7, 4, 1, 0. Then you win."},
 {type:"talk",title:"Moves from a list",mood:"think",
  body:`<p>Our games can't read the keyboard, so we give the player's moves as a list and loop through them. That also makes a game easy to replay and test.</p>`,
  demo:`const moves = ["attack", "attack", "heal", "attack"];\nlet hp = 6, foe = 9;\nfor (const m of moves) {\n  if (m === "attack") foe -= 3;\n  if (m === "heal") hp += 2;\n  console.log(m + " -> you " + hp + ", foe " + foe);\n}`,
  say:"Each move changes the state, then we print it."},
 {type:"talk",title:"Stopping early",
  body:`<p>When someone wins, the game should end even if there are moves left. Use ${C("break")}, or check a ${C("gameOver")} flag.</p>`,
  demo:`const rolls = [4, 6, 5, 3, 6];\nlet pos = 0;\nconst goal = 15;\nfor (const r of rolls) {\n  pos += r;\n  console.log("Rolled " + r + ", now at " + pos);\n  if (pos >= goal) {\n    console.log("Reached the finish!");\n    break;\n  }\n}`,
  say:"After 3 rolls you're at 15, so the last two rolls are never used."},
 {type:"quiz",q:"What does this print?",code:`let hp = 5;\nlet turns = 0;\nwhile (hp > 0) {\n  hp -= 2;\n  turns++;\n}\nconsole.log(turns);`,opts:["3","2","5"],a:0,mono:true,why:"5 → 3 → 1 → -1. Three turns."},
 {type:"quiz",q:"What does this print?",code:`let score = 0;\nfor (const pts of [10, 20, 30]) {\n  score += pts;\n  if (score > 25) break;\n}\nconsole.log(score);`,opts:["30","60","10"],a:0,mono:true,why:"10, then 30 (more than 25), so it stops."},
 {type:"fill",title:"Game over check",body:`<p>Keep looping while both are still standing.</p>`,code:`let you = 5, foe = 7;\nwhile (you > 0 [0] foe > 0) {\n  foe -= 3;\n  you -= 1;\n}\nconsole.log(you + " " + foe);`,blanks:["&&"],tokens:["&&","||","!"],why:"The fight goes on only while BOTH have hp left."},
 {type:"code",title:"Race to the finish",body:`<p>Add each roll to ${C("pos")}. Stop as soon as pos reaches ${C("goal")} or more and print ${C("Finished in N rolls!")}. If the rolls run out first, print ${C("Out of rolls at P")}.</p>`,start:`const rolls = [3, 5, 2, 6, 4];\nconst goal = 15;\nlet pos = 0;\nlet count = 0;\n// your loop here\n`,
  use:[[/for\s*\(|while\s*\(/,"Loop over the rolls."]],out:["Finished in 4 rolls!"],variants:[[/goal = 15/,"goal = 30",["Out of rolls at 20"]],[/goal = 15/,"goal = 3",["Finished in 1 rolls!"]]],
  hint:`const rolls = [3, 5, 2, 6, 4];\nconst goal = 15;\nlet pos = 0;\nlet count = 0;\nlet done = false;\nfor (const r of rolls) {\n  pos += r;\n  count++;\n  if (pos >= goal) {\n    done = true;\n    break;\n  }\n}\nif (done) console.log("Finished in " + count + " rolls!");\nelse console.log("Out of rolls at " + pos);`},
 {type:"code",title:"Turn-based fight",body:`<p>Each round you hit the foe for ${C("yourPower")}; if the foe is still alive, it hits you for ${C("foePower")}. Loop until someone hits 0, then print ${C("You win!")} or ${C("You lose!")}.</p>`,start:`let you = 10, foe = 12;\nconst yourPower = 4, foePower = 3;\n// fight here\n`,
  use:[[/while\s*\(/,"Use a while loop for the rounds."]],out:["You win!"],variants:[[/foePower = 3/,"foePower = 5",["You lose!"]]],
  hint:`let you = 10, foe = 12;\nconst yourPower = 4, foePower = 3;\nwhile (you > 0 && foe > 0) {\n  foe -= yourPower;\n  if (foe > 0) you -= foePower;\n}\nconsole.log(you > 0 ? "You win!" : "You lose!");`},
 {type:"game"},{type:"done"}],
 pool:[
  [`let n = 0;\nwhile (n < 10) n += 4;\nconsole.log(n);`,["12","10","8"]],
  [`let t = 0;\nfor (const m of ["a", "b", "c"]) t++;\nconsole.log(t);`,["3","2","abc"]],
  [`let hp = 3;\nwhile (hp > 0) hp--;\nconsole.log(hp);`,["0","-1","1"]],
  [`let s = 0;\nfor (const r of [2, 9, 4]) {\n  if (r > 5) break;\n  s += r;\n}\nconsole.log(s);`,["2","15","6"]],
  [`let over = false, i = 0;\nwhile (!over) {\n  i += 5;\n  if (i >= 12) over = true;\n}\nconsole.log(i);`,["15","12","10"]]
 ]},
{id:"g3",title:"Dice & randomness",sub:"Math.random and seeded random",steps:[
 {type:"talk",title:"Rolling a die",
  body:`<p>${C("Math.random()")} gives a number from 0 up to (not including) 1. Multiply, round down, and add 1 to get a die roll from 1 to 6. Run it a few times: it changes!</p>`,
  demo:`function rollDie() {\n  return Math.floor(Math.random() * 6) + 1;\n}\nconsole.log(rollDie(), rollDie(), rollDie());`,
  say:"Every press of Run gives different rolls."},
 {type:"talk",title:"Random you can replay",mood:"think",
  body:`<p>Real games often use a <b>seed</b>: a starting number that makes the same \"random\" sequence every time. Minecraft worlds work this way! Here's a tiny seeded generator. Same seed, same rolls.</p>`,
  demo:RAND_FN+`\nconst rand = makeRandom(42);\nconst rolls = [];\nfor (let i = 0; i < 5; i++) {\n  rolls.push(Math.floor(rand() * 6) + 1);\n}\nconsole.log(rolls.join(" "));`,
  say:"Seed 42 always rolls 6 5 6 5 4. Change the seed for a new sequence."},
 {type:"talk",title:"Random picks and chances",mood:"cheer",
  body:`<p>To pick a random item, roll a random position. For a chance, like a 25% critical hit, check ${C("rand() < 0.25")}.</p>`,
  demo:RAND_FN+`\nconst rand = makeRandom(7);\nconst loot = ["sword", "shield", "potion", "banana"];\nfor (let i = 0; i < 3; i++) {\n  const item = loot[Math.floor(rand() * loot.length)];\n  const crit = rand() < 0.25;\n  console.log(item + (crit ? " (shiny!)" : ""));\n}`,
  say:"Seed 7 always gives the same three drops."},
 {type:"quiz",q:"What range does Math.floor(Math.random() * 6) + 1 give?",opts:["1 to 6","0 to 6","0 to 5"],a:0,mono:true,why:"random()*6 is 0 up to 5.99, floor makes 0–5, and +1 makes 1–6."},
 {type:"quiz",q:"Why do games use a seed?",opts:["So the same random sequence can be made again","To make the game run faster","So random numbers are bigger"],a:0,why:"Same seed, same world. Handy for sharing levels and testing."},
 {type:"fill",title:"Roll a d20",body:`<p>Make a function that rolls a 20-sided die (1 to 20).</p>`,code:`function d20() {\n  return Math.[0](Math.random() * 20) + [1];\n}\nconst r = d20();\nconsole.log(r >= 1 && r <= 20);`,blanks:["floor","1"],tokens:["floor","1","round","0","20"],why:"floor then +1 gives 1 to 20."},
 {type:"code",title:"Seeded dice",body:`<p>Use ${C("makeRandom(99)")} to roll a six-sided die 4 times and print the rolls joined by spaces, then the total like ${C("Total: 7")}.</p>`,start:RAND_FN+`\n// make rand with seed 99, roll 4 times\n`,
  use:[[/makeRandom\s*\(\s*99\s*\)/,"Use makeRandom(99)."],[/Math\.floor/,"Turn rand() into 1–6 with Math.floor(rand() * 6) + 1."]],out:["1 3 2 1","Total: 7"],variants:[[/makeRandom\(99\)/,"makeRandom(42)",["6 5 6 5","Total: 22"]]],
  hint:RAND_FN+`\nconst rand = makeRandom(99);\nconst rolls = [];\nfor (let i = 0; i < 4; i++) {\n  rolls.push(Math.floor(rand() * 6) + 1);\n}\nconsole.log(rolls.join(" "));\nconsole.log("Total: " + rolls.reduce((a, b) => a + b, 0));`},
 {type:"game"},{type:"done"}],
 pool:[
  [`console.log(Math.floor(5.9));`,["5","6","5.9"]],
  [`console.log(Math.floor(0.5 * 6) + 1);`,["4","3","6"]],
  [`const loot = ["a", "b", "c"];\nconsole.log(loot[Math.floor(0.7 * loot.length)]);`,["c","b","a"]],
  [`const r = 0.1;\nconsole.log(r < 0.25 ? "crit" : "hit");`,["crit","hit","0.1"]],
  [`console.log(Math.floor(0.99 * 6) + 1);`,["6","7","5"]]
 ]},
{id:"g4",title:"Project: Dice Duel",sub:"your first complete game",project:true,steps:[
 {type:"talk",title:"Dice Duel",mood:"cheer",
  body:`<p>Two players, Mo and Kiki, each start with 20 hp. Every round both roll a die; the lower roll loses hp equal to the difference. First to 0 loses. You'll build it in three steps.</p>`,
  say:"Your first full game, start to finish!"},
 {type:"code",title:"Step 1: one round",body:`<p>Finish ${C("playRound")}: roll for each player, then lower the loser's hp by the difference. On a tie nothing happens. Print the round like ${C("Mo 4 vs Kiki 2 -> Kiki loses 2")} or ${C("Mo 3 vs Kiki 3 -> tie")}.</p>`,start:RAND_FN+`\nconst rand = makeRandom(1);\nconst roll = () => Math.floor(rand() * 6) + 1;\nconst mo = { name: "Mo", hp: 20 };\nconst kiki = { name: "Kiki", hp: 20 };\n\nfunction playRound(a, b) {\n  const ra = roll();\n  const rb = roll();\n  // your code here\n}\n\nplayRound(mo, kiki);\nplayRound(mo, kiki);\nconsole.log(mo.hp + " " + kiki.hp);\n`,
  use:[[/hp\s*-=/,"Lower the loser's hp with -=."]],out:["Mo 2 vs Kiki 4 -> Mo loses 2","Mo 3 vs Kiki 6 -> Mo loses 3","15 20"],
  hint:RAND_FN+`\nconst rand = makeRandom(1);\nconst roll = () => Math.floor(rand() * 6) + 1;\nconst mo = { name: "Mo", hp: 20 };\nconst kiki = { name: "Kiki", hp: 20 };\n\nfunction playRound(a, b) {\n  const ra = roll();\n  const rb = roll();\n  let msg = a.name + " " + ra + " vs " + b.name + " " + rb + " -> ";\n  if (ra > rb) {\n    b.hp -= ra - rb;\n    msg += b.name + " loses " + (ra - rb);\n  } else if (rb > ra) {\n    a.hp -= rb - ra;\n    msg += a.name + " loses " + (rb - ra);\n  } else {\n    msg += "tie";\n  }\n  console.log(msg);\n}\n\nplayRound(mo, kiki);\nplayRound(mo, kiki);\nconsole.log(mo.hp + " " + kiki.hp);`},
 {type:"code",title:"Step 2: play to the end",body:`<p>Now loop rounds until someone's hp is 0 or less, then print the winner like ${C("Kiki wins after 9 rounds!")}. (The rounds print quietly this time: ${C("playRound")} just returns.)</p>`,start:RAND_FN+`\nconst rand = makeRandom(1);\nconst roll = () => Math.floor(rand() * 6) + 1;\nconst mo = { name: "Mo", hp: 20 };\nconst kiki = { name: "Kiki", hp: 20 };\n\nfunction playRound(a, b) {\n  const ra = roll(), rb = roll();\n  if (ra > rb) b.hp -= ra - rb;\n  if (rb > ra) a.hp -= rb - ra;\n}\n\nlet rounds = 0;\n// loop here, then print the winner\n`,
  use:[[/while\s*\(/,"Keep playing with a while loop."]],out:["Kiki wins after 18 rounds!"],variants:[[/makeRandom\(1\)/,"makeRandom(2024)",["Kiki wins after 25 rounds!"]]],
  hint:RAND_FN+`\nconst rand = makeRandom(1);\nconst roll = () => Math.floor(rand() * 6) + 1;\nconst mo = { name: "Mo", hp: 20 };\nconst kiki = { name: "Kiki", hp: 20 };\n\nfunction playRound(a, b) {\n  const ra = roll(), rb = roll();\n  if (ra > rb) b.hp -= ra - rb;\n  if (rb > ra) a.hp -= rb - ra;\n}\n\nlet rounds = 0;\nwhile (mo.hp > 0 && kiki.hp > 0) {\n  playRound(mo, kiki);\n  rounds++;\n}\nconst winner = mo.hp > 0 ? mo : kiki;\nconsole.log(winner.name + " wins after " + rounds + " rounds!");`},
 {type:"code",title:"Step 3: best of 5",body:`<p>Play 5 whole duels (reset hp to 20 each time) with one ${C("rand")}, count the wins, and print like ${C("Mo 2 - 3 Kiki")}.</p>`,start:RAND_FN+`\nconst rand = makeRandom(1);\nconst roll = () => Math.floor(rand() * 6) + 1;\n\nfunction duel() {\n  let a = 20, b = 20;\n  while (a > 0 && b > 0) {\n    const ra = roll(), rb = roll();\n    if (ra > rb) b -= ra - rb;\n    if (rb > ra) a -= rb - ra;\n  }\n  return a > 0 ? "Mo" : "Kiki";\n}\n\n// play 5 duels and print the score\n`,
  use:[[/for\s*\(|while\s*\(/,"Loop 5 times."],[/duel\s*\(\s*\)/,"Call duel() each time."]],out:["Mo 0 - 5 Kiki"],variants:[[/makeRandom\(1\)/,"makeRandom(7)",["Mo 2 - 3 Kiki"]]],
  hint:RAND_FN+`\nconst rand = makeRandom(1);\nconst roll = () => Math.floor(rand() * 6) + 1;\n\nfunction duel() {\n  let a = 20, b = 20;\n  while (a > 0 && b > 0) {\n    const ra = roll(), rb = roll();\n    if (ra > rb) b -= ra - rb;\n    if (rb > ra) a -= rb - ra;\n  }\n  return a > 0 ? "Mo" : "Kiki";\n}\n\nlet mo = 0, kiki = 0;\nfor (let i = 0; i < 5; i++) {\n  if (duel() === "Mo") mo++;\n  else kiki++;\n}\nconsole.log("Mo " + mo + " - " + kiki + " Kiki");`},
 {type:"done"}]}
]},
{name:"Grids & maps",lessons:[
{id:"g5",title:"Drawing a board",sub:"2D arrays become game maps",steps:[
 {type:"talk",title:"A map is a grid",
  body:`<p>Lots of games happen on a grid: chess, Minesweeper, Pokémon maps. An array of strings is the easiest way to draw one. Each string is a row; each character is a tile.</p>`,
  demo:`const map = [\n  "#######",\n  "#.....#",\n  "#..@..#",\n  "#.....#",\n  "#######"\n];\nfor (const row of map) console.log(row);`,
  say:"# is a wall, . is floor, @ is you. Old-school games looked exactly like this!"},
 {type:"talk",title:"Arrays of arrays",mood:"think",
  body:`<p>Strings can't be changed in place, so for a map that changes, split each row into an array of tiles. ${C("grid[y][x]")} is the tile in row y, column x. ${C(".join(\"\")")} glues a row back for printing.</p>`,
  demo:`const grid = [\n  "....".split(""),\n  "....".split(""),\n  "....".split("")\n];\ngrid[1][2] = "@";\ngrid[0][0] = "$";\nfor (const row of grid) console.log(row.join(""));`,
  say:"y goes down the rows, x goes across the columns."},
 {type:"talk",title:"Building a grid with loops",
  body:`<p>Make an empty grid of any size with two loops. A border check turns the edges into walls.</p>`,
  demo:`function makeRoom(w, h) {\n  const g = [];\n  for (let y = 0; y < h; y++) {\n    const row = [];\n    for (let x = 0; x < w; x++) {\n      const edge = x === 0 || y === 0 || x === w - 1 || y === h - 1;\n      row.push(edge ? "#" : ".");\n    }\n    g.push(row);\n  }\n  return g;\n}\nfor (const row of makeRoom(6, 4)) console.log(row.join(""));`,
  say:"A 6 by 4 room with walls all around."},
 {type:"quiz",q:"In grid[y][x], what is y?",opts:["The row (going down)","The column (going across)","The tile's letter"],a:0,why:"The first index picks the row, the second picks the spot in that row."},
 {type:"quiz",q:"What does this print?",code:`const g = ["abc", "def"];\nconsole.log(g[1][0]);`,opts:["d","b","a"],a:0,mono:true,why:"Row 1 is \"def\", and position 0 in it is d."},
 {type:"fill",title:"Place the treasure",body:`<p>Put a ${C("$")} in row 0, column 2.</p>`,code:`const grid = ["...".split(""), "...".split("")];\nconst row = [0];\nconst col = [1];\ngrid[row][col] = "$";\nconsole.log(grid.map(r => r.join("")).join(" "));`,blanks:["0","2"],tokens:["0","2","1","3"],why:"grid[row][column]."},
 {type:"code",title:"Checkerboard",body:`<p>Print a ${C("size")} × ${C("size")} checkerboard: ${C("#")} where x + y is even, ${C(".")} where it's odd.</p>`,start:`const size = 4;\n// your loops here\n`,
  use:[[/%\s*2/,"Use (x + y) % 2 to alternate."]],out:["#.#.",".#.#","#.#.",".#.#"],variants:[[/size = 4/,"size = 3",["#.#",".#.","#.#"]]],
  hint:`const size = 4;\nfor (let y = 0; y < size; y++) {\n  let row = "";\n  for (let x = 0; x < size; x++) {\n    row += (x + y) % 2 === 0 ? "#" : ".";\n  }\n  console.log(row);\n}`},
 {type:"code",title:"Count the coins",body:`<p>Count every ${C("$")} on the map and print ${C("Coins: 4")}.</p>`,start:`const map = [\n  "#$..#",\n  "#.$$#",\n  "#..$#"\n];\n// count them\n`,
  use:[[/for\s*\(/,"Loop over the rows and characters."]],out:["Coins: 4"],variants:[[/"#\.\.\$#"/,"\"#$.$#\"",["Coins: 5"]]],
  hint:`const map = [\n  "#$..#",\n  "#.$$#",\n  "#..$#"\n];\nlet coins = 0;\nfor (const row of map) {\n  for (const tile of row) {\n    if (tile === "$") coins++;\n  }\n}\nconsole.log("Coins: " + coins);`},
 {type:"game"},{type:"done"}],
 pool:[
  [`const g = ["ab", "cd"];\nconsole.log(g[0][1]);`,["b","c","a"]],
  [`const g = ["ab", "cd"];\nconsole.log(g.length);`,["2","4","1"]],
  [`console.log(["x", "y", "z"].join(""));`,["xyz","x,y,z","x y z"]],
  [`const r = "..#".split("");\nr[0] = "@";\nconsole.log(r.join(""));`,["@.#","..#","@..#"]],
  [`console.log("#".repeat(3) + ".".repeat(2));`,["###..","#.#.#","##..."]],
  [`const g = [[1, 2], [3, 4]];\nconsole.log(g[1][1] + g[0][0]);`,["5","3","7"]]
 ]},
{id:"g6",title:"Moving around",sub:"position, directions and walls",steps:[
 {type:"talk",title:"Where are you?",
  body:`<p>The player's position is just two numbers: ${C("x")} and ${C("y")}. Moving right adds 1 to x; moving down adds 1 to y (rows count downwards).</p>`,
  demo:`const player = { x: 1, y: 1 };\nconst moves = "RRD";\nfor (const m of moves) {\n  if (m === "R") player.x++;\n  if (m === "L") player.x--;\n  if (m === "D") player.y++;\n  if (m === "U") player.y--;\n}\nconsole.log(player.x + "," + player.y);`,
  say:"Two rights and one down: 3,2."},
 {type:"talk",title:"A direction table",mood:"think",
  body:`<p>Instead of four ifs, keep a table of how each direction changes x and y. This trick is in almost every grid game.</p>`,
  demo:`const DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nlet x = 2, y = 2;\nfor (const m of "UULR") {\n  const [dx, dy] = DIRS[m];\n  x += dx;\n  y += dy;\n}\nconsole.log(x + "," + y);`,
  say:"Up twice, left, right: 2,0."},
 {type:"talk",title:"Bumping into walls",mood:"oops",
  body:`<p>Before moving, look at the tile you're about to step on. If it's a wall, stay put. That's <b>collision detection</b>.</p>`,
  demo:`const map = [\n  "#####",\n  "#..##",\n  "#...#",\n  "#####"\n];\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nlet x = 1, y = 1;\nfor (const m of "RRRD") {\n  const [dx, dy] = DIRS[m];\n  if (map[y + dy][x + dx] === "#") {\n    console.log(m + ": bonk!");\n  } else {\n    x += dx;\n    y += dy;\n    console.log(m + ": now at " + x + "," + y);\n  }\n}`,
  say:"The second R hits a wall, so does the third. Then D works."},
 {type:"quiz",q:"The player is at x 3, y 5. They move U. Where are they now?",opts:["3,4","3,6","2,5"],a:0,mono:true,why:"Up means one row higher on screen, which is y - 1."},
 {type:"quiz",q:"What does this print?",code:`let x = 0;\nfor (const m of "RRLR") x += m === "R" ? 1 : -1;\nconsole.log(x);`,opts:["2","4","0"],a:0,mono:true,why:"+1 +1 -1 +1 = 2."},
 {type:"fill",title:"Check for walls",body:`<p>Only move if the next tile isn't a wall.</p>`,code:`const row = "#..#";\nlet x = 1;\nfor (const m of "RR") {\n  if (row[x + 1] [0] "#") x++;\n}\nconsole.log(x);`,blanks:["!=="],tokens:["!==","===","<"],why:"!== means \"is not\". The second R bumps into the wall."},
 {type:"code",title:"Robot walk",body:`<p>The robot starts at 0,0. Follow ${C("moves")} using the direction table, then print where it ends up like ${C("2,-1")}.</p>`,start:`const DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nconst moves = "RRUDU";\nlet x = 0, y = 0;\n// your code here\n`,
  use:[[/DIRS\s*\[/,"Look up each move in DIRS."]],out:["2,-1"],variants:[[/"RRUDU"/,"\"LLLD\"",["-3,1"]]],
  hint:`const DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nconst moves = "RRUDU";\nlet x = 0, y = 0;\nfor (const m of moves) {\n  const [dx, dy] = DIRS[m];\n  x += dx;\n  y += dy;\n}\nconsole.log(x + "," + y);`},
 {type:"code",title:"Walls and bumps",body:`<p>Walk through the map. Skip any move into a ${C("#")} and count the bumps. Print the final position and bumps like ${C("3,2 bumps: 2")}.</p>`,start:`const map = [\n  "######",\n  "#..#.#",\n  "#....#",\n  "######"\n];\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nlet x = 1, y = 1, bumps = 0;\nconst moves = "RRDRRU";\n// your code here\n`,
  use:[[/===\s*"#"|!==\s*"#"/,"Check the next tile for \"#\"."]],out:["4,1 bumps: 1"],variants:[[/"RRDRRU"/,"\"DDRR\"",["3,2 bumps: 1"]]],
  hint:`const map = [\n  "######",\n  "#..#.#",\n  "#....#",\n  "######"\n];\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nlet x = 1, y = 1, bumps = 0;\nconst moves = "RRDRRU";\nfor (const m of moves) {\n  const [dx, dy] = DIRS[m];\n  if (map[y + dy][x + dx] === "#") {\n    bumps++;\n  } else {\n    x += dx;\n    y += dy;\n  }\n}\nconsole.log(x + "," + y + " bumps: " + bumps);`},
 {type:"game"},{type:"done"}],
 pool:[
  [`let y = 4;\nfor (const m of "UUD") y += m === "D" ? 1 : -1;\nconsole.log(y);`,["3","5","2"]],
  [`const D = { R: [1, 0] };\nconst [dx, dy] = D.R;\nconsole.log(dx + dy);`,["1","0","10"]],
  [`const row = "#.#";\nconsole.log(row[1] === "#");`,["false","true","."]],
  [`let x = 1, y = 1;\nx += 2;\ny -= 1;\nconsole.log(x + "," + y);`,["3,0","3,2","1,1"]],
  [`const map = ["###", "#.#"];\nconsole.log(map[1][1]);`,[".","#","undefined"]]
 ]},
{id:"g7",title:"Project: Treasure Hunt",sub:"a map, a player and coins to collect",project:true,steps:[
 {type:"talk",title:"Treasure Hunt",mood:"cheer",
  body:`<p>You'll build a tiny exploration game: draw the map with the player on it, walk around collecting coins, and win when you reach the exit ${C("E")}.</p>`,
  say:"Grab every coin you can!"},
 {type:"code",title:"Step 1: draw the map",body:`<p>Write ${C("draw(map, px, py)")} that prints each row, but with ${C("@")} where the player is.</p>`,start:`const map = [\n  "#######",\n  "#.$..$#",\n  "#..#..#",\n  "#$...E#",\n  "#######"\n];\n\nfunction draw(map, px, py) {\n  // your code here\n}\n\ndraw(map, 1, 1);\n`,
  use:[[/@/,"Print \"@\" at the player's spot."]],out:["#######","#@$..$#","#..#..#","#$...E#","#######"],variants:[[/draw\(map, 1, 1\)/,"draw(map, 2, 2)",["#######","#.$..$#","#.@#..#","#$...E#","#######"]]],
  hint:`const map = [\n  "#######",\n  "#.$..$#",\n  "#..#..#",\n  "#$...E#",\n  "#######"\n];\n\nfunction draw(map, px, py) {\n  for (let y = 0; y < map.length; y++) {\n    let row = "";\n    for (let x = 0; x < map[y].length; x++) {\n      row += x === px && y === py ? "@" : map[y][x];\n    }\n    console.log(row);\n  }\n}\n\ndraw(map, 1, 1);`},
 {type:"code",title:"Step 2: collect coins",body:`<p>Walk the ${C("moves")}. Walls block you. Stepping on ${C("$")} collects it (turn that tile into ${C(".")} so it can't be collected twice). Print ${C("Coins: N")} at the end.</p>`,start:`const map = [\n  "#######",\n  "#.$..$#",\n  "#..#..#",\n  "#$...E#",\n  "#######"\n].map(r => r.split(""));\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nlet x = 1, y = 1, coins = 0;\nconst moves = "RRRRLLLLDDL";\n// your code here\n`,
  use:[[/"\$"/,"Check for \"$\" tiles."],[/=\s*"\."/,"Turn a collected coin into \".\"."]],out:["Coins: 3"],variants:[[/"RRRRLLLLDDL"/,"\"RLRL\"",["Coins: 1"]]],
  hint:`const map = [\n  "#######",\n  "#.$..$#",\n  "#..#..#",\n  "#$...E#",\n  "#######"\n].map(r => r.split(""));\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nlet x = 1, y = 1, coins = 0;\nconst moves = "RRRRLLLLDDL";\nfor (const m of moves) {\n  const [dx, dy] = DIRS[m];\n  if (map[y + dy][x + dx] === "#") continue;\n  x += dx;\n  y += dy;\n  if (map[y][x] === "$") {\n    coins++;\n    map[y][x] = ".";\n  }\n}\nconsole.log("Coins: " + coins);`},
 {type:"code",title:"Step 3: find the exit",body:`<p>Add a win: when you step on ${C("E")}, print ${C("Escaped with N coins in M moves!")} and stop. If the moves run out first, print ${C("Still lost...")}.</p>`,start:`const map = [\n  "#######",\n  "#.$..$#",\n  "#..#..#",\n  "#$...E#",\n  "#######"\n].map(r => r.split(""));\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nlet x = 1, y = 1, coins = 0, steps = 0;\nconst moves = "RRRRDDRRR";\nfor (const m of moves) {\n  const [dx, dy] = DIRS[m];\n  if (map[y + dy][x + dx] === "#") continue;\n  x += dx;\n  y += dy;\n  if (map[y][x] === "$") {\n    coins++;\n    map[y][x] = ".";\n  }\n}\nconsole.log("Coins: " + coins);\n`,
  use:[[/"E"/,"Check for the exit tile \"E\"."],[/break|return/,"Stop the game when you escape."]],out:["Escaped with 2 coins in 6 moves!"],variants:[[/"RRRRDDRRR"/,"\"DDRR\"",["Still lost..."]]],
  hint:`const map = [\n  "#######",\n  "#.$..$#",\n  "#..#..#",\n  "#$...E#",\n  "#######"\n].map(r => r.split(""));\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nlet x = 1, y = 1, coins = 0, steps = 0;\nconst moves = "RRRRDDRRR";\nlet escaped = false;\nfor (const m of moves) {\n  steps++;\n  const [dx, dy] = DIRS[m];\n  if (map[y + dy][x + dx] === "#") continue;\n  x += dx;\n  y += dy;\n  if (map[y][x] === "$") {\n    coins++;\n    map[y][x] = ".";\n  }\n  if (map[y][x] === "E") {\n    escaped = true;\n    break;\n  }\n}\nif (escaped) console.log("Escaped with " + coins + " coins in " + steps + " moves!");\nelse console.log("Still lost...");`},
 {type:"done"}]}
]},
{name:"Classic games",lessons:[
{id:"g8",title:"Guess the number",sub:"hints, tries and replay",steps:[
 {type:"talk",title:"The oldest computer game",
  body:`<p>One of the first games people ever wrote: the computer picks a secret number and you guess, getting <b>higher</b> or <b>lower</b> hints. We'll feed in the guesses as a list.</p>`,
  demo:`const secret = 37;\nconst guesses = [50, 25, 37];\nfor (const g of guesses) {\n  if (g < secret) console.log(g + " is too low");\n  else if (g > secret) console.log(g + " is too high");\n  else console.log(g + " is right!");\n}`,
  say:"too high, too low, right!"},
 {type:"talk",title:"The smart way to guess",mood:"think",
  body:`<p>The best strategy is to always guess the middle of what's left. That's called <b>binary search</b>, and it finds any number from 1 to 100 in at most 7 guesses. Here the computer plays against itself.</p>`,
  demo:`const secret = 73;\nlet lo = 1, hi = 100, tries = 0;\nwhile (true) {\n  const guess = Math.floor((lo + hi) / 2);\n  tries++;\n  console.log("Guess " + tries + ": " + guess);\n  if (guess === secret) break;\n  if (guess < secret) lo = guess + 1;\n  else hi = guess - 1;\n}`,
  say:"Found in 6 guesses."},
 {type:"quiz",q:"The secret is 40 and you guess 55. What hint should you get?",opts:["Too high","Too low","Correct"],a:0,why:"55 is bigger than 40."},
 {type:"quiz",q:"Using the always-guess-the-middle trick, what's your first guess for 1 to 100?",opts:["50","1","25"],a:0,mono:true,why:"Math.floor((1 + 100) / 2) is 50."},
 {type:"fill",title:"Give a hint",body:`<p>Finish the hint.</p>`,code:`const secret = 8;\nconst g = 3;\nconsole.log(g [0] secret ? "higher!" : "lower!");`,blanks:["<"],tokens:["<",">","==="],why:"If the guess is smaller, tell them to go higher."},
 {type:"code",title:"Guessing game",body:`<p>Go through the guesses. Print ${C("Too low")} or ${C("Too high")} for wrong ones. When a guess is right, print ${C("Got it in N tries!")} and stop. If none are right, print ${C("The number was S")}.</p>`,start:`const secret = 42;\nconst guesses = [50, 30, 42, 41];\n// your code here\n`,
  use:[[/break|return/,"Stop once they get it."]],out:["Too high","Too low","Got it in 3 tries!"],variants:[[/42, 41/,"40, 41",["Too high","Too low","Too low","Too low","The number was 42"]]],
  hint:`const secret = 42;\nconst guesses = [50, 30, 42, 41];\nlet tries = 0, won = false;\nfor (const g of guesses) {\n  tries++;\n  if (g < secret) console.log("Too low");\n  else if (g > secret) console.log("Too high");\n  else {\n    console.log("Got it in " + tries + " tries!");\n    won = true;\n    break;\n  }\n}\nif (!won) console.log("The number was " + secret);`},
 {type:"game"},{type:"done"}],
 pool:[
  [`console.log(Math.floor((1 + 10) / 2));`,["5","5.5","6"]],
  [`const s = 7, g = 9;\nconsole.log(g > s ? "lower" : "higher");`,["lower","higher","9"]],
  [`let lo = 1, hi = 20;\nconst g = Math.floor((lo + hi) / 2);\nlo = g + 1;\nconsole.log(lo);`,["11","10","21"]],
  [`let t = 0;\nfor (const g of [5, 9, 7]) {\n  t++;\n  if (g === 9) break;\n}\nconsole.log(t);`,["2","3","1"]]
 ]},
{id:"g9",title:"Hangman",sub:"hidden letters and lives",steps:[
 {type:"talk",title:"Showing the hidden word",
  body:`<p>Keep the guessed letters in a ${C("Set")}. To show the word, swap each letter for itself if it's been guessed, or ${C("_")} if not.</p>`,
  demo:`const word = "banana";\nconst guessed = new Set(["a", "n"]);\nlet shown = "";\nfor (const ch of word) {\n  shown += guessed.has(ch) ? ch : "_";\n}\nconsole.log(shown);`,
  say:"_anana. We haven't guessed b yet."},
 {type:"talk",title:"Lives",mood:"oops",
  body:`<p>A wrong guess costs a life. The game ends when you run out of lives, or when there are no ${C("_")} left in the shown word.</p>`,
  demo:`const word = "kiwi";\nconst guessed = new Set();\nlet lives = 3;\nfor (const g of ["e", "i", "z", "k"]) {\n  guessed.add(g);\n  if (!word.includes(g)) lives--;\n  let shown = "";\n  for (const ch of word) shown += guessed.has(ch) ? ch : "_";\n  console.log(g + ": " + shown + "  lives " + lives);\n}`,
  say:"Two misses, so 1 life left, and we still need the w."},
 {type:"quiz",q:"What does this print?",code:`const s = new Set(["a"]);\ns.add("a");\ns.add("b");\nconsole.log(s.size);`,opts:["2","3","1"],a:0,mono:true,why:"A Set ignores duplicates."},
 {type:"quiz",q:"How do you know the player has guessed the whole word?",opts:["The shown word has no _ left","lives is 0","guessed.size is the word's length"],a:0,why:"If every letter is showing, they've won."},
 {type:"fill",title:"Mask the word",body:`<p>Show guessed letters, hide the rest.</p>`,code:`const word = "ook";\nconst guessed = new Set(["o"]);\nlet shown = "";\nfor (const ch of word) shown += guessed.[0](ch) ? ch : "_";\nconsole.log(shown);`,blanks:["has"],tokens:["has","includes","get","add"],why:"Sets use .has() to check."},
 {type:"code",title:"Full hangman",body:`<p>Play through ${C("guesses")} with 4 lives. After each guess print the shown word. Stop when the word is solved (print ${C("You win!")}) or lives hit 0 (print ${C("Out of lives! It was WORD")}).</p>`,start:`const word = "mango";\nconst guesses = ["a", "e", "o", "m", "x", "n", "g"];\nconst guessed = new Set();\nlet lives = 4;\n// your code here\n`,
  use:[[/lives--|lives\s*-=/,"Lose a life for a wrong guess."],[/includes\s*\(\s*"_"\s*\)|indexOf/,"Check if any _ are left."]],out:["_a___","_a___","_a__o","ma__o","ma__o","man_o","mango","You win!"],variants:[[/"x", "n", "g"/,"\"x\", \"y\", \"z\"",["_a___","_a___","_a__o","ma__o","ma__o","ma__o","ma__o","Out of lives! It was mango"]]],
  hint:`const word = "mango";\nconst guesses = ["a", "e", "o", "m", "x", "n", "g"];\nconst guessed = new Set();\nlet lives = 4;\nfor (const g of guesses) {\n  guessed.add(g);\n  if (!word.includes(g)) lives--;\n  let shown = "";\n  for (const ch of word) shown += guessed.has(ch) ? ch : "_";\n  console.log(shown);\n  if (!shown.includes("_")) {\n    console.log("You win!");\n    break;\n  }\n  if (lives === 0) {\n    console.log("Out of lives! It was " + word);\n    break;\n  }\n}`},
 {type:"game"},{type:"done"}],
 pool:[
  [`const s = new Set(["x"]);\nconsole.log(s.has("y"));`,["false","true","x"]],
  [`console.log("kiwi".includes("w"));`,["true","false","2"]],
  [`let out = "";\nfor (const c of "aba") out += c === "a" ? c : "_";\nconsole.log(out);`,["a_a","_b_","aba"]],
  [`console.log("_a_".includes("_"));`,["true","false","1"]],
  [`const s = new Set();\nfor (const c of "hello") s.add(c);\nconsole.log(s.size);`,["4","5","3"]]
 ]},
{id:"g10",title:"Tic-tac-toe",sub:"a board, turns and finding a winner",steps:[
 {type:"talk",title:"The board",
  body:`<p>Store the 9 squares in one array, numbered 0 to 8 across the rows. Print it 3 at a time.</p>`,
  demo:`const board = ["X", "O", "X", " ", "X", " ", "O", " ", " "];\nfunction show(b) {\n  for (let r = 0; r < 3; r++) {\n    console.log(b[r * 3] + "|" + b[r * 3 + 1] + "|" + b[r * 3 + 2]);\n  }\n}\nshow(board);`,
  say:"Square r*3 + c is row r, column c."},
 {type:"talk",title:"Every way to win",mood:"think",
  body:`<p>There are exactly 8 winning lines: 3 rows, 3 columns, 2 diagonals. List them once, then check each: a line wins if all 3 squares match and aren't empty.</p>`,
  demo:`const LINES = [\n  [0, 1, 2], [3, 4, 5], [6, 7, 8],\n  [0, 3, 6], [1, 4, 7], [2, 5, 8],\n  [0, 4, 8], [2, 4, 6]\n];\nfunction winner(b) {\n  for (const [a, c, d] of LINES) {\n    if (b[a] !== " " && b[a] === b[c] && b[a] === b[d]) return b[a];\n  }\n  return null;\n}\nconsole.log(winner(["X", "O", " ", "O", "X", " ", " ", " ", "X"]));\nconsole.log(winner(["X", "O", " ", " ", " ", " ", " ", " ", " "]));`,
  say:"X wins on the diagonal, and the second board has no winner yet: null."},
 {type:"talk",title:"Taking turns",
  body:`<p>Switch players after every move: ${C('player = player === "X" ? "O" : "X"')}. If all 9 squares are full and no one won, it's a draw.</p>`,
  demo:`const board = Array(9).fill(" ");\nlet player = "X";\nfor (const sq of [4, 0, 8]) {\n  board[sq] = player;\n  player = player === "X" ? "O" : "X";\n}\nconsole.log(board.join(""));\nconsole.log("Next: " + player);`,
  say:"X in the middle, O in the corner, X in the other corner. O is up next."},
 {type:"quiz",q:"Which square number is row 2, column 1?",opts:["7","5","3"],a:0,mono:true,why:"2 × 3 + 1 = 7."},
 {type:"quiz",q:"How many ways are there to win tic-tac-toe?",opts:["8","6","9"],a:0,why:"3 rows + 3 columns + 2 diagonals."},
 {type:"fill",title:"Switch players",body:`<p>Flip between X and O.</p>`,code:`let p = "X";\np = p === "X" [0] "O" [1] "X";\nconsole.log(p);`,blanks:["?",":"],tokens:["?",":","||","&&"],why:"The ternary: condition ? if true : if false."},
 {type:"code",title:"Who won?",body:`<p>Finish ${C("winner(b)")}: return ${C("X")} or ${C("O")} if they have a line, ${C("draw")} if the board is full with no winner, otherwise ${C("none")}.</p>`,start:`const LINES = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];\n\nfunction winner(b) {\n  // your code here\n}\n\nconsole.log(winner("XXXOO    ".split("")));\nconsole.log(winner("XOXXOOOXX".split("")));\nconsole.log(winner("XO       ".split("")));\nconsole.log(winner("OX OX O  ".split("")));\n`,
  use:[[/LINES/,"Check every line in LINES."],[/includes\s*\(\s*" "\s*\)|every|indexOf/,"Check whether the board is full."]],out:["X","draw","none","O"],
  hint:`const LINES = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];\n\nfunction winner(b) {\n  for (const [a, c, d] of LINES) {\n    if (b[a] !== " " && b[a] === b[c] && b[a] === b[d]) return b[a];\n  }\n  return b.includes(" ") ? "none" : "draw";\n}\n\nconsole.log(winner("XXXOO    ".split("")));\nconsole.log(winner("XOXXOOOXX".split("")));\nconsole.log(winner("XO       ".split("")));\nconsole.log(winner("OX OX O  ".split("")));`},
 {type:"game"},{type:"done"}],
 pool:[
  [`const b = "XO X     ".split("");\nconsole.log(b[3]);`,["X"," ","O"]],
  [`console.log(1 * 3 + 2);`,["5","6","3"]],
  [`let p = "O";\np = p === "X" ? "O" : "X";\nconsole.log(p);`,["X","O","XO"]],
  [`const b = Array(9).fill(" ");\nb[4] = "X";\nconsole.log(b.filter(s => s === " ").length);`,["8","9","1"]],
  [`const b = "XXX      ".split("");\nconsole.log(b[0] === b[1] && b[1] === b[2]);`,["true","false","X"]]
 ]},
{id:"g11",title:"Project: Tic-tac-toe referee",sub:"play whole games from a list of moves",project:true,steps:[
 {type:"talk",title:"Be the referee",mood:"cheer",
  body:`<p>You'll write a referee that plays a whole game from a list of square numbers, refuses illegal moves, announces the winner, and then plays a <b>tournament</b>.</p>`,
  say:"Referees have to know every rule!"},
 {type:"code",title:"Step 1: play a game",body:`<p>Finish ${C("play(moves)")}: X goes first and players alternate. After each move check for a winner and return ${C("X wins")} / ${C("O wins")} right away. If the moves run out, return ${C("draw")} when the board is full, otherwise ${C("unfinished")}.</p>`,start:`const LINES = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];\nfunction winner(b) {\n  for (const [a, c, d] of LINES) {\n    if (b[a] !== " " && b[a] === b[c] && b[a] === b[d]) return b[a];\n  }\n  return null;\n}\n\nfunction play(moves) {\n  const board = Array(9).fill(" ");\n  let player = "X";\n  // your code here\n}\n\nconsole.log(play([4, 0, 2, 6, 3, 5, 1, 7, 8]));\nconsole.log(play([0, 3, 1, 4, 2]));\nconsole.log(play([4, 0, 8, 2, 1, 7, 6, 3, 5]));\nconsole.log(play([4, 0]));\n`,
  use:[[/winner\s*\(\s*board\s*\)/,"Call winner(board) after each move."]],out:["draw","X wins","draw","unfinished"],variants:[[/play\(\[0, 3, 1, 4, 2\]\)/,"play([0, 3, 1, 4, 8, 5])",["draw","O wins","draw","unfinished"]]],
  hint:`const LINES = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];\nfunction winner(b) {\n  for (const [a, c, d] of LINES) {\n    if (b[a] !== " " && b[a] === b[c] && b[a] === b[d]) return b[a];\n  }\n  return null;\n}\n\nfunction play(moves) {\n  const board = Array(9).fill(" ");\n  let player = "X";\n  for (const sq of moves) {\n    board[sq] = player;\n    const w = winner(board);\n    if (w) return w + " wins";\n    player = player === "X" ? "O" : "X";\n  }\n  return board.includes(" ") ? "unfinished" : "draw";\n}\n\nconsole.log(play([4, 0, 2, 6, 3, 5, 1, 7, 8]));\nconsole.log(play([0, 3, 1, 4, 2]));\nconsole.log(play([4, 0, 8, 2, 1, 7, 6, 3, 5]));\nconsole.log(play([4, 0]));`},
 {type:"code",title:"Step 2: no cheating",body:`<p>If a move picks a square that's already taken, return ${C("illegal move by X at 4")} (with the right player and square).</p>`,start:`const LINES = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];\nfunction winner(b) {\n  for (const [a, c, d] of LINES) {\n    if (b[a] !== " " && b[a] === b[c] && b[a] === b[d]) return b[a];\n  }\n  return null;\n}\n\nfunction play(moves) {\n  const board = Array(9).fill(" ");\n  let player = "X";\n  for (const sq of moves) {\n    board[sq] = player;\n    const w = winner(board);\n    if (w) return w + " wins";\n    player = player === "X" ? "O" : "X";\n  }\n  return board.includes(" ") ? "unfinished" : "draw";\n}\n\nconsole.log(play([4, 4]));\nconsole.log(play([0, 1, 2, 0]));\nconsole.log(play([0, 3, 1, 4, 2]));\n`,
  use:[[/!==\s*" "|===\s*"X"|===\s*"O"/,"Check whether the square is already taken."]],out:["illegal move by O at 4","illegal move by O at 0","X wins"],
  hint:`const LINES = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];\nfunction winner(b) {\n  for (const [a, c, d] of LINES) {\n    if (b[a] !== " " && b[a] === b[c] && b[a] === b[d]) return b[a];\n  }\n  return null;\n}\n\nfunction play(moves) {\n  const board = Array(9).fill(" ");\n  let player = "X";\n  for (const sq of moves) {\n    if (board[sq] !== " ") return "illegal move by " + player + " at " + sq;\n    board[sq] = player;\n    const w = winner(board);\n    if (w) return w + " wins";\n    player = player === "X" ? "O" : "X";\n  }\n  return board.includes(" ") ? "unfinished" : "draw";\n}\n\nconsole.log(play([4, 4]));\nconsole.log(play([0, 1, 2, 0]));\nconsole.log(play([0, 3, 1, 4, 2]));`},
 {type:"code",title:"Step 3: tournament",body:`<p>${C("games")} holds several games. Play them all and count wins for X, O and draws. Print ${C("X: 2  O: 1  Draws: 1")}.</p>`,start:`const LINES = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];\nfunction winner(b) {\n  for (const [a, c, d] of LINES) {\n    if (b[a] !== " " && b[a] === b[c] && b[a] === b[d]) return b[a];\n  }\n  return null;\n}\nfunction play(moves) {\n  const board = Array(9).fill(" ");\n  let player = "X";\n  for (const sq of moves) {\n    board[sq] = player;\n    const w = winner(board);\n    if (w) return w;\n    player = player === "X" ? "O" : "X";\n  }\n  return "draw";\n}\n\nconst games = [\n  [0, 3, 1, 4, 2],\n  [4, 0, 2, 6, 3, 5, 1, 7, 8],\n  [0, 3, 1, 4, 8, 5],\n  [6, 0, 7, 1, 8]\n];\n// count the results and print them\n`,
  use:[[/for\s*\(/,"Loop over the games."]],out:["X: 2  O: 1  Draws: 1"],variants:[[/\[6, 0, 7, 1, 8\]/,"[4, 0, 8, 2, 1, 7, 6, 3, 5]",["X: 1  O: 1  Draws: 2"]]],
  hint:`const LINES = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];\nfunction winner(b) {\n  for (const [a, c, d] of LINES) {\n    if (b[a] !== " " && b[a] === b[c] && b[a] === b[d]) return b[a];\n  }\n  return null;\n}\nfunction play(moves) {\n  const board = Array(9).fill(" ");\n  let player = "X";\n  for (const sq of moves) {\n    board[sq] = player;\n    const w = winner(board);\n    if (w) return w;\n    player = player === "X" ? "O" : "X";\n  }\n  return "draw";\n}\n\nconst games = [\n  [0, 3, 1, 4, 2],\n  [4, 0, 2, 6, 3, 5, 1, 7, 8],\n  [0, 3, 1, 4, 8, 5],\n  [6, 0, 7, 1, 8]\n];\nconst score = { X: 0, O: 0, draw: 0 };\nfor (const g of games) score[play(g)]++;\nconsole.log("X: " + score.X + "  O: " + score.O + "  Draws: " + score.draw);`},
 {type:"done"}]}
]},
{name:"Bigger games",lessons:[
{id:"g12",title:"Characters with classes",sub:"heroes, monsters and attacks",steps:[
 {type:"talk",title:"A class for every character",
  body:`<p>A ${C("class")} is a blueprint for characters. Each one gets its own name and hp, and they all share the same methods.</p>`,
  demo:`class Fighter {\n  constructor(name, hp, power) {\n    this.name = name;\n    this.hp = hp;\n    this.power = power;\n  }\n  attack(target) {\n    target.hp = Math.max(0, target.hp - this.power);\n    console.log(this.name + " hits " + target.name + " for " + this.power + " (" + target.hp + " left)");\n  }\n  get alive() {\n    return this.hp > 0;\n  }\n}\n\nconst mo = new Fighter("Mo", 12, 4);\nconst slime = new Fighter("Slime", 7, 2);\nmo.attack(slime);\nslime.attack(mo);\nmo.attack(slime);\nconsole.log(slime.alive);`,
  say:"get alive lets you write slime.alive without parentheses."},
 {type:"talk",title:"Special types with extends",mood:"cheer",
  body:`<p>${C("extends")} makes a special kind of character that changes some behavior. Here a Mage's attack ignores half of... well, it just hits twice as hard every third turn.</p>`,
  demo:`class Fighter {\n  constructor(name, hp, power) {\n    this.name = name;\n    this.hp = hp;\n    this.power = power;\n  }\n  damage() {\n    return this.power;\n  }\n}\n\nclass Mage extends Fighter {\n  constructor(name, hp, power) {\n    super(name, hp, power);\n    this.turns = 0;\n  }\n  damage() {\n    this.turns++;\n    return this.turns % 3 === 0 ? this.power * 2 : this.power;\n  }\n}\n\nconst m = new Mage("Kiki", 8, 3);\nconst hits = [];\nfor (let i = 0; i < 6; i++) hits.push(m.damage());\nconsole.log(hits.join(" "));`,
  say:"3 3 6 3 3 6. Every third spell is a big one."},
 {type:"quiz",q:"What does this print?",code:`class C {\n  constructor(n) { this.n = n; }\n  double() { this.n *= 2; }\n}\nconst c = new C(3);\nc.double();\nc.double();\nconsole.log(c.n);`,opts:["12","6","3"],a:0,mono:true,why:"3 → 6 → 12."},
 {type:"quiz",q:"What does super(...) do in a child class's constructor?",opts:["Runs the parent's constructor","Makes the class faster","Copies another object"],a:0,why:"It sets up everything the parent class needs."},
 {type:"fill",title:"Make a hero",body:`<p>Create a hero and attack.</p>`,code:`class Hero {\n  constructor(name) {\n    [0].name = name;\n  }\n}\nconst h = [1] Hero("Bao");\nconsole.log(h.name);`,blanks:["this","new"],tokens:["this","new","self","make"],why:"this.name stores it on the object; new makes one."},
 {type:"code",title:"Healer",body:`<p>Make ${C("Healer")} extend ${C("Fighter")} with a ${C("heal(friend)")} method that adds 5 hp (up to ${C("friend.maxHp")}) and prints ${C("Ivy heals Mo to 10")}.</p>`,start:`class Fighter {\n  constructor(name, hp) {\n    this.name = name;\n    this.hp = hp;\n    this.maxHp = hp;\n  }\n}\n\n// write Healer here\n\nconst mo = new Fighter("Mo", 12);\nmo.hp = 5;\nconst ivy = new Healer("Ivy", 8);\nivy.heal(mo);\nivy.heal(mo);\n`,
  use:[[/class\s+Healer\s+extends\s+Fighter/,"Start with class Healer extends Fighter."],[/Math\.min/,"Use Math.min so hp never passes maxHp."]],out:["Ivy heals Mo to 10","Ivy heals Mo to 12"],
  hint:`class Fighter {\n  constructor(name, hp) {\n    this.name = name;\n    this.hp = hp;\n    this.maxHp = hp;\n  }\n}\n\nclass Healer extends Fighter {\n  heal(friend) {\n    friend.hp = Math.min(friend.maxHp, friend.hp + 5);\n    console.log(this.name + " heals " + friend.name + " to " + friend.hp);\n  }\n}\n\nconst mo = new Fighter("Mo", 12);\nmo.hp = 5;\nconst ivy = new Healer("Ivy", 8);\nivy.heal(mo);\nivy.heal(mo);`},
 {type:"game"},{type:"done"}],
 pool:[
  [`class A { constructor() { this.hp = 5; } }\nconst a = new A();\na.hp -= 2;\nconsole.log(a.hp);`,["3","5","2"]],
  [`class A { hi() { return "a"; } }\nclass B extends A { hi() { return "b"; } }\nconsole.log(new B().hi());`,["b","a","ab"]],
  [`class A { get two() { return 2; } }\nconsole.log(new A().two * 3);`,["6","2","NaN"]],
  [`class A { constructor(n) { this.n = n; } }\nconst x = new A(1);\nconst y = x;\ny.n = 9;\nconsole.log(x.n);`,["9","1","undefined"]]
 ]},
{id:"g13",title:"Inventory & items",sub:"lists of objects, using and stacking items",steps:[
 {type:"talk",title:"A bag of items",
  body:`<p>An inventory is an array of item objects. Each item can have a name, a type and an amount. ${C(".find()")} looks one up by name.</p>`,
  demo:`const bag = [\n  { name: "potion", qty: 2 },\n  { name: "banana", qty: 5 }\n];\nconst p = bag.find(i => i.name === "potion");\np.qty--;\nfor (const item of bag) console.log(item.name + " x" + item.qty);`,
  say:"potion x1, banana x5."},
 {type:"talk",title:"Stacking and running out",mood:"think",
  body:`<p>Picking up something you already have should add to its stack. When an amount hits 0, remove it with ${C(".filter()")}.</p>`,
  demo:`let bag = [{ name: "potion", qty: 1 }];\n\nfunction pickUp(name) {\n  const have = bag.find(i => i.name === name);\n  if (have) have.qty++;\n  else bag.push({ name: name, qty: 1 });\n}\nfunction use(name) {\n  const have = bag.find(i => i.name === name);\n  if (!have) return console.log("No " + name + "!");\n  have.qty--;\n  bag = bag.filter(i => i.qty > 0);\n  console.log("Used " + name);\n}\n\npickUp("key");\npickUp("potion");\nuse("potion");\nuse("potion");\nuse("potion");\nconsole.log(bag.map(i => i.name + " x" + i.qty).join(", "));`,
  say:"Two potions get used, the third try fails, and only the key is left."},
 {type:"quiz",q:"What does find give back if nothing matches?",opts:["undefined","An empty object","An error"],a:0,why:"That's why we check if (have) before using it."},
 {type:"quiz",q:"What does this print?",code:`const bag = [{ n: "a", q: 0 }, { n: "b", q: 2 }];\nconsole.log(bag.filter(i => i.q > 0).length);`,opts:["1","2","0"],a:0,mono:true,why:"Only b has more than 0."},
 {type:"fill",title:"Find the sword",body:`<p>Look up the sword.</p>`,code:`const bag = [{ name: "sword", dmg: 7 }];\nconst s = bag.[0](i => i.name [1] "sword");\nconsole.log(s.dmg);`,blanks:["find","==="],tokens:["find","===","filter","="],why:"find the first item where the name matches."},
 {type:"code",title:"Shopkeeper",body:`<p>Finish ${C("buy(name)")}: look up the price in ${C("shop")}. If you can't afford it, print ${C("Not enough gold for X")}. Otherwise subtract the gold, add it to ${C("bag")} (stacking!) and print ${C("Bought X, G gold left")}.</p>`,start:`const shop = { potion: 5, sword: 20, banana: 1 };\nlet gold = 12;\nconst bag = [];\n\nfunction buy(name) {\n  // your code here\n}\n\nbuy("potion");\nbuy("sword");\nbuy("potion");\nbuy("banana");\nconsole.log(bag.map(i => i.name + " x" + i.qty).join(", "));\n`,
  use:[[/gold\s*-=/,"Take the price from gold."],[/\.find\s*\(/,"Use find to stack items you already have."]],out:["Bought potion, 7 gold left","Not enough gold for sword","Bought potion, 2 gold left","Bought banana, 1 gold left","potion x2, banana x1"],
  hint:`const shop = { potion: 5, sword: 20, banana: 1 };\nlet gold = 12;\nconst bag = [];\n\nfunction buy(name) {\n  const price = shop[name];\n  if (price > gold) {\n    console.log("Not enough gold for " + name);\n    return;\n  }\n  gold -= price;\n  const have = bag.find(i => i.name === name);\n  if (have) have.qty++;\n  else bag.push({ name: name, qty: 1 });\n  console.log("Bought " + name + ", " + gold + " gold left");\n}\n\nbuy("potion");\nbuy("sword");\nbuy("potion");\nbuy("banana");\nconsole.log(bag.map(i => i.name + " x" + i.qty).join(", "));`},
 {type:"game"},{type:"done"}],
 pool:[
  [`const b = [{ n: "x" }, { n: "y" }];\nconsole.log(b.find(i => i.n === "y").n);`,["y","x","undefined"]],
  [`const b = [{ q: 2 }, { q: 3 }];\nconsole.log(b.reduce((s, i) => s + i.q, 0));`,["5","23","2"]],
  [`const b = [{ n: "a" }];\nconsole.log(b.find(i => i.n === "z"));`,["undefined","null","a"]],
  [`const shop = { gem: 9 };\nlet gold = 10;\ngold -= shop.gem;\nconsole.log(gold);`,["1","19","9"]],
  [`const b = [{ n: "a", q: 1 }];\nb[0].q += 4;\nconsole.log(b[0].q);`,["5","1","14"]]
 ]},
{id:"g14",title:"Text adventure",sub:"rooms, exits and commands",steps:[
 {type:"talk",title:"A world of rooms",
  body:`<p>Text adventures were some of the first video games. The world is an object of <b>rooms</b>; each room has a description and <b>exits</b> pointing to other rooms.</p>`,
  demo:`const rooms = {\n  hall: { desc: "a dusty hall", exits: { north: "library", east: "kitchen" } },\n  library: { desc: "shelves of old books", exits: { south: "hall" } },\n  kitchen: { desc: "a kitchen that smells of bananas", exits: { west: "hall" } }\n};\nlet here = "hall";\nconsole.log("You are in " + rooms[here].desc + ".");\nconsole.log("Exits: " + Object.keys(rooms[here].exits).join(", "));`,
  say:"Object.keys lists the exit names."},
 {type:"talk",title:"Following commands",mood:"think",
  body:`<p>Commands like ${C('"go north"')} get split into a verb and a target. If the exit exists, move; if not, complain. A ${C("switch")} on the verb keeps it tidy.</p>`,
  demo:`const rooms = {\n  hall: { desc: "a dusty hall", exits: { north: "library" } },\n  library: { desc: "shelves of old books", exits: { south: "hall" } }\n};\nlet here = "hall";\nfor (const cmd of ["go west", "go north", "look"]) {\n  const [verb, target] = cmd.split(" ");\n  switch (verb) {\n    case "go":\n      if (rooms[here].exits[target]) {\n        here = rooms[here].exits[target];\n        console.log("You walk " + target + ".");\n      } else {\n        console.log("You can't go " + target + ".");\n      }\n      break;\n    case "look":\n      console.log("You see " + rooms[here].desc + ".");\n      break;\n  }\n}`,
  say:"Can't go west, walk north, then look around the library."},
 {type:"quiz",q:"What does this print?",code:`const [a, b] = "take key".split(" ");\nconsole.log(b);`,opts:["key","take","take key"],a:0,mono:true,why:"split gives [\"take\", \"key\"], and b gets the second one."},
 {type:"quiz",q:"What does this print?",code:`const ex = { north: "attic" };\nconsole.log(ex["south"]);`,opts:["undefined","attic","null"],a:0,mono:true,why:"There's no south key, so you get undefined (which counts as false in an if)."},
 {type:"fill",title:"List the exits",body:`<p>Print the exit names.</p>`,code:`const exits = { up: "roof", down: "cellar" };\nconsole.log(Object.[0](exits).[1](" and "));`,blanks:["keys","join"],tokens:["keys","join","values","split"],why:"Object.keys gives [\"up\", \"down\"], and join glues them."},
 {type:"code",title:"Find the key",body:`<p>Handle ${C("go")}, ${C("take")} and ${C("open")}. ${C("take key")} only works in the room where the key is. ${C("open door")} works only in the hall <b>with</b> the key: print ${C("You escape!")} and stop. Print the messages shown in the expected output.</p>`,start:`const rooms = {\n  hall: { exits: { east: "study" } },\n  study: { exits: { west: "hall" }, item: "key" }\n};\nlet here = "hall";\nconst bag = [];\nconst cmds = ["open door", "go east", "take key", "go west", "open door"];\nfor (const cmd of cmds) {\n  const [verb, target] = cmd.split(" ");\n  // your code here\n}\n`,
  use:[[/switch|if\s*\(\s*verb/,"Check the verb."],[/bag\.push|bag\.includes/,"Keep the key in bag."]],out:["The door is locked.","You go east.","You take the key.","You go west.","You escape!"],variants:[[/"take key", /,"",["The door is locked.","You go east.","You go west.","The door is locked."]]],
  hint:`const rooms = {\n  hall: { exits: { east: "study" } },\n  study: { exits: { west: "hall" }, item: "key" }\n};\nlet here = "hall";\nconst bag = [];\nconst cmds = ["open door", "go east", "take key", "go west", "open door"];\nfor (const cmd of cmds) {\n  const [verb, target] = cmd.split(" ");\n  if (verb === "go" && rooms[here].exits[target]) {\n    here = rooms[here].exits[target];\n    console.log("You go " + target + ".");\n  } else if (verb === "take" && rooms[here].item === target) {\n    bag.push(target);\n    rooms[here].item = null;\n    console.log("You take the " + target + ".");\n  } else if (verb === "open" && here === "hall") {\n    if (bag.includes("key")) {\n      console.log("You escape!");\n      break;\n    }\n    console.log("The door is locked.");\n  } else {\n    console.log("Nothing happens.");\n  }\n}`},
 {type:"game"},{type:"done"}],
 pool:[
  [`console.log("go north".split(" ")[1]);`,["north","go","go north"]],
  [`const r = { a: { x: 1 } };\nconsole.log(r.a.x + 1);`,["2","1","11"]],
  [`console.log(Object.keys({ n: 1, s: 2 }).length);`,["2","3","1"]],
  [`const bag = ["key"];\nconsole.log(bag.includes("map"));`,["false","true","-1"]],
  [`let here = "hall";\nconst ex = { up: "attic" };\nif (ex.up) here = ex.up;\nconsole.log(here);`,["attic","hall","up"]]
 ]},
{id:"g15",title:"Project: Dungeon Crawler",sub:"everything together in one game",project:true,steps:[
 {type:"talk",title:"The final quest",mood:"cheer",
  body:`<p>Your capstone: a dungeon on a grid. Walk around, fight monsters you bump into, drink potions, and reach the stairs. You'll use state, loops, grids, objects and classes.</p>`,
  say:"Finish this and you've made a real game. Show someone!"},
 {type:"code",title:"Step 1: walk the dungeon",body:`<p>Move through the map with the moves. Walls block you. Stepping on ${C("p")} picks up a potion (+4 hp, max 10) and clears the tile. Print the hero's final position and hp like ${C("At 6,1 with 10 hp")}.</p>`,start:`const map = [\n  "########",\n  "#..p...#",\n  "#.##.#.#",\n  "#p...#>#",\n  "########"\n].map(r => r.split(""));\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nconst hero = { x: 1, y: 1, hp: 6, maxHp: 10 };\nconst moves = "RRRRR";\n// your code here\n`,
  use:[[/"p"/,"Check for potion tiles."],[/Math\.min/,"Don't heal past maxHp."]],out:["At 6,1 with 10 hp"],variants:[[/"RRRRR"/,"\"DDRR\"",["At 3,3 with 10 hp"]],[/"RRRRR"/,"\"RL\"",["At 1,1 with 6 hp"]]],
  hint:`const map = [\n  "########",\n  "#..p...#",\n  "#.##.#.#",\n  "#p...#>#",\n  "########"\n].map(r => r.split(""));\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nconst hero = { x: 1, y: 1, hp: 6, maxHp: 10 };\nconst moves = "RRRRR";\nfor (const m of moves) {\n  const [dx, dy] = DIRS[m];\n  if (map[hero.y + dy][hero.x + dx] === "#") continue;\n  hero.x += dx;\n  hero.y += dy;\n  if (map[hero.y][hero.x] === "p") {\n    hero.hp = Math.min(hero.maxHp, hero.hp + 4);\n    map[hero.y][hero.x] = ".";\n  }\n}\nconsole.log("At " + hero.x + "," + hero.y + " with " + hero.hp + " hp");`},
 {type:"code",title:"Step 2: monsters",body:`<p>Monsters are listed by position. If you try to step onto a monster, you attack it instead (it loses ${C("hero.power")}) and it hits back if still alive (you lose its ${C("power")}). A defeated monster is removed and you stay put that turn. Print each fight line as shown.</p>`,start:`const map = [\n  "#######",\n  "#.....#",\n  "#######"\n].map(r => r.split(""));\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nconst hero = { x: 1, y: 1, hp: 10, power: 3 };\nlet monsters = [{ name: "Rat", x: 3, y: 1, hp: 5, power: 2 }];\nconst moves = "RRRRR";\nfor (const m of moves) {\n  const [dx, dy] = DIRS[m];\n  const nx = hero.x + dx, ny = hero.y + dy;\n  if (map[ny][nx] === "#") continue;\n  // fight a monster at nx, ny, or move\n}\nconsole.log("At " + hero.x + "," + hero.y + " with " + hero.hp + " hp");\n`,
  use:[[/monsters\.find|monsters\.filter|for\s*\(\s*const\s+\w+\s+of\s+monsters/,"Look for a monster at the next square."]],out:["You hit Rat (2 left)","Rat hits you (8 left)","You defeat Rat!","At 4,1 with 8 hp"],
  hint:`const map = [\n  "#######",\n  "#.....#",\n  "#######"\n].map(r => r.split(""));\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nconst hero = { x: 1, y: 1, hp: 10, power: 3 };\nlet monsters = [{ name: "Rat", x: 3, y: 1, hp: 5, power: 2 }];\nconst moves = "RRRRR";\nfor (const m of moves) {\n  const [dx, dy] = DIRS[m];\n  const nx = hero.x + dx, ny = hero.y + dy;\n  if (map[ny][nx] === "#") continue;\n  const mon = monsters.find(o => o.x === nx && o.y === ny);\n  if (mon) {\n    mon.hp -= hero.power;\n    if (mon.hp > 0) {\n      console.log("You hit " + mon.name + " (" + mon.hp + " left)");\n      hero.hp -= mon.power;\n      console.log(mon.name + " hits you (" + hero.hp + " left)");\n    } else {\n      console.log("You defeat " + mon.name + "!");\n      monsters = monsters.filter(o => o !== mon);\n    }\n  } else {\n    hero.x = nx;\n    hero.y = ny;\n  }\n}\nconsole.log("At " + hero.x + "," + hero.y + " with " + hero.hp + " hp");`},
 {type:"code",title:"Step 3: win or lose",body:`<p>Put it all together. Reaching ${C(">")} prints ${C("You found the stairs with N hp!")} and ends the game. If hp drops to 0, print ${C("You were defeated...")} and end. If the moves run out, print ${C("Still exploring.")}.</p>`,start:`const map = [\n  "########",\n  "#......#",\n  "#.####.#",\n  "#.....>#",\n  "########"\n].map(r => r.split(""));\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nconst hero = { x: 1, y: 1, hp: 10, power: 3 };\nlet monsters = [\n  { name: "Rat", x: 4, y: 1, hp: 5, power: 2 },\n  { name: "Ogre", x: 6, y: 2, hp: 9, power: 4 }\n];\nconst moves = "RRRRRRRRRRDDDDD";\n// your game loop here\n`,
  use:[[/">"/,"Check for the stairs \">\"."],[/hp\s*<=\s*0/,"Check whether the hero has run out of hp."]],out:["You hit Rat (2 left)","Rat hits you (8 left)","You defeat Rat!","You hit Ogre (6 left)","Ogre hits you (4 left)","You hit Ogre (3 left)","Ogre hits you (0 left)","You were defeated..."],variants:[[/power: 4/,"power: 1",["You hit Rat (2 left)","Rat hits you (8 left)","You defeat Rat!","You hit Ogre (6 left)","Ogre hits you (7 left)","You hit Ogre (3 left)","Ogre hits you (6 left)","You defeat Ogre!","You found the stairs with 6 hp!"]]],
  hint:`const map = [\n  "########",\n  "#......#",\n  "#.####.#",\n  "#.....>#",\n  "########"\n].map(r => r.split(""));\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nconst hero = { x: 1, y: 1, hp: 10, power: 3 };\nlet monsters = [\n  { name: "Rat", x: 4, y: 1, hp: 5, power: 2 },\n  { name: "Ogre", x: 6, y: 2, hp: 9, power: 4 }\n];\nconst moves = "RRRRRRRRRRDDDDD";\nlet over = false;\nfor (const m of moves) {\n  const [dx, dy] = DIRS[m];\n  const nx = hero.x + dx, ny = hero.y + dy;\n  if (map[ny][nx] === "#") continue;\n  const mon = monsters.find(o => o.x === nx && o.y === ny);\n  if (mon) {\n    mon.hp -= hero.power;\n    if (mon.hp > 0) {\n      console.log("You hit " + mon.name + " (" + mon.hp + " left)");\n      hero.hp -= mon.power;\n      console.log(mon.name + " hits you (" + hero.hp + " left)");\n      if (hero.hp <= 0) {\n        console.log("You were defeated...");\n        over = true;\n        break;\n      }\n    } else {\n      console.log("You defeat " + mon.name + "!");\n      monsters = monsters.filter(o => o !== mon);\n    }\n    continue;\n  }\n  hero.x = nx;\n  hero.y = ny;\n  if (map[ny][nx] === ">") {\n    console.log("You found the stairs with " + hero.hp + " hp!");\n    over = true;\n    break;\n  }\n}\nif (!over) console.log("Still exploring.");`},
 {type:"done"}]}
]}
]};
