/* Build a Game: a JavaScript track where every lesson builds part of a real (console) game.
   Runs in the same JavaScript runner as the JS course. Randomness uses a seeded generator so results
   can be checked; tests/verify_course.py runs every snippet. */
const RAND_FN=`function makeRandom(seed) {\n  return function () {\n    seed = (seed * 9301 + 49297) % 233280;\n    return seed / 233280;\n  };\n}\n`;

const DICE=`// 🎲 TypeMonkey's dice: same seed, same rolls every time.
// (You don't need to change anything down here.)
function roll() {
  seed = (seed * 9301 + 49297) % 233280;
  return Math.floor(seed / 233280 * 6) + 1;
}
`;

const COURSE_GAME={id:"game",name:"Build a Game",blurb:"Make real games in JavaScript: dice duels, treasure maps, hangman, tic-tac-toe and a dungeon crawler. Starts super easy, so it's a fun first course too. Unit 1 is free.",units:[
{name:"Game basics",free:true,lessons:[
{id:"g0",title:"Your first game",sub:"a title screen and a score",steps:[
 {type:"talk",title:"Let's make games!",mood:"cheer",
  body:`<p>Every game you've ever played is made of code. In this course you'll build real (text) games: dice battles, treasure maps, hangman and a dungeon. We'll start super small. Press ▶ Run and watch the <b>game screen</b>.</p>`,
  demo:`console.log("=== BANANA QUEST ===");\nconsole.log("🐵 A hungry monkey needs bananas!");\nconsole.log("Press START to play");`,
  say:"That's a title screen. Every game starts with one!"},
 {type:"talk",title:"Games remember things",
  body:`<p>A game needs to remember stuff: the player's name, the score, how many bananas you have. That's what <b>variables</b> are for. Use ${C("let")} for things that will change.</p>`,
  demo:`let player = "Mo";\nlet bananas = 0;\nconsole.log(player + " has " + bananas + " bananas");\nbananas = bananas + 3;\nconsole.log(player + " found some! Now: " + bananas);`,
  say:"Mo has 0 bananas, then Mo found some! Now: 3"},
 {type:"talk",title:"Scoring points",mood:"think",
  body:`<p>${C("score += 10")} is a quick way to add 10 points. You'll use it in almost every game.</p>`,
  demo:`let score = 0;\nscore += 10;   // grabbed a coin\nscore += 50;   // beat a monster\nconsole.log("⭐ Score: " + score);`,
  say:"⭐ Score: 60"},
 {type:"quiz",q:"What does this print?",code:`let coins = 2;\ncoins += 3;\nconsole.log(coins);`,opts:["5","23","3"],a:0,mono:true,why:"2 + 3 = 5."},
 {type:"fill",title:"Add points",body:`<p>Give the player 25 points.</p>`,code:`let score = 0;\nscore [0] 25;\nconsole.log(score);`,blanks:["+="],tokens:["+=","-=","=="],why:"+= adds to what's already there."},
 {type:"code",title:"Your title screen",body:`<p>Make a title screen for your own game! Print ${C("=== MONKEY MAYHEM ===")} and then ${C("Player: Mo")} using the ${C("player")} variable.</p>`,start:`let player = "Mo";\n// print the title, then the player\n`,
  use:[[/console\.log/,"Print with console.log(...)."],[/\+\s*player|player\s*\+/,"Glue the player variable on with +."]],out:["=== MONKEY MAYHEM ===","Player: Mo"],variants:[[/"Mo"/,"\"Kiki\"",["=== MONKEY MAYHEM ===","Player: Kiki"]]],
  hint:`let player = "Mo";\nconsole.log("=== MONKEY MAYHEM ===");\nconsole.log("Player: " + player);`},
 {type:"code",title:"Banana grab",body:`<p>The monkey finds 3 bananas, then 5 more. Add them to ${C("bananas")} with ${C("+=")}, then print ${C("Bananas: 8")}.</p>`,start:`let bananas = 0;\n// found 3, then 5\n`,
  use:[[/\+=/,"Add them with +=."]],out:["Bananas: 8"],variants:[[/let bananas = 0/,"let bananas = 10",["Bananas: 18"]]],
  hint:`let bananas = 0;\nbananas += 3;\nbananas += 5;\nconsole.log("Bananas: " + bananas);`},
 {type:"game"},{type:"done"}],
 pool:[
  [`let s = 0;\ns += 10;\nconsole.log(s);`,["10","0","s"]],
  [`let name = "Mo";\nconsole.log("Hi " + name);`,["Hi Mo","Hi name","Mo"]],
  [`let b = 5;\nb = b + 1;\nconsole.log(b);`,["6","5","51"]],
  [`console.log("=" + "=" + "=");`,["===","3","= = ="]],
  [`let lives = 3;\nlives -= 1;\nconsole.log(lives);`,["2","3","4"]]
 ]},
{id:"g1",title:"Health bars",sub:"drawing hearts and keeping hp in range",steps:[
 {type:"talk",title:"Drawing a health bar",mood:"cheer",
  body:`<p>${C('"♥".repeat(3)')} makes ♥♥♥. Use it to draw a health bar: full hearts for the health you have, empty ones for what's missing.</p>`,
  demo:`const maxHp = 5;\nlet hp = 3;\nconsole.log("♥".repeat(hp) + "♡".repeat(maxHp - hp));\nhp = 5;\nconsole.log("♥".repeat(hp) + "♡".repeat(maxHp - hp));`,
  say:"♥♥♥♡♡, then ♥♥♥♥♥."},
 {type:"talk",title:"Ouch! And healing",
  body:`<p>Getting hit takes hp away; a potion gives some back. Print the bar after each change and you can watch it go up and down.</p>`,
  demo:`let hp = 5;\nhp -= 2;\nconsole.log("Ouch! " + "♥".repeat(hp));\nhp += 1;\nconsole.log("Potion! " + "♥".repeat(hp));`,
  say:"Ouch! ♥♥♥ then Potion! ♥♥♥♥"},
 {type:"talk",title:"Keeping values in range",mood:"think",
  body:`<p>Health shouldn't go below 0 or above the max. ${C("Math.min")} picks the smaller number, ${C("Math.max")} the bigger one. Together they keep a value in range.</p>`,
  demo:`const maxHp = 10;\nlet hp = 8;\nhp = Math.min(maxHp, hp + 5);   // heal, but not past max\nconsole.log(hp);\nhp = Math.max(0, hp - 25);      // big hit, but not below 0\nconsole.log(hp);`,
  say:"10, then 0."},
 {type:"talk",title:"Keeping it all together",
  body:`<p>Once there's lots to remember, keep it together in one object, like ${C("player.hp")} and ${C("player.coins")}.</p>`,
  demo:`const player = { name: "Mo", hp: 10, coins: 0 };\nplayer.coins += 3;\nconsole.log(player.name + " ♥" + player.hp + " 🪙" + player.coins);`,
  say:"Mo ♥10 🪙3"},
 {type:"quiz",q:"What does this print?",code:`console.log("♥".repeat(2) + "♡");`,opts:["♥♥♡","♥♡♡","♥2♡"],a:0,mono:true,why:"Two full hearts, then one empty."},
 {type:"quiz",q:"What does this print?",code:`let hp = 4;\nhp = Math.max(0, hp - 9);\nconsole.log(hp);`,opts:["0","-5","4"],a:0,mono:true,why:"Math.max(0, -5) picks the bigger one: 0."},
 {type:"fill",title:"Heal, but not too much",body:`<p>Heal by 4 without going past the max.</p>`,code:`const maxHp = 10;\nlet hp = 9;\nhp = Math.[0](maxHp, hp + 4);\nconsole.log(hp);`,blanks:["min"],tokens:["min","max","round","abs"],why:"min picks the smaller value, so it can never pass maxHp."},
 {type:"code",title:"Draw the bar",body:`<p>Print a bar with ${C("♥")} for each point of ${C("hp")} and ${C("♡")} for each missing point. With 3 of 5 it looks like ${C("♥♥♥♡♡")}.</p>`,start:`const maxHp = 5;\nlet hp = 3;\n// print the bar\n`,
  use:[[/repeat/,"Use .repeat() to draw the hearts."]],out:["♥♥♥♡♡"],variants:[[/hp = 3/,"hp = 1",["♥♡♡♡♡"]]],
  hint:`const maxHp = 5;\nlet hp = 3;\nconsole.log("♥".repeat(hp) + "♡".repeat(maxHp - hp));`},
 {type:"code",title:"Drink a potion",body:`<p>${C("hit")} is done for you. Finish ${C("heal")} so it adds the amount but never goes past ${C("player.maxHp")}.</p>`,start:`const player = { hp: 10, maxHp: 10 };\n\nfunction hit(p, dmg) {\n  p.hp = Math.max(0, p.hp - dmg);\n}\nfunction heal(p, amount) {\n  // your code here\n}\n\nhit(player, 4);\nconsole.log(player.hp);\nheal(player, 2);\nconsole.log(player.hp);\nheal(player, 99);\nconsole.log(player.hp);\n`,
  use:[[/Math\.min|if\s*\(/,"Use Math.min (or an if) so hp can't go past maxHp."]],out:["6","8","10"],
  hint:`const player = { hp: 10, maxHp: 10 };\n\nfunction hit(p, dmg) {\n  p.hp = Math.max(0, p.hp - dmg);\n}\nfunction heal(p, amount) {\n  p.hp = Math.min(p.maxHp, p.hp + amount);\n}\n\nhit(player, 4);\nconsole.log(player.hp);\nheal(player, 2);\nconsole.log(player.hp);\nheal(player, 99);\nconsole.log(player.hp);`},
 {type:"game"},{type:"done"}],
 pool:[
  [`console.log("♥".repeat(3));`,["♥♥♥","♥3","♥ ♥ ♥"]],
  [`console.log(Math.min(5, 12));`,["5","12","17"]],
  [`const p = { hp: 3 };\np.hp--;\nconsole.log(p.hp);`,["2","3","4"]],
  [`let hp = 7;\nhp = Math.min(10, hp + 6);\nconsole.log(hp);`,["10","13","7"]],
  [`const p = { name: "Bao", lvl: 1 };\np.lvl++;\nconsole.log(p.name + p.lvl);`,["Bao2","Bao1","3"]]
 ]},
{id:"g2",title:"The game loop",sub:"turns, rounds and game over",steps:[
 {type:"talk",title:"Loop until game over",
  body:`<p>Games run in a <b>loop</b>: take a turn, update things, check if the game is over, repeat. A ${C("while")} loop is perfect: it keeps going while the monster still has health.</p>`,
  demo:`let monsterHp = 10;\nwhile (monsterHp > 0) {\n  monsterHp -= 3;\n  console.log("💥 Bonk! Monster has " + Math.max(0, monsterHp) + " hp");\n}\nconsole.log("🏆 You win!");`,
  say:"Four bonks and the monster is done. You win!"},
 {type:"talk",title:"Counting turns",mood:"think",
  body:`<p>Add a counter to know how long the fight took. Make it before the loop and add 1 each turn.</p>`,
  demo:`let monsterHp = 10;\nlet turns = 0;\nwhile (monsterHp > 0) {\n  monsterHp -= 3;\n  turns++;\n}\nconsole.log("Won in " + turns + " turns!");`,
  say:"Won in 4 turns!"},
 {type:"talk",title:"Moves from a list",
  body:`<p>Our games can't read the keyboard, so the player's moves come from a list. A ${C("for...of")} loop goes through them one by one.</p>`,
  demo:`const moves = ["attack", "attack", "heal", "attack"];\nlet hp = 6, foe = 9;\nfor (const m of moves) {\n  if (m === "attack") foe -= 3;\n  if (m === "heal") hp += 2;\n  console.log(m + " -> you " + hp + ", foe " + foe);\n}`,
  say:"Each move changes something, then we print it."},
 {type:"talk",title:"Stopping early",mood:"cheer",
  body:`<p>When someone wins, the game should end right away, even if there are moves left. ${C("break")} jumps out of the loop.</p>`,
  demo:`const rolls = [4, 6, 5, 3, 6];\nlet pos = 0;\nfor (const r of rolls) {\n  pos += r;\n  console.log("Rolled " + r + ", now at " + pos);\n  if (pos >= 15) {\n    console.log("🏁 Reached the finish!");\n    break;\n  }\n}`,
  say:"After 3 rolls you're at 15, so the last two rolls are never used."},
 {type:"quiz",q:"What does this print?",code:`let hp = 5;\nlet turns = 0;\nwhile (hp > 0) {\n  hp -= 2;\n  turns++;\n}\nconsole.log(turns);`,opts:["3","2","5"],a:0,mono:true,why:"5 → 3 → 1 → -1. Three turns."},
 {type:"quiz",q:"What does this print?",code:`let score = 0;\nfor (const pts of [10, 20, 30]) {\n  score += pts;\n  if (score > 25) break;\n}\nconsole.log(score);`,opts:["30","60","10"],a:0,mono:true,why:"10, then 30 (more than 25), so it stops."},
 {type:"fill",title:"Keep fighting",body:`<p>Keep looping while the monster has hp.</p>`,code:`let monster = 7;\n[0] (monster > 0) {\n  monster -= 2;\n}\nconsole.log(monster);`,blanks:["while"],tokens:["while","if","for"],why:"while keeps going as long as the condition is true."},
 {type:"code",title:"Monster fight",body:`<p>Each turn, hit the monster for 4. Print ${C("Bonk! Monster has N hp")} each turn (never below 0), then ${C("You win!")} at the end.</p>`,start:`let monster = 10;\n// your loop here\n`,
  use:[[/while\s*\(/,"Use a while loop."]],out:["Bonk! Monster has 6 hp","Bonk! Monster has 2 hp","Bonk! Monster has 0 hp","You win!"],variants:[[/monster = 10/,"monster = 5",["Bonk! Monster has 1 hp","Bonk! Monster has 0 hp","You win!"]]],
  hint:`let monster = 10;\nwhile (monster > 0) {\n  monster -= 4;\n  console.log("Bonk! Monster has " + Math.max(0, monster) + " hp");\n}\nconsole.log("You win!");`},
 {type:"code",title:"Race to the finish",body:`<p>Add each roll to ${C("pos")} and count the rolls. As soon as pos reaches ${C("goal")} or more, print ${C("Finished in N rolls!")} and stop with ${C("break")}.</p>`,start:`const rolls = [3, 5, 2, 6, 4];\nconst goal = 15;\nlet pos = 0;\nlet count = 0;\nfor (const r of rolls) {\n  // your code here\n}\n`,
  use:[[/\bbreak\b/,"Stop the loop with break once you finish."]],out:["Finished in 4 rolls!"],variants:[[/goal = 15/,"goal = 8",["Finished in 2 rolls!"]]],
  hint:`const rolls = [3, 5, 2, 6, 4];\nconst goal = 15;\nlet pos = 0;\nlet count = 0;\nfor (const r of rolls) {\n  pos += r;\n  count++;\n  if (pos >= goal) {\n    console.log("Finished in " + count + " rolls!");\n    break;\n  }\n}`},
 {type:"game"},{type:"done"}],
 pool:[
  [`let n = 0;\nwhile (n < 10) n += 4;\nconsole.log(n);`,["12","10","8"]],
  [`let t = 0;\nfor (const m of ["a", "b", "c"]) t++;\nconsole.log(t);`,["3","2","abc"]],
  [`let hp = 3;\nwhile (hp > 0) hp--;\nconsole.log(hp);`,["0","-1","1"]],
  [`let s = 0;\nfor (const r of [2, 9, 4]) {\n  if (r > 5) break;\n  s += r;\n}\nconsole.log(s);`,["2","15","6"]],
  [`let i = 0;\nwhile (i < 12) i += 5;\nconsole.log(i);`,["15","12","10"]]
 ]},
{id:"g3",title:"Rolling dice",sub:"random numbers that games can replay",steps:[
 {type:"talk",title:"A real random roll",
  body:`<p>${C("Math.random()")} gives a random number between 0 and 1. This line turns it into a die roll from 1 to 6. Press Run a few times: it changes!</p>`,
  demo:`const r = Math.floor(Math.random() * 6) + 1;\nconsole.log("🎲 You rolled " + r);`,
  say:"Every Run gives a different roll."},
 {type:"talk",title:"TypeMonkey's dice",mood:"think",
  body:`<p>Real games often use a <b>seed</b>: a starting number that makes the same \"random\" rolls every time. (Minecraft worlds work like this!) So TypeMonkey can check your answers, the challenges give you a ready-made ${C("roll()")} at the bottom. You just call it.</p>`,
  demo:`let seed = 42;\nconsole.log(roll(), roll(), roll());\n\n`+DICE,
  say:"Seed 42 always rolls 6 5 6. Change the seed for different rolls."},
 {type:"talk",title:"Doing things with rolls",mood:"cheer",
  body:`<p>Store a roll in a variable to use it more than once, add rolls up, or check for a lucky number.</p>`,
  demo:`let seed = 7;\nconst a = roll();\nconst b = roll();\nconsole.log("🎲 " + a + " + 🎲 " + b + " = " + (a + b));\nif (a + b >= 7) console.log("Lucky!");\nelse console.log("Try again");\n\n`+DICE,
  say:"3 + 4 = 7, Lucky!"},
 {type:"quiz",q:"What range does Math.floor(Math.random() * 6) + 1 give?",opts:["1 to 6","0 to 6","0 to 5"],a:0,mono:true,why:"random()*6 is 0 up to 5.99, floor makes 0–5, and +1 makes 1–6."},
 {type:"quiz",q:"Why do games use a seed?",opts:["So the same random rolls can be made again","To make the game faster","So the numbers are bigger"],a:0,why:"Same seed, same world. Handy for sharing levels and testing."},
 {type:"fill",title:"Roll a d20",body:`<p>Make a function that rolls a 20-sided die (1 to 20).</p>`,code:`function d20() {\n  return Math.[0](Math.random() * 20) + [1];\n}\nconst r = d20();\nconsole.log(r >= 1 && r <= 20);`,blanks:["floor","1"],tokens:["floor","1","round","0","20"],why:"floor then +1 gives 1 to 20."},
 {type:"code",title:"Roll two dice",body:`<p>Call ${C("roll()")} twice and save the results in ${C("a")} and ${C("b")}. Print ${C("You rolled 6 and 5")}, then ${C("Total: 11")}.</p>`,start:`let seed = 42;\n// roll twice, then print\n\n`+DICE,
  use:[[/roll\s*\(\s*\)[\s\S]*roll\s*\(\s*\)/,"Call roll() twice."]],out:["You rolled 6 and 5","Total: 11"],variants:[[/seed = 42/,"seed = 99",["You rolled 1 and 3","Total: 4"]]],
  hint:`let seed = 42;\nconst a = roll();\nconst b = roll();\nconsole.log("You rolled " + a + " and " + b);\nconsole.log("Total: " + (a + b));\n\n`+DICE},
 {type:"code",title:"Wait for a six",body:`<p>Keep rolling until you get a 6, counting the rolls. Then print ${C("Got a 6 after N rolls!")}.</p>`,start:`let seed = 3;\nlet rolls = 0;\n// your loop here\n\n`+DICE,
  use:[[/while|for/,"Keep rolling in a loop."]],out:["Got a 6 after 3 rolls!"],variants:[[/seed = 3/,"seed = 99",["Got a 6 after 11 rolls!"]]],
  hint:`let seed = 3;\nlet rolls = 0;\nlet r = 0;\nwhile (r !== 6) {\n  r = roll();\n  rolls++;\n}\nconsole.log("Got a 6 after " + rolls + " rolls!");\n\n`+DICE},
 {type:"game"},{type:"done"}],
 pool:[
  [`console.log(Math.floor(5.9));`,["5","6","5.9"]],
  [`console.log(Math.floor(0.5 * 6) + 1);`,["4","3","6"]],
  [`const a = 3, b = 4;\nconsole.log(a + b >= 7 ? "Lucky!" : "Try again");`,["Lucky!","Try again","7"]],
  [`const loot = ["a", "b", "c"];\nconsole.log(loot[Math.floor(0.7 * loot.length)]);`,["c","b","a"]],
  [`console.log(Math.floor(0.99 * 6) + 1);`,["6","7","5"]]
 ]},
{id:"g4",title:"Project: Dice Duel",sub:"your first complete game",project:true,steps:[
 {type:"talk",title:"Dice Duel",mood:"cheer",
  body:`<p>Mo and Kiki are having a dice duel! You'll build it in three small steps: one round, then best of five, then a full battle with health.</p>`,
  say:"Your first full game. Let's go!"},
 {type:"code",title:"Step 1: one round",body:`<p>Roll once for Mo and once for Kiki. Print ${C("Mo rolled 2, Kiki rolled 4")}. Then print who wins the round: ${C("Mo wins the round!")}, ${C("Kiki wins the round!")} or ${C("It's a tie!")}.</p>`,start:`let seed = 1;\nconst mo = roll();\nconst kiki = roll();\n// print the rolls, then the winner\n\n`+DICE,
  use:[[/if\s*\(/,"Compare the rolls with if."]],out:["Mo rolled 2, Kiki rolled 4","Kiki wins the round!"],variants:[[/seed = 1/,"seed = 3",["Mo rolled 2, Kiki rolled 2","It's a tie!"]],[/seed = 1/,"seed = 2024",["Mo rolled 6, Kiki rolled 4","Mo wins the round!"]]],
  hint:`let seed = 1;\nconst mo = roll();\nconst kiki = roll();\nconsole.log("Mo rolled " + mo + ", Kiki rolled " + kiki);\nif (mo > kiki) console.log("Mo wins the round!");\nelse if (kiki > mo) console.log("Kiki wins the round!");\nelse console.log("It's a tie!");\n\n`+DICE},
 {type:"code",title:"Step 2: best of five",body:`<p>Play 5 rounds. Each round, whoever rolls higher gets a point (ties don't count). Print the score like ${C("Mo 3 - 2 Kiki")}, then the winner like ${C("Mo wins the duel! 🏆")}.</p>`,start:`let seed = 1;\nlet moWins = 0;\nlet kikiWins = 0;\nfor (let i = 0; i < 5; i++) {\n  const mo = roll();\n  const kiki = roll();\n  // give a point to the winner\n}\n// print the score and the winner\n\n`+DICE,
  use:[[/moWins\s*\+\+|moWins\s*\+=/,"Give Mo a point with moWins++."]],out:["Mo 3 - 2 Kiki","Mo wins the duel! 🏆"],variants:[[/seed = 1/,"seed = 7",["Mo 1 - 4 Kiki","Kiki wins the duel! 🏆"]]],
  hint:`let seed = 1;\nlet moWins = 0;\nlet kikiWins = 0;\nfor (let i = 0; i < 5; i++) {\n  const mo = roll();\n  const kiki = roll();\n  if (mo > kiki) moWins++;\n  if (kiki > mo) kikiWins++;\n}\nconsole.log("Mo " + moWins + " - " + kikiWins + " Kiki");\nif (moWins > kikiWins) console.log("Mo wins the duel! 🏆");\nelse if (kikiWins > moWins) console.log("Kiki wins the duel! 🏆");\nelse console.log("It's a draw!");\n\n`+DICE},
 {type:"code",title:"Step 3: health battle",body:`<p>Now both start with 20 hp. Each round, the lower roll loses hp equal to the difference (a tie does nothing). The loop is ready: fill in the damage, then the winner prints itself.</p>`,start:`let seed = 1;\nlet moHp = 20;\nlet kikiHp = 20;\nlet rounds = 0;\nwhile (moHp > 0 && kikiHp > 0) {\n  const mo = roll();\n  const kiki = roll();\n  // the lower roll loses hp\n  rounds++;\n}\nconst winner = moHp > 0 ? "Mo" : "Kiki";\nconsole.log(winner + " wins after " + rounds + " rounds!");\n\n`+DICE,
  use:[[/Hp\s*-=/,"Lower the loser's hp with -=."]],out:["Kiki wins after 18 rounds!"],variants:[[/seed = 1/,"seed = 2024",["Kiki wins after 25 rounds!"]]],
  hint:`let seed = 1;\nlet moHp = 20;\nlet kikiHp = 20;\nlet rounds = 0;\nwhile (moHp > 0 && kikiHp > 0) {\n  const mo = roll();\n  const kiki = roll();\n  if (mo > kiki) kikiHp -= mo - kiki;\n  if (kiki > mo) moHp -= kiki - mo;\n  rounds++;\n}\nconst winner = moHp > 0 ? "Mo" : "Kiki";\nconsole.log(winner + " wins after " + rounds + " rounds!");\n\n`+DICE},
 {type:"done"}]}
]},
{name:"Grids & maps",lessons:[
{id:"g5",title:"Drawing a board",sub:"2D arrays become game maps",steps:[
 {type:"talk",title:"A map is a grid",
  body:`<p>Lots of games happen on a grid: chess, Minesweeper, Pokémon maps. An array of strings is the easiest way to draw one. Each string is a row; each character is a tile.</p>`,
  demo:`const map = [\n  "#######",\n  "#.....#",\n  "#..@..#",\n  "#.....#",\n  "#######"\n];\nfor (const row of map) console.log(row);`,
  say:"# is a wall, . is floor, @ is you. Old-school games looked exactly like this!"},
 {type:"talk",title:"Arrays of arrays",mood:"think",
  body:`<p>Strings can't be changed in place, so for a map that changes, split each row into an array of tiles. ${C("grid[y][x]")} is the tile in row y, column x. ${C(".join(\"\")")} glues a row back for printing.</p>`,
  demo:`const grid = [\n  "....".split(""),\n  "....".split(""),\n  "....".split("")\n];\ngrid[1][2] = "@";\ngrid[0][0] = "$";\nfor (const row of grid) console.log(row.join(""));`,
  say:"y goes down the rows, x goes across the columns."},
 {type:"talk",title:"Building a grid with loops",
  body:`<p>Make an empty grid of any size with two loops. A border check turns the edges into walls.</p>`,
  demo:`function makeRoom(w, h) {\n  const g = [];\n  for (let y = 0; y < h; y++) {\n    const row = [];\n    for (let x = 0; x < w; x++) {\n      const edge = x === 0 || y === 0 || x === w - 1 || y === h - 1;\n      row.push(edge ? "#" : ".");\n    }\n    g.push(row);\n  }\n  return g;\n}\nfor (const row of makeRoom(6, 4)) console.log(row.join(""));`,
  say:"A 6 by 4 room with walls all around."},
 {type:"quiz",q:"In grid[y][x], what is y?",opts:["The row (going down)","The column (going across)","The tile's letter"],a:0,why:"The first index picks the row, the second picks the spot in that row."},
 {type:"quiz",q:"What does this print?",code:`const g = ["abc", "def"];\nconsole.log(g[1][0]);`,opts:["d","b","a"],a:0,mono:true,why:"Row 1 is \"def\", and position 0 in it is d."},
 {type:"fill",title:"Place the treasure",body:`<p>Put a ${C("$")} in row 0, column 2.</p>`,code:`const grid = ["...".split(""), "...".split("")];\nconst row = [0];\nconst col = [1];\ngrid[row][col] = "$";\nconsole.log(grid.map(r => r.join("")).join(" "));`,blanks:["0","2"],tokens:["0","2","1","3"],why:"grid[row][column]."},
 {type:"code",title:"Checkerboard",body:`<p>Print a ${C("size")} × ${C("size")} checkerboard: ${C("#")} where x + y is even, ${C(".")} where it's odd.</p>`,start:`const size = 4;\n// your loops here\n`,
  use:[[/%\s*2/,"Use (x + y) % 2 to alternate."]],out:["#.#.",".#.#","#.#.",".#.#"],variants:[[/size = 4/,"size = 3",["#.#",".#.","#.#"]]],
  hint:`const size = 4;\nfor (let y = 0; y < size; y++) {\n  let row = "";\n  for (let x = 0; x < size; x++) {\n    row += (x + y) % 2 === 0 ? "#" : ".";\n  }\n  console.log(row);\n}`},
 {type:"code",title:"Count the coins",body:`<p>Count every ${C("$")} on the map and print ${C("Coins: 4")}.</p>`,start:`const map = [\n  "#$..#",\n  "#.$$#",\n  "#..$#"\n];\n// count them\n`,
  use:[[/for\s*\(/,"Loop over the rows and characters."]],out:["Coins: 4"],variants:[[/"#\.\.\$#"/,"\"#$.$#\"",["Coins: 5"]]],
  hint:`const map = [\n  "#$..#",\n  "#.$$#",\n  "#..$#"\n];\nlet coins = 0;\nfor (const row of map) {\n  for (const tile of row) {\n    if (tile === "$") coins++;\n  }\n}\nconsole.log("Coins: " + coins);`},
 {type:"game"},{type:"done"}],
 pool:[
  [`const g = ["ab", "cd"];\nconsole.log(g[0][1]);`,["b","c","a"]],
  [`const g = ["ab", "cd"];\nconsole.log(g.length);`,["2","4","1"]],
  [`console.log(["x", "y", "z"].join(""));`,["xyz","x,y,z","x y z"]],
  [`const r = "..#".split("");\nr[0] = "@";\nconsole.log(r.join(""));`,["@.#","..#","@..#"]],
  [`console.log("#".repeat(3) + ".".repeat(2));`,["###..","#.#.#","##..."]],
  [`const g = [[1, 2], [3, 4]];\nconsole.log(g[1][1] + g[0][0]);`,["5","3","7"]]
 ]},
{id:"g6",title:"Moving around",sub:"position, directions and walls",steps:[
 {type:"talk",title:"Where are you?",
  body:`<p>The player's position is just two numbers: ${C("x")} and ${C("y")}. Moving right adds 1 to x; moving down adds 1 to y (rows count downwards).</p>`,
  demo:`const player = { x: 1, y: 1 };\nconst moves = "RRD";\nfor (const m of moves) {\n  if (m === "R") player.x++;\n  if (m === "L") player.x--;\n  if (m === "D") player.y++;\n  if (m === "U") player.y--;\n}\nconsole.log(player.x + "," + player.y);`,
  say:"Two rights and one down: 3,2."},
 {type:"talk",title:"A direction table",mood:"think",
  body:`<p>Instead of four ifs, keep a table of how each direction changes x and y. This trick is in almost every grid game.</p>`,
  demo:`const DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nlet x = 2, y = 2;\nfor (const m of "UULR") {\n  const [dx, dy] = DIRS[m];\n  x += dx;\n  y += dy;\n}\nconsole.log(x + "," + y);`,
  say:"Up twice, left, right: 2,0."},
 {type:"talk",title:"Bumping into walls",mood:"oops",
  body:`<p>Before moving, look at the tile you're about to step on. If it's a wall, stay put. That's <b>collision detection</b>.</p>`,
  demo:`const map = [\n  "#####",\n  "#..##",\n  "#...#",\n  "#####"\n];\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nlet x = 1, y = 1;\nfor (const m of "RRRD") {\n  const [dx, dy] = DIRS[m];\n  if (map[y + dy][x + dx] === "#") {\n    console.log(m + ": bonk!");\n  } else {\n    x += dx;\n    y += dy;\n    console.log(m + ": now at " + x + "," + y);\n  }\n}`,
  say:"The second R hits a wall, so does the third. Then D works."},
 {type:"quiz",q:"The player is at x 3, y 5. They move U. Where are they now?",opts:["3,4","3,6","2,5"],a:0,mono:true,why:"Up means one row higher on screen, which is y - 1."},
 {type:"quiz",q:"What does this print?",code:`let x = 0;\nfor (const m of "RRLR") x += m === "R" ? 1 : -1;\nconsole.log(x);`,opts:["2","4","0"],a:0,mono:true,why:"+1 +1 -1 +1 = 2."},
 {type:"fill",title:"Check for walls",body:`<p>Only move if the next tile isn't a wall.</p>`,code:`const row = "#..#";\nlet x = 1;\nfor (const m of "RR") {\n  if (row[x + 1] [0] "#") x++;\n}\nconsole.log(x);`,blanks:["!=="],tokens:["!==","===","<"],why:"!== means \"is not\". The second R bumps into the wall."},
 {type:"code",title:"Robot walk",body:`<p>The robot starts at 0,0. Follow ${C("moves")} using the direction table, then print where it ends up like ${C("2,-1")}.</p>`,start:`const DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nconst moves = "RRUDU";\nlet x = 0, y = 0;\n// your code here\n`,
  use:[[/DIRS\s*\[/,"Look up each move in DIRS."]],out:["2,-1"],variants:[[/"RRUDU"/,"\"LLLD\"",["-3,1"]]],
  hint:`const DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nconst moves = "RRUDU";\nlet x = 0, y = 0;\nfor (const m of moves) {\n  const [dx, dy] = DIRS[m];\n  x += dx;\n  y += dy;\n}\nconsole.log(x + "," + y);`},
 {type:"code",title:"Walls and bumps",body:`<p>Walk through the map. Skip any move into a ${C("#")} and count the bumps. Print the final position and bumps like ${C("3,2 bumps: 2")}.</p>`,start:`const map = [\n  "######",\n  "#..#.#",\n  "#....#",\n  "######"\n];\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nlet x = 1, y = 1, bumps = 0;\nconst moves = "RRDRRU";\n// your code here\n`,
  use:[[/===\s*"#"|!==\s*"#"/,"Check the next tile for \"#\"."]],out:["4,1 bumps: 1"],variants:[[/"RRDRRU"/,"\"DDRR\"",["3,2 bumps: 1"]]],
  hint:`const map = [\n  "######",\n  "#..#.#",\n  "#....#",\n  "######"\n];\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nlet x = 1, y = 1, bumps = 0;\nconst moves = "RRDRRU";\nfor (const m of moves) {\n  const [dx, dy] = DIRS[m];\n  if (map[y + dy][x + dx] === "#") {\n    bumps++;\n  } else {\n    x += dx;\n    y += dy;\n  }\n}\nconsole.log(x + "," + y + " bumps: " + bumps);`},
 {type:"game"},{type:"done"}],
 pool:[
  [`let y = 4;\nfor (const m of "UUD") y += m === "D" ? 1 : -1;\nconsole.log(y);`,["3","5","2"]],
  [`const D = { R: [1, 0] };\nconst [dx, dy] = D.R;\nconsole.log(dx + dy);`,["1","0","10"]],
  [`const row = "#.#";\nconsole.log(row[1] === "#");`,["false","true","."]],
  [`let x = 1, y = 1;\nx += 2;\ny -= 1;\nconsole.log(x + "," + y);`,["3,0","3,2","1,1"]],
  [`const map = ["###", "#.#"];\nconsole.log(map[1][1]);`,[".","#","undefined"]]
 ]},
{id:"g7",title:"Project: Treasure Hunt",sub:"a map, a player and coins to collect",project:true,steps:[
 {type:"talk",title:"Treasure Hunt",mood:"cheer",
  body:`<p>You'll build a tiny exploration game: draw the map with the player on it, walk around collecting coins, and win when you reach the exit ${C("E")}.</p>`,
  say:"Grab every coin you can!"},
 {type:"code",title:"Step 1: draw the map",body:`<p>Write ${C("draw(map, px, py)")} that prints each row, but with ${C("@")} where the player is.</p>`,start:`const map = [\n  "#######",\n  "#.$..$#",\n  "#..#..#",\n  "#$...E#",\n  "#######"\n];\n\nfunction draw(map, px, py) {\n  // your code here\n}\n\ndraw(map, 1, 1);\n`,
  use:[[/@/,"Print \"@\" at the player's spot."]],out:["#######","#@$..$#","#..#..#","#$...E#","#######"],variants:[[/draw\(map, 1, 1\)/,"draw(map, 2, 2)",["#######","#.$..$#","#.@#..#","#$...E#","#######"]]],
  hint:`const map = [\n  "#######",\n  "#.$..$#",\n  "#..#..#",\n  "#$...E#",\n  "#######"\n];\n\nfunction draw(map, px, py) {\n  for (let y = 0; y < map.length; y++) {\n    let row = "";\n    for (let x = 0; x < map[y].length; x++) {\n      row += x === px && y === py ? "@" : map[y][x];\n    }\n    console.log(row);\n  }\n}\n\ndraw(map, 1, 1);`},
 {type:"code",title:"Step 2: collect coins",body:`<p>Walk the ${C("moves")}. Walls block you. Stepping on ${C("$")} collects it (turn that tile into ${C(".")} so it can't be collected twice). Print ${C("Coins: N")} at the end.</p>`,start:`const map = [\n  "#######",\n  "#.$..$#",\n  "#..#..#",\n  "#$...E#",\n  "#######"\n].map(r => r.split(""));\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nlet x = 1, y = 1, coins = 0;\nconst moves = "RRRRLLLLDDL";\n// your code here\n`,
  use:[[/"\$"/,"Check for \"$\" tiles."],[/=\s*"\."/,"Turn a collected coin into \".\"."]],out:["Coins: 3"],variants:[[/"RRRRLLLLDDL"/,"\"RLRL\"",["Coins: 1"]]],
  hint:`const map = [\n  "#######",\n  "#.$..$#",\n  "#..#..#",\n  "#$...E#",\n  "#######"\n].map(r => r.split(""));\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nlet x = 1, y = 1, coins = 0;\nconst moves = "RRRRLLLLDDL";\nfor (const m of moves) {\n  const [dx, dy] = DIRS[m];\n  if (map[y + dy][x + dx] === "#") continue;\n  x += dx;\n  y += dy;\n  if (map[y][x] === "$") {\n    coins++;\n    map[y][x] = ".";\n  }\n}\nconsole.log("Coins: " + coins);`},
 {type:"code",title:"Step 3: find the exit",body:`<p>Add a win: when you step on ${C("E")}, print ${C("Escaped with N coins in M moves!")} and stop. If the moves run out first, print ${C("Still lost...")}.</p>`,start:`const map = [\n  "#######",\n  "#.$..$#",\n  "#..#..#",\n  "#$...E#",\n  "#######"\n].map(r => r.split(""));\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nlet x = 1, y = 1, coins = 0, steps = 0;\nconst moves = "RRRRDDRRR";\nfor (const m of moves) {\n  const [dx, dy] = DIRS[m];\n  if (map[y + dy][x + dx] === "#") continue;\n  x += dx;\n  y += dy;\n  if (map[y][x] === "$") {\n    coins++;\n    map[y][x] = ".";\n  }\n}\nconsole.log("Coins: " + coins);\n`,
  use:[[/"E"/,"Check for the exit tile \"E\"."],[/break|return/,"Stop the game when you escape."]],out:["Escaped with 2 coins in 6 moves!"],variants:[[/"RRRRDDRRR"/,"\"DDRR\"",["Still lost..."]]],
  hint:`const map = [\n  "#######",\n  "#.$..$#",\n  "#..#..#",\n  "#$...E#",\n  "#######"\n].map(r => r.split(""));\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nlet x = 1, y = 1, coins = 0, steps = 0;\nconst moves = "RRRRDDRRR";\nlet escaped = false;\nfor (const m of moves) {\n  steps++;\n  const [dx, dy] = DIRS[m];\n  if (map[y + dy][x + dx] === "#") continue;\n  x += dx;\n  y += dy;\n  if (map[y][x] === "$") {\n    coins++;\n    map[y][x] = ".";\n  }\n  if (map[y][x] === "E") {\n    escaped = true;\n    break;\n  }\n}\nif (escaped) console.log("Escaped with " + coins + " coins in " + steps + " moves!");\nelse console.log("Still lost...");`},
 {type:"done"}]}
]},
{name:"Classic games",lessons:[
{id:"g8",title:"Guess the number",sub:"hints, tries and replay",steps:[
 {type:"talk",title:"The oldest computer game",
  body:`<p>One of the first games people ever wrote: the computer picks a secret number and you guess, getting <b>higher</b> or <b>lower</b> hints. We'll feed in the guesses as a list.</p>`,
  demo:`const secret = 37;\nconst guesses = [50, 25, 37];\nfor (const g of guesses) {\n  if (g < secret) console.log(g + " is too low");\n  else if (g > secret) console.log(g + " is too high");\n  else console.log(g + " is right!");\n}`,
  say:"too high, too low, right!"},
 {type:"talk",title:"The smart way to guess",mood:"think",
  body:`<p>The best strategy is to always guess the middle of what's left. That's called <b>binary search</b>, and it finds any number from 1 to 100 in at most 7 guesses. Here the computer plays against itself.</p>`,
  demo:`const secret = 73;\nlet lo = 1, hi = 100, tries = 0;\nwhile (true) {\n  const guess = Math.floor((lo + hi) / 2);\n  tries++;\n  console.log("Guess " + tries + ": " + guess);\n  if (guess === secret) break;\n  if (guess < secret) lo = guess + 1;\n  else hi = guess - 1;\n}`,
  say:"Found in 6 guesses."},
 {type:"quiz",q:"The secret is 40 and you guess 55. What hint should you get?",opts:["Too high","Too low","Correct"],a:0,why:"55 is bigger than 40."},
 {type:"quiz",q:"Using the always-guess-the-middle trick, what's your first guess for 1 to 100?",opts:["50","1","25"],a:0,mono:true,why:"Math.floor((1 + 100) / 2) is 50."},
 {type:"fill",title:"Give a hint",body:`<p>Finish the hint.</p>`,code:`const secret = 8;\nconst g = 3;\nconsole.log(g [0] secret ? "higher!" : "lower!");`,blanks:["<"],tokens:["<",">","==="],why:"If the guess is smaller, tell them to go higher."},
 {type:"code",title:"Guessing game",body:`<p>Go through the guesses. Print ${C("Too low")} or ${C("Too high")} for wrong ones. When a guess is right, print ${C("Got it in N tries!")} and stop. If none are right, print ${C("The number was S")}.</p>`,start:`const secret = 42;\nconst guesses = [50, 30, 42, 41];\n// your code here\n`,
  use:[[/break|return/,"Stop once they get it."]],out:["Too high","Too low","Got it in 3 tries!"],variants:[[/42, 41/,"40, 41",["Too high","Too low","Too low","Too low","The number was 42"]]],
  hint:`const secret = 42;\nconst guesses = [50, 30, 42, 41];\nlet tries = 0, won = false;\nfor (const g of guesses) {\n  tries++;\n  if (g < secret) console.log("Too low");\n  else if (g > secret) console.log("Too high");\n  else {\n    console.log("Got it in " + tries + " tries!");\n    won = true;\n    break;\n  }\n}\nif (!won) console.log("The number was " + secret);`},
 {type:"game"},{type:"done"}],
 pool:[
  [`console.log(Math.floor((1 + 10) / 2));`,["5","5.5","6"]],
  [`const s = 7, g = 9;\nconsole.log(g > s ? "lower" : "higher");`,["lower","higher","9"]],
  [`let lo = 1, hi = 20;\nconst g = Math.floor((lo + hi) / 2);\nlo = g + 1;\nconsole.log(lo);`,["11","10","21"]],
  [`let t = 0;\nfor (const g of [5, 9, 7]) {\n  t++;\n  if (g === 9) break;\n}\nconsole.log(t);`,["2","3","1"]]
 ]},
{id:"g9",title:"Hangman",sub:"hidden letters and lives",steps:[
 {type:"talk",title:"Showing the hidden word",
  body:`<p>Keep the guessed letters in a ${C("Set")}. To show the word, swap each letter for itself if it's been guessed, or ${C("_")} if not.</p>`,
  demo:`const word = "banana";\nconst guessed = new Set(["a", "n"]);\nlet shown = "";\nfor (const ch of word) {\n  shown += guessed.has(ch) ? ch : "_";\n}\nconsole.log(shown);`,
  say:"_anana. We haven't guessed b yet."},
 {type:"talk",title:"Lives",mood:"oops",
  body:`<p>A wrong guess costs a life. The game ends when you run out of lives, or when there are no ${C("_")} left in the shown word.</p>`,
  demo:`const word = "kiwi";\nconst guessed = new Set();\nlet lives = 3;\nfor (const g of ["e", "i", "z", "k"]) {\n  guessed.add(g);\n  if (!word.includes(g)) lives--;\n  let shown = "";\n  for (const ch of word) shown += guessed.has(ch) ? ch : "_";\n  console.log(g + ": " + shown + "  lives " + lives);\n}`,
  say:"Two misses, so 1 life left, and we still need the w."},
 {type:"quiz",q:"What does this print?",code:`const s = new Set(["a"]);\ns.add("a");\ns.add("b");\nconsole.log(s.size);`,opts:["2","3","1"],a:0,mono:true,why:"A Set ignores duplicates."},
 {type:"quiz",q:"How do you know the player has guessed the whole word?",opts:["The shown word has no _ left","lives is 0","guessed.size is the word's length"],a:0,why:"If every letter is showing, they've won."},
 {type:"fill",title:"Mask the word",body:`<p>Show guessed letters, hide the rest.</p>`,code:`const word = "ook";\nconst guessed = new Set(["o"]);\nlet shown = "";\nfor (const ch of word) shown += guessed.[0](ch) ? ch : "_";\nconsole.log(shown);`,blanks:["has"],tokens:["has","includes","get","add"],why:"Sets use .has() to check."},
 {type:"code",title:"Full hangman",body:`<p>Play through ${C("guesses")} with 4 lives. After each guess print the shown word. Stop when the word is solved (print ${C("You win!")}) or lives hit 0 (print ${C("Out of lives! It was WORD")}).</p>`,start:`const word = "mango";\nconst guesses = ["a", "e", "o", "m", "x", "n", "g"];\nconst guessed = new Set();\nlet lives = 4;\n// your code here\n`,
  use:[[/lives--|lives\s*-=/,"Lose a life for a wrong guess."],[/includes\s*\(\s*"_"\s*\)|indexOf/,"Check if any _ are left."]],out:["_a___","_a___","_a__o","ma__o","ma__o","man_o","mango","You win!"],variants:[[/"x", "n", "g"/,"\"x\", \"y\", \"z\"",["_a___","_a___","_a__o","ma__o","ma__o","ma__o","ma__o","Out of lives! It was mango"]]],
  hint:`const word = "mango";\nconst guesses = ["a", "e", "o", "m", "x", "n", "g"];\nconst guessed = new Set();\nlet lives = 4;\nfor (const g of guesses) {\n  guessed.add(g);\n  if (!word.includes(g)) lives--;\n  let shown = "";\n  for (const ch of word) shown += guessed.has(ch) ? ch : "_";\n  console.log(shown);\n  if (!shown.includes("_")) {\n    console.log("You win!");\n    break;\n  }\n  if (lives === 0) {\n    console.log("Out of lives! It was " + word);\n    break;\n  }\n}`},
 {type:"game"},{type:"done"}],
 pool:[
  [`const s = new Set(["x"]);\nconsole.log(s.has("y"));`,["false","true","x"]],
  [`console.log("kiwi".includes("w"));`,["true","false","2"]],
  [`let out = "";\nfor (const c of "aba") out += c === "a" ? c : "_";\nconsole.log(out);`,["a_a","_b_","aba"]],
  [`console.log("_a_".includes("_"));`,["true","false","1"]],
  [`const s = new Set();\nfor (const c of "hello") s.add(c);\nconsole.log(s.size);`,["4","5","3"]]
 ]},
{id:"g10",title:"Tic-tac-toe",sub:"a board, turns and finding a winner",steps:[
 {type:"talk",title:"The board",
  body:`<p>Store the 9 squares in one array, numbered 0 to 8 across the rows. Print it 3 at a time.</p>`,
  demo:`const board = ["X", "O", "X", " ", "X", " ", "O", " ", " "];\nfunction show(b) {\n  for (let r = 0; r < 3; r++) {\n    console.log(b[r * 3] + "|" + b[r * 3 + 1] + "|" + b[r * 3 + 2]);\n  }\n}\nshow(board);`,
  say:"Square r*3 + c is row r, column c."},
 {type:"talk",title:"Every way to win",mood:"think",
  body:`<p>There are exactly 8 winning lines: 3 rows, 3 columns, 2 diagonals. List them once, then check each: a line wins if all 3 squares match and aren't empty.</p>`,
  demo:`const LINES = [\n  [0, 1, 2], [3, 4, 5], [6, 7, 8],\n  [0, 3, 6], [1, 4, 7], [2, 5, 8],\n  [0, 4, 8], [2, 4, 6]\n];\nfunction winner(b) {\n  for (const [a, c, d] of LINES) {\n    if (b[a] !== " " && b[a] === b[c] && b[a] === b[d]) return b[a];\n  }\n  return null;\n}\nconsole.log(winner(["X", "O", " ", "O", "X", " ", " ", " ", "X"]));\nconsole.log(winner(["X", "O", " ", " ", " ", " ", " ", " ", " "]));`,
  say:"X wins on the diagonal, and the second board has no winner yet: null."},
 {type:"talk",title:"Taking turns",
  body:`<p>Switch players after every move: ${C('player = player === "X" ? "O" : "X"')}. If all 9 squares are full and no one won, it's a draw.</p>`,
  demo:`const board = Array(9).fill(" ");\nlet player = "X";\nfor (const sq of [4, 0, 8]) {\n  board[sq] = player;\n  player = player === "X" ? "O" : "X";\n}\nconsole.log(board.join(""));\nconsole.log("Next: " + player);`,
  say:"X in the middle, O in the corner, X in the other corner. O is up next."},
 {type:"quiz",q:"Which square number is row 2, column 1?",opts:["7","5","3"],a:0,mono:true,why:"2 × 3 + 1 = 7."},
 {type:"quiz",q:"How many ways are there to win tic-tac-toe?",opts:["8","6","9"],a:0,why:"3 rows + 3 columns + 2 diagonals."},
 {type:"fill",title:"Switch players",body:`<p>Flip between X and O.</p>`,code:`let p = "X";\np = p === "X" [0] "O" [1] "X";\nconsole.log(p);`,blanks:["?",":"],tokens:["?",":","||","&&"],why:"The ternary: condition ? if true : if false."},
 {type:"code",title:"Who won?",body:`<p>Finish ${C("winner(b)")}: return ${C("X")} or ${C("O")} if they have a line, ${C("draw")} if the board is full with no winner, otherwise ${C("none")}.</p>`,start:`const LINES = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];\n\nfunction winner(b) {\n  // your code here\n}\n\nconsole.log(winner("XXXOO    ".split("")));\nconsole.log(winner("XOXXOOOXX".split("")));\nconsole.log(winner("XO       ".split("")));\nconsole.log(winner("OX OX O  ".split("")));\n`,
  use:[[/LINES/,"Check every line in LINES."],[/includes\s*\(\s*" "\s*\)|every|indexOf/,"Check whether the board is full."]],out:["X","draw","none","O"],
  hint:`const LINES = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];\n\nfunction winner(b) {\n  for (const [a, c, d] of LINES) {\n    if (b[a] !== " " && b[a] === b[c] && b[a] === b[d]) return b[a];\n  }\n  return b.includes(" ") ? "none" : "draw";\n}\n\nconsole.log(winner("XXXOO    ".split("")));\nconsole.log(winner("XOXXOOOXX".split("")));\nconsole.log(winner("XO       ".split("")));\nconsole.log(winner("OX OX O  ".split("")));`},
 {type:"game"},{type:"done"}],
 pool:[
  [`const b = "XO X     ".split("");\nconsole.log(b[3]);`,["X"," ","O"]],
  [`console.log(1 * 3 + 2);`,["5","6","3"]],
  [`let p = "O";\np = p === "X" ? "O" : "X";\nconsole.log(p);`,["X","O","XO"]],
  [`const b = Array(9).fill(" ");\nb[4] = "X";\nconsole.log(b.filter(s => s === " ").length);`,["8","9","1"]],
  [`const b = "XXX      ".split("");\nconsole.log(b[0] === b[1] && b[1] === b[2]);`,["true","false","X"]]
 ]},
{id:"g11",title:"Project: Tic-tac-toe referee",sub:"play whole games from a list of moves",project:true,steps:[
 {type:"talk",title:"Be the referee",mood:"cheer",
  body:`<p>You'll write a referee that plays a whole game from a list of square numbers, refuses illegal moves, announces the winner, and then plays a <b>tournament</b>.</p>`,
  say:"Referees have to know every rule!"},
 {type:"code",title:"Step 1: play a game",body:`<p>Finish ${C("play(moves)")}: X goes first and players alternate. After each move check for a winner and return ${C("X wins")} / ${C("O wins")} right away. If the moves run out, return ${C("draw")} when the board is full, otherwise ${C("unfinished")}.</p>`,start:`const LINES = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];\nfunction winner(b) {\n  for (const [a, c, d] of LINES) {\n    if (b[a] !== " " && b[a] === b[c] && b[a] === b[d]) return b[a];\n  }\n  return null;\n}\n\nfunction play(moves) {\n  const board = Array(9).fill(" ");\n  let player = "X";\n  // your code here\n}\n\nconsole.log(play([4, 0, 2, 6, 3, 5, 1, 7, 8]));\nconsole.log(play([0, 3, 1, 4, 2]));\nconsole.log(play([4, 0, 8, 2, 1, 7, 6, 3, 5]));\nconsole.log(play([4, 0]));\n`,
  use:[[/winner\s*\(\s*board\s*\)/,"Call winner(board) after each move."]],out:["draw","X wins","draw","unfinished"],variants:[[/play\(\[0, 3, 1, 4, 2\]\)/,"play([0, 3, 1, 4, 8, 5])",["draw","O wins","draw","unfinished"]]],
  hint:`const LINES = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];\nfunction winner(b) {\n  for (const [a, c, d] of LINES) {\n    if (b[a] !== " " && b[a] === b[c] && b[a] === b[d]) return b[a];\n  }\n  return null;\n}\n\nfunction play(moves) {\n  const board = Array(9).fill(" ");\n  let player = "X";\n  for (const sq of moves) {\n    board[sq] = player;\n    const w = winner(board);\n    if (w) return w + " wins";\n    player = player === "X" ? "O" : "X";\n  }\n  return board.includes(" ") ? "unfinished" : "draw";\n}\n\nconsole.log(play([4, 0, 2, 6, 3, 5, 1, 7, 8]));\nconsole.log(play([0, 3, 1, 4, 2]));\nconsole.log(play([4, 0, 8, 2, 1, 7, 6, 3, 5]));\nconsole.log(play([4, 0]));`},
 {type:"code",title:"Step 2: no cheating",body:`<p>If a move picks a square that's already taken, return ${C("illegal move by X at 4")} (with the right player and square).</p>`,start:`const LINES = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];\nfunction winner(b) {\n  for (const [a, c, d] of LINES) {\n    if (b[a] !== " " && b[a] === b[c] && b[a] === b[d]) return b[a];\n  }\n  return null;\n}\n\nfunction play(moves) {\n  const board = Array(9).fill(" ");\n  let player = "X";\n  for (const sq of moves) {\n    board[sq] = player;\n    const w = winner(board);\n    if (w) return w + " wins";\n    player = player === "X" ? "O" : "X";\n  }\n  return board.includes(" ") ? "unfinished" : "draw";\n}\n\nconsole.log(play([4, 4]));\nconsole.log(play([0, 1, 2, 0]));\nconsole.log(play([0, 3, 1, 4, 2]));\n`,
  use:[[/!==\s*" "|===\s*"X"|===\s*"O"/,"Check whether the square is already taken."]],out:["illegal move by O at 4","illegal move by O at 0","X wins"],
  hint:`const LINES = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];\nfunction winner(b) {\n  for (const [a, c, d] of LINES) {\n    if (b[a] !== " " && b[a] === b[c] && b[a] === b[d]) return b[a];\n  }\n  return null;\n}\n\nfunction play(moves) {\n  const board = Array(9).fill(" ");\n  let player = "X";\n  for (const sq of moves) {\n    if (board[sq] !== " ") return "illegal move by " + player + " at " + sq;\n    board[sq] = player;\n    const w = winner(board);\n    if (w) return w + " wins";\n    player = player === "X" ? "O" : "X";\n  }\n  return board.includes(" ") ? "unfinished" : "draw";\n}\n\nconsole.log(play([4, 4]));\nconsole.log(play([0, 1, 2, 0]));\nconsole.log(play([0, 3, 1, 4, 2]));`},
 {type:"code",title:"Step 3: tournament",body:`<p>${C("games")} holds several games. Play them all and count wins for X, O and draws. Print ${C("X: 2  O: 1  Draws: 1")}.</p>`,start:`const LINES = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];\nfunction winner(b) {\n  for (const [a, c, d] of LINES) {\n    if (b[a] !== " " && b[a] === b[c] && b[a] === b[d]) return b[a];\n  }\n  return null;\n}\nfunction play(moves) {\n  const board = Array(9).fill(" ");\n  let player = "X";\n  for (const sq of moves) {\n    board[sq] = player;\n    const w = winner(board);\n    if (w) return w;\n    player = player === "X" ? "O" : "X";\n  }\n  return "draw";\n}\n\nconst games = [\n  [0, 3, 1, 4, 2],\n  [4, 0, 2, 6, 3, 5, 1, 7, 8],\n  [0, 3, 1, 4, 8, 5],\n  [6, 0, 7, 1, 8]\n];\n// count the results and print them\n`,
  use:[[/for\s*\(/,"Loop over the games."]],out:["X: 2  O: 1  Draws: 1"],variants:[[/\[6, 0, 7, 1, 8\]/,"[4, 0, 8, 2, 1, 7, 6, 3, 5]",["X: 1  O: 1  Draws: 2"]]],
  hint:`const LINES = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];\nfunction winner(b) {\n  for (const [a, c, d] of LINES) {\n    if (b[a] !== " " && b[a] === b[c] && b[a] === b[d]) return b[a];\n  }\n  return null;\n}\nfunction play(moves) {\n  const board = Array(9).fill(" ");\n  let player = "X";\n  for (const sq of moves) {\n    board[sq] = player;\n    const w = winner(board);\n    if (w) return w;\n    player = player === "X" ? "O" : "X";\n  }\n  return "draw";\n}\n\nconst games = [\n  [0, 3, 1, 4, 2],\n  [4, 0, 2, 6, 3, 5, 1, 7, 8],\n  [0, 3, 1, 4, 8, 5],\n  [6, 0, 7, 1, 8]\n];\nconst score = { X: 0, O: 0, draw: 0 };\nfor (const g of games) score[play(g)]++;\nconsole.log("X: " + score.X + "  O: " + score.O + "  Draws: " + score.draw);`},
 {type:"done"}]}
]},
{name:"Bigger games",lessons:[
{id:"g12",title:"Characters with classes",sub:"heroes, monsters and attacks",steps:[
 {type:"talk",title:"A class for every character",
  body:`<p>A ${C("class")} is a blueprint for characters. Each one gets its own name and hp, and they all share the same methods.</p>`,
  demo:`class Fighter {\n  constructor(name, hp, power) {\n    this.name = name;\n    this.hp = hp;\n    this.power = power;\n  }\n  attack(target) {\n    target.hp = Math.max(0, target.hp - this.power);\n    console.log(this.name + " hits " + target.name + " for " + this.power + " (" + target.hp + " left)");\n  }\n  get alive() {\n    return this.hp > 0;\n  }\n}\n\nconst mo = new Fighter("Mo", 12, 4);\nconst slime = new Fighter("Slime", 7, 2);\nmo.attack(slime);\nslime.attack(mo);\nmo.attack(slime);\nconsole.log(slime.alive);`,
  say:"get alive lets you write slime.alive without parentheses."},
 {type:"talk",title:"Special types with extends",mood:"cheer",
  body:`<p>${C("extends")} makes a special kind of character that changes some behavior. Here a Mage's attack ignores half of... well, it just hits twice as hard every third turn.</p>`,
  demo:`class Fighter {\n  constructor(name, hp, power) {\n    this.name = name;\n    this.hp = hp;\n    this.power = power;\n  }\n  damage() {\n    return this.power;\n  }\n}\n\nclass Mage extends Fighter {\n  constructor(name, hp, power) {\n    super(name, hp, power);\n    this.turns = 0;\n  }\n  damage() {\n    this.turns++;\n    return this.turns % 3 === 0 ? this.power * 2 : this.power;\n  }\n}\n\nconst m = new Mage("Kiki", 8, 3);\nconst hits = [];\nfor (let i = 0; i < 6; i++) hits.push(m.damage());\nconsole.log(hits.join(" "));`,
  say:"3 3 6 3 3 6. Every third spell is a big one."},
 {type:"quiz",q:"What does this print?",code:`class C {\n  constructor(n) { this.n = n; }\n  double() { this.n *= 2; }\n}\nconst c = new C(3);\nc.double();\nc.double();\nconsole.log(c.n);`,opts:["12","6","3"],a:0,mono:true,why:"3 → 6 → 12."},
 {type:"quiz",q:"What does super(...) do in a child class's constructor?",opts:["Runs the parent's constructor","Makes the class faster","Copies another object"],a:0,why:"It sets up everything the parent class needs."},
 {type:"fill",title:"Make a hero",body:`<p>Create a hero and attack.</p>`,code:`class Hero {\n  constructor(name) {\n    [0].name = name;\n  }\n}\nconst h = [1] Hero("Bao");\nconsole.log(h.name);`,blanks:["this","new"],tokens:["this","new","self","make"],why:"this.name stores it on the object; new makes one."},
 {type:"code",title:"Healer",body:`<p>Make ${C("Healer")} extend ${C("Fighter")} with a ${C("heal(friend)")} method that adds 5 hp (up to ${C("friend.maxHp")}) and prints ${C("Ivy heals Mo to 10")}.</p>`,start:`class Fighter {\n  constructor(name, hp) {\n    this.name = name;\n    this.hp = hp;\n    this.maxHp = hp;\n  }\n}\n\n// write Healer here\n\nconst mo = new Fighter("Mo", 12);\nmo.hp = 5;\nconst ivy = new Healer("Ivy", 8);\nivy.heal(mo);\nivy.heal(mo);\n`,
  use:[[/class\s+Healer\s+extends\s+Fighter/,"Start with class Healer extends Fighter."],[/Math\.min/,"Use Math.min so hp never passes maxHp."]],out:["Ivy heals Mo to 10","Ivy heals Mo to 12"],
  hint:`class Fighter {\n  constructor(name, hp) {\n    this.name = name;\n    this.hp = hp;\n    this.maxHp = hp;\n  }\n}\n\nclass Healer extends Fighter {\n  heal(friend) {\n    friend.hp = Math.min(friend.maxHp, friend.hp + 5);\n    console.log(this.name + " heals " + friend.name + " to " + friend.hp);\n  }\n}\n\nconst mo = new Fighter("Mo", 12);\nmo.hp = 5;\nconst ivy = new Healer("Ivy", 8);\nivy.heal(mo);\nivy.heal(mo);`},
 {type:"game"},{type:"done"}],
 pool:[
  [`class A { constructor() { this.hp = 5; } }\nconst a = new A();\na.hp -= 2;\nconsole.log(a.hp);`,["3","5","2"]],
  [`class A { hi() { return "a"; } }\nclass B extends A { hi() { return "b"; } }\nconsole.log(new B().hi());`,["b","a","ab"]],
  [`class A { get two() { return 2; } }\nconsole.log(new A().two * 3);`,["6","2","NaN"]],
  [`class A { constructor(n) { this.n = n; } }\nconst x = new A(1);\nconst y = x;\ny.n = 9;\nconsole.log(x.n);`,["9","1","undefined"]]
 ]},
{id:"g13",title:"Inventory & items",sub:"lists of objects, using and stacking items",steps:[
 {type:"talk",title:"A bag of items",
  body:`<p>An inventory is an array of item objects. Each item can have a name, a type and an amount. ${C(".find()")} looks one up by name.</p>`,
  demo:`const bag = [\n  { name: "potion", qty: 2 },\n  { name: "banana", qty: 5 }\n];\nconst p = bag.find(i => i.name === "potion");\np.qty--;\nfor (const item of bag) console.log(item.name + " x" + item.qty);`,
  say:"potion x1, banana x5."},
 {type:"talk",title:"Stacking and running out",mood:"think",
  body:`<p>Picking up something you already have should add to its stack. When an amount hits 0, remove it with ${C(".filter()")}.</p>`,
  demo:`let bag = [{ name: "potion", qty: 1 }];\n\nfunction pickUp(name) {\n  const have = bag.find(i => i.name === name);\n  if (have) have.qty++;\n  else bag.push({ name: name, qty: 1 });\n}\nfunction use(name) {\n  const have = bag.find(i => i.name === name);\n  if (!have) return console.log("No " + name + "!");\n  have.qty--;\n  bag = bag.filter(i => i.qty > 0);\n  console.log("Used " + name);\n}\n\npickUp("key");\npickUp("potion");\nuse("potion");\nuse("potion");\nuse("potion");\nconsole.log(bag.map(i => i.name + " x" + i.qty).join(", "));`,
  say:"Two potions get used, the third try fails, and only the key is left."},
 {type:"quiz",q:"What does find give back if nothing matches?",opts:["undefined","An empty object","An error"],a:0,why:"That's why we check if (have) before using it."},
 {type:"quiz",q:"What does this print?",code:`const bag = [{ n: "a", q: 0 }, { n: "b", q: 2 }];\nconsole.log(bag.filter(i => i.q > 0).length);`,opts:["1","2","0"],a:0,mono:true,why:"Only b has more than 0."},
 {type:"fill",title:"Find the sword",body:`<p>Look up the sword.</p>`,code:`const bag = [{ name: "sword", dmg: 7 }];\nconst s = bag.[0](i => i.name [1] "sword");\nconsole.log(s.dmg);`,blanks:["find","==="],tokens:["find","===","filter","="],why:"find the first item where the name matches."},
 {type:"code",title:"Shopkeeper",body:`<p>Finish ${C("buy(name)")}: look up the price in ${C("shop")}. If you can't afford it, print ${C("Not enough gold for X")}. Otherwise subtract the gold, add it to ${C("bag")} (stacking!) and print ${C("Bought X, G gold left")}.</p>`,start:`const shop = { potion: 5, sword: 20, banana: 1 };\nlet gold = 12;\nconst bag = [];\n\nfunction buy(name) {\n  // your code here\n}\n\nbuy("potion");\nbuy("sword");\nbuy("potion");\nbuy("banana");\nconsole.log(bag.map(i => i.name + " x" + i.qty).join(", "));\n`,
  use:[[/gold\s*-=/,"Take the price from gold."],[/\.find\s*\(/,"Use find to stack items you already have."]],out:["Bought potion, 7 gold left","Not enough gold for sword","Bought potion, 2 gold left","Bought banana, 1 gold left","potion x2, banana x1"],
  hint:`const shop = { potion: 5, sword: 20, banana: 1 };\nlet gold = 12;\nconst bag = [];\n\nfunction buy(name) {\n  const price = shop[name];\n  if (price > gold) {\n    console.log("Not enough gold for " + name);\n    return;\n  }\n  gold -= price;\n  const have = bag.find(i => i.name === name);\n  if (have) have.qty++;\n  else bag.push({ name: name, qty: 1 });\n  console.log("Bought " + name + ", " + gold + " gold left");\n}\n\nbuy("potion");\nbuy("sword");\nbuy("potion");\nbuy("banana");\nconsole.log(bag.map(i => i.name + " x" + i.qty).join(", "));`},
 {type:"game"},{type:"done"}],
 pool:[
  [`const b = [{ n: "x" }, { n: "y" }];\nconsole.log(b.find(i => i.n === "y").n);`,["y","x","undefined"]],
  [`const b = [{ q: 2 }, { q: 3 }];\nconsole.log(b.reduce((s, i) => s + i.q, 0));`,["5","23","2"]],
  [`const b = [{ n: "a" }];\nconsole.log(b.find(i => i.n === "z"));`,["undefined","null","a"]],
  [`const shop = { gem: 9 };\nlet gold = 10;\ngold -= shop.gem;\nconsole.log(gold);`,["1","19","9"]],
  [`const b = [{ n: "a", q: 1 }];\nb[0].q += 4;\nconsole.log(b[0].q);`,["5","1","14"]]
 ]},
{id:"g14",title:"Text adventure",sub:"rooms, exits and commands",steps:[
 {type:"talk",title:"A world of rooms",
  body:`<p>Text adventures were some of the first video games. The world is an object of <b>rooms</b>; each room has a description and <b>exits</b> pointing to other rooms.</p>`,
  demo:`const rooms = {\n  hall: { desc: "a dusty hall", exits: { north: "library", east: "kitchen" } },\n  library: { desc: "shelves of old books", exits: { south: "hall" } },\n  kitchen: { desc: "a kitchen that smells of bananas", exits: { west: "hall" } }\n};\nlet here = "hall";\nconsole.log("You are in " + rooms[here].desc + ".");\nconsole.log("Exits: " + Object.keys(rooms[here].exits).join(", "));`,
  say:"Object.keys lists the exit names."},
 {type:"talk",title:"Following commands",mood:"think",
  body:`<p>Commands like ${C('"go north"')} get split into a verb and a target. If the exit exists, move; if not, complain. A ${C("switch")} on the verb keeps it tidy.</p>`,
  demo:`const rooms = {\n  hall: { desc: "a dusty hall", exits: { north: "library" } },\n  library: { desc: "shelves of old books", exits: { south: "hall" } }\n};\nlet here = "hall";\nfor (const cmd of ["go west", "go north", "look"]) {\n  const [verb, target] = cmd.split(" ");\n  switch (verb) {\n    case "go":\n      if (rooms[here].exits[target]) {\n        here = rooms[here].exits[target];\n        console.log("You walk " + target + ".");\n      } else {\n        console.log("You can't go " + target + ".");\n      }\n      break;\n    case "look":\n      console.log("You see " + rooms[here].desc + ".");\n      break;\n  }\n}`,
  say:"Can't go west, walk north, then look around the library."},
 {type:"quiz",q:"What does this print?",code:`const [a, b] = "take key".split(" ");\nconsole.log(b);`,opts:["key","take","take key"],a:0,mono:true,why:"split gives [\"take\", \"key\"], and b gets the second one."},
 {type:"quiz",q:"What does this print?",code:`const ex = { north: "attic" };\nconsole.log(ex["south"]);`,opts:["undefined","attic","null"],a:0,mono:true,why:"There's no south key, so you get undefined (which counts as false in an if)."},
 {type:"fill",title:"List the exits",body:`<p>Print the exit names.</p>`,code:`const exits = { up: "roof", down: "cellar" };\nconsole.log(Object.[0](exits).[1](" and "));`,blanks:["keys","join"],tokens:["keys","join","values","split"],why:"Object.keys gives [\"up\", \"down\"], and join glues them."},
 {type:"code",title:"Find the key",body:`<p>Handle ${C("go")}, ${C("take")} and ${C("open")}. ${C("take key")} only works in the room where the key is. ${C("open door")} works only in the hall <b>with</b> the key: print ${C("You escape!")} and stop. Print the messages shown in the expected output.</p>`,start:`const rooms = {\n  hall: { exits: { east: "study" } },\n  study: { exits: { west: "hall" }, item: "key" }\n};\nlet here = "hall";\nconst bag = [];\nconst cmds = ["open door", "go east", "take key", "go west", "open door"];\nfor (const cmd of cmds) {\n  const [verb, target] = cmd.split(" ");\n  // your code here\n}\n`,
  use:[[/switch|if\s*\(\s*verb/,"Check the verb."],[/bag\.push|bag\.includes/,"Keep the key in bag."]],out:["The door is locked.","You go east.","You take the key.","You go west.","You escape!"],variants:[[/"take key", /,"",["The door is locked.","You go east.","You go west.","The door is locked."]]],
  hint:`const rooms = {\n  hall: { exits: { east: "study" } },\n  study: { exits: { west: "hall" }, item: "key" }\n};\nlet here = "hall";\nconst bag = [];\nconst cmds = ["open door", "go east", "take key", "go west", "open door"];\nfor (const cmd of cmds) {\n  const [verb, target] = cmd.split(" ");\n  if (verb === "go" && rooms[here].exits[target]) {\n    here = rooms[here].exits[target];\n    console.log("You go " + target + ".");\n  } else if (verb === "take" && rooms[here].item === target) {\n    bag.push(target);\n    rooms[here].item = null;\n    console.log("You take the " + target + ".");\n  } else if (verb === "open" && here === "hall") {\n    if (bag.includes("key")) {\n      console.log("You escape!");\n      break;\n    }\n    console.log("The door is locked.");\n  } else {\n    console.log("Nothing happens.");\n  }\n}`},
 {type:"game"},{type:"done"}],
 pool:[
  [`console.log("go north".split(" ")[1]);`,["north","go","go north"]],
  [`const r = { a: { x: 1 } };\nconsole.log(r.a.x + 1);`,["2","1","11"]],
  [`console.log(Object.keys({ n: 1, s: 2 }).length);`,["2","3","1"]],
  [`const bag = ["key"];\nconsole.log(bag.includes("map"));`,["false","true","-1"]],
  [`let here = "hall";\nconst ex = { up: "attic" };\nif (ex.up) here = ex.up;\nconsole.log(here);`,["attic","hall","up"]]
 ]},
{id:"g15",title:"Project: Dungeon Crawler",sub:"everything together in one game",project:true,steps:[
 {type:"talk",title:"The final quest",mood:"cheer",
  body:`<p>Your capstone: a dungeon on a grid. Walk around, fight monsters you bump into, drink potions, and reach the stairs. You'll use state, loops, grids, objects and classes.</p>`,
  say:"Finish this and you've made a real game. Show someone!"},
 {type:"code",title:"Step 1: walk the dungeon",body:`<p>Move through the map with the moves. Walls block you. Stepping on ${C("p")} picks up a potion (+4 hp, max 10) and clears the tile. Print the hero's final position and hp like ${C("At 6,1 with 10 hp")}.</p>`,start:`const map = [\n  "########",\n  "#..p...#",\n  "#.##.#.#",\n  "#p...#>#",\n  "########"\n].map(r => r.split(""));\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nconst hero = { x: 1, y: 1, hp: 6, maxHp: 10 };\nconst moves = "RRRRR";\n// your code here\n`,
  use:[[/"p"/,"Check for potion tiles."],[/Math\.min/,"Don't heal past maxHp."]],out:["At 6,1 with 10 hp"],variants:[[/"RRRRR"/,"\"DDRR\"",["At 3,3 with 10 hp"]],[/"RRRRR"/,"\"RL\"",["At 1,1 with 6 hp"]]],
  hint:`const map = [\n  "########",\n  "#..p...#",\n  "#.##.#.#",\n  "#p...#>#",\n  "########"\n].map(r => r.split(""));\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nconst hero = { x: 1, y: 1, hp: 6, maxHp: 10 };\nconst moves = "RRRRR";\nfor (const m of moves) {\n  const [dx, dy] = DIRS[m];\n  if (map[hero.y + dy][hero.x + dx] === "#") continue;\n  hero.x += dx;\n  hero.y += dy;\n  if (map[hero.y][hero.x] === "p") {\n    hero.hp = Math.min(hero.maxHp, hero.hp + 4);\n    map[hero.y][hero.x] = ".";\n  }\n}\nconsole.log("At " + hero.x + "," + hero.y + " with " + hero.hp + " hp");`},
 {type:"code",title:"Step 2: monsters",body:`<p>Monsters are listed by position. If you try to step onto a monster, you attack it instead (it loses ${C("hero.power")}) and it hits back if still alive (you lose its ${C("power")}). A defeated monster is removed and you stay put that turn. Print each fight line as shown.</p>`,start:`const map = [\n  "#######",\n  "#.....#",\n  "#######"\n].map(r => r.split(""));\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nconst hero = { x: 1, y: 1, hp: 10, power: 3 };\nlet monsters = [{ name: "Rat", x: 3, y: 1, hp: 5, power: 2 }];\nconst moves = "RRRRR";\nfor (const m of moves) {\n  const [dx, dy] = DIRS[m];\n  const nx = hero.x + dx, ny = hero.y + dy;\n  if (map[ny][nx] === "#") continue;\n  // fight a monster at nx, ny, or move\n}\nconsole.log("At " + hero.x + "," + hero.y + " with " + hero.hp + " hp");\n`,
  use:[[/monsters\.find|monsters\.filter|for\s*\(\s*const\s+\w+\s+of\s+monsters/,"Look for a monster at the next square."]],out:["You hit Rat (2 left)","Rat hits you (8 left)","You defeat Rat!","At 4,1 with 8 hp"],
  hint:`const map = [\n  "#######",\n  "#.....#",\n  "#######"\n].map(r => r.split(""));\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nconst hero = { x: 1, y: 1, hp: 10, power: 3 };\nlet monsters = [{ name: "Rat", x: 3, y: 1, hp: 5, power: 2 }];\nconst moves = "RRRRR";\nfor (const m of moves) {\n  const [dx, dy] = DIRS[m];\n  const nx = hero.x + dx, ny = hero.y + dy;\n  if (map[ny][nx] === "#") continue;\n  const mon = monsters.find(o => o.x === nx && o.y === ny);\n  if (mon) {\n    mon.hp -= hero.power;\n    if (mon.hp > 0) {\n      console.log("You hit " + mon.name + " (" + mon.hp + " left)");\n      hero.hp -= mon.power;\n      console.log(mon.name + " hits you (" + hero.hp + " left)");\n    } else {\n      console.log("You defeat " + mon.name + "!");\n      monsters = monsters.filter(o => o !== mon);\n    }\n  } else {\n    hero.x = nx;\n    hero.y = ny;\n  }\n}\nconsole.log("At " + hero.x + "," + hero.y + " with " + hero.hp + " hp");`},
 {type:"code",title:"Step 3: win or lose",body:`<p>Put it all together. Reaching ${C(">")} prints ${C("You found the stairs with N hp!")} and ends the game. If hp drops to 0, print ${C("You were defeated...")} and end. If the moves run out, print ${C("Still exploring.")}.</p>`,start:`const map = [\n  "########",\n  "#......#",\n  "#.####.#",\n  "#.....>#",\n  "########"\n].map(r => r.split(""));\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nconst hero = { x: 1, y: 1, hp: 10, power: 3 };\nlet monsters = [\n  { name: "Rat", x: 4, y: 1, hp: 5, power: 2 },\n  { name: "Ogre", x: 6, y: 2, hp: 9, power: 4 }\n];\nconst moves = "RRRRRRRRRRDDDDD";\n// your game loop here\n`,
  use:[[/">"/,"Check for the stairs \">\"."],[/hp\s*<=\s*0/,"Check whether the hero has run out of hp."]],out:["You hit Rat (2 left)","Rat hits you (8 left)","You defeat Rat!","You hit Ogre (6 left)","Ogre hits you (4 left)","You hit Ogre (3 left)","Ogre hits you (0 left)","You were defeated..."],variants:[[/power: 4/,"power: 1",["You hit Rat (2 left)","Rat hits you (8 left)","You defeat Rat!","You hit Ogre (6 left)","Ogre hits you (7 left)","You hit Ogre (3 left)","Ogre hits you (6 left)","You defeat Ogre!","You found the stairs with 6 hp!"]]],
  hint:`const map = [\n  "########",\n  "#......#",\n  "#.####.#",\n  "#.....>#",\n  "########"\n].map(r => r.split(""));\nconst DIRS = { U: [0, -1], D: [0, 1], L: [-1, 0], R: [1, 0] };\nconst hero = { x: 1, y: 1, hp: 10, power: 3 };\nlet monsters = [\n  { name: "Rat", x: 4, y: 1, hp: 5, power: 2 },\n  { name: "Ogre", x: 6, y: 2, hp: 9, power: 4 }\n];\nconst moves = "RRRRRRRRRRDDDDD";\nlet over = false;\nfor (const m of moves) {\n  const [dx, dy] = DIRS[m];\n  const nx = hero.x + dx, ny = hero.y + dy;\n  if (map[ny][nx] === "#") continue;\n  const mon = monsters.find(o => o.x === nx && o.y === ny);\n  if (mon) {\n    mon.hp -= hero.power;\n    if (mon.hp > 0) {\n      console.log("You hit " + mon.name + " (" + mon.hp + " left)");\n      hero.hp -= mon.power;\n      console.log(mon.name + " hits you (" + hero.hp + " left)");\n      if (hero.hp <= 0) {\n        console.log("You were defeated...");\n        over = true;\n        break;\n      }\n    } else {\n      console.log("You defeat " + mon.name + "!");\n      monsters = monsters.filter(o => o !== mon);\n    }\n    continue;\n  }\n  hero.x = nx;\n  hero.y = ny;\n  if (map[ny][nx] === ">") {\n    console.log("You found the stairs with " + hero.hp + " hp!");\n    over = true;\n    break;\n  }\n}\nif (!over) console.log("Still exploring.");`},
 {type:"done"}]}
]}
]};
