/* New units: JavaScript Unit 7 and Python Unit 7. */
COURSE_JS.units.push({name:"Real-world JavaScript",lessons:[
{id:"js26",title:"Strings in depth",sub:"split, join, slice, trim, replaceAll",steps:[
 {type:"talk",title:"Cutting strings up",
  body:`<p>${C(".split()")} breaks a string into an array. ${C(".join()")} glues an array back into a string. ${C(".slice(a, b)")} copies part of a string.</p>`,
  demo:`const csv = "ava,leo,kai";\nconst names = csv.split(",");\nconsole.log(names);\nconsole.log(names.join(" & "));\nconsole.log("TypeMonkey".slice(0, 4));\nconsole.log("TypeMonkey".slice(-6));`,
  say:"Negative numbers in slice count from the end."},
 {type:"talk",title:"Cleaning text",mood:"think",
  body:`<p>${C(".trim()")} removes spaces at the ends, ${C(".replaceAll()")} swaps every match, and ${C(".padStart()")} pads to a length, which is great for scoreboards.</p>`,
  demo:`console.log("  hi  ".trim() + "!");\nconsole.log("a-b-c".replaceAll("-", "+"));\nconsole.log("7".padStart(3, "0"));\nconsole.log("ook".repeat(2));`,
  say:"Real apps clean up what users type all the time."},
 {type:"quiz",q:"What does this print?",code:`console.log("a b c".split(" ").length);`,opts:["3","5","1"],a:0,mono:true,why:"Splitting on spaces gives [\"a\", \"b\", \"c\"]."},
 {type:"fill",title:"Initials",body:`<p>Turn ${C("\"Sam Lee\"")} into ${C("S.L.")}.</p>`,code:`const parts = "Sam Lee".[0](" ");\nconsole.log(parts.map(p => p.charAt(0) + ".").[1](""));`,blanks:["split","join"],tokens:["split","join","slice","trim"],why:"split makes the array, join glues the initials together."},
 {type:"code",title:"Shout the words",body:`<p>Turn ${C("sentence")} into all caps with the words joined by ${C(" 🍌 ")}. Print the result.</p>`,
  start:`const sentence = "i love bananas";\n`,use:[[/\.split\(/,"Split the sentence into words."],[/\.join\(/,"Join the words back together."]],out:["I 🍌 LOVE 🍌 BANANAS"],variants:[[/"i love bananas"/,'"go team"',["GO 🍌 TEAM"]]],
  hint:`const sentence = "i love bananas";\nconsole.log(sentence.toUpperCase().split(" ").join(" 🍌 "));`},
 {type:"game"},{type:"done"}],
 pool:[[`console.log("a,b".split(","));`,["[\"a\",\"b\"]","a b","[\"a,b\"]"]],[`console.log(["x", "y"].join("-"));`,["x-y","xy","[\"x-y\"]"]],[`console.log("banana".slice(1, 3));`,["an","ba","ana"]],[`console.log(" ok ".trim().length);`,["2","4","3"]],[`console.log("5".padStart(2, "0"));`,["05","50","5"]],[`console.log("ababab".replaceAll("a", ""));`,["bbb","ababab","aaa"]]]},
{id:"js27",title:"Errors: try & catch",sub:"handle problems without crashing",steps:[
 {type:"talk",title:"When things go wrong",mood:"oops",
  body:`<p>Some errors stop your program. ${C("try")} runs risky code, and if it throws an error, ${C("catch")} handles it instead of crashing.</p>`,
  demo:`try {\n  const data = JSON.parse("{ broken");\n  console.log(data);\n} catch (err) {\n  console.log("Couldn't read that: " + err.name);\n}\nconsole.log("The program keeps going!");`,
  say:"JSON.parse turns text into an object. Broken text throws a SyntaxError."},
 {type:"talk",title:"Throwing your own errors",mood:"think",
  body:`<p>${C("throw new Error(\"...\")")} signals a problem. ${C("finally")} always runs, error or not.</p>`,
  demo:`function withdraw(balance, amount) {\n  if (amount > balance) throw new Error("Not enough bananas");\n  return balance - amount;\n}\ntry {\n  console.log(withdraw(10, 3));\n  console.log(withdraw(10, 50));\n} catch (e) {\n  console.log("Error: " + e.message);\n} finally {\n  console.log("Done");\n}`,
  say:"Output: 7, then Error: Not enough bananas, then Done."},
 {type:"quiz",q:"When does a finally block run?",opts:["Always, error or not","Only when there's an error","Only when there's no error"],a:0,why:"finally is for cleanup that must always happen."},
 {type:"fill",title:"Catch it",body:`<p>Handle the error.</p>`,code:`[0] {\n  null.length;\n} [1] (e) {\n  console.log("Oops");\n}`,blanks:["try","catch"],tokens:["try","catch","throw","finally"],why:"try runs the risky code; catch handles the error."},
 {type:"code",title:"Safe divide",body:`<p>Write ${C("safeDivide(a, b)")} that throws an Error with the message ${C("Can't divide by zero")} when b is 0. Otherwise return a / b. The calls below should print 5 and then the message.</p>`,
  start:`// write safeDivide here\n\ntry {\n  console.log(safeDivide(10, 2));\n  console.log(safeDivide(1, 0));\n} catch (e) {\n  console.log(e.message);\n}\n`,use:[[/throw\s+new\s+Error/,"Throw an error with throw new Error(\"...\")."]],out:["5","Can't divide by zero"],
  hint:`function safeDivide(a, b) {\n  if (b === 0) throw new Error("Can't divide by zero");\n  return a / b;\n}\n\ntry {\n  console.log(safeDivide(10, 2));\n  console.log(safeDivide(1, 0));\n} catch (e) {\n  console.log(e.message);\n}`},
 {type:"game"},{type:"done"}],
 pool:[[`try {\n  console.log("a");\n  throw new Error("b");\n} catch (e) {\n  console.log(e.message);\n}`,["a b","a","b"]],[`try {\n  console.log(1);\n} catch (e) {\n  console.log(2);\n} finally {\n  console.log(3);\n}`,["1 3","1 2 3","3"]],[`try {\n  undefinedThing();\n} catch (e) {\n  console.log(e.name);\n}`,["ReferenceError","TypeError","Error"]],[`console.log(JSON.parse("[1,2]").length);`,["2","5","[1,2]"]]]},
{id:"js28",title:"Destructuring & spread",sub:"modern shortcuts pros use",steps:[
 {type:"talk",title:"Destructuring",
  body:`<p>Pull values out of objects and arrays into variables in one line.</p>`,
  demo:`const player = { name: "Ava", score: 92, level: 4 };\nconst { name, score } = player;\nconsole.log(name, score);\n\nconst [first, second] = ["gold", "silver", "bronze"];\nconsole.log(first, second);`,
  say:"Output: Ava 92, then gold silver."},
 {type:"talk",title:"Spread ...",mood:"cheer",
  body:`<p>${C("...")} spreads an array or object out. Use it to combine or copy.</p>`,
  demo:`const a = [1, 2];\nconst b = [...a, 3, 4];\nconsole.log(b);\n\nconst base = { hp: 10, speed: 2 };\nconst boss = { ...base, hp: 99 };\nconsole.log(boss);\nconsole.log(Math.max(...b));`,
  say:"Later properties win, so hp becomes 99."},
 {type:"quiz",q:"What does this print?",code:`const [x, , z] = [5, 6, 7];\nconsole.log(x + z);`,opts:["12","11","18"],a:0,mono:true,why:"The empty spot skips 6, so x is 5 and z is 7."},
 {type:"fill",title:"Combine lists",body:`<p>Make one array with both lists.</p>`,code:`const fruits = ["kiwi"];\nconst veggies = ["kale"];\nconst all = [[0]fruits, [1]veggies];\nconsole.log(all);`,blanks:["...","..."],tokens:["...","...","+","&"],why:"Spread both arrays into a new one."},
 {type:"code",title:"Upgrade the hero",body:`<p>Make ${C("hero2")}: a copy of ${C("hero")} with ${C("level")} set to 2, using spread. Then pull out ${C("name")} and ${C("level")} from hero2 with destructuring and print them.</p>`,
  start:`const hero = { name: "Mo", level: 1, hp: 30 };\n`,use:[[/\.\.\.hero/,"Copy hero with { ...hero, ... }"],[/const\s*\{[^}]*\}\s*=\s*hero2/,"Destructure: const { name, level } = hero2;"]],out:["Mo 2"],
  hint:`const hero = { name: "Mo", level: 1, hp: 30 };\nconst hero2 = { ...hero, level: 2 };\nconst { name, level } = hero2;\nconsole.log(name, level);`},
 {type:"game"},{type:"done"}],
 pool:[[`const { a } = { a: 3, b: 4 };\nconsole.log(a);`,["3","4","undefined"]],[`console.log([...[1, 2], ...[3]]);`,["[1,2,3]","[[1,2],[3]]","[1,2]"]],[`const o = { x: 1, ...{ x: 2 } };\nconsole.log(o.x);`,["2","1","undefined"]],[`const [p, q] = [9];\nconsole.log(q);`,["undefined","9","0"]],[`console.log(Math.min(...[4, 1, 7]));`,["1","4","7"]]]},
{id:"js29",title:"Project: Quiz Game",sub:"build the engine behind a quiz app",project:true,steps:[
 {type:"talk",title:"Make your own quiz app",mood:"cheer",
  body:`<p>Quiz apps (like this one!) store questions as data and score answers with code. You'll build that engine.</p>`,
  demo:`const questions = [\n  { q: "2 + 2?", answer: "4" },\n  { q: "Capital of France?", answer: "Paris" }\n];\nconsole.log(questions.length + " questions loaded");`,
  say:"Questions as data: easy to add more later."},
 {type:"code",title:"Step 1: grade one answer",body:`<p>Write ${C("grade(question, guess)")} that returns true if the guess matches the answer, ignoring capital letters and extra spaces.</p>`,
  start:`function grade(question, guess) {\n  // your code here\n}\n\nconsole.log(grade({ q: "City?", answer: "Paris" }, "  paris "));\nconsole.log(grade({ q: "City?", answer: "Paris" }, "Rome"));\n`,
  use:[[/toLowerCase|toUpperCase/,"Compare in the same case."],[/trim\(/,"Remove extra spaces with trim()."]],out:["true","false"],
  hint:`function grade(question, guess) {\n  return guess.trim().toLowerCase() === question.answer.toLowerCase();\n}\n\nconsole.log(grade({ q: "City?", answer: "Paris" }, "  paris "));\nconsole.log(grade({ q: "City?", answer: "Paris" }, "Rome"));`},
 {type:"code",title:"Step 2: score a whole quiz",body:`<p>Loop through the questions and guesses, count the correct ones, and print ${C("Score: 2/3")}.</p>`,
  start:`const questions = [\n  { q: "2 + 2?", answer: "4" },\n  { q: "Opposite of hot?", answer: "cold" },\n  { q: "Monkey food?", answer: "banana" }\n];\nconst guesses = ["4", "warm", "Banana"];\nconst grade = (q, g) => g.trim().toLowerCase() === q.answer.toLowerCase();\n\n// count the right answers and print the score\n`,
  use:[[/\bfor\b|forEach|filter/,"Loop through the questions."]],out:["Score: 2/3"],variants:[[/"warm"/,'"cold"',["Score: 3/3"]]],
  hint:"const questions = [\n  { q: \"2 + 2?\", answer: \"4\" },\n  { q: \"Opposite of hot?\", answer: \"cold\" },\n  { q: \"Monkey food?\", answer: \"banana\" }\n];\nconst guesses = [\"4\", \"warm\", \"Banana\"];\nconst grade = (q, g) => g.trim().toLowerCase() === q.answer.toLowerCase();\n\nlet score = 0;\nfor (let i = 0; i < questions.length; i++) {\n  if (grade(questions[i], guesses[i])) score++;\n}\nconsole.log(`Score: ${score}/${questions.length}`);"},
 {type:"talk",title:"The finished engine",mood:"cheer",
  body:`<p>With a results message added, here's a complete quiz engine. Swap in your own questions and it works!</p>`,
  demo:"const questions = [\n  { q: \"2 + 2?\", answer: \"4\" },\n  { q: \"Opposite of hot?\", answer: \"cold\" },\n  { q: \"Monkey food?\", answer: \"banana\" }\n];\nconst guesses = [\"4\", \"warm\", \"Banana\"];\nconst grade = (q, g) => g.trim().toLowerCase() === q.answer.toLowerCase();\n\nconst results = questions.map((q, i) => grade(q, guesses[i]));\nresults.forEach((ok, i) => console.log(`${ok ? \"✓\" : \"✗\"} ${questions[i].q}`));\nconst score = results.filter(Boolean).length;\nconst pct = Math.round(score / questions.length * 100);\nconsole.log(`Score: ${score}/${questions.length} (${pct}%)`);\nconsole.log(pct >= 60 ? \"You pass! 🍌\" : \"Try again!\");",
  say:"You built the brain of a quiz app. Nice!"},
 {type:"done"}]}
]});

COURSE_PY.units.push({name:"Python power-ups",lessons:[
{id:"py21",title:"Tuples & sets",sub:"fixed lists and unique items",steps:[
 {type:"talk",title:"Tuples",
  body:`<p>A <b>tuple</b> is like a list you can't change, written with parentheses. Great for things that belong together, like coordinates.</p>`,
  demo:`point = (3, 5)\nx, y = point\nprint(point, x + y)\nprint(len(point))\n# point[0] = 9 would be an error: tuples can't change`,
  say:"Unpacking: x, y = point grabs both values at once."},
 {type:"talk",title:"Sets",mood:"think",
  body:`<p>A <b>set</b> keeps only <b>unique</b> items. Perfect for removing duplicates or checking membership fast.</p>`,
  demo:`visits = ["Mo", "Ava", "Mo", "Leo", "Ava"]\nunique = set(visits)\nprint(len(unique))\nprint(sorted(unique))\nprint("Leo" in unique)`,
  say:"Sets don't keep order, so sort them when you print."},
 {type:"quiz",q:"What does this print?",code:`print(len(set([1, 1, 2, 2, 2, 3])))`,opts:["3","6","1"],a:0,mono:true,why:"The unique items are 1, 2 and 3."},
 {type:"fill",title:"Swap!",body:`<p>Swap a and b in one line using tuples.</p>`,code:`a = 1\nb = 2\na, b = [0], [1]\nprint(a, b)`,blanks:["b","a"],tokens:["b","a","1","2"],why:"Python builds the tuple (b, a) and unpacks it.",out:"2 1"},
 {type:"code",title:"Unique visitors",body:`<p>Print how many <b>different</b> animals visited, then their names sorted A to Z.</p>`,
  start:`visitors = ["Mo", "Kiki", "Mo", "Bao", "Kiki", "Mo"]\n`,use:[[/\bset\s*\(/,"Use set() to remove duplicates."]],out:["3","['Bao', 'Kiki', 'Mo']"],
  hint:`visitors = ["Mo", "Kiki", "Mo", "Bao", "Kiki", "Mo"]\nunique = set(visitors)\nprint(len(unique))\nprint(sorted(unique))`},
 {type:"game"},{type:"done"}],
 pool:[[`t = (1, 2, 3)\nprint(t[-1])`,["3","1","(1, 2, 3)"]],[`a, b = (4, 5)\nprint(b - a)`,["1","-1","9"]],[`print(sorted({3, 1, 2}))`,["[1, 2, 3]","{1, 2, 3}","[3, 1, 2]"]],[`s = {1, 2}\ns.add(2)\nprint(len(s))`,["2","3","1"]],[`print(5 in {1, 5, 9})`,["True","False","5"]]]},
{id:"py22",title:"Sorting & lambda",sub:"sort anything, any way",steps:[
 {type:"talk",title:"sorted() and .sort()",
  body:`<p>${C("sorted()")} returns a new sorted list. ${C(".sort()")} sorts a list in place. Both take ${C("reverse=True")}.</p>`,
  demo:`nums = [5, 2, 9, 1]\nprint(sorted(nums))\nprint(sorted(nums, reverse=True))\nwords = ["kiwi", "fig", "banana"]\nwords.sort()\nprint(words)`,
  say:"Words sort A to Z."},
 {type:"talk",title:"Sort by anything with key",mood:"cheer",
  body:`<p>${C("key=")} takes a function that says what to sort by. ${C("lambda")} makes a tiny one-line function right there.</p>`,
  demo:`words = ["kiwi", "fig", "banana"]\nprint(sorted(words, key=len))\nplayers = [("Leo", 72), ("Ava", 95), ("Kai", 81)]\nprint(sorted(players, key=lambda p: p[1], reverse=True))`,
  say:"lambda p: p[1] means: sort each player by their score."},
 {type:"quiz",q:"What does this print?",code:`print(sorted(["bb", "a", "ccc"], key=len))`,opts:["['a', 'bb', 'ccc']","['ccc', 'bb', 'a']","['a', 'ccc', 'bb']"],a:0,mono:true,why:"Sorted by length: 1, 2, 3 letters."},
 {type:"fill",title:"High scores first",body:`<p>Sort biggest first.</p>`,code:`scores = [40, 90, 70]\nprint(sorted(scores, [0]=True))`,blanks:["reverse"],tokens:["reverse","key","desc","flip"],why:"reverse=True sorts from biggest to smallest.",out:"[90, 70, 40]"},
 {type:"code",title:"Leaderboard",body:`<p>Sort the players by score, highest first, and print each like ${C("1. Ava 95")}.</p>`,
  start:`players = [("Leo", 72), ("Ava", 95), ("Kai", 81)]\n`,use:[[/sorted\s*\(|\.sort\s*\(/,"Sort the players."],[/lambda/,"Use key=lambda p: p[1] to sort by score."]],out:["1. Ava 95","2. Kai 81","3. Leo 72"],
  hint:`players = [("Leo", 72), ("Ava", 95), ("Kai", 81)]\nranked = sorted(players, key=lambda p: p[1], reverse=True)\nfor i, (name, score) in enumerate(ranked, start=1):\n    print(f"{i}. {name} {score}")`},
 {type:"game"},{type:"done"}],
 pool:[[`print(sorted([3, 1, 2], reverse=True))`,["[3, 2, 1]","[1, 2, 3]","[3, 1, 2]"]],[`a = [2, 1]\na.sort()\nprint(a)`,["[1, 2]","[2, 1]","None"]],[`f = lambda x: x * 3\nprint(f(4))`,["12","7","x * 3"]],[`print(sorted(["b", "A", "a"]))`,["['A', 'a', 'b']","['a', 'A', 'b']","['a', 'b', 'A']"]],[`print(max(["kiwi", "fig", "banana"], key=len))`,["banana","kiwi","fig"]]]},
{id:"py23",title:"Recursion",sub:"functions that call themselves",steps:[
 {type:"talk",title:"A function calling itself",mood:"think",
  body:`<p><b>Recursion</b> is when a function calls itself on a smaller version of the problem. It needs a <b>base case</b> that stops it.</p>`,
  demo:`def countdown(n):\n    if n == 0:\n        print("Liftoff!")\n        return\n    print(n)\n    countdown(n - 1)\n\ncountdown(3)`,
  say:"Base case: n == 0 stops the chain."},
 {type:"talk",title:"Factorial",
  body:`<p>5! means 5 × 4 × 3 × 2 × 1. Notice 5! = 5 × 4!. That's a recursive pattern.</p>`,
  demo:`def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)\n\nprint(factorial(5))\nprint(factorial(1))`,
  say:"Output: 120, then 1."},
 {type:"quiz",q:"What happens if a recursive function has no base case?",opts:["It calls itself forever until Python stops it","It returns 0","It runs once"],a:0,why:"Python raises a RecursionError when the calls go too deep."},
 {type:"fill",title:"Sum to n",body:`<p>Add 1 + 2 + ... + n recursively.</p>`,code:`def total(n):\n    if n == 0:\n        [0] 0\n    return n + [1](n - 1)\n\nprint(total(4))`,blanks:["return","total"],tokens:["return","total","print","n"],why:"Base case returns 0; otherwise n plus the total of the rest.",out:"10"},
 {type:"code",title:"Power up",body:`<p>Write a recursive ${C("power(base, exp)")} without using ${C("**")}. Hint: power(b, 0) is 1, and power(b, e) is b × power(b, e - 1).</p>`,
  start:`def power(base, exp):\n    # your code here\n    pass\n\nprint(power(2, 5))\nprint(power(3, 0))\n`,use:[[/power\s*\(\s*base\s*,\s*exp\s*-\s*1\s*\)/,"Call power(base, exp - 1) inside power."]],out:["32","1"],
  hint:`def power(base, exp):\n    if exp == 0:\n        return 1\n    return base * power(base, exp - 1)\n\nprint(power(2, 5))\nprint(power(3, 0))`},
 {type:"game"},{type:"done"}],
 pool:[[`def f(n):\n    if n == 0:\n        return 0\n    return 2 + f(n - 1)\n\nprint(f(3))`,["6","3","0"]],[`def f(s):\n    if s == "":\n        return ""\n    return f(s[1:]) + s[0]\n\nprint(f("abc"))`,["cba","abc","a"]],[`def fib(n):\n    return n if n < 2 else fib(n - 1) + fib(n - 2)\n\nprint(fib(6))`,["8","6","13"]],[`def c(n):\n    if n > 0:\n        print(n)\n        c(n - 2)\n\nc(5)`,["5 3 1","5 4 3 2 1","5 3"]]]},
{id:"py24",title:"Project: Text Adventure",sub:"dictionaries + loops + functions",project:true,steps:[
 {type:"talk",title:"Build a mini adventure",mood:"cheer",
  body:`<p>Classic computer games were text adventures: rooms connected by exits. You'll build one where the rooms are a dictionary and the player's moves are a list.</p>`,
  demo:`rooms = {\n    "hut": {"desc": "a cozy hut", "north": "jungle"},\n    "jungle": {"desc": "a noisy jungle", "south": "hut", "east": "river"},\n    "river": {"desc": "a sparkly river", "west": "jungle"},\n}\nprint(rooms["jungle"]["desc"])`,
  say:"Each room knows its description and where each exit leads."},
 {type:"code",title:"Step 1: move one step",body:`<p>Write ${C("move(rooms, here, direction)")} that returns the room in that direction, or ${C("here")} if there's no exit that way.</p>`,
  start:`rooms = {\n    "hut": {"desc": "a cozy hut", "north": "jungle"},\n    "jungle": {"desc": "a noisy jungle", "south": "hut", "east": "river"},\n    "river": {"desc": "a sparkly river", "west": "jungle"},\n}\n\ndef move(rooms, here, direction):\n    # your code here\n    pass\n\nprint(move(rooms, "hut", "north"))\nprint(move(rooms, "hut", "east"))\n`,
  use:[[/\.get\s*\(|\bin\b/,"Check if the exit exists with .get() or in."]],out:["jungle","hut"],
  hint:`rooms = {\n    "hut": {"desc": "a cozy hut", "north": "jungle"},\n    "jungle": {"desc": "a noisy jungle", "south": "hut", "east": "river"},\n    "river": {"desc": "a sparkly river", "west": "jungle"},\n}\n\ndef move(rooms, here, direction):\n    return rooms[here].get(direction, here)\n\nprint(move(rooms, "hut", "north"))\nprint(move(rooms, "hut", "east"))`},
 {type:"code",title:"Step 2: play a whole trip",body:`<p>Start in the hut. For each move in ${C("moves")}, move and print ${C("You are in a noisy jungle")} style lines.</p>`,
  start:`rooms = {\n    "hut": {"desc": "a cozy hut", "north": "jungle"},\n    "jungle": {"desc": "a noisy jungle", "south": "hut", "east": "river"},\n    "river": {"desc": "a sparkly river", "west": "jungle"},\n}\nmoves = ["north", "east", "north"]\n\ndef move(rooms, here, direction):\n    return rooms[here].get(direction, here)\n\nhere = "hut"\n# loop through moves\n`,
  use:[[/\bfor\b/,"Loop through the moves."]],out:["You are in a noisy jungle","You are in a sparkly river","You are in a sparkly river"],
  hint:`rooms = {\n    "hut": {"desc": "a cozy hut", "north": "jungle"},\n    "jungle": {"desc": "a noisy jungle", "south": "hut", "east": "river"},\n    "river": {"desc": "a sparkly river", "west": "jungle"},\n}\nmoves = ["north", "east", "north"]\n\ndef move(rooms, here, direction):\n    return rooms[here].get(direction, here)\n\nhere = "hut"\nfor m in moves:\n    here = move(rooms, here, m)\n    print(f"You are in {rooms[here]['desc']}")`},
 {type:"talk",title:"The finished adventure",mood:"cheer",
  body:`<p>Add treasure and a win condition and you have a real game.</p>`,
  demo:`rooms = {\n    "hut": {"desc": "a cozy hut", "north": "jungle"},\n    "jungle": {"desc": "a noisy jungle", "south": "hut", "east": "river"},\n    "river": {"desc": "a sparkly river", "west": "jungle", "item": "golden banana"},\n}\nmoves = ["north", "west", "east"]\nhere, bag = "hut", []\nfor m in moves:\n    nxt = rooms[here].get(m)\n    if nxt is None:\n        print(f"You can't go {m} from here.")\n        continue\n    here = nxt\n    print(f"You walk {m} into {rooms[here]['desc']}.")\n    if "item" in rooms[here]:\n        bag.append(rooms[here].pop("item"))\n        print(f"You found the {bag[-1]}!")\nprint("You win!" if "golden banana" in bag else "Keep exploring...")`,
  say:"Output: walk north, can't go west, walk east, find the golden banana, You win! You finished Python Power-ups!"},
 {type:"done"}]}
]});
