/* Extra Output Rush rounds. Each entry is [code, [correct, wrong, wrong]]; they're appended to each lesson's game.
   All answers are checked by the test suite against real tools (node, python3, g++, SQLite) or the verified runners. */
const EXTRA_POOLS={
/* ---------- JavaScript ---------- */
js1:[[`const word = "ook";\nconsole.log(word + word);`,["ookook","ook ook","wordword"]],[`console.log("5" + "5");`,["55","10","5 5"]],[`let a = "x";\nconsole.log(a + 1);`,["x1","1","NaN"]]],
js2:[[`console.log(20 % 6);`,["2","3","3.33"]],[`console.log(3 * (2 + 2));`,["12","8","10"]],[`console.log(2 ** 3 ** 0);`,["2","1","8"]]],
js3:[[`console.log("Banana".toLowerCase().length);`,["6","banana","5"]],["const n = 4;\nconsole.log(`${n} * 2 = ${n * 2}`);",["4 * 2 = 8","n * 2 = 8","4 * 2 = n * 2"]],[`console.log("monkey".includes("key"));`,["true","false","key"]]],
js4:[[`let x = 10;\nx -= 4;\nx *= 2;\nconsole.log(x);`,["12","16","2"]],[`let s = "A";\ns = s + s;\ns = s + s;\nconsole.log(s);`,["AAAA","AA","AAA"]],[`let n = 7;\nn %= 3;\nconsole.log(n);`,["1","2","7"]]],
js5:[[`console.log(4 !== "4");`,["true","false","4"]],[`console.log(7 > 7);`,["false","true","7"]],[`console.log(1 + 1 === 2);`,["true","false","2"]]],
js6:[[`const age = 13;\nif (age >= 13) {\n  console.log("teen");\n} else {\n  console.log("kid");\n}`,["teen","kid","teen kid"]],[`const n = 0;\nif (n > 0) {\n  console.log("pos");\n} else {\n  console.log("not pos");\n}`,["not pos","pos","0"]],[`const w = "rain";\nif (w === "sun") {\n  console.log("shades");\n}\nconsole.log("done");`,["done","shades done","shades"]]],
js7:[[`console.log(!(3 > 2));`,["false","true","!true"]],[`const a = true, b = false;\nconsole.log(a || b && b);`,["true","false","truefalse"]],[`const t = 72;\nif (t > 80) console.log("hot");\nelse if (t > 60) console.log("warm");\nelse console.log("cold");`,["warm","hot","cold"]]],
js9:[[`for (let i = 1; i < 10; i *= 3) {\n  console.log(i);\n}`,["1 3 9","1 3 9 27","3 9"]],[`let s = "";\nfor (let i = 0; i < 4; i++) s += i;\nconsole.log(s);`,["0123","6","1234"]],[`for (let i = 5; i > 0; i -= 2) {\n  console.log(i);\n}`,["5 3 1","5 3","4 2"]]],
js10:[[`let n = 100;\nlet steps = 0;\nwhile (n > 1) {\n  n = n / 10;\n  steps++;\n}\nconsole.log(steps);`,["2","3","1"]],[`let i = 3;\nwhile (i--) {\n  console.log(i);\n}`,["2 1 0","3 2 1","2 1"]],[`let s = "";\nwhile (s.length < 3) s += "z";\nconsole.log(s);`,["zzz","zz","zzzz"]]],
js11:[[`let c = 0;\nfor (let i = 1; i <= 10; i++) {\n  if (i % 3 === 0) c++;\n}\nconsole.log(c);`,["3","4","10"]],[`for (let i = 0; i < 5; i++) {\n  if (i === 1) continue;\n  if (i === 3) break;\n  console.log(i);\n}`,["0 2","0 1 2","0 2 4"]],[`let big = 0;\nfor (const n of [4, 11, 7]) {\n  if (n > big) big = n;\n}\nconsole.log(big);`,["11","7","4"]]],
js13:[[`function hi(name) {\n  console.log("Hi " + name);\n}\nhi("Mo");`,["Hi Mo","Hi name","Hi"]],[`function f() {\n  console.log(1);\n  console.log(2);\n}\nf();`,["1 2","1","2"]],[`function f(a, b) {\n  console.log(b, a);\n}\nf("x", "y");`,["y x","x y","yx"]]],
js14:[[`function f(n) {\n  return n % 2 === 0;\n}\nconsole.log(f(7));`,["false","true","1"]],[`function f(a) {\n  return a + "!";\n}\nconsole.log(f(f("ook")));`,["ook!!","ook!","ook"]],[`function f(n) {\n  if (n > 10) return "big";\n  return "small";\n}\nconsole.log(f(10));`,["small","big","10"]]],
js15:[[`const add = (a, b) => a + b;\nconsole.log(add("1", 2));`,["12","3","NaN"]],[`const f = n => n * n;\nconsole.log(f(3) + f(1));`,["10","16","9"]],[`let count = 0;\nconst inc = () => { count++; };\ninc();\ninc();\nconsole.log(count);`,["2","0","1"]]],
js17:[[`const a = ["red", "green", "blue"];\nconsole.log(a[a.length - 2]);`,["green","blue","red"]],[`const a = [1, 2, 3];\na[1] = a[0] + a[2];\nconsole.log(a);`,["[1,4,3]","[1,2,3]","[4,2,3]"]],[`const a = [];\nconsole.log(a.length);`,["0","undefined","1"]]],
js18:[[`const a = [1, 2];\na.push(a.length);\nconsole.log(a);`,["[1,2,2]","[1,2,3]","[1,2]"]],[`const a = ["x", "y", "z"];\nconsole.log(a.indexOf("z"));`,["2","3","-1"]],[`const a = [9];\nconst p = a.pop();\nconsole.log(p, a.length);`,["9 0","9 1","0 9"]]],
js19:[[`let s = 0;\n[1, 2, 3, 4].forEach(n => s += n);\nconsole.log(s);`,["10","4","1234"]],[`const a = ["a", "b", "c"];\nfor (let i = a.length - 1; i >= 0; i--) {\n  console.log(a[i]);\n}`,["c b a","a b c","c b"]],[`let out = "";\nfor (const w of ["hi", "yo"]) out += w[0];\nconsole.log(out);`,["hy","hiyo","h"]]],
js20:[[`console.log([1, 2, 3, 4].filter(n => n % 2 === 1));`,["[1,3]","[2,4]","[1,2,3,4]"]],[`console.log([2, 4].map(n => n / 2));`,["[1,2]","[4,8]","[2,4]"]],[`console.log(["a", "bb", "ccc"].map(s => s.length));`,["[1,2,3]","[3,2,1]","[\"a\",\"bb\",\"ccc\"]"]]],
js22:[[`const p = { x: 1, y: 2 };\nconsole.log(p.x + p.y);`,["3","12","undefined"]],[`const o = { name: "Mo" };\nconsole.log(o.name.length);`,["2","4","undefined"]],[`const o = { a: { b: 5 } };\nconsole.log(o.a.b);`,["5","undefined","error"]]],
js23:[[`const o = { n: 1 };\no.n++;\no.m = o.n * 10;\nconsole.log(o.m);`,["20","10","11"]],[`const pet = {\n  sound: "woof",\n  speak() { return this.sound + "!"; }\n};\nconsole.log(pet.speak());`,["woof!","sound!","undefined!"]],[`const o = { a: 1 };\ndelete o.a;\nconsole.log(o.a);`,["undefined","1","null"]]],
js24:[[`const a = [{ n: "Ava", s: 3 }, { n: "Leo", s: 9 }];\nconsole.log(a.filter(x => x.s > 5).map(x => x.n));`,["[\"Leo\"]","[\"Ava\"]","[\"Ava\",\"Leo\"]"]],[`const a = [{ q: 2 }, { q: 3 }];\nlet t = 1;\nfor (const o of a) t *= o.q;\nconsole.log(t);`,["6","5","1"]],[`const a = [{ v: 1 }, { v: 2 }, { v: 3 }];\nconsole.log(a[a.length - 1].v);`,["3","1","undefined"]]],

/* ---------- Python ---------- */
py1:[[`print("a" + "b" * 2)`,["abb","abab","ab2"]],[`print(10 - 3, "apples")`,["7 apples","10 - 3 apples","7apples"]],[`print("Hi", end="")\nprint("!")`,["Hi!","Hi !","Hi"]]],
py2:[[`x = 3\ny = x * 2\nx = 10\nprint(y)`,["6","20","10"]],[`print(type("7"))`,["<class 'str'>","<class 'int'>","7"]],[`a = "4"\nprint(int(a) * 2)`,["8","44","4"]]],
py3:[[`s = "banana"\nprint(s[1:4])`,["ana","ban","anan"]],[`print("ook".upper() + "!")`,["OOK!","ook!","Ook!"]],[`n = 5\nprint(f"{n} squared is {n ** 2}")`,["5 squared is 25","5 squared is 10","n squared is 25"]]],
py4:[[`print(7 // 2 + 7 % 2)`,["4","3","3.5"]],[`print(abs(-7) + 1)`,["8","-6","6"]],[`print(min(5, 2, 9) * 10)`,["20","50","90"]]],
py5:[[`print(not True or False)`,["False","True","None"]],[`print(5 != 5)`,["False","True","5"]],[`print(3 < 5 < 4)`,["False","True","Error"]]],
py6:[[`n = 7\nif n % 2 == 0:\n    print("even")\nelse:\n    print("odd")`,["odd","even","7"]],[`x = 3\nif x > 5:\n    print("big")\nelif x > 1:\n    print("medium")`,["medium","big","small"]],[`a = 0\nif a:\n    print("yes")\nelse:\n    print("no")`,["no","yes","0"]]],
py8:[[`for c in "hi":\n    print(c * 2)`,["hh ii","hi hi","hhii"]],[`total = 0\nfor n in range(1, 4):\n    total += n * n\nprint(total)`,["14","6","9"]],[`print(list(range(2, 9, 3)))`,["[2, 5, 8]","[2, 5, 8, 11]","[3, 6, 9]"]]],
py9:[[`n = 0\nwhile n < 10:\n    n += 4\nprint(n)`,["12","10","8"]],[`i = 0\nwhile True:\n    i += 1\n    if i == 3:\n        break\nprint(i)`,["3","2","4"]],[`for i in range(5):\n    if i % 2:\n        continue\n    print(i)`,["0 2 4","1 3","0 1 2 3 4"]]],
py11:[[`def f(x):\n    return x * x\n\nprint(f(f(2)))`,["16","8","4"]],[`def hi():\n    print("hi")\n\nhi()\nhi()`,["hi hi","hi","None"]],[`def f(a, b):\n    return a - b\n\nprint(f(10, 3))`,["7","-7","13"]]],
py12:[[`def f(x, y=2):\n    return x ** y\n\nprint(f(3), f(2, 3))`,["9 8","6 6","9 6"]],[`def f(*, n=1):\n    return n * 10\n\nprint(f(n=4))`,["40","10","4"]],[`count = 5\n\ndef show():\n    print(count)\n\nshow()`,["5","0","Error"]]],
py14:[[`a = [3, 1, 2]\na.sort()\nprint(a)`,["[1, 2, 3]","[3, 1, 2]","[3, 2, 1]"]],[`a = [1, 2, 3]\na.remove(2)\nprint(a)`,["[1, 3]","[1, 2]","[2, 3]"]],[`a = ["x"]\na.insert(0, "y")\nprint(a)`,["['y', 'x']","['x', 'y']","['y']"]]],
py15:[[`print([c for c in "abc" if c != "b"])`,["['a', 'c']","['b']","['a', 'b', 'c']"]],[`a = [1, 2, 3, 4, 5]\nprint(a[1::2])`,["[2, 4]","[1, 3, 5]","[2, 3, 4, 5]"]],[`print([x * 10 for x in range(3)])`,["[0, 10, 20]","[10, 20, 30]","[0, 1, 2]"]]],
py16:[[`d = {"a": 1}\nd["a"] += 1\nprint(d)`,["{'a': 2}","{'a': 1}","2"]],[`d = {"x": 1, "y": 2}\nprint(len(d), "y" in d)`,["2 True","2 False","1 True"]],[`d = {}\nd["k"] = d.get("k", 0) + 5\nprint(d["k"])`,["5","0","Error"]]],
py18:[[`class C:\n    def __init__(self, n):\n        self.n = n\n    def double(self):\n        return self.n * 2\n\nprint(C(4).double())`,["8","4","None"]],[`class P:\n    count = 0\n    def __init__(self):\n        P.count += 1\n\nP()\nP()\nprint(P.count)`,["2","0","1"]],[`class D:\n    def __str__(self):\n        return "a dog"\n\nprint(D())`,["a dog","D","None"]]],
py19:[[`try:\n    x = 1 / 0\nexcept ZeroDivisionError:\n    x = -1\nprint(x)`,["-1","0","inf"]],[`try:\n    print("a")\nexcept ValueError:\n    print("b")\nfinally:\n    print("c")`,["a c","a b c","a"]],[`try:\n    int("7")\n    print("ok")\nexcept ValueError:\n    print("bad")`,["ok","bad","7"]]],

/* ---------- SQL ---------- */
sql1:[[`SELECT shift FROM keepers WHERE id = 3;`,["morning","night","Kai"]],[`SELECT name, species FROM animals WHERE id = 2;`,["Kiki | parrot","Mo | monkey","Kiki"]],[`SELECT qty FROM snacks WHERE id = 3;`,["20","3","bamboo"]]],
sql2:[[`SELECT name FROM animals WHERE species = 'monkey' AND age > 3;`,["Mo","Pip","Mo\nPip"]],[`SELECT food FROM snacks WHERE animal_id = 1;`,["banana\nmango","banana","mango"]],[`SELECT name FROM keepers WHERE shift <> 'night';`,["Ava\nKai","Leo\nMia","Ava"]]],
sql3:[[`SELECT name FROM animals ORDER BY name LIMIT 2;`,["Bao\nKiki","Mo\nKiki","Bao"]],[`SELECT food FROM snacks ORDER BY qty LIMIT 1;`,["mango","bamboo","seeds"]],[`SELECT name FROM animals ORDER BY age DESC LIMIT 1 OFFSET 1;`,["Zuri","Kiki","Bao"]]],
sql4:[[`SELECT COUNT(*) FROM snacks WHERE qty > 5;`,["3","2","4"]],[`SELECT MIN(age), MAX(age) FROM animals;`,["2 | 12","12 | 2","2"]],[`SELECT SUM(qty) FROM snacks WHERE animal_id = 1;`,["8","6","2"]]],
sql5:[[`SELECT keeper_id, COUNT(*) FROM animals WHERE keeper_id = 1 GROUP BY keeper_id;`,["1 | 3","1 | 1","3"]],[`SELECT shift FROM keepers GROUP BY shift HAVING COUNT(*) = 2 ORDER BY shift;`,["morning\nnight","morning","night"]],[`SELECT COUNT(*) FROM (SELECT food FROM snacks GROUP BY food);`,["5","6","2"]]],
sql6:[[`SELECT name FROM animals WHERE name LIKE '_o';`,["Mo","Bao\nOdo","Mo\nOdo"]],[`SELECT COUNT(*) FROM animals WHERE age BETWEEN 2 AND 5;`,["3","2","4"]],[`SELECT name FROM animals WHERE keeper_id IN (2, 3);`,["Kiki\nZuri","Kiki","Zuri"]]],
sql7:[[`SELECT k.shift FROM animals a JOIN keepers k ON a.keeper_id = k.id WHERE a.name = 'Mo';`,["morning","night","Ava"]],[`SELECT COUNT(*) FROM snacks s JOIN animals a ON s.animal_id = a.id WHERE a.species = 'monkey';`,["3","2","1"]],[`SELECT a.name FROM animals a JOIN keepers k ON a.keeper_id = k.id WHERE k.name = 'Leo';`,["Kiki","Mo","Zuri"]]],
sql8:[[`SELECT COUNT(*) FROM keepers k LEFT JOIN animals a ON a.keeper_id = k.id WHERE a.id IS NULL;`,["1","0","4"]],[`SELECT a.name, COUNT(s.id) FROM animals a LEFT JOIN snacks s ON s.animal_id = a.id WHERE a.id = 6 GROUP BY a.id;`,["Odo | 0","Odo | 1","Odo | NULL"]],[`SELECT COUNT(*) FROM animals a LEFT JOIN snacks s ON s.animal_id = a.id;`,["7","6","5"]]],
sql10:[[`INSERT INTO animals (id, name, species, age, keeper_id) VALUES (7, 'Lulu', 'lemur', 3, 2);\nSELECT COUNT(*) FROM animals WHERE keeper_id = 2;`,["2","1","3"]],[`INSERT INTO snacks (id, animal_id, food, qty) VALUES (9, 6, 'mice', 4), (10, 6, 'mice', 2);\nSELECT SUM(qty) FROM snacks WHERE food = 'mice';`,["6","4","2"]],[`INSERT INTO keepers (id, name, shift) VALUES (8, 'Ro', 'night');\nSELECT name FROM keepers ORDER BY id DESC LIMIT 1;`,["Ro","Mia","Ava"]]],
sql11:[[`UPDATE snacks SET qty = 0 WHERE food = 'seeds';\nSELECT SUM(qty) FROM snacks;`,["46","50","4"]],[`DELETE FROM snacks WHERE animal_id = 1;\nSELECT COUNT(*) FROM snacks;`,["4","5","6"]],[`UPDATE keepers SET name = 'Ava B' WHERE id = 1;\nSELECT name FROM keepers WHERE id = 1;`,["Ava B","Ava","1"]]],

/* ---------- C# ---------- */
cs1:[[`Console.Write("Hi");\nConsole.WriteLine("!");\nConsole.WriteLine("Bye");`,["Hi! Bye","Hi ! Bye","Hi!Bye"]],[`Console.WriteLine("a" + "b" + 1);`,["ab1","ab","a b 1"]],[`Console.WriteLine(1 + 2 + "3");`,["33","123","6"]]],
cs2:[[`int a = 5;\nint b = a;\na = 9;\nConsole.WriteLine(b);`,["5","9","0"]],[`string s = "ook";\nConsole.WriteLine($"{s}{s}");`,["ookook","ook ook","{s}{s}"]],[`var x = 2.5;\nConsole.WriteLine(x * 4);`,["10","10.0","2.54"]]],
cs3:[[`Console.WriteLine(7 % 3);`,["1","2","2.33"]],[`int n = 5;\nif (n > 3 && n < 10) Console.WriteLine("in");\nelse Console.WriteLine("out");`,["in","out","5"]],[`Console.WriteLine(10 / 3 * 3);`,["9","10","9.99"]]],
cs4:[[`int total = 0;\nfor (int i = 1; i <= 5; i++) total += i;\nConsole.WriteLine(total);`,["15","5","10"]],[`int n = 1;\ndo {\n  n *= 3;\n} while (n < 20);\nConsole.WriteLine(n);`,["27","9","20"]],[`for (int i = 0; i < 6; i += 2) Console.Write(i);`,["024","0246","246"]]],
cs5:[[`static int Sq(int n) => n * n;\n\nConsole.WriteLine(Sq(3) + Sq(2));`,["13","25","10"]],[`static string Twice(string s) => s + s;\n\nConsole.WriteLine(Twice("ha"));`,["haha","ha","ha ha"]],[`static void Hi() {\n  Console.Write("Hi ");\n}\n\nHi();\nHi();`,["Hi Hi","Hi","HiHi"]]],
cs7:[[`Cat c = new Cat("Tom");\nConsole.WriteLine(c.Name.ToUpper());\n\nclass Cat {\n  public string Name;\n  public Cat(string n) { Name = n; }\n}`,["TOM","Tom","CAT"]],[`P p = new P();\np.X = 4;\nP q = p;\nq.X++;\nConsole.WriteLine(p.X);\n\nclass P {\n  public int X;\n}`,["5","4","0"]],[`B b = new B();\nConsole.WriteLine(b.Size * 2);\n\nclass B {\n  public int Size = 7;\n}`,["14","7","0"]]],
cs8:[[`Acct a = new Acct();\na.Add(5);\na.Add(-2);\nConsole.WriteLine(a.Total);\n\nclass Acct {\n  public int Total { get; private set; }\n  public void Add(int n) { if (n > 0) Total += n; }\n}`,["5","3","-2"]],[`Pet p = new Pet();\nConsole.WriteLine(p.Hi());\n\nclass Pet {\n  public string Name { get; set; } = "Rex";\n  public string Hi() => $"I am {Name}";\n}`,["I am Rex","I am Name","Rex"]],[`T t = new T();\nt.Flip();\nt.Flip();\nConsole.WriteLine(t.On);\n\nclass T {\n  public bool On { get; set; }\n  public void Flip() { On = !On; }\n}`,["False","True","2"]]],
cs10:[[`var l = new List<int> { 5, 6 };\nl.Insert(0, 4);\nConsole.WriteLine(l[0] + l.Count);`,["7","4","9"]],[`int[] a = { 2, 4, 6 };\nint s = 0;\nforeach (int x in a) s += x;\nConsole.WriteLine(s);`,["12","6","3"]],[`var l = new List<string> { "a", "b", "c" };\nl.RemoveAt(1);\nConsole.WriteLine(string.Join("", l));`,["ac","ab","bc"]]],
cs11:[[`var d = new Dictionary<string, int> { ["x"] = 1 };\nd["y"] = d["x"] + 1;\nConsole.WriteLine(d["y"]);`,["2","1","0"]],[`var d = new Dictionary<string, int> { ["a"] = 3 };\nd.Remove("a");\nConsole.WriteLine(d.Count);`,["0","1","3"]],[`var d = new Dictionary<int, string> { [1] = "one", [2] = "two" };\nConsole.WriteLine(d[2]);`,["two","one","2"]]],

/* ---------- C++ ---------- */
cpp1:[[`std::cout << "A" << 1 << "B";`,["A1B","A 1 B","AB1"]],[`std::cout << 7 * 6 << "\\n" << 6 * 7;`,["42 42","4242","42"]],[`std::cout << "Hi" << std::endl << "Bye";`,["Hi Bye","HiBye","Hi"]]],
cpp2:[[`int a = 3;\nint b = a * a;\nstd::cout << b;`,["9","6","33"]],[`std::string s = "ook";\ns += "!";\nstd::cout << s;`,["ook!","ook","!"]],[`bool t = 5 > 2;\nstd::cout << t + 1;`,["2","true1","1"]]],
cpp3:[[`std::cout << 17 / 5 << " " << 17 % 5;`,["3 2","3.4 2","3 3"]],[`int n = 4;\nif (n % 2 == 0) std::cout << "even";\nelse std::cout << "odd";`,["even","odd","4"]],[`std::cout << (5 > 3 || 2 > 4);`,["1","0","true"]]],
cpp4:[[`int s = 0;\nfor (int i = 1; i <= 3; i++) s += i * 10;\nstd::cout << s;`,["60","30","6"]],[`int n = 3;\nwhile (n > 0) {\n  std::cout << n;\n  n--;\n}`,["321","3210","123"]],[`for (int i = 0; i < 4; i++) {\n  if (i == 2) continue;\n  std::cout << i;\n}`,["013","0123","01"]]],
cpp5:[[`int add(int a, int b) { return a + b; }\nint main() {\n  std::cout << add(add(1, 2), 3);\n}`,["6","3","123"]],[`bool even(int n) { return n % 2 == 0; }\nint main() {\n  std::cout << even(10) << even(3);\n}`,["10","01","11"]],[`void hi() { std::cout << "hey "; }\nint main() {\n  hi();\n  hi();\n  hi();\n}`,["hey hey hey","hey","heyheyhey"]]],
cpp7:[[`int a = 10;\nint& r = a;\nr *= 2;\nstd::cout << a;`,["20","10","0"]],[`void inc(int& x) { x++; }\nint main() {\n  int n = 0;\n  inc(n);\n  inc(n);\n  std::cout << n;\n}`,["2","0","1"]],[`int a = 1;\nint b = 2;\nint& r = b;\nr = a;\nstd::cout << b;`,["1","2","3"]]],
cpp8:[[`int a = 5;\nint* p = &a;\n*p += 3;\nstd::cout << a;`,["8","5","3"]],[`int x = 1, y = 9;\nint* p = &x;\np = &y;\nstd::cout << *p;`,["9","1","0"]],[`int a = 2;\nint* p = &a;\nint* q = &a;\nstd::cout << (p == q);`,["1","0","2"]]],
cpp10:[[`std::vector<int> v = {1, 2, 3};\nv.push_back(v.size());\nstd::cout << v.back();`,["3","4","1"]],[`std::vector<int> v;\nfor (int i = 0; i < 3; i++) v.push_back(i * i);\nstd::cout << v[2];`,["4","2","9"]],[`std::vector<std::string> v = {"a", "b"};\nv.pop_back();\nstd::cout << v.size();`,["1","2","0"]]],
cpp11:[[`struct Pt {\n  int x = 0, y = 0;\n};\nint main() {\n  Pt p;\n  p.y = 4;\n  std::cout << p.x + p.y;\n}`,["4","0","8"]],[`class C {\npublic:\n  int v;\n  C(int n) : v(n * 2) {}\n};\nint main() {\n  C c(5);\n  std::cout << c.v;\n}`,["10","5","0"]],[`class P {\npublic:\n  int n = 1;\n  void grow() { n *= 3; }\n};\nint main() {\n  P a;\n  P b = a;\n  a.grow();\n  std::cout << a.n << b.n;\n}`,["31","33","11"]]],
};
for(const course of [COURSE_JS,COURSE_PY,COURSE_SQL,COURSE_CS,COURSE_CPP])for(const u of course.units)for(const l of u.lessons){
  const extra=EXTRA_POOLS[l.id];if(extra&&l.pool&&!l.__extra){l.pool.push(...extra);l.__extra=true}
}
