/* Swift course. Runs in TypeMonkey's in-house Swift runner (src/engines/swift.js).
   Answers are checked against the runner by tests/verify_swift.py, and against real Swift 6 by
   tests/verify_swift_real.py when a Swift compiler is available. */
const COURSE_SWIFT={id:"swift",name:"Swift",blurb:"Apple's language for iPhone, iPad and Mac apps. Clean, safe and fun to write. Unit 1 is free.",units:[
{name:"Hello, Swift",free:true,lessons:[
{id:"sw1",title:"Hello, Swift",sub:"print and your first program",steps:[
 {type:"talk",title:"Meet Swift",mood:"cheer",
  body:`<p>Swift is the language Apple made for iPhone, iPad, Mac and Apple Watch apps. It's modern and tidy: no semicolons needed, no <code class="i">main</code> method to write. Your code just runs from the top.</p>`,
  say:"Every app on your phone could have been written in Swift!"},
 {type:"talk",title:"Printing",
  body:`<p>${C("print()")} shows something and moves to a new line. Text goes in double quotes. Each statement goes on its own line.</p>`,
  demo:`print("Hello, world!")\nprint("I'm learning Swift")\nprint(2 + 3)`,
  say:"Output:\nHello, world!\nI'm learning Swift\n5"},
 {type:"talk",title:"Printing several things",mood:"think",
  body:`<p>Give ${C("print")} several values separated by commas and it puts a space between them. Add ${C('terminator: ""')} to stay on the same line.</p>`,
  demo:`print("Bananas:", 12)\nprint("Ook", terminator: " ")\nprint("ook!")\n// this is a comment: Swift ignores it`,
  say:"Bananas: 12, then Ook ook! on one line."},
 {type:"quiz",q:"What does this print?",code:`print("Hi", "there")`,opts:["Hi there","Hithere","Hi, there"],a:0,mono:true,why:"print puts a space between the values."},
 {type:"quiz",q:"Does Swift need a semicolon at the end of each line?",opts:["No, a new line ends the statement","Yes, always","Only inside functions"],a:0,why:"You only need ; to put two statements on one line."},
 {type:"fill",title:"Print a line",body:`<p>Print Hello.</p>`,code:`[0]("Hello")`,blanks:["print"],tokens:["print","console.log","echo","say"],why:"Swift uses print()."},
 {type:"quiz",q:"What does this print?",code:`print("A", terminator: "")\nprint("B")`,opts:["AB","A B","A\nB"],a:0,mono:true,why:"terminator: \"\" stops print from starting a new line."},
 {type:"code",title:"Your first program",body:`<p>Print ${C("Hello, Swift!")} on one line and ${C("I can code!")} on the next.</p>`,start:`// your code here\n`,
  use:[[/print\s*\(/,"Use print(...)."]],out:["Hello, Swift!","I can code!"],hint:`print("Hello, Swift!")\nprint("I can code!")`},
 {type:"code",title:"Let Swift do the math",body:`<p>Print the answer to ${C("15 * 4")}. Put the math inside print.</p>`,start:`// print 15 * 4\n`,
  use:[[/15\s*\*\s*4/,"Put the math in your code: print(15 * 4)"]],out:["60"],hint:`print(15 * 4)`},
 {type:"game"},{type:"done"}],
 pool:[
  [`print("Ook" + "!")`,["Ook!","Ook +!","Ook !"]],
  [`print(6 * 7)`,["42","6 * 7","67"]],
  [`print("6 * 7")`,["6 * 7","42","67"]],
  [`print("a", "b", "c")`,["a b c","abc","a,b,c"]],
  [`print(10 - 3)`,["7","10 - 3","13"]],
  [`print("x", terminator: "")\nprint("y")`,["xy","x y","yx"]]
 ]},
{id:"sw2",title:"let, var & types",sub:"constants, variables, Int, Double, String, Bool",steps:[
 {type:"talk",title:"let and var",
  body:`<p>${C("let")} makes a <b>constant</b>: it can never change. ${C("var")} makes a <b>variable</b> you can change. Swift fans use ${C("let")} whenever they can.</p>`,
  demo:`let name = "Mo"\nvar bananas = 3\nbananas = bananas + 2\nprint(name, "has", bananas, "bananas")`,
  say:"Try adding name = \"Kiki\" and Swift will refuse: it's a let."},
 {type:"talk",title:"Types",mood:"think",
  body:`<p>Every value has a type: ${C("Int")} whole numbers, ${C("Double")} decimals, ${C("String")} text, ${C("Bool")} true/false. Swift usually works the type out for you, but you can write it with a colon.</p>`,
  demo:`let lives: Int = 3\nlet price: Double = 1.99\nlet pet: String = "owl"\nlet hungry: Bool = true\nlet guess = 4.0      // Swift infers Double\nprint(lives, price, pet, hungry, guess)`,
  say:"Notice 4.0 prints as 4.0, not 4. It's a Double."},
 {type:"talk",title:"Putting values in text",mood:"cheer",
  body:`<p>Write ${C("\\(something)")} inside a string to drop a value in. This is called <b>string interpolation</b>, and it works with any value, even math.</p>`,
  demo:`let name = "Mo"\nlet age = 4\nprint("\\(name) is \\(age) years old")\nprint("Next year: \\(age + 1)")`,
  say:"Output:\nMo is 4 years old\nNext year: 5"},
 {type:"talk",title:"Types don't mix by accident",mood:"oops",
  body:`<p>Swift won't silently mix types. Gluing a number onto a String with ${C("+")} or adding an Int variable to a Double variable is an error. Convert on purpose with ${C("String(...)")} or ${C("Double(...)")}.</p>`,
  demo:`let coins = 5\nlet bonus = 2.5\nprint("Coins: " + String(coins))\nprint(Double(coins) + bonus)`,
  say:"Coins: 5, then 7.5."},
 {type:"quiz",q:"Which one can never change after it's set?",opts:["let","var","both"],a:0,mono:true,why:"let is a constant. Use var when the value will change."},
 {type:"quiz",q:"What does this print?",code:`let x = 7.0\nprint(x)`,opts:["7.0","7","x"],a:0,mono:true,why:"x is a Double, and Doubles always print with a decimal point."},
 {type:"quiz",q:"What does this print?",code:`let n = 3\nprint("I have \\(n * 2) bananas")`,opts:["I have 6 bananas","I have n * 2 bananas","I have \\(6) bananas"],a:0,mono:true,why:"Swift works out n * 2 inside \\( )."},
 {type:"quiz",q:"Which line is an error?",code:`let a = 3\nlet b = 1.5`,opts:["print(a + b)","print(Double(a) + b)","print(a * 2)"],a:0,mono:true,why:"a is an Int and b is a Double, so they can't be added until you convert one."},
 {type:"fill",title:"Pick the keyword",body:`<p>The name never changes, but the score does.</p>`,code:`[0] player = "Kiki"\n[1] score = 0\nscore = 10\nprint(player, score)`,blanks:["let","var"],tokens:["let","var","const","int"],why:"let for things that stay the same, var for things that change."},
 {type:"code",title:"Monkey profile",body:`<p>Make a constant ${C("name")} set to ${C("Mo")} and a variable ${C("age")} set to ${C("4")}. Then print ${C("Mo is 4 years old")} using string interpolation.</p>`,start:`// make name and age, then print\n`,
  use:[[/let\s+name\s*=/,"Make name with let."],[/var\s+age\s*=|let\s+age\s*=/,"Make age."],[/\\\(/,"Use \\( ) to put the values into the text."]],out:["Mo is 4 years old"],variants:[[/age\s*=\s*4/,"age = 9",["Mo is 9 years old"]]],
  hint:`let name = "Mo"\nvar age = 4\nprint("\\(name) is \\(age) years old")`},
 {type:"game"},{type:"done"}],
 pool:[
  [`var a = 4\na = a + 1\nprint(a)`,["5","4","a + 1"]],
  [`let s = "ook"\nprint(s + s)`,["ookook","ook ook","s + s"]],
  [`let n = 3\nprint("n\\(n)")`,["n3","n\\(n)","3"]],
  [`let x = 2.5\nprint(x * 2)`,["5.0","5","2.52.5"]],
  [`let b = false\nprint(b)`,["false","False","0"]],
  [`let n = 5\nprint("Total: " + String(n))`,["Total: 5","Total: n","Error"]],
  [`var t = 10\nt += 5\nprint(t)`,["15","105","10"]]
 ]},
{id:"sw3",title:"Math",sub:"Int and Double math, conversion, remainder",steps:[
 {type:"talk",title:"Whole-number division",mood:"oops",
  body:`<p>When both numbers are ${C("Int")}, ${C("/")} drops the decimal part, and ${C("%")} gives the remainder. With Doubles you get the decimal answer.</p>`,
  demo:`print(7 / 2)\nprint(7 % 2)\nprint(7.0 / 2.0)\nprint(10.0 / 4)`,
  say:"3, 1, 3.5, 2.5. (Plain numbers like 4 can become a Double when they need to.)"},
 {type:"talk",title:"Converting",
  body:`<p>${C("Double(x)")} turns an Int into a Double. ${C("Int(x)")} chops the decimal off a Double (it doesn't round). Use ${C(".rounded()")} to round.</p>`,
  demo:`let total = 7\nlet count = 2\nprint(Double(total) / Double(count))\nprint(Int(9.99))\nprint((2.5).rounded())\nprint(Int((9.6).rounded()))`,
  say:"3.5, 9, 3.0, 10."},
 {type:"talk",title:"Shortcuts and helpers",mood:"cheer",
  body:`<p>${C("+=")}, ${C("-=")}, ${C("*=")} and ${C("/=")} update a variable. Swift has no ${C("++")}. ${C("min")}, ${C("max")} and ${C("abs")} are built in, and ${C(".isMultiple(of:)")} checks divisibility.</p>`,
  demo:`var bananas = 10\nbananas += 5\nbananas -= 3\nbananas *= 2\nprint(bananas)\nprint(max(4, 9), min(4, 9), abs(-6))\nprint(12.isMultiple(of: 4))`,
  say:"24, then 9 4 6, then true."},
 {type:"quiz",q:"What does this print?",code:`print(17 / 5)`,opts:["3","3.4","4"],a:0,mono:true,why:"Both are Ints, so the .4 is dropped."},
 {type:"quiz",q:"What does this print?",code:`print(17 % 5)`,opts:["2","3","3.4"],a:0,mono:true,why:"17 = 3 × 5 + 2."},
 {type:"quiz",q:"What does this print?",code:`print(Int(4.8))`,opts:["4","5","4.8"],a:0,mono:true,why:"Int(...) chops the decimal part off."},
 {type:"quiz",q:"How do you add 1 to score in Swift?",opts:["score += 1","score++","score =+ 1"],a:0,mono:true,why:"Swift removed ++ on purpose. Use += 1."},
 {type:"fill",title:"Share the bananas",body:`<p>Work out each monkey's share and the leftovers.</p>`,code:`let bananas = 17\nlet monkeys = 5\nprint(bananas [0] monkeys)\nprint(bananas [1] monkeys)`,blanks:["/","%"],tokens:["/","%","*","-"],out:"3\n2",why:"/ shares, % finds what's left."},
 {type:"code",title:"Average score",body:`<p>Print the average of the three scores <b>with</b> its decimal part. Convert to Double before you divide.</p>`,start:`let a = 90\nlet b = 85\nlet c = 80\n// print the average\n`,
  use:[[/Double\s*\(/,"Convert with Double(...)."]],out:["85.0"],variants:[[/c = 80/,"c = 81",["85.33333333333333"]]],
  hint:`let a = 90\nlet b = 85\nlet c = 80\nprint(Double(a + b + c) / 3)`},
 {type:"code",title:"Even or odd",body:`<p>Print ${C("true")} if ${C("n")} is even and ${C("false")} if it's odd, using ${C("%")} or ${C(".isMultiple(of:)")}.</p>`,start:`let n = 14\n// your code here\n`,
  use:[[/%\s*2|isMultiple/,"Check n % 2 == 0, or n.isMultiple(of: 2)."]],out:["true"],variants:[[/n = 14/,"n = 7",["false"]]],
  hint:`let n = 14\nprint(n % 2 == 0)`},
 {type:"game"},{type:"done"}],
 pool:[
  [`print(9 / 2)`,["4","4.5","5"]],
  [`print(9 % 4)`,["1","2","2.25"]],
  [`print(9.0 / 2)`,["4.5","4","4.0"]],
  [`print(Int(7.9))`,["7","8","7.9"]],
  [`print(max(3, 8))`,["8","3","8.0"]],
  [`var x = 5\nx *= 3\nprint(x)`,["15","8","53"]],
  [`print(2 + 3 * 4)`,["14","20","24"]],
  [`print(Double(5) / 2)`,["2.5","2","2.0"]],
  [`print(10.isMultiple(of: 3))`,["false","true","1"]]
 ]},
{id:"sw4",title:"Strings",sub:"count, case, searching and characters",steps:[
 {type:"talk",title:"String superpowers",
  body:`<p>Strings know lots of tricks: ${C(".count")} (no parentheses!), ${C(".uppercased()")}, ${C(".lowercased()")}, ${C(".hasPrefix()")}, ${C(".contains()")} and ${C(".isEmpty")}.</p>`,
  demo:`let word = "Monkey"\nprint(word.count)\nprint(word.uppercased())\nprint(word.hasPrefix("Mon"))\nprint(word.contains("key"))\nprint("".isEmpty)`,
  say:"6, MONKEY, true, true, true."},
 {type:"talk",title:"Characters",mood:"think",
  body:`<p>A String is made of ${C("Character")}s. Loop over them with ${C("for c in word")}. ${C(".reversed()")} flips them; wrap it in ${C("String(...)")} to get text back.</p>`,
  demo:`let word = "banana"\nvar count = 0\nfor c in word {\n    if c == "a" {\n        count += 1\n    }\n}\nprint(count)\nprint(String(word.reversed()))`,
  say:"3, then ananab."},
 {type:"talk",title:"Splitting and joining",mood:"cheer",
  body:`<p>${C('.split(separator: " ")')} chops a String into pieces. ${C('.joined(separator: "-")')} glues an array of Strings back together.</p>`,
  demo:`let sentence = "ook eek ah"\nlet parts = sentence.split(separator: " ")\nprint(parts)\nprint(parts.count)\nprint(parts.joined(separator: "-"))`,
  say:"[\"ook\", \"eek\", \"ah\"], 3, ook-eek-ah."},
 {type:"talk",title:"No s[0] in Swift",mood:"oops",
  body:`<p>Swift strings can't be read with ${C("s[0]")}, because some characters (like emoji) take up more space than others. Use ${C(".first")}, ${C(".prefix(n)")}, or turn it into an array with ${C("Array(s)")}.</p>`,
  demo:`let s = "Swift"\nprint(s.prefix(3))\nlet letters = Array(s)\nprint(letters[0], letters[4])`,
  say:"Swi, then S t."},
 {type:"quiz",q:"What does this print?",code:`print("TypeMonkey".count)`,opts:["10","9","11"],a:0,mono:true,why:"10 characters. And it's .count, not .count()."},
 {type:"quiz",q:"What does this print?",code:`print("ook".uppercased())`,opts:["OOK","ook","Ook"],a:0,mono:true,why:"uppercased() turns every letter into a capital."},
 {type:"quiz",q:"What does this print?",code:`print(String("abc".reversed()))`,opts:["cba","abc","[c, b, a]"],a:0,mono:true,why:"reversed() flips the characters and String(...) turns them back into text."},
 {type:"fill",title:"Check the start",body:`<p>Print true if the file name starts with "img".</p>`,code:`let file = "img_042.png"\nprint(file.[0]("img"))\nprint(file.[1]("png"))`,blanks:["hasPrefix","hasSuffix"],tokens:["hasPrefix","hasSuffix","startsWith","contains"],out:"true\ntrue",why:"hasPrefix checks the start, hasSuffix checks the end."},
 {type:"code",title:"Shout it",body:`<p>Print ${C("word")} in capitals with ${C("!")} on the end, then print how many letters it has.</p>`,start:`let word = "banana"\n// your code here\n`,
  use:[[/uppercased\s*\(\s*\)/,"Use .uppercased()."],[/\.count/,"Use .count to count."]],out:["BANANA!","6"],variants:[[/"banana"/,"\"kiwi\"",["KIWI!","4"]]],
  hint:`let word = "banana"\nprint(word.uppercased() + "!")\nprint(word.count)`},
 {type:"code",title:"Vowel counter",body:`<p>Count the vowels (a, e, i, o, u) in ${C("text")} and print the number.</p>`,start:`let text = "hello world"\n// your code here\n`,
  use:[[/for\s+\w+\s+in/,"Loop over the characters with for c in text."]],out:["3"],variants:[[/"hello world"/,"\"banana split\"",["4"]]],
  hint:`let text = "hello world"\nvar vowels = 0\nfor c in text {\n    if "aeiou".contains(c) {\n        vowels += 1\n    }\n}\nprint(vowels)`},
 {type:"game"},{type:"done"}],
 pool:[
  [`print("monkey".count)`,["6","5","7"]],
  [`print("Hi".lowercased())`,["hi","HI","Hi"]],
  [`print("banana".contains("nan"))`,["true","false","2"]],
  [`print("a-b-c".split(separator: "-").count)`,["3","5","2"]],
  [`print(["x", "y"].joined(separator: "+"))`,["x+y","xy","[x, y]"]],
  [`print("Swift".prefix(2))`,["Sw","S","ift"]],
  [`print("".isEmpty)`,["true","false","0"]],
  [`print(String("ook".reversed()))`,["koo","ook","oko"]]
 ]}
]},
{name:"Decisions & loops",lessons:[
{id:"sw5",title:"Making decisions",sub:"if, else, && and ||",steps:[
 {type:"talk",title:"if and else",
  body:`<p>${C("if")} runs a block when its condition is true. No parentheses needed around the condition, but the curly braces are required.</p>`,
  demo:`let bananas = 7\nif bananas > 10 {\n    print("Feast!")\n} else if bananas > 5 {\n    print("Snack time")\n} else {\n    print("Hungry...")\n}`,
  say:"Snack time"},
 {type:"talk",title:"Comparing and combining",mood:"think",
  body:`<p>${C("==")} equal, ${C("!=")} not equal, ${C("<")} ${C(">")} ${C("<=")} ${C(">=")}. Combine with ${C("&&")} (and), ${C("||")} (or) and ${C("!")} (not). In Swift, ${C("==")} works on Strings too.</p>`,
  demo:`let temp = 25\nlet sunny = true\nif temp > 20 && sunny {\n    print("Beach day!")\n}\nlet pet = "owl"\nprint(pet == "owl", pet != "cat", !sunny)`,
  say:"Beach day!, then true true false."},
 {type:"talk",title:"The ternary shortcut",mood:"cheer",
  body:`<p>${C("condition ? a : b")} picks a value. Great for short choices.</p>`,
  demo:`let score = 82\nlet result = score >= 50 ? "pass" : "try again"\nprint(result)`,
  say:"pass"},
 {type:"quiz",q:"What does this print?",code:`let x = 5\nif x > 3 {\n    print("big")\n} else {\n    print("small")\n}`,opts:["big","small","big small"],a:0,mono:true,why:"5 > 3 is true."},
 {type:"quiz",q:"What does this print?",code:`print(true && false)`,opts:["false","true","Error"],a:0,mono:true,why:"&& needs both sides true."},
 {type:"quiz",q:"Is this valid Swift?",code:`let n = 1\nif n {\n    print("yes")\n}`,opts:["No, the condition must be a Bool","Yes, 1 counts as true","Yes, but it prints nothing"],a:0,mono:true,why:"Swift needs a real true/false. Write if n == 1 or if n != 0."},
 {type:"fill",title:"Ticket price",body:`<p>Kids under 12 pay 5, everyone else pays 9.</p>`,code:`let age = 8\n[0] age < 12 {\n    print(5)\n} [1] {\n    print(9)\n}`,blanks:["if","else"],tokens:["if","else","when","for"],out:"5",why:"if / else picks one."},
 {type:"order",title:"Grade checker",body:`<p>Put the lines in order so 85 prints B.</p>`,lines:["let score = 85","if score >= 90 {","    print(\"A\")","} else if score >= 80 {","    print(\"B\")","} else {","    print(\"C\")","}"],out:"B",why:"Check the highest grade first."},
 {type:"code",title:"Grade machine",body:`<p>Print ${C("A")} for 90 and up, ${C("B")} for 80 and up, ${C("C")} for 70 and up, and ${C("Try again")} for lower scores.</p>`,start:`let score = 72\n// your code here\n`,
  use:[[/else\s+if/,"Use else if for the middle grades."]],out:["C"],variants:[[/score = 72/,"score = 95",["A"]],[/score = 72/,"score = 80",["B"]],[/score = 72/,"score = 50",["Try again"]]],
  hint:`let score = 72\nif score >= 90 {\n    print("A")\n} else if score >= 80 {\n    print("B")\n} else if score >= 70 {\n    print("C")\n} else {\n    print("Try again")\n}`},
 {type:"code",title:"Can I ride?",body:`<p>Riders must be at least 120 cm tall <b>and</b> at least 8 years old. Print ${C("Ride on!")} or ${C("Sorry")}.</p>`,start:`let height = 130\nlet age = 7\n// your code here\n`,
  use:[[/&&/,"Both rules must be true: use &&."]],out:["Sorry"],variants:[[/age = 7/,"age = 9",["Ride on!"]],[/height = 130/,"height = 110",["Sorry"]]],
  hint:`let height = 130\nlet age = 7\nif height >= 120 && age >= 8 {\n    print("Ride on!")\n} else {\n    print("Sorry")\n}`},
 {type:"game"},{type:"done"}],
 pool:[
  [`print(5 >= 5)`,["true","false","5"]],
  [`print(!(2 > 1))`,["false","true","!true"]],
  [`print(false || true)`,["true","false","Error"]],
  [`let t = 15\nprint(t > 20 ? "hot" : "cool")`,["cool","hot","15"]],
  [`var x = 10\nif x > 5 {\n    x *= 2\n}\nprint(x)`,["20","10","5"]],
  [`let p = "cat"\nprint(p == "dog" || p.count == 3)`,["true","false","cat"]],
  [`let n = 7\nif n > 10 {\n    print("A")\n} else if n > 5 {\n    print("B")\n} else {\n    print("C")\n}`,["B","A","C"]]
 ]},
{id:"sw6",title:"switch",sub:"matching values, ranges and more",steps:[
 {type:"talk",title:"Swift's switch is smart",
  body:`<p>${C("switch")} checks a value against ${C("case")}s. Unlike many languages, Swift <b>never falls through</b> to the next case, so no ${C("break")} needed. One case can list several values.</p>`,
  demo:`let fruit = "kiwi"\nswitch fruit {\ncase "apple", "pear":\n    print("Grows on a tree")\ncase "kiwi", "grape":\n    print("Grows on a vine")\ndefault:\n    print("No idea!")\n}`,
  say:"Grows on a vine"},
 {type:"talk",title:"Ranges in cases",mood:"cheer",
  body:`<p>A case can be a <b>range</b>: ${C("90...100")} includes both ends, ${C("80..<90")} stops just before 90.</p>`,
  demo:`let score = 85\nswitch score {\ncase 90...100:\n    print("A")\ncase 80..<90:\n    print("B")\ncase 70..<80:\n    print("C")\ndefault:\n    print("Keep practicing")\n}`,
  say:"B"},
 {type:"talk",title:"It must cover everything",mood:"think",
  body:`<p>A switch has to handle <b>every</b> possible value. For numbers and Strings that means you need a ${C("default")}. ${C("case let x where ...")} catches values that pass a test.</p>`,
  demo:`let n = 42\nswitch n {\ncase 0:\n    print("zero")\ncase let x where x % 2 == 0:\n    print("\\(x) is even")\ndefault:\n    print("odd")\n}`,
  say:"42 is even"},
 {type:"quiz",q:"What does this print?",code:`let x = 1\nswitch x {\ncase 1:\n    print("A")\ncase 2:\n    print("B")\ndefault:\n    print("C")\n}`,opts:["A","AB","ABC"],a:0,mono:true,why:"Swift stops after the matching case. No fall-through."},
 {type:"quiz",q:"Which numbers does 1..<5 include?",opts:["1, 2, 3, 4","1, 2, 3, 4, 5","2, 3, 4"],a:0,mono:true,why:"..< stops just before the end. ... includes it."},
 {type:"quiz",q:"What happens if a switch on an Int has no default?",opts:["Swift won't build it: switch must be exhaustive","It just does nothing","It crashes when no case matches"],a:0,why:"Swift makes you handle every possible value."},
 {type:"fill",title:"Teen or not",body:`<p>Match the teenage years.</p>`,code:`let age = 15\nswitch age {\ncase 13[0]19:\n    print("teen")\n[1]:\n    print("not a teen")\n}`,blanks:["...","default"],tokens:["...","default","..<","else"],out:"teen",why:"13...19 includes 19, and default catches the rest."},
 {type:"code",title:"Day namer",body:`<p>Use a switch on ${C("day")}: 6 → ${C("Saturday")}, 7 → ${C("Sunday")}, 1 to 5 → ${C("Weekday")}, anything else → ${C("Not a day")}.</p>`,start:`let day = 6\n// your switch here\n`,
  use:[[/\bswitch\b/,"Use a switch."]],out:["Saturday"],variants:[[/day = 6/,"day = 7",["Sunday"]],[/day = 6/,"day = 3",["Weekday"]],[/day = 6/,"day = 9",["Not a day"]]],
  hint:`let day = 6\nswitch day {\ncase 1...5:\n    print("Weekday")\ncase 6:\n    print("Saturday")\ncase 7:\n    print("Sunday")\ndefault:\n    print("Not a day")\n}`},
 {type:"game"},{type:"done"}],
 pool:[
  [`let n = 2\nswitch n {\ncase 1: print("one")\ncase 2: print("two")\ndefault: print("?")\n}`,["two","one","?"]],
  [`let n = 50\nswitch n {\ncase 0..<10: print("small")\ncase 10..<100: print("medium")\ndefault: print("big")\n}`,["medium","small","big"]],
  [`let c = "b"\nswitch c {\ncase "a", "e", "i", "o", "u": print("vowel")\ndefault: print("consonant")\n}`,["consonant","vowel","b"]],
  [`let x = 10\nswitch x {\ncase let v where v > 5: print(v * 2)\ndefault: print(0)\n}`,["20","10","0"]],
  [`let t = 100\nswitch t {\ncase 1...100: print("in")\ndefault: print("out")\n}`,["in","out","100"]]
 ]},
{id:"sw7",title:"Loops",sub:"for-in, ranges, stride, while, repeat",steps:[
 {type:"talk",title:"for-in with ranges",
  body:`<p>${C("for i in 1...5")} runs with i = 1, 2, 3, 4, 5. Use ${C("0..<5")} to stop before 5. If you don't need the number, write ${C("_")}.</p>`,
  demo:`for i in 1...3 {\n    print("Ook #\\(i)")\n}\nfor _ in 0..<2 {\n    print("hi")\n}`,
  say:"Ook #1, #2, #3, then hi twice."},
 {type:"talk",title:"Adding things up",mood:"think",
  body:`<p>Make a total before the loop, then add to it each time. ${C("stride(from:to:by:)")} counts in steps (${C("through:")} includes the end).</p>`,
  demo:`var total = 0\nfor i in 1...10 {\n    total += i\n}\nprint(total)\nfor n in stride(from: 10, through: 0, by: -5) {\n    print(n)\n}`,
  say:"55, then 10, 5, 0."},
 {type:"talk",title:"while and repeat",
  body:`<p>${C("while")} loops as long as a condition is true. ${C("repeat { } while")} checks at the end, so it always runs at least once. ${C("break")} leaves a loop; ${C("continue")} skips to the next round.</p>`,
  demo:`var bananas = 0\nvar days = 0\nwhile bananas < 20 {\n    bananas += 6\n    days += 1\n}\nprint(days, bananas)\nvar n = 10\nrepeat {\n    print("n is \\(n)")\n} while n < 5`,
  say:"4 24, then n is 10 once."},
 {type:"talk",title:"Loops in loops",mood:"cheer",
  body:`<p>An inner loop runs all the way through for each round of the outer loop.</p>`,
  demo:`for row in 1...3 {\n    var line = ""\n    for col in 1...4 {\n        line += "\\(row * col) "\n    }\n    print(line)\n}`,
  say:"A little times table."},
 {type:"quiz",q:"What does this print?",code:`for i in 1...3 {\n    print(i, terminator: "")\n}`,opts:["123","12","0123"],a:0,mono:true,why:"1...3 includes 3."},
 {type:"quiz",q:"What does this print?",code:`for i in 0..<3 {\n    print(i, terminator: "")\n}`,opts:["012","0123","123"],a:0,mono:true,why:"0..<3 stops before 3."},
 {type:"quiz",q:"What does this print?",code:`var x = 1\nwhile x < 20 {\n    x *= 3\n}\nprint(x)`,opts:["27","9","20"],a:0,mono:true,why:"1 → 3 → 9 → 27, then it stops."},
 {type:"fill",title:"Even numbers",body:`<p>Print 2, 4, 6, 8, 10.</p>`,code:`for n in [0](from: 2, through: 10, by: [1]) {\n    print(n)\n}`,blanks:["stride","2"],tokens:["stride","2","range","1"],out:"2\n4\n6\n8\n10",why:"stride counts in steps of 2."},
 {type:"order",title:"Sum the odds",body:`<p>Add up 1, 3, 5, 7, 9 and print 25.</p>`,lines:["var sum = 0","for i in stride(from: 1, through: 9, by: 2) {","    sum += i","}","print(sum)"],out:"25",why:"Total first, loop, print after."},
 {type:"code",title:"Countdown",body:`<p>Print 5 down to 1 (one per line), then ${C("Liftoff!")}. Try ${C("(1...5).reversed()")} or stride.</p>`,start:`// your loop here\n`,
  use:[[/\bfor\b|\bwhile\b/,"Use a loop."]],out:["5","4","3","2","1","Liftoff!"],
  hint:`for i in (1...5).reversed() {\n    print(i)\n}\nprint("Liftoff!")`},
 {type:"code",title:"Times table",body:`<p>Print the ${C("n")} times table from 1 to 5, like ${C("3 x 1 = 3")}.</p>`,start:`let n = 3\n// your loop here\n`,
  use:[[/\bfor\b/,"Use a for loop."]],out:["3 x 1 = 3","3 x 2 = 6","3 x 3 = 9","3 x 4 = 12","3 x 5 = 15"],variants:[[/n = 3/,"n = 7",["7 x 1 = 7","7 x 2 = 14","7 x 3 = 21","7 x 4 = 28","7 x 5 = 35"]]],
  hint:`let n = 3\nfor i in 1...5 {\n    print("\\(n) x \\(i) = \\(n * i)")\n}`},
 {type:"code",title:"Doubling bananas",body:`<p>Start with 1 banana and double it each day. Print how many <b>days</b> until there are at least 100.</p>`,start:`var bananas = 1\nvar days = 0\n// your loop here\n`,
  use:[[/\bwhile\b/,"Use a while loop."]],out:["7"],variants:[[/bananas = 1\n/,"bananas = 30\n",["2"]]],
  hint:`var bananas = 1\nvar days = 0\nwhile bananas < 100 {\n    bananas *= 2\n    days += 1\n}\nprint(days)`},
 {type:"game"},{type:"done"}],
 pool:[
  [`var t = 0\nfor i in 1...4 {\n    t += i\n}\nprint(t)`,["10","4","24"]],
  [`var s = ""\nfor _ in 1...3 {\n    s += "ha"\n}\nprint(s)`,["hahaha","haha","ha"]],
  [`for n in stride(from: 0, to: 10, by: 4) {\n    print(n, terminator: " ")\n}`,["0 4 8","0 4 8 12","4 8"]],
  [`var i = 0\nwhile i < 5 {\n    i += 2\n}\nprint(i)`,["6","5","4"]],
  [`var c = 0\nfor _ in 0..<3 {\n    for _ in 0..<2 {\n        c += 1\n    }\n}\nprint(c)`,["6","5","3"]],
  [`for i in 1...5 {\n    if i == 3 { continue }\n    print(i, terminator: "")\n}`,["1245","12345","12"]],
  [`var p = 1\nfor _ in 1...5 {\n    p *= 2\n}\nprint(p)`,["32","10","16"]]
 ]},
{id:"sw8",title:"Project: FizzBuzz & guesser",sub:"loops and decisions together",project:true,steps:[
 {type:"talk",title:"Two classics",mood:"cheer",
  body:`<p>You'll build <b>FizzBuzz</b> (say Fizz for multiples of 3, Buzz for 5, FizzBuzz for both) and a number guessing game that runs through a list of guesses.</p>`,
  say:"These two have started a lot of programming careers!"},
 {type:"code",title:"Step 1: FizzBuzz",body:`<p>Print 1 to ${C("n")}, but ${C("Fizz")} for multiples of 3, ${C("Buzz")} for multiples of 5, and ${C("FizzBuzz")} for both. Check the FizzBuzz case first!</p>`,start:`let n = 15\nfor i in 1...n {\n    // your code here\n}\n`,
  use:[[/%\s*3|isMultiple\(of:\s*3/,"Check multiples of 3."],[/%\s*5|isMultiple\(of:\s*5/,"Check multiples of 5."]],out:["1","2","Fizz","4","Buzz","Fizz","7","8","Fizz","Buzz","11","Fizz","13","14","FizzBuzz"],variants:[[/n = 15/,"n = 5",["1","2","Fizz","4","Buzz"]]],
  hint:`let n = 15\nfor i in 1...n {\n    if i % 15 == 0 {\n        print("FizzBuzz")\n    } else if i % 3 == 0 {\n        print("Fizz")\n    } else if i % 5 == 0 {\n        print("Buzz")\n    } else {\n        print(i)\n    }\n}`},
 {type:"code",title:"Step 2: guessing game",body:`<p>The secret is 7. Go through ${C("guesses")} in order, printing ${C("Too low")} or ${C("Too high")}. When one is right, print ${C("Got it in N tries!")} and stop with ${C("break")}.</p>`,start:`let secret = 7\nlet guesses = [3, 9, 7, 5]\nvar tries = 0\nfor g in guesses {\n    // your code here\n}\n`,
  use:[[/\bbreak\b/,"Stop the loop with break."]],out:["Too low","Too high","Got it in 3 tries!"],variants:[[/let secret = 7/,"let secret = 9",["Too low","Got it in 2 tries!"]]],
  hint:`let secret = 7\nlet guesses = [3, 9, 7, 5]\nvar tries = 0\nfor g in guesses {\n    tries += 1\n    if g < secret {\n        print("Too low")\n    } else if g > secret {\n        print("Too high")\n    } else {\n        print("Got it in \\(tries) tries!")\n        break\n    }\n}`},
 {type:"done"}]}
]},
{name:"Collections & functions",lessons:[
{id:"sw9",title:"Arrays",sub:"ordered lists of values",steps:[
 {type:"talk",title:"Making an array",
  body:`<p>An array holds values in order, all of the same type. Positions start at <b>0</b>. Use ${C("var")} if you want to change it.</p>`,
  demo:`var snacks = ["banana", "mango", "kiwi"]\nprint(snacks[0])\nprint(snacks.count)\nsnacks.append("papaya")\nsnacks[1] = "lime"\nprint(snacks)`,
  say:"banana, then 3, then [\"banana\", \"lime\", \"kiwi\", \"papaya\"]."},
 {type:"talk",title:"Adding, removing, searching",mood:"think",
  body:`<p>${C(".insert(x, at:)")} and ${C(".remove(at:)")} change the middle. ${C(".contains()")} searches. ${C(".first")} and ${C(".last")} might be empty, so they're optional (more on that soon).</p>`,
  demo:`var nums = [40, 10, 30]\nnums.insert(5, at: 0)\nlet gone = nums.remove(at: 1)\nprint(gone)\nprint(nums)\nprint(nums.contains(30))\nprint(nums.sorted())\nprint(nums.isEmpty)`,
  say:"40, [5, 10, 30], true, [5, 10, 30], false."},
 {type:"talk",title:"Looping over arrays",
  body:`<p>${C("for item in array")} visits each value. ${C(".enumerated()")} gives you the position too.</p>`,
  demo:`let team = ["Mo", "Kiki", "Bao"]\nfor name in team {\n    print("Go \\(name)!")\n}\nfor (i, name) in team.enumerated() {\n    print(i, name)\n}`,
  say:"Go Mo!, Go Kiki!, Go Bao!, then 0 Mo, 1 Kiki, 2 Bao."},
 {type:"talk",title:"Off the edge",mood:"oops",
  body:`<p>Reading a position that doesn't exist crashes your program with <b>Index out of range</b>. With 3 items, the last position is 2.</p>`,
  demo:`let a = [1, 2, 3]\nprint(a[2])\nprint(a[3])`,
  say:"The second print crashes."},
 {type:"quiz",q:"What does this print?",code:`let a = [4, 8, 15]\nprint(a[1])`,opts:["8","4","15"],a:0,mono:true,why:"Position 1 is the second item."},
 {type:"quiz",q:"What does this print?",code:`var a = [1, 2]\na.append(3)\nprint(a.count)`,opts:["3","2","[1, 2, 3]"],a:0,mono:true,why:"append adds one more."},
 {type:"quiz",q:"Why does this fail?",code:`let a = [1, 2]\na.append(3)`,opts:["a is a let constant, so it can't change","append doesn't exist","Arrays can't hold Ints"],a:0,mono:true,why:"Use var for arrays you want to change."},
 {type:"fill",title:"Find the biggest",body:`<p>Print the biggest number.</p>`,code:`let nums = [12, 45, 7, 30]\nvar best = 0\nfor n [0] nums {\n    if n > best {\n        best = n\n    }\n}\n[1](best)`,blanks:["in","print"],tokens:["in","print","of",":"],out:"45",why:"for n in nums visits each number."},
 {type:"code",title:"Guest list",body:`<p>Add ${C("Leo")} and ${C("Kai")} to ${C("guests")}, remove ${C("Ava")} (she's at position 0), then print how many guests there are and each name on its own line.</p>`,start:`var guests = ["Ava"]\n// your code here\n`,
  use:[[/\.append\s*\(/,"Use .append()."],[/\.remove\s*\(\s*at:/,"Use .remove(at: 0)."],[/for\s+\w+\s+in/,"Print each name with a loop."]],out:["2","Leo","Kai"],
  hint:`var guests = ["Ava"]\nguests.append("Leo")\nguests.append("Kai")\nguests.remove(at: 0)\nprint(guests.count)\nfor g in guests {\n    print(g)\n}`},
 {type:"code",title:"Average temperature",body:`<p>Print the average of ${C("temps")} as a Double.</p>`,start:`let temps = [20, 25, 18, 21]\n// your code here\n`,
  use:[[/temps\.count/,"Divide by temps.count."]],out:["21.0"],variants:[[/18, 21/,"18, 22",["21.25"]]],
  hint:`let temps = [20, 25, 18, 21]\nvar total = 0\nfor t in temps {\n    total += t\n}\nprint(Double(total) / Double(temps.count))`},
 {type:"game"},{type:"done"}],
 pool:[
  [`let a = [3, 6, 9]\nprint(a.count)`,["3","9","2"]],
  [`let a = [3, 6, 9]\nprint(a[a.count - 1])`,["9","3","6"]],
  [`print([5, 1, 4].sorted())`,["[1, 4, 5]","[5, 4, 1]","[5, 1, 4]"]],
  [`var s = ["x", "y"]\ns[0] = "z"\nprint(s)`,["[\"z\", \"y\"]","[\"x\", \"y\"]","[\"z\"]"]],
  [`var a = [1, 2, 3]\na.remove(at: 0)\nprint(a)`,["[2, 3]","[1, 2]","[1, 3]"]],
  [`print([1, 2, 3].contains(4))`,["false","true","4"]],
  [`var a = [1, 2]\nvar b = a\nb.append(3)\nprint(a.count)`,["2","3","1"]]
 ]},
{id:"sw10",title:"Dictionaries & sets",sub:"look things up by key; unique values",steps:[
 {type:"talk",title:"Keys and values",
  body:`<p>A <b>dictionary</b> stores pairs: a key and its value. Looking up a key gives an <b>optional</b>, because the key might not be there. Use ${C("??")} to give a backup value.</p>`,
  demo:`var ages = ["Mo": 4, "Kiki": 12]\nages["Bao"] = 7\nages["Mo"] = 5\nprint(ages["Mo"] ?? 0)\nprint(ages["Zed"] ?? 0)\nprint(ages.count)`,
  say:"5, 0, 3."},
 {type:"talk",title:"Counting with a default",mood:"think",
  body:`<p>${C('dict[key, default: 0] += 1')} adds 1, starting from 0 if the key is new. It's the classic way to count things.</p>`,
  demo:`let words = ["ook", "eek", "ook", "ook"]\nvar counts: [String: Int] = [:]\nfor w in words {\n    counts[w, default: 0] += 1\n}\nprint(counts["ook"] ?? 0)\nprint(counts["eek"] ?? 0)`,
  say:"3, then 1."},
 {type:"talk",title:"Looping in order",mood:"oops",
  body:`<p>Dictionaries have <b>no fixed order</b>: Swift may list them differently each time you run. To print in a predictable order, loop over ${C(".keys.sorted()")}.</p>`,
  demo:`let stock = ["mango": 5, "banana": 8, "kiwi": 2]\nfor fruit in stock.keys.sorted() {\n    print("\\(fruit): \\(stock[fruit]!)")\n}`,
  say:"banana, kiwi, mango in alphabetical order. The ! is safe here because the key definitely exists."},
 {type:"talk",title:"Sets: no duplicates",mood:"cheer",
  body:`<p>A ${C("Set")} keeps each value only once, and checks membership super fast. Like dictionaries, sets have no order.</p>`,
  demo:`var seen: Set<String> = []\nfor animal in ["owl", "cat", "owl", "dog", "cat"] {\n    seen.insert(animal)\n}\nprint(seen.count)\nprint(seen.contains("owl"))\nprint(seen.sorted())`,
  say:"3, true, [\"cat\", \"dog\", \"owl\"]."},
 {type:"quiz",q:"What does this print?",code:`let d = ["a": 1]\nprint(d["a"] ?? 0, d["b"] ?? 0)`,opts:["1 0","1 nil","Optional(1) 0"],a:0,mono:true,why:"?? unwraps the value or uses the backup."},
 {type:"quiz",q:"What does this print?",code:`var m = ["x": 1]\nm["x"] = 5\nprint(m.count, m["x"] ?? 0)`,opts:["1 5","2 5","1 1"],a:0,mono:true,why:"Setting a key that exists replaces its value."},
 {type:"quiz",q:"Why loop over dict.keys.sorted() instead of the dictionary itself?",opts:["Dictionaries have no fixed order","It's faster","Dictionaries can't be looped over"],a:0,why:"Sorting the keys gives the same order every time."},
 {type:"fill",title:"Count the fruit",body:`<p>Count each fruit.</p>`,code:`var counts: [String: Int] = [:]\nfor f in ["fig", "fig", "lime"] {\n    counts[f, [0]: 0] += 1\n}\nprint(counts["fig"] [1] 0)`,blanks:["default","??"],tokens:["default","??","else","||"],out:"2",why:"default: starts new keys at 0; ?? unwraps the answer."},
 {type:"code",title:"Word counter",body:`<p>Count each word in ${C("text")} with a dictionary, then print ${C("ook: 3")} and ${C("eek: 1")}.</p>`,start:`let text = "ook eek ook ah ook"\nlet words = text.split(separator: " ")\n// count them here\n`,
  use:[[/default:/,"Use counts[w, default: 0] += 1."]],out:["ook: 3","eek: 1"],variants:[[/ook ah ook/,"eek ah ook",["ook: 2","eek: 2"]]],
  hint:`let text = "ook eek ook ah ook"\nlet words = text.split(separator: " ")\nvar counts: [String: Int] = [:]\nfor w in words {\n    counts[String(w), default: 0] += 1\n}\nprint("ook: \\(counts["ook"] ?? 0)")\nprint("eek: \\(counts["eek"] ?? 0)")`},
 {type:"code",title:"Unique visitors",body:`<p>Use a Set to count how many <b>different</b> names are in ${C("visits")}, then print the names in sorted order.</p>`,start:`let visits = ["Mo", "Kiki", "Mo", "Bao", "Kiki", "Mo"]\n// your code here\n`,
  use:[[/Set/,"Put them in a Set."]],out:["3","[\"Bao\", \"Kiki\", \"Mo\"]"],
  hint:`let visits = ["Mo", "Kiki", "Mo", "Bao", "Kiki", "Mo"]\nlet unique = Set(visits)\nprint(unique.count)\nprint(unique.sorted())`},
 {type:"game"},{type:"done"}],
 pool:[
  [`let d = ["x": 3]\nprint((d["x"] ?? 0) * 2)`,["6","3","nil"]],
  [`let d: [String: Int] = [:]\nprint(d["q"] ?? 7)`,["7","nil","0"]],
  [`var d = ["a": 1]\nd["b"] = 2\nprint(d.count)`,["2","1","3"]],
  [`print(Set([1, 1, 2, 2, 3]).count)`,["3","5","2"]],
  [`var d = ["k": 1]\nd["k"] = nil\nprint(d.isEmpty)`,["true","false","nil"]],
  [`let s: Set = ["a", "b"]\nprint(s.contains("c"))`,["false","true","nil"]]
 ]},
{id:"sw11",title:"Functions",sub:"argument labels, defaults, return values",steps:[
 {type:"talk",title:"Your own commands",
  body:`<p>${C("func")} names a block of code. Parameters have a name and a type. When you call it, you write the parameter's name as a <b>label</b>: ${C('greet(name: "Mo")')}. It reads almost like English.</p>`,
  demo:`func greet(name: String) {\n    print("Hi, \\(name)!")\n}\n\ngreet(name: "Mo")\ngreet(name: "Kiki")`,
  say:"Hi, Mo! then Hi, Kiki!"},
 {type:"talk",title:"Returning a value",
  body:`<p>Write ${C("-> Type")} to say what comes back, and ${C("return")} it. If the whole body is one expression, you can even leave out ${C("return")}.</p>`,
  demo:`func square(of n: Int) -> Int {\n    return n * n\n}\nfunc isEven(_ n: Int) -> Bool {\n    n % 2 == 0\n}\n\nprint(square(of: 6))\nprint(isEven(7))`,
  say:"36, false. The _ means \"no label needed when calling\"."},
 {type:"talk",title:"Labels, no labels, defaults",mood:"think",
  body:`<p>You can give a parameter an outside label different from its inside name (${C("to name")}), skip the label with ${C("_")}, or give it a default value.</p>`,
  demo:`func send(_ message: String, to name: String, times: Int = 1) {\n    for _ in 1...times {\n        print("\\(name), \\(message)")\n    }\n}\n\nsend("ook!", to: "Mo")\nsend("eek!", to: "Kiki", times: 2)`,
  say:"Mo, ook! then Kiki, eek! twice."},
 {type:"talk",title:"Returning two things",mood:"cheer",
  body:`<p>A function can return a <b>tuple</b>: several values bundled together, each with a name.</p>`,
  demo:`func minMax(_ nums: [Int]) -> (low: Int, high: Int) {\n    var low = nums[0]\n    var high = nums[0]\n    for n in nums {\n        low = min(low, n)\n        high = max(high, n)\n    }\n    return (low, high)\n}\n\nlet r = minMax([8, 3, 12, 5])\nprint(r.low, r.high)`,
  say:"3 12"},
 {type:"quiz",q:"How do you call this function?",code:`func add(a: Int, b: Int) -> Int {\n    a + b\n}`,opts:["add(a: 2, b: 3)","add(2, 3)","add(a = 2, b = 3)"],a:0,mono:true,why:"Swift uses the labels when calling."},
 {type:"quiz",q:"What does this print?",code:`func twice(_ n: Int) -> Int {\n    n * 2\n}\nprint(twice(twice(3)))`,opts:["12","6","9"],a:0,mono:true,why:"twice(3) is 6, and twice(6) is 12."},
 {type:"quiz",q:"What does _ before a parameter name mean?",opts:["No label is written when calling","The parameter is optional","The parameter is private"],a:0,why:"func shout(_ s: String) is called as shout(\"hi\")."},
 {type:"fill",title:"Write the header",body:`<p>Finish the function that adds two numbers.</p>`,code:`[0] add(_ a: Int, _ b: Int) [1] Int {\n    return a + b\n}\nprint(add(2, 3))`,blanks:["func","->"],tokens:["func","->","function",":"],out:"5",why:"func starts it, -> says what it returns."},
 {type:"code",title:"Triple it",body:`<p>Write ${C("func triple(_ n: Int) -> Int")} and print ${C("triple(4)")} and ${C("triple(10)")}.</p>`,start:`// write triple here\n\n`,
  use:[[/func\s+triple\s*\(\s*_\s+\w+\s*:\s*Int\s*\)\s*->\s*Int/,"Start with func triple(_ n: Int) -> Int"]],out:["12","30"],
  hint:`func triple(_ n: Int) -> Int {\n    return n * 3\n}\n\nprint(triple(4))\nprint(triple(10))`},
 {type:"code",title:"Temperature converter",body:`<p>Write ${C("func toFahrenheit(celsius: Double) -> Double")} (c × 9 / 5 + 32). Print it for 100 and -40.</p>`,start:`// write toFahrenheit here\n\nprint(toFahrenheit(celsius: 100))\nprint(toFahrenheit(celsius: -40))\n`,
  use:[[/func\s+toFahrenheit\s*\(\s*celsius\s*:\s*Double\s*\)/,"Start with func toFahrenheit(celsius: Double) -> Double"]],out:["212.0","-40.0"],
  hint:`func toFahrenheit(celsius: Double) -> Double {\n    return celsius * 9 / 5 + 32\n}\n\nprint(toFahrenheit(celsius: 100))\nprint(toFahrenheit(celsius: -40))`},
 {type:"game"},{type:"done"}],
 pool:[
  [`func inc(_ n: Int) -> Int { n + 1 }\nprint(inc(4))`,["5","4","inc(4)"]],
  [`func shout(_ s: String) -> String { s + "!" }\nprint(shout("ook"))`,["ook!","ook","!ook"]],
  [`func hi(name: String = "you") { print("hi \\(name)") }\nhi()`,["hi you","hi","hi name"]],
  [`func big(_ a: Int, _ b: Int) -> Int { a > b ? a : b }\nprint(big(3, 8))`,["8","3","true"]],
  [`func pair() -> (Int, Int) { (1, 2) }\nprint(pair().1)`,["2","1","(1, 2)"]],
  [`func f(_ x: Int) -> Int {\n    if x > 0 { return 1 }\n    return -1\n}\nprint(f(5) + f(-2))`,["0","2","-2"]]
 ]},
{id:"sw12",title:"Closures",sub:"map, filter, sorted, reduce",steps:[
 {type:"talk",title:"Functions without names",
  body:`<p>A <b>closure</b> is a little function you write right where you need it, in curly braces. Arrays take closures: ${C(".map")} changes every item and ${C(".filter")} keeps the ones that pass.</p>`,
  demo:`let nums = [1, 2, 3, 4, 5]\nlet doubled = nums.map { n in n * 2 }\nlet evens = nums.filter { n in n % 2 == 0 }\nprint(doubled)\nprint(evens)`,
  say:"[2, 4, 6, 8, 10], then [2, 4]."},
 {type:"talk",title:"The $0 shortcut",mood:"cheer",
  body:`<p>Swift lets you skip naming the inputs: ${C("$0")} is the first one, ${C("$1")} the second. ${C("sorted(by:)")} takes a closure that says which item comes first.</p>`,
  demo:`let names = ["Kiki", "Mo", "Bao", "Zuri"]\nprint(names.sorted())\nprint(names.sorted { $0.count < $1.count })\nprint([3, 9, 1].sorted(by: >))`,
  say:"Alphabetical, shortest first, then biggest first."},
 {type:"talk",title:"reduce: boil it down",mood:"think",
  body:`<p>${C("reduce")} combines everything into one value. Give it a starting value and a closure that adds the next item.</p>`,
  demo:`let prices = [2.5, 1.0, 4.25]\nlet total = prices.reduce(0, +)\nprint(total)\nlet longest = ["ook", "banana", "eek"].reduce("") { $1.count > $0.count ? $1 : $0 }\nprint(longest)`,
  say:"7.75, then banana."},
 {type:"talk",title:"Storing a closure",
  body:`<p>Closures are values. Store one in a constant, then call it like a function.</p>`,
  demo:`let greet = { (name: String) -> String in\n    "Hi, \\(name)!"\n}\nprint(greet("Mo"))\nlet square: (Int) -> Int = { $0 * $0 }\nprint(square(7))`,
  say:"Hi, Mo! then 49."},
 {type:"quiz",q:"What does this print?",code:`print([1, 2, 3].map { $0 * 10 })`,opts:["[10, 20, 30]","[1, 2, 3]","60"],a:0,mono:true,why:"map changes every item."},
 {type:"quiz",q:"What does this print?",code:`print([5, 12, 8, 3].filter { $0 > 6 })`,opts:["[12, 8]","[5, 3]","[12]"],a:0,mono:true,why:"filter keeps the items where the closure says true."},
 {type:"quiz",q:"What does this print?",code:`print([1, 2, 3, 4].reduce(0, +))`,opts:["10","24","[1, 2, 3, 4]"],a:0,mono:true,why:"0 + 1 + 2 + 3 + 4."},
 {type:"fill",title:"Keep the long words",body:`<p>Keep words with more than 3 letters.</p>`,code:`let words = ["ook", "banana", "kiwi"]\nprint(words.[0] { $0.count > 3 })`,blanks:["filter"],tokens:["filter","map","sorted","reduce"],out:"[\"banana\", \"kiwi\"]",why:"filter keeps the ones that pass the test."},
 {type:"code",title:"Price tags",body:`<p>Use ${C(".map")} to turn ${C("prices")} into strings like ${C("$2")}, then print the result.</p>`,start:`let prices = [2, 15, 7]\n// your code here\n`,
  use:[[/\.map/,"Use .map { ... }."]],out:["[\"$2\", \"$15\", \"$7\"]"],
  hint:`let prices = [2, 15, 7]\nlet tags = prices.map { "$\\($0)" }\nprint(tags)`},
 {type:"code",title:"Leaderboard",body:`<p>Sort ${C("scores")} from highest to lowest, keep only scores of 50 or more, and print the result.</p>`,start:`let scores = [42, 88, 51, 97, 30, 65]\n// your code here\n`,
  use:[[/sorted/,"Sort them."],[/filter/,"Use filter to keep 50 and up."]],out:["[97, 88, 65, 51]"],variants:[[/30, 65/,"30, 50",["[97, 88, 51, 50]"]]],
  hint:`let scores = [42, 88, 51, 97, 30, 65]\nprint(scores.filter { $0 >= 50 }.sorted(by: >))`},
 {type:"game"},{type:"done"}],
 pool:[
  [`print([1, 2, 3].map { $0 + 1 })`,["[2, 3, 4]","[1, 2, 3]","6"]],
  [`print([4, 1, 3].sorted(by: >))`,["[4, 3, 1]","[1, 3, 4]","[4, 1, 3]"]],
  [`print([2, 3].reduce(1, *))`,["6","5","1"]],
  [`print(["a", "bb", "ccc"].filter { $0.count >= 2 }.count)`,["2","1","3"]],
  [`let add = { (a: Int, b: Int) -> Int in a + b }\nprint(add(2, 5))`,["7","25","2"]],
  [`print([1, 2, 3, 4].filter { $0 % 2 == 1 }.map { $0 * 3 })`,["[3, 9]","[6, 12]","[1, 3]"]]
 ]}
]},
{name:"Optionals & your own types",lessons:[
{id:"sw13",title:"Optionals",sub:"values that might be missing",steps:[
 {type:"talk",title:"Maybe there's a value",
  body:`<p>An <b>optional</b> either holds a value or holds ${C("nil")} (nothing). Its type has a ${C("?")}: ${C("Int?")} means \"an Int, or nothing\". Turning text into a number gives an optional, because the text might not be a number.</p>`,
  demo:`let good = Int("42")\nlet bad = Int("banana")\nprint(good)\nprint(bad)\nvar nickname: String? = nil\nnickname = "Mo"\nprint(nickname)`,
  say:"Optional(42), nil, Optional(\"Mo\"). Printing an optional shows the wrapper."},
 {type:"talk",title:"Unwrapping with if let",mood:"think",
  body:`<p>${C("if let x = maybe")} runs the block only when there's a value, and gives you the plain value inside as ${C("x")}. ${C("??")} gives a backup value instead.</p>`,
  demo:`let input = "17"\nif let n = Int(input) {\n    print("Doubled: \\(n * 2)")\n} else {\n    print("Not a number")\n}\nlet age = Int("abc") ?? 0\nprint(age)`,
  say:"Doubled: 34, then 0."},
 {type:"talk",title:"guard let: exit early",
  body:`<p>${C("guard let")} is the opposite: if there's <b>no</b> value, leave right away. After the guard, the value is unwrapped for the rest of the function.</p>`,
  demo:`func describe(_ text: String) {\n    guard let n = Int(text) else {\n        print("\\"\\(text)\\" isn't a number")\n        return\n    }\n    print("\\(n) squared is \\(n * n)")\n}\n\ndescribe("9")\ndescribe("ook")`,
  say:"9 squared is 81, then \"ook\" isn't a number."},
 {type:"talk",title:"Force unwrap: careful!",mood:"oops",
  body:`<p>${C("!")} means \"I'm sure there's a value\". If you're wrong, the app crashes. Only use it when nil is truly impossible. ${C("?.")} (optional chaining) is safer: it gives nil instead of crashing.</p>`,
  demo:`let words: [String] = []\nprint(words.first?.count)\nlet full = ["ook", "eek"]\nprint(full.first?.count)\nprint(full.first!)\nprint(words.first!)`,
  say:"nil, Optional(3), ook, then a crash on the last line."},
 {type:"quiz",q:"What does this print?",code:`print(Int("12") ?? 0)`,opts:["12","Optional(12)","0"],a:0,mono:true,why:"The text is a number, so ?? unwraps it."},
 {type:"quiz",q:"What does this print?",code:`print(Int("12"))`,opts:["Optional(12)","12","nil"],a:0,mono:true,why:"Int(\"12\") is an optional, and printing an optional shows the wrapper."},
 {type:"quiz",q:"What does this print?",code:`let x: Int? = nil\nif let v = x {\n    print(v)\n} else {\n    print("empty")\n}`,opts:["empty","nil","0"],a:0,mono:true,why:"x has no value, so the else block runs."},
 {type:"quiz",q:"Which one can crash your app?",opts:["value!","value ?? 0","if let v = value"],a:0,mono:true,why:"! crashes when the value is nil."},
 {type:"fill",title:"Unwrap it safely",body:`<p>Print the number doubled, or Not a number.</p>`,code:`let text = "21"\n[0] [1] n = Int(text) {\n    print(n * 2)\n} else {\n    print("Not a number")\n}`,blanks:["if","let"],tokens:["if","let","var","guard","!"],out:"42",why:"if let unwraps the optional."},
 {type:"code",title:"Safe parse",body:`<p>For each item in ${C("inputs")}, print the number doubled, or ${C("skip")} if it isn't a number.</p>`,start:`let inputs = ["4", "x", "10"]\n// your code here\n`,
  use:[[/if\s+let|guard\s+let|\?\?/,"Unwrap Int(...) with if let."]],out:["8","skip","20"],
  hint:`let inputs = ["4", "x", "10"]\nfor s in inputs {\n    if let n = Int(s) {\n        print(n * 2)\n    } else {\n        print("skip")\n    }\n}`},
 {type:"code",title:"Total of good numbers",body:`<p>Add up only the entries that are numbers and print the total. ${C(".compactMap { Int($0) }")} is a neat way: it keeps only the non-nil results.</p>`,start:`let entries = ["5", "ten", "7", "", "3"]\n// your code here\n`,
  use:[[/compactMap|if\s+let|\?\?/,"Use compactMap, if let or ??."]],out:["15"],variants:[[/"ten"/,"\"10\"",["25"]]],
  hint:`let entries = ["5", "ten", "7", "", "3"]\nlet nums = entries.compactMap { Int($0) }\nprint(nums.reduce(0, +))`},
 {type:"game"},{type:"done"}],
 pool:[
  [`let x: Int? = 5\nprint(x ?? 0)`,["5","Optional(5)","0"]],
  [`let x: Int? = nil\nprint(x ?? 9)`,["9","nil","0"]],
  [`print(Int("7a"))`,["nil","7","Optional(7)"]],
  [`let s: String? = "ook"\nprint(s?.count ?? 0)`,["3","0","nil"]],
  [`let a = [Int]()\nprint(a.first ?? -1)`,["-1","nil","0"]],
  [`print(["1", "x", "2"].compactMap { Int($0) })`,["[1, 2]","[1, nil, 2]","[\"1\", \"2\"]"]]
 ]},
{id:"sw14",title:"Structs",sub:"your own value types",steps:[
 {type:"talk",title:"Make your own type",
  body:`<p>A ${C("struct")} groups related values (properties) and actions (methods). Swift gives you a free initializer with a label for each property.</p>`,
  demo:`struct Monkey {\n    var name: String\n    var bananas: Int\n\n    func greet() {\n        print("I'm \\(name) and I have \\(bananas) bananas")\n    }\n}\n\nlet mo = Monkey(name: "Mo", bananas: 3)\nmo.greet()\nprint(mo.name)\nprint(mo)`,
  say:"Printing a struct shows all its properties: Monkey(name: \"Mo\", bananas: 3)."},
 {type:"talk",title:"mutating methods",mood:"think",
  body:`<p>Methods that change a struct's properties must be marked ${C("mutating")}, and the struct must be stored in a ${C("var")}.</p>`,
  demo:`struct Counter {\n    var count = 0\n    mutating func add(_ n: Int) {\n        count += n\n    }\n}\n\nvar c = Counter()\nc.add(5)\nc.add(2)\nprint(c.count)`,
  say:"7. Because count has a default, Counter() works with no arguments."},
 {type:"talk",title:"Structs are copied",mood:"oops",
  body:`<p>Structs are <b>value types</b>: assigning one makes a full copy. Changing the copy doesn't touch the original. (Arrays, Strings and dictionaries work this way too.)</p>`,
  demo:`struct Point {\n    var x: Int\n    var y: Int\n}\n\nvar a = Point(x: 1, y: 2)\nvar b = a\nb.x = 100\nprint(a.x, b.x)`,
  say:"1 100. Two separate points."},
 {type:"talk",title:"Computed properties",mood:"cheer",
  body:`<p>A <b>computed property</b> works out its value every time you read it, instead of storing it.</p>`,
  demo:`struct Rect {\n    var width: Double\n    var height: Double\n    var area: Double {\n        width * height\n    }\n}\n\nvar r = Rect(width: 3, height: 4)\nprint(r.area)\nr.width = 10\nprint(r.area)`,
  say:"12.0, then 40.0."},
 {type:"quiz",q:"What does this print?",code:`struct Box {\n    var n: Int\n}\nvar a = Box(n: 1)\nvar b = a\nb.n = 9\nprint(a.n)`,opts:["1","9","0"],a:0,mono:true,why:"b is a copy. Changing it doesn't change a."},
 {type:"quiz",q:"Why must this method be marked mutating?",code:`struct Bank {\n    var coins = 0\n    func deposit() { coins += 1 }\n}`,opts:["It changes a property of the struct","It returns a value","It has no parameters"],a:0,mono:true,why:"Struct methods that change properties need mutating."},
 {type:"quiz",q:"What does this print?",code:`struct P {\n    var x: Int\n    var y: Int\n}\nprint(P(x: 3, y: 4))`,opts:["P(x: 3, y: 4)","(3, 4)","P"],a:0,mono:true,why:"Swift prints the type and each property."},
 {type:"fill",title:"Make a hero",body:`<p>Create a hero with the free initializer.</p>`,code:`[0] Hero {\n    var name: String\n    var hp: Int\n}\nlet h = Hero([1]: "Bao", hp: 30)\nprint(h.hp)`,blanks:["struct","name"],tokens:["struct","name","class","func"],out:"30",why:"struct defines it, and the initializer labels match the property names."},
 {type:"code",title:"Rectangle",body:`<p>Give ${C("Rect")} two computed properties: ${C("area")} (w × h) and ${C("perimeter")} (2 × (w + h)).</p>`,start:`struct Rect {\n    var w: Int\n    var h: Int\n    // add area and perimeter here\n}\n\nlet r = Rect(w: 4, h: 3)\nprint(r.area)\nprint(r.perimeter)\n`,
  use:[[/var\s+area\s*:\s*Int/,"Add var area: Int { ... }"]],out:["12","14"],variants:[[/Rect\(w: 4, h: 3\)/,"Rect(w: 5, h: 5)",["25","20"]]],
  hint:`struct Rect {\n    var w: Int\n    var h: Int\n    var area: Int {\n        w * h\n    }\n    var perimeter: Int {\n        2 * (w + h)\n    }\n}\n\nlet r = Rect(w: 4, h: 3)\nprint(r.area)\nprint(r.perimeter)`},
 {type:"code",title:"Health bar",body:`<p>Finish the mutating ${C("hit")} and ${C("heal")} methods so hp always stays between 0 and 100.</p>`,start:`struct Hero {\n    var hp = 100\n    mutating func hit(_ dmg: Int) {\n        // your code here\n    }\n    mutating func heal(_ amount: Int) {\n        // your code here\n    }\n}\n\nvar h = Hero()\nh.hit(30)\nprint(h.hp)\nh.heal(50)\nprint(h.hp)\nh.hit(500)\nprint(h.hp)\n`,
  use:[[/max\s*\(|min\s*\(|if\s/,"Keep hp in range with max/min (or an if)."]],out:["70","100","0"],
  hint:`struct Hero {\n    var hp = 100\n    mutating func hit(_ dmg: Int) {\n        hp = max(0, hp - dmg)\n    }\n    mutating func heal(_ amount: Int) {\n        hp = min(100, hp + amount)\n    }\n}\n\nvar h = Hero()\nh.hit(30)\nprint(h.hp)\nh.heal(50)\nprint(h.hp)\nh.hit(500)\nprint(h.hp)`},
 {type:"game"},{type:"done"}],
 pool:[
  [`struct P { var v = 5 }\nprint(P().v)`,["5","0","nil"]],
  [`struct P { var a: Int; var b: Int }\nlet p = P(a: 2, b: 3)\nprint(p.a * p.b)`,["6","5","23"]],
  [`struct C {\n    var n = 0\n    mutating func up() { n += 2 }\n}\nvar c = C()\nc.up()\nc.up()\nprint(c.n)`,["4","2","0"]],
  [`struct S { var x: Int }\nvar a = S(x: 1)\nvar b = a\na.x = 7\nprint(b.x)`,["1","7","0"]],
  [`struct T {\n    var c: Double\n    var f: Double { c * 9 / 5 + 32 }\n}\nprint(T(c: 0).f)`,["32.0","0.0","32"]]
 ]},
{id:"sw15",title:"Classes",sub:"reference types, init and inheritance",steps:[
 {type:"talk",title:"Classes need an init",
  body:`<p>A ${C("class")} looks like a struct, but you write the ${C("init")} yourself. ${C("self.name")} means \"this object's name\".</p>`,
  demo:`class Pet {\n    var name: String\n    var age: Int\n\n    init(name: String, age: Int) {\n        self.name = name\n        self.age = age\n    }\n\n    func humanYears() -> Int {\n        age * 7\n    }\n}\n\nlet rex = Pet(name: "Rex", age: 3)\nprint("\\(rex.name) is \\(rex.humanYears()) in human years")`,
  say:"Rex is 21 in human years."},
 {type:"talk",title:"Classes are shared",mood:"oops",
  body:`<p>Classes are <b>reference types</b>: copying the variable gives a second name for the <b>same</b> object. Change it through one name and the other sees it too. Notice you can change a property even through a ${C("let")}.</p>`,
  demo:`class Box {\n    var bananas = 0\n}\n\nlet a = Box()\nlet b = a\nb.bananas = 10\nprint(a.bananas)\nprint(a === b)`,
  say:"10 and true. === checks whether two names point at the same object."},
 {type:"talk",title:"Inheritance",mood:"cheer",
  body:`<p>A class can <b>inherit</b> from another: ${C("class Dog: Animal")}. It gets everything the parent has. Mark a replaced method with ${C("override")}, and use ${C("super")} to run the parent's version.</p>`,
  demo:`class Animal {\n    var name: String\n    init(name: String) {\n        self.name = name\n    }\n    func sound() -> String {\n        "..."\n    }\n    func speak() {\n        print("\\(name): \\(sound())")\n    }\n}\n\nclass Cat: Animal {\n    override func sound() -> String {\n        "Meow"\n    }\n}\n\nclass Lion: Cat {\n    override func sound() -> String {\n        "ROAR (" + super.sound() + ")"\n    }\n}\n\nlet zoo: [Animal] = [Cat(name: "Tom"), Lion(name: "Leo"), Animal(name: "Blob")]\nfor a in zoo {\n    a.speak()\n}`,
  say:"Tom: Meow, Leo: ROAR (Meow), Blob: ..."},
 {type:"talk",title:"super.init",
  body:`<p>When a child class adds its own properties, its init sets them first, then calls ${C("super.init(...)")} to set up the parent's.</p>`,
  demo:`class Animal {\n    var name: String\n    init(name: String) {\n        self.name = name\n    }\n}\n\nclass Bird: Animal {\n    var canFly: Bool\n    init(name: String, canFly: Bool) {\n        self.canFly = canFly\n        super.init(name: name)\n    }\n}\n\nlet b = Bird(name: "Kiki", canFly: true)\nprint(b.name, b.canFly)`,
  say:"Kiki true"},
 {type:"quiz",q:"What does this print?",code:`class C {\n    var n = 1\n}\nlet a = C()\nlet b = a\nb.n = 5\nprint(a.n)`,opts:["5","1","Error"],a:0,mono:true,why:"a and b are the same object."},
 {type:"quiz",q:"What's the big difference between a struct and a class?",opts:["Structs are copied; classes are shared","Classes are faster","Structs can't have methods"],a:0,why:"Structs are value types, classes are reference types."},
 {type:"quiz",q:"What does this print?",code:`class A {\n    func hi() -> String { "A" }\n}\nclass B: A {\n    override func hi() -> String { "B" + super.hi() }\n}\nprint(B().hi())`,opts:["BA","B","AB"],a:0,mono:true,why:"B's version runs, and super.hi() adds A's."},
 {type:"fill",title:"Make a child class",body:`<p>Make Dog a child of Pet and replace speak.</p>`,code:`class Pet {\n    func speak() -> String { "..." }\n}\nclass Dog[0] Pet {\n    [1] func speak() -> String { "Woof" }\n}\nprint(Dog().speak())`,blanks:[":","override"],tokens:[":","override","extends","super"],out:"Woof",why:"class Dog: Pet, and override to replace the method."},
 {type:"code",title:"Employees",body:`<p>Make ${C("Manager")} inherit from ${C("Employee")}. A manager's ${C("pay()")} is the normal pay plus 500. Use ${C("super.pay()")}.</p>`,start:`class Employee {\n    var name: String\n    var salary: Int\n    init(name: String, salary: Int) {\n        self.name = name\n        self.salary = salary\n    }\n    func pay() -> Int {\n        salary\n    }\n}\n\n// write Manager here\n\nlet staff: [Employee] = [Employee(name: "Ava", salary: 3000), Manager(name: "Leo", salary: 4000)]\nfor e in staff {\n    print("\\(e.name): \\(e.pay())")\n}\n`,
  use:[[/class\s+Manager\s*:\s*Employee/,"Start with class Manager: Employee."],[/override\s+func\s+pay/,"override func pay()."],[/super\.pay\s*\(\s*\)/,"Use super.pay() + 500."]],out:["Ava: 3000","Leo: 4500"],
  hint:`class Employee {\n    var name: String\n    var salary: Int\n    init(name: String, salary: Int) {\n        self.name = name\n        self.salary = salary\n    }\n    func pay() -> Int {\n        salary\n    }\n}\n\nclass Manager: Employee {\n    override func pay() -> Int {\n        super.pay() + 500\n    }\n}\n\nlet staff: [Employee] = [Employee(name: "Ava", salary: 3000), Manager(name: "Leo", salary: 4000)]\nfor e in staff {\n    print("\\(e.name): \\(e.pay())")\n}`},
 {type:"game"},{type:"done"}],
 pool:[
  [`class K {\n    var v: Int\n    init(v: Int) { self.v = v * 2 }\n}\nprint(K(v: 4).v)`,["8","4","0"]],
  [`class A { func f() -> String { "a" } }\nclass B: A { override func f() -> String { "b" } }\nlet x: A = B()\nprint(x.f())`,["b","a","ab"]],
  [`class A { var n = 3 }\nclass B: A { }\nprint(B().n)`,["3","0","nil"]],
  [`class P { var n = 1 }\nlet a = P()\nlet b = P()\nprint(a === b)`,["false","true","1"]],
  [`struct S { var n = 1 }\nclass C { var n = 1 }\nvar s1 = S()\nvar s2 = s1\ns2.n = 5\nlet c1 = C()\nlet c2 = c1\nc2.n = 5\nprint(s1.n, c1.n)`,["1 5","5 5","1 1"]]
 ]},
{id:"sw16",title:"Enums & protocols",sub:"fixed choices and shared promises",steps:[
 {type:"talk",title:"Enums: a fixed set of choices",
  body:`<p>An ${C("enum")} lists every possible value. Switching on an enum needs no ${C("default")} if you cover every case, and Swift tells you if you forget one. Inside a switch you can write just ${C(".north")}.</p>`,
  demo:`enum Direction {\n    case north, south, east, west\n}\n\nlet d = Direction.east\nswitch d {\ncase .north, .south:\n    print("up or down")\ncase .east, .west:\n    print("sideways")\n}\nprint(d)`,
  say:"sideways, then east."},
 {type:"talk",title:"Raw values and all cases",mood:"think",
  body:`<p>Give each case a <b>raw value</b> with ${C(": Int")} or ${C(": String")}. Add ${C("CaseIterable")} to get ${C(".allCases")}. Enums can have methods too.</p>`,
  demo:`enum Coin: Int, CaseIterable {\n    case penny = 1, nickel = 5, dime = 10, quarter = 25\n\n    func label() -> String {\n        "\\(self) is worth \\(rawValue)¢"\n    }\n}\n\nfor c in Coin.allCases {\n    print(c.label())\n}\nprint(Coin(rawValue: 10) ?? .penny)`,
  say:"Each coin and its value, then dime."},
 {type:"talk",title:"Protocols are promises",mood:"cheer",
  body:`<p>A ${C("protocol")} lists what a type promises to have. Any struct, class or enum can <b>conform</b> to it. Then you can treat them all the same way.</p>`,
  demo:`protocol Speaker {\n    func speak() -> String\n}\n\nstruct Parrot: Speaker {\n    func speak() -> String { "Polly wants a cracker" }\n}\n\nclass Robot: Speaker {\n    func speak() -> String { "BEEP BOOP" }\n}\n\nlet things: [Speaker] = [Parrot(), Robot()]\nfor t in things {\n    print(t.speak())\n}`,
  say:"A parrot and a robot aren't related, but both keep the Speaker promise."},
 {type:"talk",title:"Extensions add more",
  body:`<p>An ${C("extension")} adds methods to a type after it's written. On a protocol, an extension gives every conforming type a free default method.</p>`,
  demo:`protocol Named {\n    var name: String { get }\n}\n\nextension Named {\n    func greet() -> String {\n        "Hi, I'm \\(name)!"\n    }\n}\n\nstruct Monkey: Named {\n    var name: String\n}\n\nprint(Monkey(name: "Mo").greet())`,
  say:"Hi, I'm Mo!"},
 {type:"quiz",q:"What does this print?",code:`enum Size: Int {\n    case small = 1, medium, large\n}\nprint(Size.large.rawValue)`,opts:["3","2","large"],a:0,mono:true,why:"Int raw values count up from the last one: 1, 2, 3."},
 {type:"quiz",q:"What does this print?",code:`enum Light { case red, green }\nlet l = Light.green\nprint(l)`,opts:["green","Light.green","1"],a:0,mono:true,why:"Printing an enum case prints its name."},
 {type:"quiz",q:"What does a protocol do?",opts:["Lists what a conforming type promises to have","Makes a copy of a struct","Stores values by key"],a:0,why:"Types conform to protocols by providing everything they list."},
 {type:"fill",title:"Keep the promise",body:`<p>Make Square conform to Shape.</p>`,code:`protocol Shape {\n    func area() -> Double\n}\n[0] Square: [1] {\n    var side: Double\n    func area() -> Double { side * side }\n}\nprint(Square(side: 3).area())`,blanks:["struct","Shape"],tokens:["struct","Shape","protocol","extends"],out:"9.0",why:"struct Square: Shape conforms to the protocol."},
 {type:"code",title:"Traffic light",body:`<p>Add a method ${C("next()")} to ${C("Light")} that returns the next light: green → yellow → red → green.</p>`,start:`enum Light {\n    case green, yellow, red\n    // add func next() -> Light here\n}\n\nvar l = Light.green\nfor _ in 1...4 {\n    l = l.next()\n    print(l)\n}\n`,
  use:[[/func\s+next\s*\(\s*\)\s*->\s*Light/,"Add func next() -> Light."],[/switch\s+self/,"Switch on self."]],out:["yellow","red","green","yellow"],
  hint:`enum Light {\n    case green, yellow, red\n    func next() -> Light {\n        switch self {\n        case .green: return .yellow\n        case .yellow: return .red\n        case .red: return .green\n        }\n    }\n}\n\nvar l = Light.green\nfor _ in 1...4 {\n    l = l.next()\n    print(l)\n}`},
 {type:"code",title:"Shapes",body:`<p>Make ${C("Circle")} and ${C("Square")} conform to ${C("Shape")}, then print the total area of all the shapes rounded to 2 decimals using ${C("(total * 100).rounded() / 100")}.</p>`,start:`protocol Shape {\n    var area: Double { get }\n}\n\n// write Circle (radius) and Square (side) here\n\nlet shapes: [Shape] = [Circle(radius: 1), Square(side: 2)]\nvar total = 0.0\nfor s in shapes {\n    total += s.area\n}\nprint((total * 100).rounded() / 100)\n`,
  use:[[/struct\s+Circle\s*:\s*Shape|class\s+Circle\s*:\s*Shape/,"Make Circle conform to Shape."],[/Double\.pi/,"Use Double.pi for the circle."]],out:["7.14"],
  hint:`protocol Shape {\n    var area: Double { get }\n}\n\nstruct Circle: Shape {\n    var radius: Double\n    var area: Double { Double.pi * radius * radius }\n}\n\nstruct Square: Shape {\n    var side: Double\n    var area: Double { side * side }\n}\n\nlet shapes: [Shape] = [Circle(radius: 1), Square(side: 2)]\nvar total = 0.0\nfor s in shapes {\n    total += s.area\n}\nprint((total * 100).rounded() / 100)`},
 {type:"game"},{type:"done"}],
 pool:[
  [`enum C { case red, blue }\nprint(C.blue)`,["blue","C.blue","1"]],
  [`enum C: CaseIterable { case a, b, c }\nprint(C.allCases.count)`,["3","2","4"]],
  [`enum N: Int { case one = 1, two, three }\nprint(N.two.rawValue)`,["2","1","two"]],
  [`enum P: String { case dog, cat }\nprint(P.cat.rawValue)`,["cat","P.cat","1"]],
  [`protocol I { func f() -> Int }\nstruct A: I { func f() -> Int { 4 } }\nlet x: I = A()\nprint(x.f() * 2)`,["8","4","Error"]],
  [`enum D { case n, s }\nlet d = D.s\nswitch d {\ncase .n: print("N")\ncase .s: print("S")\n}`,["S","N","s"]]
 ]},
{id:"sw17",title:"Project: Pet shelter",sub:"structs, classes, enums and optionals together",project:true,steps:[
 {type:"talk",title:"Run a pet shelter",mood:"cheer",
  body:`<p>You'll build the brains of a tiny pet-adoption app: a ${C("Pet")} type with a species enum, a shelter that finds pets, and adoptions that might fail.</p>`,
  say:"This is exactly how real iPhone apps organize their data."},
 {type:"code",title:"Step 1: the Pet",body:`<p>Give ${C("Pet")} a computed property ${C("summary")} that reads like ${C("Rex the dog, 3 years")}. (Hint: ${C("\\(species)")} prints the case name.)</p>`,start:`enum Species {\n    case dog, cat, rabbit\n}\n\nstruct Pet {\n    var name: String\n    var species: Species\n    var age: Int\n    // add summary here\n}\n\nlet pets = [Pet(name: "Rex", species: .dog, age: 3), Pet(name: "Mittens", species: .cat, age: 1)]\nfor p in pets {\n    print(p.summary)\n}\n`,
  use:[[/var\s+summary\s*:\s*String/,"Add var summary: String { ... }"]],out:["Rex the dog, 3 years","Mittens the cat, 1 years"],
  hint:`enum Species {\n    case dog, cat, rabbit\n}\n\nstruct Pet {\n    var name: String\n    var species: Species\n    var age: Int\n    var summary: String {\n        "\\(name) the \\(species), \\(age) years"\n    }\n}\n\nlet pets = [Pet(name: "Rex", species: .dog, age: 3), Pet(name: "Mittens", species: .cat, age: 1)]\nfor p in pets {\n    print(p.summary)\n}`},
 {type:"code",title:"Step 2: find a pet",body:`<p>Finish ${C("find(named:)")}: return the pet with that name, or ${C("nil")} if there isn't one. The code below prints the result safely.</p>`,start:`struct Pet {\n    var name: String\n    var age: Int\n}\n\nclass Shelter {\n    var pets: [Pet] = []\n    func add(_ p: Pet) {\n        pets.append(p)\n    }\n    func find(named name: String) -> Pet? {\n        // your code here\n        return nil\n    }\n}\n\nlet s = Shelter()\ns.add(Pet(name: "Rex", age: 3))\ns.add(Pet(name: "Bun", age: 2))\nif let p = s.find(named: "Bun") {\n    print("Found \\(p.name), age \\(p.age)")\n}\nprint(s.find(named: "Zed")?.name ?? "No pet called Zed")\n`,
  use:[[/for\s+\w+\s+in\s+pets|first\s*\(\s*where/,"Loop over pets (or use pets.first(where:))."]],out:["Found Bun, age 2","No pet called Zed"],
  hint:`struct Pet {\n    var name: String\n    var age: Int\n}\n\nclass Shelter {\n    var pets: [Pet] = []\n    func add(_ p: Pet) {\n        pets.append(p)\n    }\n    func find(named name: String) -> Pet? {\n        for p in pets {\n            if p.name == name {\n                return p\n            }\n        }\n        return nil\n    }\n}\n\nlet s = Shelter()\ns.add(Pet(name: "Rex", age: 3))\ns.add(Pet(name: "Bun", age: 2))\nif let p = s.find(named: "Bun") {\n    print("Found \\(p.name), age \\(p.age)")\n}\nprint(s.find(named: "Zed")?.name ?? "No pet called Zed")`},
 {type:"code",title:"Step 3: adoptions",body:`<p>Finish ${C("adopt(_:)")}: if the pet is there, remove it from ${C("pets")} and return ${C("true")}; otherwise return ${C("false")}. Then the code prints the result and how many pets are left.</p>`,start:`class Shelter {\n    var pets = ["Rex", "Bun", "Mittens"]\n    func adopt(_ name: String) -> Bool {\n        // your code here\n        return false\n    }\n}\n\nlet s = Shelter()\nprint(s.adopt("Bun"))\nprint(s.adopt("Zed"))\nprint(s.pets.count, s.pets)\n`,
  use:[[/firstIndex|remove|removeAll/,"Find it and remove it (firstIndex(of:) then remove(at:))."]],out:["true","false","2 [\"Rex\", \"Mittens\"]"],
  hint:`class Shelter {\n    var pets = ["Rex", "Bun", "Mittens"]\n    func adopt(_ name: String) -> Bool {\n        guard let i = pets.firstIndex(of: name) else {\n            return false\n        }\n        pets.remove(at: i)\n        return true\n    }\n}\n\nlet s = Shelter()\nprint(s.adopt("Bun"))\nprint(s.adopt("Zed"))\nprint(s.pets.count, s.pets)`},
 {type:"done"}]}
]},
{name:"Pro Swift",lessons:[
{id:"sw18",title:"Errors",sub:"throw, try, do-catch",steps:[
 {type:"talk",title:"Things that can fail",mood:"oops",
  body:`<p>Some work can fail, like a withdrawal with too little money. Describe the problems as an ${C("enum")} that conforms to ${C("Error")}, mark the function ${C("throws")}, and ${C("throw")} when something's wrong.</p>`,
  demo:`enum BankError: Error {\n    case notEnoughMoney\n    case badAmount\n}\n\nfunc withdraw(_ amount: Int, from balance: Int) throws -> Int {\n    if amount <= 0 {\n        throw BankError.badAmount\n    }\n    if amount > balance {\n        throw BankError.notEnoughMoney\n    }\n    return balance - amount\n}\n\nlet left = try withdraw(30, from: 100)\nprint(left)`,
  say:"70. Calling a throwing function needs the word try."},
 {type:"talk",title:"do and catch",
  body:`<p>Put ${C("try")} calls in a ${C("do")} block. If one throws, Swift jumps to the matching ${C("catch")}. A plain ${C("catch")} catches anything, and gives you the problem as ${C("error")}.</p>`,
  demo:`enum BankError: Error {\n    case notEnoughMoney\n    case badAmount\n}\n\nfunc withdraw(_ amount: Int, from balance: Int) throws -> Int {\n    guard amount > 0 else { throw BankError.badAmount }\n    guard amount <= balance else { throw BankError.notEnoughMoney }\n    return balance - amount\n}\n\ndo {\n    print(try withdraw(10, from: 50))\n    print(try withdraw(99, from: 50))\n    print("never printed")\n} catch BankError.notEnoughMoney {\n    print("Not enough money!")\n} catch {\n    print("Other problem: \\(error)")\n}`,
  say:"40, then Not enough money! The third line is skipped."},
 {type:"talk",title:"try? turns errors into nil",mood:"cheer",
  body:`<p>${C("try?")} gives you an optional: the value if it worked, ${C("nil")} if it threw. Combine it with ${C("??")} for a quick backup.</p>`,
  demo:`enum CheckError: Error {\n    case tooShort\n}\n\nfunc checkName(_ s: String) throws -> String {\n    if s.count < 2 {\n        throw CheckError.tooShort\n    }\n    return s.uppercased()\n}\n\nprint(try? checkName("Mo"))\nprint(try? checkName("M"))\nprint((try? checkName("M")) ?? "???")`,
  say:"Optional(\"MO\"), nil, ???."},
 {type:"quiz",q:"What word must you write before calling a function marked throws?",opts:["try","catch","throw"],a:0,mono:true,why:"try marks the spot where an error might come from."},
 {type:"quiz",q:"What does this print?",code:`enum E: Error { case oops }\nfunc f() throws -> Int { throw E.oops }\nprint((try? f()) ?? 0)`,opts:["0","nil","oops"],a:0,mono:true,why:"try? gives nil, and ?? swaps that for 0."},
 {type:"quiz",q:"What does this print?",code:`enum E: Error { case bad }\ndo {\n    print("A")\n    throw E.bad\n} catch {\n    print("B")\n}\nprint("C")`,opts:["A B C","A C","B C"],a:0,mono:true,why:"A prints, the throw jumps to catch (B), then the program carries on (C)."},
 {type:"fill",title:"Catch it",body:`<p>Handle the error.</p>`,code:`enum E: Error { case broke }\nfunc risky() throws { throw E.broke }\n[0] {\n    [1] risky()\n} catch {\n    print("Caught it")\n}`,blanks:["do","try"],tokens:["do","try","catch","throw"],out:"Caught it",why:"do { try ... } catch { ... }"},
 {type:"code",title:"Age checker",body:`<p>Make ${C("setAge")} throw ${C("AgeError.negative")} for ages below 0. The code below catches it.</p>`,start:`enum AgeError: Error {\n    case negative\n}\n\nfunc setAge(_ age: Int) throws {\n    // your code here\n    print("Age set to \\(age)")\n}\n\ndo {\n    try setAge(12)\n    try setAge(-3)\n} catch AgeError.negative {\n    print("Age can't be negative")\n}\n`,
  use:[[/throw\s+AgeError\.negative/,"throw AgeError.negative"]],out:["Age set to 12","Age can't be negative"],
  hint:`enum AgeError: Error {\n    case negative\n}\n\nfunc setAge(_ age: Int) throws {\n    if age < 0 {\n        throw AgeError.negative\n    }\n    print("Age set to \\(age)")\n}\n\ndo {\n    try setAge(12)\n    try setAge(-3)\n} catch AgeError.negative {\n    print("Age can't be negative")\n}`},
 {type:"game"},{type:"done"}],
 pool:[
  [`enum E: Error { case x }\nfunc f(_ n: Int) throws -> Int {\n    if n < 0 { throw E.x }\n    return n * 2\n}\nprint((try? f(4)) ?? -1)`,["8","-1","Optional(8)"]],
  [`enum E: Error { case x }\nfunc f(_ n: Int) throws -> Int {\n    if n < 0 { throw E.x }\n    return n * 2\n}\nprint((try? f(-4)) ?? -1)`,["-1","-8","nil"]],
  [`enum E: Error { case a, b }\ndo {\n    throw E.b\n} catch E.a {\n    print("A")\n} catch {\n    print("other")\n}`,["other","A","b"]],
  [`enum E: Error { case low }\ndo {\n    throw E.low\n} catch {\n    print(error)\n}`,["low","E.low","error"]]
 ]},
{id:"sw19",title:"Project: Banana Bank",sub:"your Swift capstone",project:true,steps:[
 {type:"talk",title:"Build a bank",mood:"cheer",
  body:`<p>Your capstone: an account class with safe deposits and withdrawals that throw errors, a bank that opens accounts and finds them by id, and a monthly report.</p>`,
  say:"Finish this and you've written real Swift. Nice work!"},
 {type:"code",title:"Step 1: safe account",body:`<p>Finish ${C("withdraw")}: throw ${C("BankError.notEnoughMoney")} if the amount is more than the balance, otherwise subtract it.</p>`,start:`enum BankError: Error {\n    case badAmount, notEnoughMoney\n}\n\nclass Account {\n    let owner: String\n    private(set) var balance = 0\n    init(owner: String) {\n        self.owner = owner\n    }\n    func deposit(_ amount: Int) throws {\n        guard amount > 0 else { throw BankError.badAmount }\n        balance += amount\n    }\n    func withdraw(_ amount: Int) throws {\n        // your code here\n    }\n}\n\nlet a = Account(owner: "Mo")\ndo {\n    try a.deposit(30)\n    try a.withdraw(10)\n    try a.withdraw(100)\n} catch BankError.notEnoughMoney {\n    print("Not enough money")\n} catch {\n    print("Something else went wrong")\n}\nprint(a.balance)\n`,
  use:[[/throw\s+BankError\.notEnoughMoney/,"throw BankError.notEnoughMoney"]],out:["Not enough money","20"],
  hint:`enum BankError: Error {\n    case badAmount, notEnoughMoney\n}\n\nclass Account {\n    let owner: String\n    private(set) var balance = 0\n    init(owner: String) {\n        self.owner = owner\n    }\n    func deposit(_ amount: Int) throws {\n        guard amount > 0 else { throw BankError.badAmount }\n        balance += amount\n    }\n    func withdraw(_ amount: Int) throws {\n        guard amount <= balance else { throw BankError.notEnoughMoney }\n        balance -= amount\n    }\n}\n\nlet a = Account(owner: "Mo")\ndo {\n    try a.deposit(30)\n    try a.withdraw(10)\n    try a.withdraw(100)\n} catch BankError.notEnoughMoney {\n    print("Not enough money")\n} catch {\n    print("Something else went wrong")\n}\nprint(a.balance)`},
 {type:"code",title:"Step 2: the bank",body:`<p>Finish ${C("open(for:)")}: make a new Account, store it in ${C("accounts")} under the next id (starting at 1), and return the id. ${C("find")} gives it back as an optional.</p>`,start:`class Account {\n    let owner: String\n    var balance = 0\n    init(owner: String) {\n        self.owner = owner\n    }\n}\n\nclass Bank {\n    var accounts: [Int: Account] = [:]\n    var nextId = 1\n    func open(for owner: String) -> Int {\n        // your code here\n        return 0\n    }\n    func find(_ id: Int) -> Account? {\n        accounts[id]\n    }\n}\n\nlet bank = Bank()\nlet mo = bank.open(for: "Mo")\nlet kiki = bank.open(for: "Kiki")\nbank.find(kiki)?.balance += 20\nprint(mo, kiki)\nprint(bank.find(2)?.owner ?? "nobody", bank.find(2)?.balance ?? 0)\nprint(bank.find(9)?.owner ?? "nobody")\n`,
  use:[[/accounts\s*\[\s*\w+\s*\]\s*=/,"Store it with accounts[id] = ..."]],out:["1 2","Kiki 20","nobody"],
  hint:`class Account {\n    let owner: String\n    var balance = 0\n    init(owner: String) {\n        self.owner = owner\n    }\n}\n\nclass Bank {\n    var accounts: [Int: Account] = [:]\n    var nextId = 1\n    func open(for owner: String) -> Int {\n        let id = nextId\n        accounts[id] = Account(owner: owner)\n        nextId += 1\n        return id\n    }\n    func find(_ id: Int) -> Account? {\n        accounts[id]\n    }\n}\n\nlet bank = Bank()\nlet mo = bank.open(for: "Mo")\nlet kiki = bank.open(for: "Kiki")\nbank.find(kiki)?.balance += 20\nprint(mo, kiki)\nprint(bank.find(2)?.owner ?? "nobody", bank.find(2)?.balance ?? 0)\nprint(bank.find(9)?.owner ?? "nobody")`},
 {type:"code",title:"Step 3: monthly report",body:`<p>Add ${C("report()")} to Bank: print each account in id order like ${C("#1 Mo: 50")}, then ${C("Total: 70")}. Loop over ${C("accounts.keys.sorted()")} so the order is always the same.</p>`,start:`class Account {\n    let owner: String\n    var balance: Int\n    init(owner: String, balance: Int) {\n        self.owner = owner\n        self.balance = balance\n    }\n}\n\nclass Bank {\n    var accounts: [Int: Account] = [:]\n    // add report() here\n}\n\nlet bank = Bank()\nbank.accounts[2] = Account(owner: "Kiki", balance: 20)\nbank.accounts[1] = Account(owner: "Mo", balance: 50)\nbank.report()\n`,
  use:[[/func\s+report\s*\(\s*\)/,"Add func report()."],[/keys\.sorted\s*\(\s*\)/,"Loop over accounts.keys.sorted()."]],out:["#1 Mo: 50","#2 Kiki: 20","Total: 70"],
  hint:`class Account {\n    let owner: String\n    var balance: Int\n    init(owner: String, balance: Int) {\n        self.owner = owner\n        self.balance = balance\n    }\n}\n\nclass Bank {\n    var accounts: [Int: Account] = [:]\n    func report() {\n        var total = 0\n        for id in accounts.keys.sorted() {\n            let a = accounts[id]!\n            print("#\\(id) \\(a.owner): \\(a.balance)")\n            total += a.balance\n        }\n        print("Total: \\(total)")\n    }\n}\n\nlet bank = Bank()\nbank.accounts[2] = Account(owner: "Kiki", balance: 20)\nbank.accounts[1] = Account(owner: "Mo", balance: 50)\nbank.report()`},
 {type:"done"}]}
]}
]};

/* Unit 6: Swift power-ups. Outputs checked against real Swift 6 by tests/verify_swift_real.py. */
COURSE_SWIFT.units.push({name:"Swift power-ups",lessons:[
{id:"sw20",title:"Teach Swift new tricks",sub:"extensions on Int and String",steps:[
 {type:"talk",title:"A warm-up: give Int a new trick",mood:"cheer",
  body:`<p>You already used ${C("extension")} on your own types. You can extend Swift's own types too! Here every ${C("Int")} learns a new property called ${C("isEven")}. Inside the extension, ${C("self")} is the number you asked.</p>`,
  demo:`extension Int {\n    var isEven: Bool {\n        self % 2 == 0\n    }\n}\n\nprint(4.isEven)\nprint(7.isEven)`,
  say:"Output:\ntrue\nfalse"},
 {type:"talk",title:"Methods work too",
  body:`<p>An extension can add methods as well. Inside a ${C("String")} extension you can call other String methods, like ${C("uppercased()")}, without writing ${C("self.")} in front.</p>`,
  demo:`extension String {\n    func shout() -> String {\n        uppercased() + "!"\n    }\n}\n\nprint("ook".shout())\nprint("hello monkey".shout())`,
  say:"OOK! and HELLO MONKEY!"},
 {type:"quiz",q:"What does this print?",code:`extension Int {\n    var doubled: Int { self * 2 }\n}\nprint(5.doubled)`,opts:["10","5","52"],a:0,mono:true,why:"self is 5, so doubled is 5 * 2."},
 {type:"quiz",q:"Inside an extension on Int, what is self?",opts:["The number you used it on","The word Int","Always zero"],a:0,why:"For 5.doubled, self is 5."},
 {type:"fill",title:"Square it",body:`<p>Add a ${C("squared")} property to every Int.</p>`,code:`[0] Int {\n    var squared: Int { [1] * self }\n}\nprint(3.squared)`,blanks:["extension","self"],tokens:["extension","self","struct","this"],out:"9",why:"extension Int adds to Int, and self is the number."},
 {type:"code",title:"Is it big?",body:`<p>Add a computed property ${C("isBig")} to ${C("Int")} that is ${C("true")} when the number is <b>over 100</b>. The two prints are already written, so the output should be ${C("true")} then ${C("false")}.</p>`,start:`extension Int {\n    // add var isBig: Bool { ... } here\n}\n\nprint(250.isBig)\nprint(42.isBig)\n`,
  use:[[/var\s+isBig\s*:\s*Bool/,"Add var isBig: Bool { ... } inside the extension."]],out:["true","false"],
  hint:`extension Int {\n    var isBig: Bool {\n        self > 100\n    }\n}\n\nprint(250.isBig)\nprint(42.isBig)`},
 {type:"code",title:"Say it twice",body:`<p>Finish ${C("twice()")} so it gives back the text two times in a row. Replace ${C('return ""')} with your answer. The output should be ${C("ookook")} then ${C("nana")}.</p>`,start:`extension String {\n    func twice() -> String {\n        // give back the text two times\n        return ""\n    }\n}\n\nprint("ook".twice())\nprint("na".twice())\n`,
  use:[[/func\s+twice/,"Keep func twice() -> String."]],out:["ookook","nana"],
  hint:`extension String {\n    func twice() -> String {\n        return self + self\n    }\n}\n\nprint("ook".twice())\nprint("na".twice())`},
 {type:"game"},{type:"done"}],
 pool:[
  [`extension Int {\n    var tripled: Int { self * 3 }\n}\nprint(4.tripled)`,["12","4","43"]],
  [`extension Int {\n    var isZero: Bool { self == 0 }\n}\nprint(0.isZero)`,["true","false","0"]],
  [`extension String {\n    func wow() -> String { self + "!" }\n}\nprint("ook".wow())`,["ook!","ook","!ook"]],
  [`extension Int {\n    func plus(_ n: Int) -> Int { self + n }\n}\nprint(2.plus(5))`,["7","25","2"]],
  [`extension String {\n    var size: Int { count }\n}\nprint("banana".size)`,["6","5","banana"]],
  [`extension Int {\n    var half: Int { self / 2 }\n}\nprint(9.half)`,["4","4.5","5"]]
 ]},
{id:"sw21",title:"Enums that carry values",sub:"associated values and switch",steps:[
 {type:"talk",title:"A case can hold a value",
  body:`<p>Sometimes a choice needs extra information. A ${C("coins")} reward needs to say <i>how many</i>. Put the type in brackets after the case: ${C("case coins(Int)")}. In a ${C("switch")}, ${C("let n")} pulls the value out.</p>`,
  demo:`enum Reward {\n    case banana\n    case coins(Int)\n}\n\nlet prizes: [Reward] = [.banana, .coins(5)]\nfor p in prizes {\n    switch p {\n    case .banana:\n        print("A banana!")\n    case .coins(let n):\n        print("\\(n) coins")\n    }\n}`,
  say:"A banana!, then 5 coins."},
 {type:"talk",title:"Labels make it clear",mood:"think",
  body:`<p>You can give the values labels, like ${C("jump(height: 3)")}. To check for just one case, use ${C("if case")}.</p>`,
  demo:`enum Move {\n    case jump(height: Int)\n    case say(text: String)\n}\n\nlet m = Move.jump(height: 3)\nif case .jump(let h) = m {\n    print("Jumped \\(h) meters")\n}\nprint(m)`,
  say:"Jumped 3 meters, then jump(height: 3)."},
 {type:"quiz",q:"What does this print?",code:`enum Shape {\n    case square(Int)\n}\nlet s = Shape.square(4)\nswitch s {\ncase .square(let side):\n    print(side * side)\n}`,opts:["16","4","square(4)"],a:0,mono:true,why:"side is 4, and 4 * 4 is 16."},
 {type:"quiz",q:"How do you get the 5 out of .coins(5)?",opts:["case .coins(let n): in a switch","coins.value","Reward[5]"],a:0,why:"The pattern .coins(let n) puts the value into n."},
 {type:"fill",title:"Bag of nuts",body:`<p>A snack can be some nuts. Print how many.</p>`,code:`enum Snack {\n    case nuts([0])\n}\nlet s = Snack.nuts(3)\nswitch s {\ncase .nuts([1] n):\n    print(n)\n}`,blanks:["Int","let"],tokens:["Int","let","String","func"],out:"3",why:"case nuts(Int) holds a number, and let n pulls it out."},
 {type:"code",title:"Weather report",body:`<p>The ${C(".rain")} case is missing its text. Make it give back ${C("Rain: 5mm")} for ${C(".rain(mm: 5)")}. Use ${C("\\(mm)")} to put the number in the text. Output: ${C("Sunny!")} then ${C("Rain: 5mm")}.</p>`,start:`enum Weather {\n    case sunny\n    case rain(mm: Int)\n}\n\nfunc describe(_ w: Weather) -> String {\n    switch w {\n    case .sunny:\n        return "Sunny!"\n    case .rain(let mm):\n        // give back text like "Rain: 5mm"\n        return ""\n    }\n}\n\nprint(describe(.sunny))\nprint(describe(.rain(mm: 5)))\n`,
  use:[[/\\\(\s*mm\s*\)/,"Put the amount into the text with \\(mm)."]],out:["Sunny!","Rain: 5mm"],variants:[[/mm: 5\)\)/,"mm: 12))",["Sunny!","Rain: 12mm"]]],
  hint:`enum Weather {\n    case sunny\n    case rain(mm: Int)\n}\n\nfunc describe(_ w: Weather) -> String {\n    switch w {\n    case .sunny:\n        return "Sunny!"\n    case .rain(let mm):\n        return "Rain: \\(mm)mm"\n    }\n}\n\nprint(describe(.sunny))\nprint(describe(.rain(mm: 5)))`},
 {type:"code",title:"Count the loot",body:`<p>Go through ${C("haul")}: add each ${C(".coins")} amount to ${C("coins")}, and add 1 to ${C("bananas")} for each ${C(".banana")}. Use a ${C("switch")} inside the loop. Output: ${C("Coins: 15")} then ${C("Bananas: 2")}.</p>`,start:`enum Reward {\n    case banana\n    case coins(Int)\n}\n\nlet haul: [Reward] = [.coins(5), .banana, .coins(10), .banana]\nvar coins = 0\nvar bananas = 0\nfor r in haul {\n    // switch on r here\n}\nprint("Coins: \\(coins)")\nprint("Bananas: \\(bananas)")\n`,
  use:[[/switch\s+r|if\s+case/,"Switch on r inside the loop."],[/\.coins\s*\(\s*let/,"Use case .coins(let n) to get the amount."]],out:["Coins: 15","Bananas: 2"],
  hint:`enum Reward {\n    case banana\n    case coins(Int)\n}\n\nlet haul: [Reward] = [.coins(5), .banana, .coins(10), .banana]\nvar coins = 0\nvar bananas = 0\nfor r in haul {\n    switch r {\n    case .banana:\n        bananas += 1\n    case .coins(let n):\n        coins += n\n    }\n}\nprint("Coins: \\(coins)")\nprint("Bananas: \\(bananas)")`},
 {type:"game"},{type:"done"}],
 pool:[
  [`enum R { case coins(Int) }\nlet r = R.coins(7)\nswitch r {\ncase .coins(let n): print(n)\n}`,["7","coins(7)","R.coins"]],
  [`enum R { case coins(Int) }\nprint(R.coins(2))`,["coins(2)","2","R.coins(2)"]],
  [`enum P { case pt(x: Int, y: Int) }\nlet p = P.pt(x: 1, y: 2)\nif case .pt(let x, let y) = p { print(x + y) }`,["3","12","pt(x: 1, y: 2)"]],
  [`enum S { case a, b(Int) }\nlet s = S.a\nswitch s {\ncase .a: print("A")\ncase .b(let n): print(n)\n}`,["A","a","0"]],
  [`enum T { case say(String) }\nlet t = T.say("hi")\nswitch t {\ncase .say(let w): print(w + w)\n}`,["hihi","hi","say(hi)"]],
  [`enum M { case jump(height: Int) }\nprint(M.jump(height: 4))`,["jump(height: 4)","4","jump(4)"]]
 ]},
{id:"sw22",title:"Generics",sub:"one function for any type",steps:[
 {type:"talk",title:"The same code for every type",
  body:`<p>Write ${C("<T>")} after a function's name and ${C("T")} stands for <b>any type</b>. Swift fills it in each time you call the function: here once with ${C("Int")} and once with ${C("String")}.</p>`,
  demo:`func twice<T>(_ value: T) -> [T] {\n    [value, value]\n}\n\nprint(twice(7))\nprint(twice("ook"))`,
  say:"[7, 7] and [\"ook\", \"ook\"]. Arrays are generic too: [Int] is really Array<Int>."},
 {type:"talk",title:"Rules for T",mood:"think",
  body:`<p>To compare values with ${C(">")}, say that ${C("T")} must be ${C("Comparable")}: ${C("<T: Comparable>")}. Numbers and Strings are both Comparable.</p>`,
  demo:`func biggest<T: Comparable>(_ a: T, _ b: T) -> T {\n    a > b ? a : b\n}\n\nprint(biggest(3, 9))\nprint(biggest("apple", "banana"))`,
  say:"9, then banana (it comes later in the alphabet)."},
 {type:"talk",title:"Generic types",mood:"cheer",
  body:`<p>Structs can be generic too. A ${C("Box<Item>")} can hold any kind of item.</p>`,
  demo:`struct Box<Item> {\n    var item: Item\n}\n\nlet a = Box(item: 5)\nlet b = Box(item: "banana")\nprint(a.item + 1)\nprint(b.item.count)`,
  say:"6, then 6."},
 {type:"quiz",q:"What does this print?",code:`func pair<T>(_ x: T) -> (T, T) {\n    (x, x)\n}\nprint(pair(1))`,opts:["(1, 1)","[1, 1]","1 1"],a:0,mono:true,why:"pair gives back a tuple with x in it twice."},
 {type:"quiz",q:"What does <T: Comparable> mean?",opts:["T can be any type that works with < and >","T must be an Int","T is short for Text"],a:0,why:"The rule after the colon says what T must be able to do."},
 {type:"fill",title:"Last one",body:`<p>Make ${C("last")} work for an array of any type.</p>`,code:`func last[0](_ items: [T]) -> T? {\n    items.last\n}\nprint(last([1, 2, 3]) ?? 0)`,blanks:["<T>"],tokens:["<T>","(T)","[T]","T"],out:"3",why:"<T> after the name makes the function generic."},
 {type:"code",title:"Repeat it",body:`<p>Finish ${C("repeatItem")}: give back an array with ${C("item")} in it ${C("times")} times. Replace ${C("return []")}. (Tip: ${C("Array(repeating: item, count: times)")}.) Output: ${C('["ook", "ook", "ook"]')} then ${C("[7, 7]")}.</p>`,start:`func repeatItem<T>(_ item: T, times: Int) -> [T] {\n    // make an array with item in it, times times\n    return []\n}\n\nprint(repeatItem("ook", times: 3))\nprint(repeatItem(7, times: 2))\n`,
  use:[[/func\s+repeatItem\s*<\s*T\s*>/,"Keep func repeatItem<T>."]],out:['["ook", "ook", "ook"]',"[7, 7]"],
  hint:`func repeatItem<T>(_ item: T, times: Int) -> [T] {\n    return Array(repeating: item, count: times)\n}\n\nprint(repeatItem("ook", times: 3))\nprint(repeatItem(7, times: 2))`},
 {type:"code",title:"Smallest of all",body:`<p>Fill in the loop so ${C("smallest")} keeps the smallest item it has seen: if ${C("x < best")}, set ${C("best = x")}. Output: ${C("2")} then ${C("apple")}.</p>`,start:`func smallest<T: Comparable>(_ items: [T]) -> T? {\n    guard var best = items.first else {\n        return nil\n    }\n    for x in items {\n        // if x is smaller than best, keep x\n    }\n    return best\n}\n\nprint(smallest([5, 2, 8]) ?? 0)\nprint(smallest(["kiwi", "apple", "fig"]) ?? "")\n`,
  use:[[/x\s*<\s*best|best\s*>\s*x/,"Compare: if x < best"],[/best\s*=\s*x/,"Keep the smaller one: best = x"]],out:["2","apple"],
  hint:`func smallest<T: Comparable>(_ items: [T]) -> T? {\n    guard var best = items.first else {\n        return nil\n    }\n    for x in items {\n        if x < best {\n            best = x\n        }\n    }\n    return best\n}\n\nprint(smallest([5, 2, 8]) ?? 0)\nprint(smallest(["kiwi", "apple", "fig"]) ?? "")`},
 {type:"game"},{type:"done"}],
 pool:[
  [`func same<T>(_ x: T) -> T { x }\nprint(same("ook"))`,["ook","T","\"ook\""]],
  [`func two<T>(_ x: T) -> [T] { [x, x] }\nprint(two(3))`,["[3, 3]","[3]","6"]],
  [`func big<T: Comparable>(_ a: T, _ b: T) -> T { a > b ? a : b }\nprint(big(4, 2))`,["4","2","true"]],
  [`struct Box<T> { var v: T }\nprint(Box(v: 9).v)`,["9","Box(v: 9)","T"]],
  [`func first<T>(_ a: [T]) -> T? { a.first }\nprint(first([8, 9]) ?? 0)`,["8","9","Optional(8)"]],
  [`func big<T: Comparable>(_ a: T, _ b: T) -> T { a > b ? a : b }\nprint(big("fig", "apple"))`,["fig","apple","true"]]
 ]},
{id:"sw23",title:"Watchers & shared values",sub:"didSet and static",steps:[
 {type:"talk",title:"didSet watches a property",
  body:`<p>Add ${C("didSet")} to a property and Swift runs that code every time the property changes. Inside, ${C("oldValue")} is what it was before.</p>`,
  demo:`struct Player {\n    var score = 0 {\n        didSet {\n            print("Score: \\(oldValue) -> \\(score)")\n        }\n    }\n}\n\nvar p = Player()\np.score += 10\np.score = 25`,
  say:"Score: 0 -> 10, then Score: 10 -> 25."},
 {type:"talk",title:"static: one value for the whole type",mood:"think",
  body:`<p>A ${C("static")} property belongs to the type itself, not to each value. Every monkey shares it, and you reach it with the type's name: ${C("Game.maxLives")}.</p>`,
  demo:`struct Game {\n    static let maxLives = 3\n    static var gamesPlayed = 0\n}\n\nGame.gamesPlayed += 1\nGame.gamesPlayed += 1\nprint(Game.maxLives, Game.gamesPlayed)`,
  say:"3 2"},
 {type:"quiz",q:"What does this print?",code:`struct Lamp {\n    var on = false {\n        didSet { print("click") }\n    }\n}\nvar l = Lamp()\nl.on = true\nl.on = false`,opts:["click click","click","Nothing"],a:0,mono:true,why:"didSet runs every time on changes: twice here."},
 {type:"quiz",q:"How do you read a static property called top in a struct called Score?",opts:["Score.top","Score().top","top.Score"],a:0,why:"Static properties belong to the type, so you use the type's name."},
 {type:"fill",title:"Watch the bananas",body:`<p>Print a message each time ${C("bananas")} changes.</p>`,code:`struct Bag {\n    var bananas = 0 {\n        [0] {\n            print("Now \\(bananas)")\n        }\n    }\n}\nvar b = Bag()\nb.bananas = 4`,blanks:["didSet"],tokens:["didSet","static","func","get"],out:"Now 4",why:"didSet runs right after the property changes."},
 {type:"code",title:"Best score",body:`<p>In ${C("didSet")}, if the new ${C("score")} is bigger than ${C("best")}, set ${C("best = score")}. The scores 40, 60, 30 are set for you, so the output should be ${C("Score: 30, best: 60")}.</p>`,start:`struct Player {\n    var best = 0\n    var score = 0 {\n        didSet {\n            // if score is bigger than best, update best\n        }\n    }\n}\n\nvar p = Player()\np.score = 40\np.score = 60\np.score = 30\nprint("Score: \\(p.score), best: \\(p.best)")\n`,
  use:[[/score\s*>\s*best|best\s*<\s*score|max\s*\(/,"Compare score with best."],[/best\s*=/,"Update best."]],out:["Score: 30, best: 60"],
  hint:`struct Player {\n    var best = 0\n    var score = 0 {\n        didSet {\n            if score > best {\n                best = score\n            }\n        }\n    }\n}\n\nvar p = Player()\np.score = 40\np.score = 60\np.score = 30\nprint("Score: \\(p.score), best: \\(p.best)")`},
 {type:"code",title:"Count the monkeys",body:`<p>Every time a ${C("Monkey")} is made, add 1 to the shared ${C("Monkey.count")}. Write that one line in ${C("init")}. Output: ${C("Monkeys made: 3")}.</p>`,start:`struct Monkey {\n    static var count = 0\n    var name: String\n\n    init(name: String) {\n        self.name = name\n        // add 1 to Monkey.count\n    }\n}\n\nlet troop = [Monkey(name: "Mo"), Monkey(name: "Kiki"), Monkey(name: "Zed")]\nprint("Monkeys made: \\(Monkey.count)")\n`,
  use:[[/Monkey\.count\s*\+=\s*1|Monkey\.count\s*=\s*Monkey\.count\s*\+\s*1/,"Write Monkey.count += 1 inside init."]],out:["Monkeys made: 3"],
  hint:`struct Monkey {\n    static var count = 0\n    var name: String\n\n    init(name: String) {\n        self.name = name\n        Monkey.count += 1\n    }\n}\n\nlet troop = [Monkey(name: "Mo"), Monkey(name: "Kiki"), Monkey(name: "Zed")]\nprint("Monkeys made: \\(Monkey.count)")`},
 {type:"game"},{type:"done"}],
 pool:[
  [`struct G { static var n = 1 }\nG.n += 4\nprint(G.n)`,["5","1","4"]],
  [`struct G { static let lives = 3 }\nprint(G.lives * 2)`,["6","3","32"]],
  [`struct T {\n    var v = 1 { didSet { print(oldValue) } }\n}\nvar t = T()\nt.v = 9`,["1","9","0"]],
  [`struct T {\n    var v = 1 { didSet { print(v) } }\n}\nvar t = T()\nt.v = 9`,["9","1","10"]],
  [`struct T {\n    var v = 0 { didSet { print("x") } }\n}\nvar t = T()\nt.v += 1\nt.v += 1`,["x x","x","1 2"]],
  [`struct C {\n    static var made = 0\n    init() { C.made += 1 }\n}\nlet a = [C(), C()]\nprint(C.made, a.count)`,["2 2","0 2","1 2"]]
 ]},
{id:"sw24",title:"Project: Monkey Quest",sub:"power-ups together, one small step at a time",project:true,steps:[
 {type:"talk",title:"Build a quest bag",mood:"cheer",
  body:`<p>You'll build the item bag for a jungle adventure game, one small piece at a time: items that carry values, a bag that reports every change, and a helper that works for any list.</p>`,
  say:"Three small steps. You've already practised every one of them!"},
 {type:"code",title:"Step 1: name the key",body:`<p>${C("Item")} has a ${C("label")} for each case. Banana and coins are done. Finish the ${C(".key")} case so it gives back text like ${C("red key")}. Output: ${C("banana")}, ${C("5 coins")}, ${C("red key")}.</p>`,start:`enum Item {\n    case banana\n    case coins(Int)\n    case key(color: String)\n\n    var label: String {\n        switch self {\n        case .banana:\n            return "banana"\n        case .coins(let n):\n            return "\\(n) coins"\n        case .key(let color):\n            // give back text like "red key"\n            return ""\n        }\n    }\n}\n\nlet items: [Item] = [.banana, .coins(5), .key(color: "red")]\nfor i in items {\n    print(i.label)\n}\n`,
  use:[[/\\\(\s*color\s*\)/,"Put the color into the text with \\(color)."]],out:["banana","5 coins","red key"],variants:[[/color: "red"\)\]/,`color: "gold")]`,["banana","5 coins","gold key"]]],
  hint:`enum Item {\n    case banana\n    case coins(Int)\n    case key(color: String)\n\n    var label: String {\n        switch self {\n        case .banana:\n            return "banana"\n        case .coins(let n):\n            return "\\(n) coins"\n        case .key(let color):\n            return "\\(color) key"\n        }\n    }\n}\n\nlet items: [Item] = [.banana, .coins(5), .key(color: "red")]\nfor i in items {\n    print(i.label)\n}`},
 {type:"code",title:"Step 2: the bag",body:`<p>The bag already reports every change with ${C("didSet")}. Write the body of ${C("add(_:)")}: one line that appends the item to ${C("items")}. Output: ${C("Bag has 1 item(s)")} then ${C("Bag has 2 item(s)")}.</p>`,start:`struct Bag {\n    var items: [String] = [] {\n        didSet {\n            print("Bag has \\(items.count) item(s)")\n        }\n    }\n\n    mutating func add(_ item: String) {\n        // append item to items\n    }\n}\n\nvar bag = Bag()\nbag.add("banana")\nbag.add("red key")\n`,
  use:[[/items\.append\s*\(|items\s*\+=/,"Use items.append(item)."]],out:["Bag has 1 item(s)","Bag has 2 item(s)"],
  hint:`struct Bag {\n    var items: [String] = [] {\n        didSet {\n            print("Bag has \\(items.count) item(s)")\n        }\n    }\n\n    mutating func add(_ item: String) {\n        items.append(item)\n    }\n}\n\nvar bag = Bag()\nbag.add("banana")\nbag.add("red key")`},
 {type:"code",title:"Step 3: count anything",body:`<p>${C("countWhere")} works for a list of any type ${C("T")}. Finish the loop: add 1 to ${C("total")} when ${C("test(x)")} is true. Output: ${C("2")} (big numbers) then ${C("1")} (words starting with k).</p>`,start:`func countWhere<T>(_ list: [T], _ test: (T) -> Bool) -> Int {\n    var total = 0\n    for x in list {\n        // if test(x) is true, add 1 to total\n    }\n    return total\n}\n\nprint(countWhere([5, 50, 500]) { $0 > 10 })\nprint(countWhere(["kiwi", "fig", "plum"]) { $0.hasPrefix("k") })\n`,
  use:[[/test\s*\(\s*x\s*\)/,"Call test(x) inside the loop."],[/total\s*\+=\s*1|total\s*=\s*total\s*\+\s*1/,"Add 1 to total."]],out:["2","1"],
  hint:`func countWhere<T>(_ list: [T], _ test: (T) -> Bool) -> Int {\n    var total = 0\n    for x in list {\n        if test(x) {\n            total += 1\n        }\n    }\n    return total\n}\n\nprint(countWhere([5, 50, 500]) { $0 > 10 })\nprint(countWhere(["kiwi", "fig", "plum"]) { $0.hasPrefix("k") })`},
 {type:"done"}]}
]});
