/* HTML & CSS course. Code renders live in the app. Challenges are checked by inspecting the page the learner built:
   checks:[{sel, msg, text?:RegExp, count?:n, attr?:[name,RegExp], style?:{property:value|RegExp}}] */
const WEB_UNIT1={name:"HTML basics",free:true,lessons:[
{id:"web1",title:"Your first web page",sub:"tags, headings, paragraphs",steps:[
 {type:"talk",title:"Every website is HTML",mood:"cheer",
  body:`<p>HTML describes what's on a page: headings, text, images, buttons. It's made of <b>tags</b> in angle brackets. Most come in pairs: an opening ${C("&lt;p&gt;")} and a closing ${C("&lt;/p&gt;")}.</p>`,
  demo:`<h1>Hello, web!</h1>\n<p>This is my very first web page.</p>`,
  say:"Tap ▶ Show page. You just made a website! Change the words and show it again."},
 {type:"talk",title:"Headings and paragraphs",mood:"think",
  body:`<p>${C("&lt;h1&gt;")} is the biggest heading, down to ${C("&lt;h6&gt;")}, the smallest. ${C("&lt;p&gt;")} is a paragraph. ${C("&lt;br&gt;")} is a line break and doesn't need a closing tag.</p>`,
  demo:`<h1>TypeMonkey Zoo</h1>\n<h2>Opening hours</h2>\n<p>Open every day.<br>Bananas served at noon.</p>\n<h3>Small print</h3>\n<p>Please don't feed the parrot.</p>`,
  say:"Use h1 once for the page title, then h2, h3 for sections."},
 {type:"quiz",q:"Which tag closes a paragraph?",opts:["</p>","<p/>","<close p>"],a:0,mono:true,why:"Closing tags have a slash right after the <."},
 {type:"fill",title:"Make a heading",body:`<p>Create the biggest heading.</p>`,code:`<[0]>Welcome!</[1]>`,blanks:["h1","h1"],tokens:["h1","h1","p","title"],why:"Opening and closing tags must match."},
 {type:"code",title:"Your turn: a mini page",
  body:`<p>Make a page with an ${C("&lt;h1&gt;")} that says ${C("TypeMonkey")} and a ${C("&lt;p&gt;")} paragraph underneath with any sentence.</p>`,
  start:`<!-- your HTML here -->\n`,
  checks:[{sel:"h1",text:/TypeMonkey/i,msg:"Add an <h1> that says TypeMonkey."},{sel:"p",text:/\S/,msg:"Add a <p> paragraph with some text in it."}],
  hint:`<h1>TypeMonkey</h1>\n<p>The coolest coding monkey around.</p>`},
 {type:"quiz",q:"Which is the biggest heading?",opts:["<h1>","<h6>","<head>"],a:0,mono:true,why:"Smaller numbers mean bigger, more important headings."},
 {type:"done"}]},
{id:"web2",title:"Lists & text styles",sub:"ul, ol, li, strong, em",steps:[
 {type:"talk",title:"Lists",
  body:`<p>${C("&lt;ul&gt;")} is a bulleted list. ${C("&lt;ol&gt;")} is a numbered list. Each item goes in an ${C("&lt;li&gt;")}.</p>`,
  demo:`<h2>Snacks</h2>\n<ul>\n  <li>Bananas</li>\n  <li>Mangoes</li>\n</ul>\n<h2>Morning routine</h2>\n<ol>\n  <li>Wake up</li>\n  <li>Eat a banana</li>\n  <li>Code</li>\n</ol>`,
  say:"Tags can go inside other tags. That's called nesting."},
 {type:"talk",title:"Bold and italic",mood:"think",
  body:`<p>${C("&lt;strong&gt;")} marks important text (bold). ${C("&lt;em&gt;")} adds emphasis (italic). They go inside other text.</p>`,
  demo:`<p>This is <strong>very important</strong>.</p>\n<p>I <em>really</em> love bananas.</p>`,
  say:"Screen readers say strong and em text with extra emphasis too."},
 {type:"quiz",q:"Which list shows numbers?",opts:["<ol>","<ul>","<li>"],a:0,mono:true,why:"ol means ordered list. ul means unordered (bullets)."},
 {type:"order",title:"Build a list",body:`<p>Put the tags in the right order.</p>`,lines:["<ul>","  <li>Kiwi</li>","  <li>Papaya</li>","</ul>"],why:"Open the list, add items, close the list.",noRun:true},
 {type:"code",title:"Top 3 list",
  body:`<p>Make a <b>numbered</b> list with at least 3 of your favorite things.</p>`,
  start:`<h2>My top 3</h2>\n`,
  checks:[{sel:"ol",msg:"Use an <ol> for a numbered list."},{sel:"ol > li",count:3,msg:"Put at least 3 <li> items inside your <ol>."}],
  hint:`<h2>My top 3</h2>\n<ol>\n  <li>Bananas</li>\n  <li>Coding</li>\n  <li>Naps</li>\n</ol>`},
 {type:"done"}]},
{id:"web3",title:"Links & images",sub:"a href, img src, alt",steps:[
 {type:"talk",title:"Links",
  body:`<p>${C("&lt;a&gt;")} makes a link. The ${C("href")} <b>attribute</b> says where it goes. Attributes go inside the opening tag.</p>`,
  demo:`<p>Learn more on <a href="https://developer.mozilla.org">MDN</a>.</p>\n<p><a href="#top">Back to top</a></p>`,
  say:"Attributes look like name=\"value\"."},
 {type:"talk",title:"Images",mood:"think",
  body:`<p>${C("&lt;img&gt;")} shows a picture. ${C("src")} is the image file and ${C("alt")} describes it for people who can't see it. It doesn't need a closing tag.</p>`,
  demo:`<img src="monkey.png" alt="An orange monkey wearing glasses" width="120">\n<p>No image file here, so you see the alt text instead. That's exactly why alt matters!</p>`,
  say:"Always write alt text. It helps blind users and shows when an image fails."},
 {type:"quiz",q:"What does the alt attribute do?",opts:["Describes the image in words","Sets the image size","Links to another page"],a:0,why:"Screen readers read alt text aloud."},
 {type:"fill",title:"Make a link",body:`<p>Link to example.com.</p>`,code:`<a [0]="https://example.com">Visit</[1]>`,blanks:["href","a"],tokens:["href","a","src","link"],why:"href holds the address; close with </a>."},
 {type:"code",title:"Fan page",
  body:`<p>Add an image with ${C("alt")} text, and a link (an ${C("&lt;a&gt;")} with an ${C("href")}).</p>`,
  start:`<h1>Banana Fan Club</h1>\n`,
  checks:[{sel:"img[alt]",attr:["alt",/\S/],msg:"Add an <img> with alt text describing it."},{sel:"a[href]",attr:["href",/\S/],msg:"Add a link: <a href=\"...\">text</a>"}],
  hint:`<h1>Banana Fan Club</h1>\n<img src="banana.png" alt="A ripe yellow banana">\n<p><a href="https://example.com">Join the club</a></p>`},
 {type:"done"}]}
]};

const WEB_UNIT2={name:"CSS basics",lessons:[
{id:"web4",title:"Your first CSS",sub:"selectors, color, font-size",steps:[
 {type:"talk",title:"Making it pretty",mood:"cheer",
  body:`<p>HTML is what's on the page. <b>CSS</b> is how it looks. Put CSS inside a ${C("&lt;style&gt;")} tag. A rule is a <b>selector</b>, then properties in curly braces.</p>`,
  demo:`<style>\n  h1 {\n    color: darkorange;\n    font-size: 40px;\n  }\n  p {\n    color: gray;\n  }\n</style>\n\n<h1>TypeMonkey</h1>\n<p>Now with style.</p>`,
  say:"Try changing darkorange to purple, or 40px to 60px."},
 {type:"talk",title:"Colors and text",mood:"think",
  body:`<p>Colors can be names (${C("tomato")}), hex codes (${C("#FF7A1A")}) or ${C("rgb(255, 122, 26)")}. Text properties include ${C("font-family")}, ${C("font-weight")} and ${C("text-align")}.</p>`,
  demo:`<style>\n  h2 { color: #FF7A1A; text-align: center; }\n  p { font-family: Georgia, serif; font-weight: bold; }\n</style>\n<h2>Centered and orange</h2>\n<p>Bold and fancy.</p>`,
  say:"Every property ends with a semicolon."},
 {type:"quiz",q:"In h1 { color: red; }, which part is the selector?",opts:["h1","color","red"],a:0,mono:true,why:"The selector picks which elements the rule styles."},
 {type:"fill",title:"Blue paragraphs",body:`<p>Make every paragraph blue.</p>`,code:`<style>\n  [0] { [1]: blue; }\n</style>\n<p>Hi!</p>`,blanks:["p","color"],tokens:["p","color","text","paint"],why:"Select p, set color."},
 {type:"code",title:"Style a heading",
  body:`<p>Make the ${C("h1")} orange (use the color name ${C("orange")}) and give it a ${C("font-size")} of ${C("48px")}.</p>`,
  start:`<style>\n  /* your CSS here */\n</style>\n\n<h1>Bananas!</h1>\n`,
  checks:[{sel:"h1",style:{color:"orange"},msg:"Set the h1's color to orange."},{sel:"h1",style:{"font-size":"48px"},msg:"Set the h1's font-size to 48px."}],
  hint:`<style>\n  h1 {\n    color: orange;\n    font-size: 48px;\n  }\n</style>\n\n<h1>Bananas!</h1>`},
 {type:"done"}]},
{id:"web5",title:"Classes & IDs",sub:"style just the elements you pick",steps:[
 {type:"talk",title:"Classes",
  body:`<p>Give elements a ${C("class")}, then select it in CSS with a dot: ${C(".name")}. Many elements can share a class.</p>`,
  demo:`<style>\n  .tag {\n    background: gold;\n    padding: 4px 10px;\n    border-radius: 99px;\n  }\n</style>\n<p><span class="tag">new</span> Banana bread</p>\n<p><span class="tag">hot</span> Mango smoothie</p>`,
  say:"<span> is an inline box you can style without starting a new line."},
 {type:"talk",title:"IDs",mood:"think",
  body:`<p>An ${C("id")} is unique: only one element per page should have it. Select it with ${C("#")}. Use classes for styling most of the time.</p>`,
  demo:`<style>\n  #hero { color: white; background: darkgreen; padding: 16px; }\n</style>\n<div id="hero">Welcome to the jungle</div>`,
  say:"<div> is a general-purpose block box. You'll use it constantly."},
 {type:"quiz",q:"How do you select class=\"price\" in CSS?",opts:[".price","#price","price"],a:0,mono:true,why:"Dot for class, hash for id, plain name for a tag."},
 {type:"fill",title:"Style the warning",body:`<p>Make the warning class red.</p>`,code:`<style>\n  [0]warning { color: red; }\n</style>\n<p class="[1]">Don't feed the parrot!</p>`,blanks:[".","warning"],tokens:[".","warning","#","alert"],why:".warning matches class=\"warning\"."},
 {type:"code",title:"Highlight the deal",
  body:`<p>Give the second paragraph the class ${C("deal")}, then make ${C(".deal")} have a ${C("background")} of ${C("yellow")}.</p>`,
  start:`<style>\n</style>\n\n<p>Bananas $1</p>\n<p>Mangoes $2 (half price!)</p>\n<p>Kiwis $3</p>\n`,
  checks:[{sel:"p.deal",text:/Mango/,msg:"Add class=\"deal\" to the mango paragraph."},{sel:".deal",style:{"background-color":"yellow"},msg:"Give .deal a yellow background."},{sel:"p:not(.deal)",count:2,msg:"Only the mango paragraph should have the deal class."}],
  hint:`<style>\n  .deal { background: yellow; }\n</style>\n\n<p>Bananas $1</p>\n<p class="deal">Mangoes $2 (half price!)</p>\n<p>Kiwis $3</p>`},
 {type:"done"}]},
{id:"web6",title:"The box model",sub:"padding, border, margin",steps:[
 {type:"talk",title:"Everything is a box",
  body:`<p>Every element is a box with layers: <b>content</b>, then <b>padding</b> (space inside), <b>border</b>, and <b>margin</b> (space outside).</p>`,
  demo:`<style>\n  .box {\n    background: #FFE3C7;\n    padding: 20px;\n    border: 4px solid #FF7A1A;\n    margin: 16px;\n  }\n</style>\n<div class="box">I'm a box!</div>\n<div class="box">Me too!</div>`,
  say:"Padding is inside the border. Margin pushes other boxes away."},
 {type:"talk",title:"Rounded corners and sizes",mood:"think",
  body:`<p>${C("border-radius")} rounds the corners. ${C("width")} and ${C("max-width")} control size.</p>`,
  demo:`<style>\n  .pill { background: teal; color: white; padding: 10px 20px; border-radius: 999px; width: fit-content; }\n  .card { max-width: 220px; padding: 16px; border: 2px solid #ddd; border-radius: 16px; }\n</style>\n<div class="pill">Pill button</div>\n<br>\n<div class="card">A card that never gets wider than 220px.</div>`,
  say:"999px radius is a trick for perfectly round ends."},
 {type:"quiz",q:"Which adds space INSIDE the border?",opts:["padding","margin","gap"],a:0,mono:true,why:"Padding is inside. Margin is outside."},
 {type:"fill",title:"Round it",body:`<p>Round the corners by 12px.</p>`,code:`<style>\n  .card { [0]: 12px; }\n</style>`,blanks:["border-radius"],tokens:["border-radius","corner","round","radius"],why:"border-radius rounds the corners."},
 {type:"code",title:"Make a card",
  body:`<p>Style ${C(".card")} with ${C("padding: 16px")}, a ${C("border")} of ${C("2px solid orange")}, and ${C("border-radius: 12px")}.</p>`,
  start:`<style>\n  .card {\n  }\n</style>\n\n<div class="card">\n  <h3>Mo</h3>\n  <p>Age 4 · loves bananas</p>\n</div>\n`,
  checks:[{sel:".card",style:{"padding-top":"16px","padding-left":"16px"},msg:"Give the card padding: 16px."},{sel:".card",style:{"border-top-width":"2px","border-top-style":"solid","border-top-color":"orange"},msg:"Give the card border: 2px solid orange."},{sel:".card",style:{"border-top-left-radius":"12px"},msg:"Give the card border-radius: 12px."}],
  hint:`<style>\n  .card {\n    padding: 16px;\n    border: 2px solid orange;\n    border-radius: 12px;\n  }\n</style>\n\n<div class="card">\n  <h3>Mo</h3>\n  <p>Age 4 · loves bananas</p>\n</div>`},
 {type:"done"}]}
]};

const WEB_UNIT3={name:"Layout",lessons:[
{id:"web7",title:"Flexbox",sub:"lining things up in a row",steps:[
 {type:"talk",title:"display: flex",
  body:`<p>Add ${C("display: flex")} to a container and its children line up in a row. ${C("gap")} adds space between them.</p>`,
  demo:`<style>\n  .row { display: flex; gap: 10px; }\n  .row div { background: #FFD25C; padding: 12px; border-radius: 8px; }\n</style>\n<div class="row">\n  <div>One</div>\n  <div>Two</div>\n  <div>Three</div>\n</div>`,
  say:"Flexbox is how most website navigation bars are built."},
 {type:"talk",title:"Aligning",mood:"think",
  body:`<p>${C("justify-content")} spreads items along the row (${C("center")}, ${C("space-between")}). ${C("align-items")} lines them up across it. ${C("flex-wrap: wrap")} lets them drop to a new line.</p>`,
  demo:`<style>\n  .nav { display: flex; justify-content: space-between; align-items: center; background: #14201B; color: white; padding: 10px 14px; border-radius: 10px; }\n  .links { display: flex; gap: 12px; }\n</style>\n<div class="nav">\n  <b>🐒 TypeMonkey</b>\n  <div class="links"><span>Learn</span><span>Play</span></div>\n</div>`,
  say:"A real nav bar in a few lines!"},
 {type:"quiz",q:"Which property turns on flexbox?",opts:["display: flex","flex: on","position: flex"],a:0,mono:true,why:"It goes on the parent container."},
 {type:"fill",title:"Center everything",body:`<p>Center the items in the row.</p>`,code:`<style>\n  .row { display: [0]; justify-content: [1]; }\n</style>`,blanks:["flex","center"],tokens:["flex","center","middle","block"],why:"display: flex, then justify-content: center."},
 {type:"code",title:"Button row",
  body:`<p>Make ${C(".buttons")} a flex row with a ${C("gap")} of ${C("8px")}.</p>`,
  start:`<style>\n  .buttons {\n  }\n  button { padding: 8px 14px; }\n</style>\n\n<div class="buttons">\n  <button>Play</button>\n  <button>Learn</button>\n  <button>Shop</button>\n</div>\n`,
  checks:[{sel:".buttons",style:{display:"flex"},msg:"Set display: flex on .buttons."},{sel:".buttons",style:{"column-gap":"8px"},msg:"Set gap: 8px on .buttons."}],
  hint:`<style>\n  .buttons {\n    display: flex;\n    gap: 8px;\n  }\n  button { padding: 8px 14px; }\n</style>\n\n<div class="buttons">\n  <button>Play</button>\n  <button>Learn</button>\n  <button>Shop</button>\n</div>`},
 {type:"done"}]},
{id:"web8",title:"CSS Grid",sub:"rows and columns",steps:[
 {type:"talk",title:"display: grid",
  body:`<p>Grid lays things out in columns <b>and</b> rows. ${C("grid-template-columns: 1fr 1fr 1fr")} makes three equal columns. ${C("fr")} means "a fraction of the space".</p>`,
  demo:`<style>\n  .grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 8px; }\n  .grid div { background: #CDEFD9; padding: 14px; text-align: center; border-radius: 8px; }\n</style>\n<div class="grid">\n  <div>🐒</div><div>🦜</div><div>🐼</div>\n  <div>🦒</div><div>🦉</div><div>🍌</div>\n</div>`,
  say:"Six items, three columns, so two rows appear automatically."},
 {type:"talk",title:"repeat()",mood:"think",
  body:`<p>${C("repeat(4, 1fr)")} is short for four equal columns. Columns can be different sizes too: ${C("2fr 1fr")}.</p>`,
  demo:`<style>\n  .layout { display: grid; grid-template-columns: 2fr 1fr; gap: 8px; }\n  .layout div { background: #E6E1FF; padding: 14px; border-radius: 8px; }\n</style>\n<div class="layout">\n  <div>Main content (2 parts)</div>\n  <div>Sidebar (1 part)</div>\n</div>`,
  say:"Flexbox for one row, grid for two dimensions. That's the rule of thumb."},
 {type:"quiz",q:"What does grid-template-columns: repeat(3, 1fr) make?",opts:["Three equal columns","Three rows","One column 3 times wider"],a:0,mono:true,why:"repeat(3, 1fr) = 1fr 1fr 1fr."},
 {type:"fill",title:"Two columns",body:`<p>Make a two-column grid.</p>`,code:`<style>\n  .g { display: [0]; grid-template-columns: [1]; }\n</style>`,blanks:["grid","1fr 1fr"],tokens:["grid","1fr 1fr","flex","2fr"],why:"display: grid with two 1fr columns."},
 {type:"code",title:"Photo wall",
  body:`<p>Make ${C(".wall")} a grid with ${C("grid-template-columns: repeat(3, 1fr)")}.</p>`,
  start:`<style>\n  .wall {\n  }\n  .wall div { background: #FFD25C; height: 60px; border-radius: 8px; }\n</style>\n\n<div class="wall">\n  <div></div><div></div><div></div>\n  <div></div><div></div><div></div>\n</div>\n`,
  checks:[{sel:".wall",style:{display:"grid"},msg:"Set display: grid on .wall."},{sel:".wall",style:{"grid-template-columns":/^(\S+\s+){2}\S+$/},msg:"Give .wall three columns with repeat(3, 1fr)."}],
  hint:`<style>\n  .wall {\n    display: grid;\n    grid-template-columns: repeat(3, 1fr);\n    gap: 8px;\n  }\n  .wall div { background: #FFD25C; height: 60px; border-radius: 8px; }\n</style>\n\n<div class="wall">\n  <div></div><div></div><div></div>\n  <div></div><div></div><div></div>\n</div>`},
 {type:"done"}]},
{id:"web9",title:"Project: Profile Card",sub:"HTML + CSS + flexbox",project:true,steps:[
 {type:"talk",title:"Design a profile card",mood:"cheer",
  body:`<p>Profile cards are everywhere: social apps, games, team pages. You'll build one with an avatar, a name, a bio and stats in a row.</p>`,
  demo:`<style>\n  .profile { max-width: 260px; padding: 18px; border-radius: 18px; background: #FFF4E5; border: 2px solid #FFB36B; text-align: center; }\n  .avatar { font-size: 48px; }\n  .stats { display: flex; justify-content: space-around; margin-top: 10px; }\n</style>\n<div class="profile">\n  <div class="avatar">🐒</div>\n  <h2>TypeMonkey</h2>\n  <p>Coding buddy. Banana enthusiast.</p>\n  <div class="stats"><span>🔥 12</span><span>🍌 340</span><span>⭐ 9</span></div>\n</div>`,
  say:"Here's the goal. Now you'll build your own."},
 {type:"code",title:"Step 1: the HTML",
  body:`<p>Inside the ${C(".profile")} div, add an ${C("&lt;h2&gt;")} with a name and a ${C("&lt;p&gt;")} bio.</p>`,
  start:`<div class="profile">\n  <div class="avatar">🦊</div>\n  <!-- add an h2 and a p -->\n</div>\n`,
  checks:[{sel:".profile h2",text:/\S/,msg:"Add an <h2> with a name inside .profile."},{sel:".profile p",text:/\S/,msg:"Add a <p> bio inside .profile."}],
  hint:`<div class="profile">\n  <div class="avatar">🦊</div>\n  <h2>Fox</h2>\n  <p>Quick and clever.</p>\n</div>`},
 {type:"code",title:"Step 2: card styles",
  body:`<p>Give ${C(".profile")} ${C("padding: 18px")}, ${C("border-radius: 18px")} and ${C("text-align: center")}.</p>`,
  start:`<style>\n  .profile {\n  }\n</style>\n\n<div class="profile">\n  <div class="avatar">🦊</div>\n  <h2>Fox</h2>\n  <p>Quick and clever.</p>\n</div>\n`,
  checks:[{sel:".profile",style:{"padding-top":"18px"},msg:"Add padding: 18px."},{sel:".profile",style:{"border-top-left-radius":"18px"},msg:"Add border-radius: 18px."},{sel:".profile",style:{"text-align":"center"},msg:"Add text-align: center."}],
  hint:`<style>\n  .profile {\n    padding: 18px;\n    border-radius: 18px;\n    text-align: center;\n    background: #FFF4E5;\n  }\n</style>\n\n<div class="profile">\n  <div class="avatar">🦊</div>\n  <h2>Fox</h2>\n  <p>Quick and clever.</p>\n</div>`},
 {type:"code",title:"Step 3: the stats row",
  body:`<p>Add a ${C(".stats")} div with at least 3 ${C("&lt;span&gt;")}s, and make it a flex row with ${C("justify-content: space-around")}.</p>`,
  start:`<style>\n  .profile { padding: 18px; border-radius: 18px; text-align: center; background: #FFF4E5; }\n</style>\n\n<div class="profile">\n  <div class="avatar">🦊</div>\n  <h2>Fox</h2>\n  <p>Quick and clever.</p>\n  <!-- stats row here -->\n</div>\n`,
  checks:[{sel:".stats span",count:3,msg:"Add a .stats div with 3 <span> items."},{sel:".stats",style:{display:"flex"},msg:"Make .stats display: flex."},{sel:".stats",style:{"justify-content":"space-around"},msg:"Add justify-content: space-around to .stats."}],
  hint:`<style>\n  .profile { padding: 18px; border-radius: 18px; text-align: center; background: #FFF4E5; }\n  .stats { display: flex; justify-content: space-around; }\n</style>\n\n<div class="profile">\n  <div class="avatar">🦊</div>\n  <h2>Fox</h2>\n  <p>Quick and clever.</p>\n  <div class="stats"><span>🔥 5</span><span>⭐ 3</span><span>🏆 1</span></div>\n</div>`},
 {type:"done"}]}
]};

const WEB_UNIT4={name:"Real web pages",lessons:[
{id:"web10",title:"Forms & buttons",sub:"input, label, button, select",steps:[
 {type:"talk",title:"Collecting input",
  body:`<p>Forms collect information. ${C("&lt;label&gt;")} names a field, and ${C("&lt;input&gt;")} is the field. Connect them with ${C("for")} and ${C("id")}.</p>`,
  demo:`<form>\n  <label for="name">Your name</label><br>\n  <input id="name" type="text" placeholder="Mo">\n  <br><br>\n  <label for="age">Age</label><br>\n  <input id="age" type="number" min="1">\n  <br><br>\n  <button type="button">Sign up</button>\n</form>`,
  say:"Tap a label and the cursor jumps into its input. That's the for/id connection."},
 {type:"talk",title:"More input types",mood:"think",
  body:`<p>${C("type")} changes the input: ${C("email")}, ${C("password")}, ${C("checkbox")}, ${C("date")}. ${C("&lt;select&gt;")} makes a dropdown.</p>`,
  demo:`<label><input type="checkbox"> I love bananas</label><br><br>\n<label for="fav">Favorite fruit</label>\n<select id="fav">\n  <option>Banana</option>\n  <option>Mango</option>\n</select><br><br>\n<input type="password" placeholder="Secret">`,
  say:"Phones even show a different keyboard for email and number inputs."},
 {type:"quiz",q:"How does a label connect to its input?",opts:["The label's for matches the input's id","They must be next to each other","The label goes after the input"],a:0,why:"for=\"name\" points at id=\"name\"."},
 {type:"fill",title:"An email field",body:`<p>Make an email input.</p>`,code:`<input [0]="email" placeholder="you@example.com">`,blanks:["type"],tokens:["type","kind","format","id"],why:"type=\"email\" makes an email field."},
 {type:"code",title:"Join the club form",
  body:`<p>Build a form with a ${C("&lt;label&gt;")}, an ${C("&lt;input type=\"email\"&gt;")} and a ${C("&lt;button&gt;")}.</p>`,
  start:`<h2>Join the Banana Club</h2>\n<form>\n</form>\n`,
  checks:[{sel:"form label",msg:"Add a <label> inside the form."},{sel:"form input[type=email]",msg:"Add <input type=\"email\"> inside the form."},{sel:"form button",msg:"Add a <button> inside the form."}],
  hint:`<h2>Join the Banana Club</h2>\n<form>\n  <label for="email">Email</label><br>\n  <input id="email" type="email"><br><br>\n  <button type="button">Join</button>\n</form>`},
 {type:"done"}]},
{id:"web11",title:"Semantic HTML",sub:"header, nav, main, footer, accessibility",steps:[
 {type:"talk",title:"Tags with meaning",
  body:`<p>Instead of ${C("&lt;div&gt;")} everywhere, <b>semantic</b> tags describe what a section is: ${C("&lt;header&gt;")}, ${C("&lt;nav&gt;")}, ${C("&lt;main&gt;")}, ${C("&lt;section&gt;")} and ${C("&lt;footer&gt;")}.</p>`,
  demo:`<header>\n  <h1>TypeMonkey News</h1>\n  <nav><a href="#">Home</a> · <a href="#">Games</a></nav>\n</header>\n<main>\n  <section>\n    <h2>Monkey learns CSS</h2>\n    <p>Experts are amazed.</p>\n  </section>\n</main>\n<footer>© 2026 TypeMonkey</footer>`,
  say:"It looks the same, but screen readers and search engines understand it much better."},
 {type:"talk",title:"Accessibility",mood:"think",
  body:`<p>Accessible pages work for everyone: alt text on images, labels on inputs, real ${C("&lt;button&gt;")}s for actions, and enough color contrast to read easily.</p>`,
  demo:`<button type="button">✅ Good: a real button</button>\n<p style="color:#ccc">❌ Hard to read: light gray on white</p>\n<p style="color:#333">✅ Easy to read: dark text</p>`,
  say:"About 1 in 4 adults has some kind of disability. Accessible design matters."},
 {type:"quiz",q:"Which tag is for the main navigation links?",opts:["<nav>","<links>","<menu-bar>"],a:0,mono:true,why:"nav marks a group of navigation links."},
 {type:"order",title:"Page outline",body:`<p>Put the page sections in order, top to bottom.</p>`,lines:["<header>…</header>","<main>…</main>","<footer>…</footer>"],why:"Header at the top, main content, footer at the bottom.",noRun:true},
 {type:"code",title:"Make it semantic",
  body:`<p>Build a page with a ${C("&lt;header&gt;")} containing an ${C("&lt;h1&gt;")}, a ${C("&lt;main&gt;")} with a paragraph, and a ${C("&lt;footer&gt;")}.</p>`,
  start:`<!-- header, main, footer -->\n`,
  checks:[{sel:"header h1",msg:"Put an <h1> inside a <header>."},{sel:"main p",msg:"Put a <p> inside <main>."},{sel:"footer",msg:"Add a <footer>."}],
  hint:`<header>\n  <h1>My Site</h1>\n</header>\n<main>\n  <p>Welcome to my page.</p>\n</main>\n<footer>Made with 🍌</footer>`},
 {type:"done"}]},
{id:"web12",title:"Final Project: Landing Page",sub:"everything you've learned, in one page",project:true,steps:[
 {type:"talk",title:"Build a real landing page",mood:"cheer",
  body:`<p>Final project: a landing page for the TypeMonkey Fan Club. A header, a big hero message, a grid of features and a sign-up form. This is what real web developers build every day.</p>`,
  say:"Let's make something you'd actually show your friends."},
 {type:"code",title:"Step 1: header and hero",
  body:`<p>Add a ${C("&lt;header&gt;")} with a ${C("&lt;nav&gt;")}, and a ${C("&lt;section class=\"hero\"&gt;")} with an ${C("&lt;h1&gt;")} and a ${C("&lt;p&gt;")}.</p>`,
  start:`<!-- header with nav, then a hero section -->\n`,
  checks:[{sel:"header nav",msg:"Put a <nav> inside a <header>."},{sel:"section.hero h1",msg:"Add <section class=\"hero\"> with an <h1>."},{sel:"section.hero p",msg:"Add a <p> to the hero section."}],
  hint:`<header>\n  <nav><b>🐒 Fan Club</b> · <a href="#join">Join</a></nav>\n</header>\n<section class="hero">\n  <h1>Code with TypeMonkey</h1>\n  <p>Learn, play and earn bananas.</p>\n</section>`},
 {type:"code",title:"Step 2: features grid",
  body:`<p>Add a ${C(".features")} div with at least 3 child divs, and make it a ${C("grid")} with 3 columns.</p>`,
  start:`<style>\n</style>\n\n<div class="features">\n</div>\n`,
  checks:[{sel:".features > div",count:3,msg:"Put at least 3 divs inside .features."},{sel:".features",style:{display:"grid"},msg:"Make .features display: grid."},{sel:".features",style:{"grid-template-columns":/^(\S+\s+){2}\S+$/},msg:"Give .features 3 columns: repeat(3, 1fr)."}],
  hint:`<style>\n  .features { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; }\n  .features div { background: #FFF4E5; padding: 12px; border-radius: 12px; }\n</style>\n\n<div class="features">\n  <div>📚 Lessons</div>\n  <div>🎮 Games</div>\n  <div>🍌 Rewards</div>\n</div>`},
 {type:"code",title:"Step 3: the sign-up form",
  body:`<p>Add a ${C("&lt;form id=\"join\"&gt;")} with a labeled email input and a button. Style the button with an orange ${C("background")}.</p>`,
  start:`<style>\n</style>\n\n`,
  checks:[{sel:"form#join input[type=email]",msg:"Add <form id=\"join\"> with an email input."},{sel:"form#join label",msg:"Give the input a <label>."},{sel:"form#join button",style:{"background-color":"orange"},msg:"Style the form's button with background: orange."}],
  hint:`<style>\n  button { background: orange; border: 0; padding: 10px 16px; border-radius: 8px; font-weight: bold; }\n</style>\n\n<form id="join">\n  <label for="email">Email</label>\n  <input id="email" type="email">\n  <button type="button">Join the club</button>\n</form>`},
 {type:"talk",title:"The finished page",mood:"cheer",
  body:`<p>Here's everything together. Tap ▶ Show page, then try making it yours: change colors, add sections, swap the emoji.</p>`,
  demo:`<style>\n  header nav { display: flex; justify-content: space-between; padding: 10px; background: #14201B; color: white; border-radius: 10px; }\n  header a { color: #FFD25C; }\n  .hero { text-align: center; padding: 26px 10px; }\n  .hero h1 { color: #FF7A1A; font-size: 34px; margin: 0; }\n  .features { display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; }\n  .features div { background: #FFF4E5; padding: 12px; border-radius: 12px; text-align: center; }\n  form { margin-top: 16px; display: flex; flex-wrap: wrap; gap: 8px; align-items: center; justify-content: center; }\n  button { background: orange; border: 0; padding: 10px 16px; border-radius: 8px; font-weight: bold; }\n  footer { text-align: center; color: gray; margin-top: 16px; }\n</style>\n<header><nav><b>🐒 Fan Club</b><a href="#join">Join</a></nav></header>\n<main>\n  <section class="hero">\n    <h1>Code with TypeMonkey</h1>\n    <p>Learn, play and earn bananas.</p>\n  </section>\n  <div class="features">\n    <div>📚<br>Lessons</div><div>🎮<br>Games</div><div>🍌<br>Rewards</div>\n  </div>\n  <form id="join">\n    <label for="email">Email</label>\n    <input id="email" type="email">\n    <button type="button">Join the club</button>\n  </form>\n</main>\n<footer>Made with HTML &amp; CSS · You finished the course! 🎉</footer>`,
  say:"You built a real landing page. You finished HTML & CSS!"},
 {type:"done"}]}
]};

const COURSE_WEB={id:"web",name:"HTML & CSS",blurb:"Build real web pages and watch them appear as you type. Unit 1 is free.",units:[WEB_UNIT1,WEB_UNIT2,WEB_UNIT3,WEB_UNIT4]};
