#!/usr/bin/env python3
"""Checks the Swift course against TypeMonkey's in-house Swift runner (src/engines/swift.js).

This needs no Swift compiler (verify_swift_real.py is the one that compares with real Swift). It checks that:
  - every Output Rush round and "What does this print?" quiz must print the answer marked correct
  - every code challenge's answer must print exactly its expected lines (and each variant too),
    and its starter code must NOT already pass
  - fill-ins and order puzzles must run (and match their expected output when they have one)
  - demos must run without errors, except the ones that show a crash on purpose
  - the EXTRA programs below, whose output was written from the Swift language reference,
    must print exactly that
  - the REAL programs below must print exactly what real Swift printed for them (see verify_swift_real.py,
    which also compares everything here with a real Swift compiler when one is installed)
Usage: python3 tests/verify_swift.py [-v]
"""
import json, pathlib, re, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
VERBOSE = "-v" in sys.argv
INTENTIONAL_CRASH = {"sw9", "sw13"}  # demos that show "Index out of range" / a nil unwrap on purpose

EXTRA = [
    ('var d: [String: [Int]] = [:]\nd["a", default: []].append(1)\nd["a", default: []].append(2)\nprint(d)\nprint(type(of: 5), type(of: "x"))\nvar c: [String: Int] = [:]\nprint(c["z", default: 0], c.count)', '["a": [1, 2]]\nInt String\n0 0'),
    ('print("Hello, world!")\nlet name = "Mo"\nvar age = 4\nage += 1\nprint("\\(name) is \\(age)")\nprint(7 / 2, 7 % 2, 7.0 / 2)\nprint(3.14159)\nprint(10.0 / 4)', "Hello, world!\nMo is 5\n3 1 3.5\n3.14159\n2.5"),
    ('print(0.1 + 0.2)\nprint(10.0 / 3)\nprint(1.0)\nprint(100.0 * 3)\nprint(-7 / 2, -7 % 2)\nprint(Double(7) / 2)', "0.30000000000000004\n3.3333333333333335\n1.0\n300.0\n-3 -1\n3.5"),
    ('var nums = [3, 1, 2]\nnums.append(5)\nprint(nums)\nprint(nums.count, nums.sorted(), nums.first!)\nprint(nums.map { $0 * 2 })\nprint(nums.filter { $0 > 2 }.reduce(0, +))', "[3, 1, 2, 5]\n4 [1, 2, 3, 5] 3\n[6, 2, 4, 10]\n8"),
    ('let n: Int? = Int("42")\nprint(n)\nif let x = n { print(x + 1) }\nprint(Int("x") ?? 0)\nvar d = ["a": 1]\nd["b"] = 2\nprint(d["a"], d["z"])\nprint(d["b"] ?? 0)', "Optional(42)\n43\n0\nOptional(1) nil\n2"),
    ('func greet(_ name: String, times: Int = 1) -> String {\n    return String(repeating: "Hi \\(name)! ", count: times)\n}\nprint(greet("Mo", times: 2))\nfunc add(a: Int, b: Int) -> Int { a + b }\nprint(add(a: 2, b: 3))', "Hi Mo! Hi Mo! \n5"),
    ('struct Point {\n    var x: Int\n    var y: Int\n    mutating func move(by d: Int) { x += d; y += d }\n}\nvar p = Point(x: 1, y: 2)\nvar q = p\nq.move(by: 5)\nprint(p, q)', "Point(x: 1, y: 2) Point(x: 6, y: 7)"),
    ('class Animal {\n    var name: String\n    init(name: String) { self.name = name }\n    func speak() -> String { "..." }\n}\nclass Dog: Animal {\n    override func speak() -> String { "Woof" }\n}\nlet a: [Animal] = [Animal(name: "x"), Dog(name: "Rex")]\nfor an in a { print(an.name, an.speak()) }\nlet d1 = Dog(name: "A")\nlet d2 = d1\nd2.name = "B"\nprint(d1.name)', "x ...\nRex Woof\nB"),
    ('enum Dir: CaseIterable { case north, south, east, west }\nlet d = Dir.east\nswitch d {\ncase .north, .south: print("vertical")\ncase .east, .west: print("horizontal")\n}\nprint(Dir.allCases.count, d)\nlet score = 85\nswitch score {\ncase 90...100: print("A")\ncase 80..<90: print("B")\ndefault: print("C")\n}', "horizontal\n4 east\nB"),
    ('for i in 1...3 { print(i, terminator: " ") }\nprint()\nfor i in stride(from: 10, to: 0, by: -3) { print(i) }\nvar k = 0\nwhile k < 3 { k += 1 }\nrepeat { k -= 1 } while k > 0\nprint(k)', "1 2 3 \n10\n7\n4\n1\n0"),
    ('enum BankError: Error { case insufficient }\nfunc withdraw(_ amt: Int, from bal: Int) throws -> Int {\n    guard amt <= bal else { throw BankError.insufficient }\n    return bal - amt\n}\ndo {\n    print(try withdraw(5, from: 10))\n    print(try withdraw(50, from: 10))\n} catch BankError.insufficient {\n    print("Not enough")\n}\nlet r = try? withdraw(1, from: 0)\nprint(r)', "5\nNot enough\nnil"),
    ('let s = "Hello"\nprint(s.count, s.uppercased(), s.hasPrefix("He"))\nprint(String(s.reversed()))\nfor c in "ab" { print(c) }\nlet words = "a b c".split(separator: " ")\nprint(words)\nprint(words.joined(separator: "-"))', '5 HELLO true\nolleH\na\nb\n["a", "b", "c"]\na-b-c'),
    ('protocol Shape { var area: Double { get } }\nstruct Sq: Shape {\n    var side: Double\n    var area: Double { side * side }\n}\nlet shapes: [Shape] = [Sq(side: 2), Sq(side: 3)]\nfor s in shapes { print(s.area) }\nlet t = (1, "a")\nprint(t, t.0)\nlet (aa, bb) = t\nprint(aa, bb)', '4.0\n9.0\n(1, "a") 1\n1 a'),
    ('let words = ["apple", "fig", "banana"]\nprint(words.sorted { $0.count < $1.count })\nprint(words.map { $0.count })\nprint(words.contains("fig"), words.firstIndex(of: "banana") ?? -1)\nprint(words.joined(separator: ", "))', '["fig", "apple", "banana"]\n[5, 3, 6]\ntrue 2\napple, fig, banana'),
    ('var scores = ["Mo": 3]\nscores["Mo", default: 0] += 2\nscores["Kiki", default: 0] += 1\nfor k in scores.keys.sorted() { print(k, scores[k]!) }', "Kiki 1\nMo 5"),
    ('let x: Int? = nil\nprint(x ?? 5)\nlet names: [String] = []\nprint(names.first ?? "none")\nprint(names.first?.count)\nlet s: String? = "hey"\nprint(s?.uppercased() ?? "")', "5\nnone\nnil\nHEY"),
    ('func describe(_ v: Int) -> String {\n    switch v {\n    case ..<0: return "negative"\n    case 0: return "zero"\n    case 1...9: return "small"\n    default: return "big"\n    }\n}\nprint(describe(-4), describe(0), describe(5), describe(50))', "negative zero small big"),
    ('struct Temp {\n    var celsius: Double\n    var fahrenheit: Double { celsius * 9 / 5 + 32 }\n}\nvar t = Temp(celsius: 100)\nprint(t.fahrenheit)\nt.celsius = 0\nprint(t.fahrenheit)', "212.0\n32.0"),
    ('enum Planet: Int { case mercury = 1, venus, earth }\nprint(Planet.earth.rawValue)\nprint(Planet(rawValue: 2) ?? .mercury)\nprint(Planet(rawValue: 9))', "3\nvenus\nnil"),
    ('var total = 0\nfor (i, v) in [10, 20, 30].enumerated() { total += i * v }\nprint(total)\nlet pairs = zip([1, 2, 3], ["a", "b", "c"])\nfor (n, l) in pairs { print(n, l, terminator: "; ") }\nprint()', "80\n1 a; 2 b; 3 c; "),
    ('let x = 5\nx = 6', "ERROR"),
    ('let a = 3\nlet b = 0.5\nprint(a + b)', "ERROR"),
    ('print("Total: " + 5)', "ERROR"),
    ('let n = 3\nswitch n {\ncase 1: print("one")\n}', "ERROR"),
    ('let arr = [1, 2]\nprint(arr[5])', "CRASH"),
    ('let v: Int? = nil\nprint(v!)', "CRASH"),
    ('let nums = [1, 2]\nnums.append(3)', "ERROR"),
    ('struct P { var x = 0 }\nlet p = P()\np.x = 3', "ERROR"),
    ('print(1 + 0.5, 2 * 1.5)\nlet d: Double = 3\nprint(d)\nvar e = 2.0\ne += 1\nprint(e)', "1.5 3.0\n3.0\n3.0"),
    ('print((2.5).rounded(), (-2.5).rounded(), (2.4).rounded())\nprint(Int(-3.9))\nprint(abs(-3), max(1, 9, 4))', "3.0 -3.0 2.0\n-3\n3 9"),
    ('class Counter {\n    static var made = 0\n    var n = 0\n    init() { Counter.made += 1 }\n    func up() { n += 1 }\n}\nlet c = Counter()\nc.up()\nc.up()\n_ = Counter()\nprint(c.n, Counter.made)', "2 2"),
    ('var stack: [String] = []\nstack.append("a")\nstack.append("b")\nlet top = stack.removeLast()\nprint(top, stack, stack.isEmpty)', 'b ["a"] false'),
    ('let grid = [[1, 2], [3, 4]]\nprint(grid[1][0])\nvar g = grid\ng[0][0] = 9\nprint(grid[0][0], g[0][0])', "3\n1 9"),
    ('func swapped(_ t: (Int, Int)) -> (Int, Int) { (t.1, t.0) }\nprint(swapped((1, 2)))\nvar a = 1, b = 2\n(a, b) = (b, a)\nprint(a, b)', "(2, 1)\n2 1"),
    ('let s = "a,b,,c"\nprint(s.split(separator: ",").count)\nprint("hello".contains("ell"), "Hello".lowercased().hasSuffix("lo"))', "3\ntrue true"),
]


# Programs a learner might write, with the output real Swift printed for them (Swift 6.0.2, swiftc on Linux, captured by
# tests/verify_swift_real.py). ERROR = compile error, CRASH = runtime crash. Dictionaries with 2+ entries and random
# values are left out because real Swift prints those in a different order each run.
REAL = [
    ('print([(1, "a"), (2, "b")])\nprint([[1, 2], [3]])\nlet mixed: [Any] = [1, "two", 3.0]\nprint(mixed)\nprint([Optional(1), nil])',
     '[(1, "a"), (2, "b")]\n[[1, 2], [3]]\n[1, "two", 3.0]\n[Optional(1), nil]'),
    ('print(Double.nan, Double.infinity, -Double.infinity)\nprint(1.0 / 0.0)\nprint(0.0 / 0.0 == 0.0 / 0.0)',
     'nan inf -inf\ninf\nfalse'),
    ('debugPrint("hi")\ndebugPrint(5, "a", [1, 2])\ndebugPrint(Character("x"))',
     '"hi"\n5 "a" [1, 2]\n"x"'),
    ('var n: Int? = 5\nn? += 1\nprint(n)\nvar m: Int? = nil\nm? += 1\nprint(m)',
     'Optional(6)\nnil'),
    ('func kind(_ c: Character) -> String {\n    switch c {\n    case "0"..."9": return "digit"\n    case "a"..."z": return "lower"\n    case "A"..."Z": return "upper"\n    default: return "other"\n    }\n}\nprint(kind("5"), kind("q"), kind("Q"), kind("!"))',
     'digit lower upper other'),
    ('func apply(_ a: Int, _ b: Int, op: (Int, Int) -> Int = (+)) -> Int { op(a, b) }\nprint(apply(3, 4))\nprint(apply(3, 4, op: *))\nprint(apply(3, 4, op: max))\nprint([3, 1, 2].reduce(0, max))',
     '7\n12\n4\n3'),
    ('enum Status: String { case on, off }\nlet raw = ["on", "x", "off"]\nprint(raw.compactMap(Status.init))\nprint(raw.compactMap { Status(rawValue: $0) })',
     '[main.Status.on, main.Status.off]\n[main.Status.on, main.Status.off]'),
    ('struct P { var x: Int; var y: Int }\nextension P { init(both: Int) { self.init(x: both, y: both) } }\nprint(P(x: 1, y: 2), P(both: 3))',
     'P(x: 1, y: 2) P(x: 3, y: 3)'),
    ('import Foundation\nprint(String(format: "%e", 12345.678))\nprint(String(format: "%.2f", 3.14159))\nprint(String(format: "%5d|%-5d|%05d", 42, 42, 42))\nprint(String(format: "%@ has %d", "Mo", 3))',
     '1.234568e+04\n3.14\n   42|42   |00042\nMo has 3'),
    ('let a = [10, 20, 30, 40, 50]\nlet s = a[2...]\nprint(s, s.startIndex, s[2], s.count)\nprint(Array(a[1..<3]))\nprint(a[..<2], a[...1])',
     '[30, 40, 50] 2 30 3\n[20, 30]\n[10, 20] [10, 20]'),
    ('let text = "a1b22c"\nprint(text.split(whereSeparator: { $0.isNumber }))\nprint("one  two".split(separator: " "))\nprint("a,b,,c".split(separator: ",", omittingEmptySubsequences: false))',
     '["a", "b", "c"]\n["one", "two"]\n["a", "b", "", "c"]'),
    ('let x = 5\nprint(~x, x & 3, x | 2, x ^ 1, x << 2, x >> 1)',
     '-6 1 7 4 20 2'),
    ('var i8: Int8 = 127\ni8 += 1\nprint(i8)',
     'CRASH'),
    ('let words = ["apple", "avocado", "banana", "blueberry", "cherry"]\nlet g = Dictionary(grouping: words, by: { $0.first! })\nfor k in g.keys.sorted() { print(k, g[k]!) }',
     'a ["apple", "avocado"]\nb ["banana", "blueberry"]\nc ["cherry"]'),
    ('let f: (Int) -> String = { n in\n    switch n {\n    case 0: return "zero"\n    default: return "many"\n    }\n}\nprint(f(0), f(3))\nlet h = { (n: Int) -> String in\n    switch n {\n    case 0: return "zero"\n    default: return "lots"\n    }\n}\nprint(h(1))',
     'zero many\nlots'),
    ('let u = UnicodeScalar("A")\nprint(u, u.value)\nlet c: Character = "B"\nprint(c.asciiValue!, Character(UnicodeScalar(67)))',
     'A 65\n66 C'),
    ('let o: Int? = 4\nprint(o.map { $0 * 2 }, o.flatMap { $0 > 3 ? $0 : nil })\nlet none: Int? = nil\nprint(none.map { $0 * 2 })',
     'Optional(8) Optional(4)\nnil'),
    ('class Base { var v: Int; init(v: Int) { self.v = v } }\nfinal class Sub: Base { func show() { print(v) } }\nSub(v: 7).show()',
     '7'),
    ('var cb: ((Int, Int) -> Int)? = { $0 + $1 }\nprint(cb?(1, 2))\ncb = nil\nprint(cb?(1, 2))',
     'Optional(3)\nnil'),
    ('func minMax(_ a: [Int]) -> (min: Int, max: Int) { (a.min()!, a.max()!) }\nlet r = minMax([3, 9, 1])\nprint(r.min, r.max, r)',
     '1 9 (min: 1, max: 9)'),
    ('print("héllo".utf8.count, "héllo".count)',
     '6 5'),
    ('print(["x", "y"].enumerated().map { "\\($0):\\($1)" })\nprint([[1], [2, 3]].joined().map { $0 })\nprint(Array([[1], [2]].joined()))\nprint([["a", "b"], ["c"]].joined().count)',
     '["0:x", "1:y"]\n[1, 2, 3]\n[1, 2]\n3'),
    ('enum Dir { case north, south }\nstruct P { var x: Int; var d: Dir }\nclass C { var v = 1 }\nprint([Dir.north], Optional(Dir.south), P(x: 1, d: .north))\nprint([P(x: 2, d: .south)])\nprint(Optional(P(x: 3, d: .north)))\nprint(C(), [C()])\nprint(Dir.north)\nlet t = (Dir.north, "s")\nprint(t)',
     '[main.Dir.north] Optional(main.Dir.south) P(x: 1, d: main.Dir.north)\n[main.P(x: 2, d: main.Dir.south)]\nOptional(main.P(x: 3, d: main.Dir.north))\nmain.C [main.C]\nnorth\n(main.Dir.north, "s")'),
    ('enum Shape { case circle(radius: Double), rect(Double, Double), dot }\nlet s: [Shape] = [.circle(radius: 1), .rect(2, 3), .dot]\nprint(s)\nfor x in s { print(x) }\nprint(Optional(Shape.dot))',
     '[main.Shape.circle(radius: 1.0), main.Shape.rect(2.0, 3.0), main.Shape.dot]\ncircle(radius: 1.0)\nrect(2.0, 3.0)\ndot\nOptional(main.Shape.dot)'),
    ('print(1/3.0, 2.0/3.0, 100.0, 1e20, 1.5e-5, 0.0001, 12345678.9, 1e16, 1e15, 123456789012345678.0)\nprint(Double(Int.max), Float(1) / 3)\nprint(-0.0, 5e-324, 2.5e-4)',
     '0.3333333333333333 0.6666666666666666 100.0 1e+20 1.5e-05 0.0001 12345678.9 1e+16 1000000000000000.0 1.2345678901234568e+17\n9.223372036854776e+18 0.33333334\n-0.0 5e-324 0.00025'),
    ('print(Int.max, Int.min)\nprint(7 / -2, -7 % 3, 7 % -3)\nprint(Int(7.9), Int(-7.9), Int("12"), Int("1.5"), Int(" 3"))\nprint(Double("3.5"), Double("abc"), Double("1e3"))',
     '9223372036854775807 -9223372036854775808\n-3 -1 1\n7 -7 Optional(12) nil nil\nOptional(3.5) nil Optional(1000.0)'),
    ('let x: Int? = 5\nlet y: Int? = nil\nprint(x, y, x ?? 0, y ?? 0)\nprint(x == 5, y == nil, x != nil)\nlet z: String? = "hi"\nprint(z, z!, "\\(z)")\nlet arr: [Int?] = [1, nil, 3]\nprint(arr)\nprint(arr.compactMap { $0 })',
     'Optional(5) nil 5 0\ntrue true true\nOptional("hi") hi Optional("hi")\n[Optional(1), nil, Optional(3)]\n[1, 3]'),
    ('var dict = ["b": 2, "a": 1]\nprint(dict.count, dict["a"], dict["q"])\ndict["c"] = 3\ndict["b"] = nil\nprint(dict.keys.sorted(), dict.values.sorted())\nfor (k, v) in dict.sorted(by: { $0.key < $1.key }) { print(k, v) }\nprint(dict.sorted { $0.value > $1.value }.map { $0.key })\nlet e: [String: Int] = [:]\nprint(e, e.isEmpty)\nprint(["one": 1])',
     '2 Optional(1) nil\n["a", "c"] [1, 3]\na 1\nc 3\n["c", "a"]\n[:] true\n["one": 1]'),
    ('var st: Set<Int> = [3, 1, 2]\nst.insert(5)\nst.insert(1)\nprint(st.count, st.contains(5), st.sorted())\nlet o: Set = [1, 2, 9]\nprint(st.intersection(o).sorted(), st.union(o).sorted(), st.subtracting(o).sorted())\nprint(st.symmetricDifference(o).sorted())\nprint(Set([1, 1, 2]).count)',
     '4 true [1, 2, 3, 5]\n[1, 2] [1, 2, 3, 5, 9] [3, 5]\n[3, 5, 9]\n2'),
    ('let s = "Hello, World"\nprint(s.count, s.uppercased(), s.lowercased())\nprint(s.contains("World"), s.hasPrefix("Hell"), s.hasSuffix("d"))\nprint(s.first!, s.last!, String(s.reversed()))\nprint(s.replacingOccurrences(of: "l", with: "L"))\nprint(s.split(separator: ",").map { $0.trimmingCharacters(in: .whitespaces) })\nprint(Array(s).count, Array("abc"))\nprint(s.prefix(5), s.suffix(5), s.dropFirst(7))\nprint(String(repeating: "ab", count: 3))\nlet ch: Character = "a"\nprint(ch, ch.isLetter, ch.uppercased(), String(ch) + "b")\nprint("abc".map { String($0).uppercased() }.joined())\nprint("a-b".components(separatedBy: "-"))',
     'ERROR'),
    ('let name = "Mo"\nlet n = 3\nprint("\\(name) has \\(n * 2) bananas, \\(n > 2 ? "many" : "few")")\nprint("sum: \\([1, 2, 3].reduce(0, +)), \\(Double(n) / 2)")\nprint("\\(name.count) \\(name.uppercased())")\nprint("Opt: \\(Optional(4))")',
     'Mo has 6 bananas, many\nsum: 6, 1.5\n2 MO\nOpt: Optional(4)'),
    ('for i in stride(from: 0, to: 10, by: 3) { print(i, terminator: " ") }\nprint()\nfor i in stride(from: 1.0, through: 2.0, by: 0.5) { print(i, terminator: " ") }\nprint()\nfor i in (1...3).reversed() { print(i, terminator: " ") }\nprint()\nprint(Array(1...4), Array(0..<3), (1...10).count)\nprint((1...5).map { $0 * $0 }, (1..<5).filter { $0 % 2 == 0 })\nprint(1...5, 0..<3)\nlet r = 1...10\nprint(r.contains(5), r.lowerBound, r.upperBound)',
     '0 3 6 9 \n1.0 1.5 2.0 \n3 2 1 \n[1, 2, 3, 4] [0, 1, 2] 10\n[1, 4, 9, 16, 25] [2, 4]\n1...5 0..<3\ntrue 1 10'),
    ('func swapTwo(_ a: inout Int, _ b: inout Int) { let t = a; a = b; b = t }\nvar a = 1, b = 2\nswapTwo(&a, &b)\nprint(a, b)\nswap(&a, &b)\nprint(a, b)\nfunc addOne(_ arr: inout [Int]) { arr.append(1) }\nvar list = [0]\naddOne(&list)\nprint(list)',
     '2 1\n1 2\n[0, 1]'),
    ('protocol Greeter { func greet() -> String }\nextension Greeter { func greet() -> String { "Hello" } }\nstruct A: Greeter {}\nstruct B: Greeter { func greet() -> String { "Hi" } }\nlet gs: [Greeter] = [A(), B()]\nfor g in gs { print(g.greet()) }\nextension Int { var doubled: Int { self * 2 }; func times(_ f: () -> Void) { for _ in 0..<self { f() } } }\nprint(5.doubled)\n3.times { print("x") }\nextension String { func shout() -> String { uppercased() + "!" } }\nprint("hey".shout())',
     'Hello\nHi\n10\nx\nx\nx\nHEY!'),
    ('func largest<T: Comparable>(_ a: [T]) -> T { a.max()! }\nprint(largest([3, 7, 2]), largest(["b", "a"]))\nstruct Stack<T> {\n    var items: [T] = []\n    mutating func push(_ x: T) { items.append(x) }\n    mutating func pop() -> T? { items.popLast() }\n}\nvar stk = Stack<Int>()\nstk.push(1); stk.push(2)\nprint(stk.pop(), stk.items)\nfunc pair<A, B>(_ a: A, _ b: B) -> (A, B) { (a, b) }\nprint(pair(1, "x"))',
     '7 b\nOptional(2) [1]\n(1, "x")'),
    ('enum E: Error { case bad(code: Int), worse }\nfunc f(_ n: Int) throws -> Int {\n    if n < 0 { throw E.bad(code: n) }\n    if n == 0 { throw E.worse }\n    return n * 2\n}\ndo { print(try f(2)); print(try f(-3)) } catch E.bad(let c) { print("bad", c) } catch { print("other", error) }\ndo { try f(0) } catch { print("caught", error) }\nprint((try? f(4)) ?? 0, try? f(0))\ndo { _ = try f(0) } catch let err as E { print("E:", err) }',
     '4\nbad -3\ncaught worse\n8 nil\nE: worse'),
    ('func work() {\n    defer { print("cleanup") }\n    print("working")\n    for i in 1...2 {\n        defer { print("end", i) }\n        print("loop", i)\n    }\n}\nwork()',
     'working\nloop 1\nend 1\nloop 2\nend 2\ncleanup'),
    ('struct Counter {\n    var count = 0 { didSet { print("changed from \\(oldValue) to \\(count)") } }\n    var label: String { willSet { print("will be \\(newValue)") } }\n    static let max = 10\n    static func make() -> Counter { Counter(label: "x") }\n}\nvar c = Counter.make()\nc.count += 1\nc.label = "y"\nprint(Counter.max, c)',
     'changed from 0 to 1\nwill be y\n10 Counter(count: 1, label: "y")'),
    ('class Animal {\n    var name: String\n    init(name: String) { self.name = name }\n    func speak() -> String { "..." }\n    var desc: String { "\\(name) says \\(speak())" }\n}\nclass Dog: Animal {\n    var tricks: Int\n    init(name: String, tricks: Int) { self.tricks = tricks; super.init(name: name) }\n    override func speak() -> String { "Woof" }\n    override var desc: String { super.desc + " (\\(tricks) tricks)" }\n}\nlet d = Dog(name: "Rex", tricks: 2)\nprint(d.desc)\nlet an: Animal = d\nprint(an.speak(), an is Dog, (an as? Dog)?.tricks ?? 0)\nprint(d)',
     'Rex says Woof (2 tricks)\nWoof true 2\nmain.Dog'),
    ('struct Pt: Equatable, Hashable, CustomStringConvertible { var x: Int; var y: Int\n    var description: String { "(\\(x), \\(y))" } }\nlet p1 = Pt(x: 1, y: 2)\nprint(p1, p1 == Pt(x: 1, y: 2), [p1], Set([p1, p1]).count)\nprint("\\(p1)")',
     '(1, 2) true [(1, 2)] 1\n(1, 2)'),
    ('let nums = [5, 3, 8, 1]\nprint(nums.sorted(), nums.sorted(by: >), nums.min()!, nums.max()!)\nprint(nums.first(where: { $0 > 4 }), nums.firstIndex(of: 8), nums.contains(3))\nprint(nums.reduce(0) { $0 + $1 }, nums.map(String.init), nums.filter { $0.isMultiple(of: 2) })\nprint(nums.allSatisfy { $0 > 0 }, nums.reversed(), Array(nums.reversed()))\nprint(nums.enumerated().map { $0.offset * $0.element })\nprint(nums.prefix(2), nums.suffix(2), nums.dropFirst(), nums.dropLast(2))',
     '[1, 3, 5, 8] [8, 5, 3, 1] 1 8\nOptional(5) Optional(2) true\n17 ["5", "3", "8", "1"] [8]\ntrue ReversedCollection<Array<Int>>(_base: [5, 3, 8, 1]) [1, 8, 3, 5]\n[0, 3, 16, 3]\n[5, 3] [8, 1] [3, 8, 1] [5, 3]'),
    ('struct Rect {\n    var width: Double\n    var height: Double\n    var area: Double { width * height }\n    var perimeter: Double {\n        get { 2 * (width + height) }\n    }\n    var side: Double {\n        get { width }\n        set { width = newValue; height = newValue }\n    }\n    func scaled(by f: Double) -> Rect { Rect(width: width * f, height: height * f) }\n    mutating func double() { width *= 2; height *= 2 }\n    static var count = 0\n    static func unit() -> Rect { Rect(width: 1, height: 1) }\n}\nvar r = Rect(width: 2, height: 3)\nprint(r.area, r.perimeter)\nr.side = 4\nprint(r)\nr.double()\nprint(r.area, r.scaled(by: 0.5))\nprint(Rect.unit(), Rect.count)',
     '6.0 10.0\nRect(width: 4.0, height: 4.0)\n64.0 Rect(width: 4.0, height: 4.0)\nRect(width: 1.0, height: 1.0) 0'),
    ('class Vehicle {\n    let wheels: Int\n    var speed = 0\n    init(wheels: Int) { self.wheels = wheels }\n    convenience init() { self.init(wheels: 4) }\n    func describe() -> String { "\\(wheels) wheels at \\(speed)" }\n}\nclass Bike: Vehicle {\n    init() { super.init(wheels: 2) }\n    override func describe() -> String { "Bike: " + super.describe() }\n}\nlet v = Vehicle()\nv.speed = 30\nprint(v.describe())\nlet b = Bike()\nprint(b.describe(), b is Vehicle)\nlet things: [Vehicle] = [v, b]\nprint(things.map { $0.wheels })',
     '4 wheels at 30\nBike: 2 wheels at 0 true\n[4, 2]'),
    ('class Node {\n    var value: Int\n    var next: Node?\n    init(_ value: Int, next: Node? = nil) { self.value = value; self.next = next }\n}\nlet list = Node(1, next: Node(2, next: Node(3)))\nvar cur: Node? = list\nvar total = 0\nwhile let n = cur { total += n.value; cur = n.next }\nprint(total, list.next?.next?.value ?? -1, list.next?.next?.next?.value ?? -1)',
     '6 3 -1'),
    ('enum Coin: Int, CaseIterable {\n    case penny = 1, nickel = 5, dime = 10, quarter = 25\n    var name: String {\n        switch self {\n        case .penny: return "penny"\n        default: return "\\(self)"\n        }\n    }\n}\nfor c in Coin.allCases { print(c.name, c.rawValue) }\nprint(Coin.allCases.map { $0.rawValue }.reduce(0, +))\nprint(Coin(rawValue: 10)!, Coin(rawValue: 3) == nil)',
     'penny 1\nnickel 5\ndime 10\nquarter 25\n41\ndime true'),
    ('enum Light {\n    case red, yellow, green\n    mutating func next() {\n        switch self {\n        case .red: self = .green\n        case .green: self = .yellow\n        case .yellow: self = .red\n        }\n    }\n}\nvar l = Light.red\nl.next()\nprint(l)\nl.next(); l.next()\nprint(l)',
     'green\nred'),
    ('enum Result2 { case success(Int), failure(String) }\nlet rs: [Result2] = [.success(5), .failure("oops"), .success(-1)]\nfor x in rs {\n    switch x {\n    case .success(let n) where n > 0: print("good", n)\n    case .success(let n): print("meh", n)\n    case .failure(let msg): print("bad:", msg)\n    }\n}\nif case .failure(let m) = rs[1] { print("first failure:", m) }',
     'good 5\nbad: oops\nmeh -1\nfirst failure: oops'),
    ('let point = (3, -2)\nswitch point {\ncase (0, 0): print("origin")\ncase (let x, 0): print("on x", x)\ncase (0, _): print("on y")\ncase let (x, y) where x > 0 && y < 0: print("quadrant 4", x, y)\ndefault: print("elsewhere")\n}\nlet age = 15\nswitch age {\ncase 0..<13: print("child")\ncase 13...19: print("teen")\ndefault: print("adult")\n}',
     'quadrant 4 3 -2\nteen'),
    ('func fetch(_ id: Int) -> String? { id > 0 ? "item\\(id)" : nil }\nfunc show(_ id: Int) {\n    guard let item = fetch(id) else {\n        print("nothing for", id)\n        return\n    }\n    print("got", item)\n}\nshow(3); show(0)\nif let a = fetch(1), let b = fetch(2), a != b { print(a, b) }\nlet maybe: String? = fetch(5)\nprint(maybe?.count ?? 0, maybe?.uppercased())\nvar opt: Int? = nil\nopt = 4\nif var o = opt { o += 1; print(o) }\nprint(opt != nil ? "has" : "none")',
     'got item3\nnothing for 0\nitem1 item2\n5 Optional("ITEM5")\n5\nhas'),
    ('var counter = 0\nlet inc = { counter += 1 }\ninc(); inc()\nprint(counter)\nfunc makeCounter() -> () -> Int {\n    var c = 0\n    return { c += 1; return c }\n}\nlet next = makeCounter()\nprint(next(), next(), next())\nlet other = makeCounter()\nprint(other())\nfunc apply(_ f: (Int) -> Int, to x: Int) -> Int { f(x) }\nprint(apply({ $0 * 3 }, to: 4), apply({ x in x + 1 }, to: 1))\nlet square: (Int) -> Int = { $0 * $0 }\nprint([1, 2, 3].map(square))\nlet add: (Int, Int) -> Int = { a, b in a + b }\nprint(add(2, 5))',
     '2\n1 2 3\n1\n12 2\n[1, 4, 9]\n7'),
    ('let names = ["Zoe", "adam", "Bob", "eve"]\nprint(names.sorted())\nprint(names.sorted { $0.lowercased() < $1.lowercased() })\nprint(names.map { $0.count }.max()!, names.filter { $0.first!.isUppercase })\nprint(names.contains { $0.hasPrefix("B") })\nprint(names.firstIndex(where: { $0.count == 4 })!)\nprint(names.compactMap { $0.count > 3 ? $0 : nil })\nprint(names.reduce("") { $0 + String($1.prefix(1)) })\nprint(names.count(where: { $0.count == 3 }))',
     '["Bob", "Zoe", "adam", "eve"]\n["adam", "Bob", "eve", "Zoe"]\n4 ["Zoe", "Bob"]\ntrue\n1\n["adam"]\nZaBe\n3'),
    ('var inventory = ["apples": 3, "pears": 0]\ninventory["apples", default: 0] += 2\ninventory["kiwis", default: 0] += 1\nif let n = inventory["pears"], n == 0 { inventory.removeValue(forKey: "pears") }\nfor name in inventory.keys.sorted() { print(name, inventory[name]!) }\nlet counts = "banana".reduce(into: [:]) { d, c in d[c, default: 0] += 1 }\nprint(counts.sorted { $0.key < $1.key }.map { "\\($0.key)\\($0.value)" }.joined(separator: " "))\nlet lengths = names2().mapValues { $0.count }\nfunc names2() -> [String: String] { ["a": "xx"] }\nprint(lengths)\nprint(inventory.filter { $0.value > 1 }.count, inventory.values.reduce(0, +))',
     'apples 5\nkiwis 1\na3 b1 n2\n["a": 2]\n1 6'),
    ('let str = "Swift is fun"\nlet w = str.split(separator: " ")\nprint(w.count, w.last!, w.map { $0.count })\nprint(str.lowercased().filter { "aeiou".contains($0) }.count)\nprint(str.replacingOccurrences(of: " ", with: "_"))\nprint(String(str.reversed()), str.uppercased().hasSuffix("FUN"))\nvar s2 = "abc"\ns2 += "def"\ns2.append("!")\nprint(s2, s2.count, s2.isEmpty, "".isEmpty)\nprint("Line1\\nLine2\\tTabbed \\"quoted\\" \\\\ back")\nlet multi = """\n    Hello\n      indented\n    World\n    """\nprint(multi)\nprint(Array("hey").map { String($0) }, "x".first! == "x")\nprint(Int("42")! + 1, String(42) + "!", "\\(3.5)", String(7.0))',
     'ERROR'),
    ('func divide(_ a: Int, by b: Int) -> (quotient: Int, remainder: Int)? {\n    if b == 0 { return nil }\n    return (a / b, a % b)\n}\nif let r = divide(17, by: 5) { print(r.quotient, r.remainder, r) }\nprint(divide(1, by: 0) == nil)\nlet (q, rem) = divide(9, by: 2)!\nprint(q, rem)\nvar tup = (name: "Mo", age: 4)\ntup.age += 1\nprint(tup, tup.name)',
     '3 2 (quotient: 3, remainder: 2)\ntrue\n4 1\n(name: "Mo", age: 5) Mo'),
    ('func sumAll(_ nums: Int...) -> Int { nums.reduce(0, +) }\nprint(sumAll(1, 2, 3), sumAll())\nfunc greet(person: String, from town: String = "Jungle") -> String { "Hi \\(person) from \\(town)" }\nprint(greet(person: "Mo"), greet(person: "Kiki", from: "Beach"))\nfunc fact(_ n: Int) -> Int { n <= 1 ? 1 : n * fact(n - 1) }\nprint(fact(10), fact(20))\nfunc fib(_ n: Int) -> Int { n < 2 ? n : fib(n - 1) + fib(n - 2) }\nprint((0..<10).map(fib))',
     '6 0\nHi Mo from Jungle Hi Kiki from Beach\n3628800 2432902008176640000\n[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]'),
    ('protocol Animal { var name: String { get }; func sound() -> String }\nextension Animal { func intro() -> String { "\\(name) says \\(sound())" } }\nstruct Cat: Animal { let name: String; func sound() -> String { "meow" } }\nstruct Cow: Animal { let name = "Bessie"; func sound() -> String { "moo" } }\nlet zoo: [Animal] = [Cat(name: "Tom"), Cow()]\nfor a in zoo { print(a.intro()) }\nprint(zoo.map { $0.name })',
     'Tom says meow\nBessie says moo\n["Tom", "Bessie"]'),
    ('struct Score: Comparable {\n    let value: Int\n    static func < (a: Score, b: Score) -> Bool { a.value < b.value }\n}\nlet scores = [Score(value: 5), Score(value: 2), Score(value: 9)]\nprint(scores.sorted().map { $0.value }, scores.max()!.value, Score(value: 1) < Score(value: 2))\nprint(Score(value: 3) == Score(value: 3))',
     '[2, 5, 9] 9 true\ntrue'),
    ('struct Vec { var x = 0.0, y = 0.0 }\nfunc + (a: Vec, b: Vec) -> Vec { Vec(x: a.x + b.x, y: a.y + b.y) }\nprint(Vec(x: 1, y: 2) + Vec(x: 0.5, y: 0.5))',
     'Vec(x: 1.5, y: 2.5)'),
    ('var arr = [1, 2, 3, 4, 5, 6]\narr.removeAll { $0 % 2 == 0 }\nprint(arr)\narr.insert(0, at: 0)\narr += [7, 8]\nprint(arr, arr.remove(at: 1), arr)\narr.swapAt(0, 1)\nprint(arr, arr.firstIndex(of: 99))\narr.sort(by: >)\nprint(arr, arr.reversed().first!)\nprint(Array(repeating: 0, count: 3), [Int](), [String](repeating: "-", count: 2).joined())\nvar grid = Array(repeating: Array(repeating: ".", count: 3), count: 2)\ngrid[1][2] = "#"\nfor row in grid { print(row.joined()) }',
     '[1, 3, 5]\n[0, 1, 3, 5, 7, 8] 1 [0, 3, 5, 7, 8]\n[3, 0, 5, 7, 8] nil\n[8, 7, 5, 3, 0] 0\n[0, 0, 0] [] --\n...\n..#'),
    ('let nums = [4, 8, 15, 16, 23, 42]\nlet evens = nums.filter { $0 % 2 == 0 }\nlet avg = Double(nums.reduce(0, +)) / Double(nums.count)\nprint(evens, avg)\nprint(String(format: "%.2f", avg))\nprint(nums.min()!, nums.max()!, nums.sorted(by: >).prefix(3))\nprint(nums.map { $0 > 10 ? "big" : "small" })\nprint(nums.enumerated().filter { $0.offset % 2 == 0 }.map { $0.element })\nprint(zip(nums, nums.dropFirst()).map { $1 - $0 })',
     'ERROR'),
    ('do {\n    struct Inner { var v = 1 }\n    print(Inner().v)\n}\nlet big = 1_000_000\nprint(big, 0b101, 0xFF, 0o17)\nprint(Int.max - 1 > 0, 2 << 3, 255 & 15)\nprint(10.0.squareRoot(), pow(2.0, 10.0), abs(-2.5))\nprint(Double.pi)\nprint((7.5).truncatingRemainder(dividingBy: 2))\nprint(Int(3.99), Int(-3.99), Int((3.5).rounded()), (3.14159 * 100).rounded() / 100)\nprint(17.0 / 4, 17 / 4, Double(17 / 4))',
     'ERROR'),
    ('let letter: Character = "b"\nswitch letter {\ncase "a", "e", "i", "o", "u": print("vowel")\ndefault: print("consonant")\n}\nlet word = "Hello"\nvar upper = 0\nfor ch in word where ch.isUppercase { upper += 1 }\nprint(upper)\nfor (i, ch) in word.enumerated() { if i < 2 { print(i, ch) } }\nprint(word.contains("l"), word.contains(Character("z")))',
     'consonant\n1\n0 H\n1 e\ntrue false'),
    ('for i in 0..<3 {\n    for j in 0..<3 {\n        if j == 2 { continue }\n        if i == 2 { break }\n        print(i, j)\n    }\n}\nouter: for i in 1...3 {\n    for j in 1...3 {\n        if i * j == 4 { break outer }\n        print(i * j, terminator: " ")\n    }\n}\nprint()\nvar k = 10\nrepeat { k -= 3 } while k > 0\nprint(k)',
     '0 0\n0 1\n1 0\n1 1\n1 2 3 2 \n-2'),
    ('print("abc".contains("bc"))',
     'true'),
    ('print(pow(2.0, 3.0))',
     'ERROR'),
    ('print(sqrt(16.0))',
     'ERROR'),
    ('print(floor(2.5), ceil(2.5), round(2.5))',
     'ERROR'),
    ('print("a b".components(separatedBy: " "))',
     'ERROR'),
    ('print(" a ".trimmingCharacters(in: .whitespaces))',
     'ERROR'),
    ('print("hello world".capitalized)',
     'ERROR'),
    ('print(String(format: "%d", 5))',
     'ERROR'),
    ('print("abc".range(of: "b") != nil)',
     'ERROR'),
    ('print(abs(-3), min(2, 3), max(2.5, 1.0))',
     '3 2 2.5'),
    ('print(Double.pi.rounded())',
     '3.0'),
    ('print("x".uppercased(), "abc".hasPrefix("a"))',
     'X true'),
    ('print((2.0).squareRoot())',
     '1.4142135623730951'),
    ('let x = 5.formatted()\nprint(x)',
     'ERROR'),
    ('print("a,b".split(separator: ","))',
     '["a", "b"]'),
    ('print("ab".lowercased().reversed().count)',
     '2'),
    ('print(log(1.0), exp(0.0), sin(0.0))',
     'ERROR'),
    ('let a = [1, 2, 3]\nprint(a[3])',
     'CRASH'),
    ('var d: [String: Int] = [:]\nprint(d["x"]!)',
     'CRASH'),
    ('let n: Int? = nil\nprint(n!)',
     'CRASH'),
    ('print(10 / 0)',
     'ERROR'),
    ('let z = 0\nprint(10 / z)',
     'CRASH'),
    ('let big = Int.max\nprint(big + 1)',
     'CRASH'),
    ('var arr: [Int] = []\narr.removeLast()',
     'CRASH'),
    ('let s = "abc"\nlet i = Int(s)!\nprint(i)',
     'CRASH'),
    ('for i in 5...1 { print(i) }',
     'CRASH'),
    ('fatalError("boom")',
     'CRASH'),
    ('let x: Int = "5"',
     'ERROR'),
    ('var y = 5\ny = "five"',
     'ERROR'),
    ('let s1 = "a" + 1',
     'ERROR'),
    ('func f() -> Int { return "x" }\nprint(f())',
     'ERROR'),
    ('let u = undefinedThing + 1',
     'ERROR'),
    ('print("hi"',
     'ERROR'),
    ('let q = 3\nif q = 3 { print("x") }',
     'ERROR'),
    ('let w = 5\nw += 1',
     'ERROR'),
    ('func g(a: Int) {}\ng(5)',
     'ERROR'),
    ('func h(_ a: Int) {}\nh(a: 5)',
     'ERROR'),
    ('struct P { let x: Int }\nvar p = P(x: 1)\np.x = 2',
     'ERROR'),
    ('let o: String? = "x"\nprint(o.count)',
     'ERROR'),
    ('let e = [1, "a"]',
     'ERROR'),
    ('var c = 0\nfor i in 1...3 {\n    c += i\n}\nprint(c, i)',
     'ERROR'),
    ('precondition(1 > 2, "math broke")',
     'CRASH'),
    ('let t = (1, 2)\nprint(t.2)',
     'ERROR'),
    ('enum E { case a, b }\nlet v = E.c',
     'ERROR'),
    ('class K { var v: Int }',
     'ERROR'),
    ('print(Double(1) + Int(2))',
     'ERROR'),
    ('let m = 3.7\nlet k: Int = m',
     'ERROR'),
    ('var opt: Int? = 3\nprint(opt + 1)',
     'ERROR'),
    ('let names = ["a"]\nnames.append("b")',
     'ERROR'),
    ('switch 5 {\ncase 1: print(1)\n}',
     'ERROR'),
    ('func r(_ n: Int) -> Int { r(n + 1) }\nprint(r(0))',
     'CRASH'),
    ('let ch: Character = "ab"',
     'ERROR'),
    ('print([1, 2, 3].first!.isEven)',
     'ERROR'),
    ('let dict = ["a": 1]\nfor (k, v) in dict { print(k, v) }\nprint(dict.first!.key, dict.keys.first!)',
     'a 1\na a'),
    ('print(-5 / 2, -5 % 2, 5 / -2, Int(-2.5), (-2.5).rounded(), (2.5).rounded(.down), (2.5).rounded(.towardZero), (-2.5).rounded(.up))',
     '-2 -1 -2 -2 -3.0 2.0 2.0 -2.0'),
    ('print(Int8.max, UInt8.max, Int16.min, Int32.max)',
     '127 255 -32768 2147483647'),
    ('let arr2 = [3, 1, 2]\nprint(arr2.sorted(by: <), arr2.min(by: >)!, arr2.sorted().reversed() as [Int])',
     '[1, 2, 3] 3 [3, 2, 1]'),
    ('print(1 == 1.0, 3 > 2.5, 0.1 + 0.2 == 0.3)',
     'true true false'),
    ('print(type(of: 1.5), type(of: [1]), type(of: ["a": 1]), type(of: (1, "x")), type(of: Optional(1)))',
     'Double Array<Int> Dictionary<String, Int> (Int, String) Optional<Int>'),
    ('let flag = true\nprint(!flag, flag && false, flag || false, flag.toggled)',
     'ERROR'),
    ('var bools = [true, false]\nbools[0].toggle()\nprint(bools)',
     '[false, false]'),
    ('extension Int {\n    var isEven: Bool { self % 2 == 0 }\n    func squared() -> Int { self * self }\n    mutating func double() { self *= 2 }\n    static var zeroValue: Int { 0 }\n}\nvar n = 7\nprint(n.isEven, n.squared(), 4.isEven)\nn.double()\nprint(n, Int.zeroValue)\nextension String {\n    var vowelCount: Int { filter { "aeiou".contains($0) }.count }\n    func repeated(_ k: Int) -> String { String(repeating: self, count: k) }\n}\nprint("banana".vowelCount, "ab".repeated(3))\nextension Array {\n    func second() -> Element? { count > 1 ? self[1] : nil }\n}\nprint([5, 6, 7].second()!, [Int]().second() == nil)\nextension Double {\n    var celsius: Double { (self - 32) * 5 / 9 }\n}\nprint(212.0.celsius)',
     'false 49 true\n14 0\n3 ababab\n6 true\n100.0'),
    ('func largest<T: Comparable>(_ a: [T]) -> T? {\n    guard var best = a.first else { return nil }\n    for x in a where x > best { best = x }\n    return best\n}\nprint(largest([3, 7, 2])!, largest(["b", "z", "a"])!, largest([Int]()) == nil)\nstruct Stack<Element> {\n    private var items: [Element] = []\n    var isEmpty: Bool { items.isEmpty }\n    var count: Int { items.count }\n    mutating func push(_ x: Element) { items.append(x) }\n    mutating func pop() -> Element? { items.popLast() }\n    func peek() -> Element? { items.last }\n}\nvar st = Stack<String>()\nst.push("a"); st.push("b")\nprint(st.count, st.peek()!, st.pop()!, st.pop()!, st.pop() == nil, st.isEmpty)\nfunc swapValues<T>(_ a: inout T, _ b: inout T) { let t = a; a = b; b = t }\nvar x1 = "x", x2 = "y"\nswapValues(&x1, &x2)\nprint(x1, x2)\nstruct Pair<A, B> { let first: A; let second: B }\nlet pr = Pair(first: 1, second: "one")\nprint(pr.first, pr.second, pr)',
     '7 z true\n2 b b a true true\ny x\n1 one Pair<Int, String>(first: 1, second: "one")'),
    ('struct Matrix {\n    var data = [[0, 0], [0, 0]]\n    subscript(r: Int, c: Int) -> Int {\n        get { data[r][c] }\n        set { data[r][c] = newValue }\n    }\n}\nvar mx = Matrix()\nmx[0, 1] = 5\nprint(mx[0, 1], mx.data)\nstruct Week {\n    let days = ["Mon", "Tue", "Wed"]\n    subscript(i: Int) -> String { days[i % days.count] }\n}\nprint(Week()[4])',
     '5 [[0, 5], [0, 0]]\nTue'),
    ('struct ValidationError: Error { let reason: String }\nenum NetError: Error, CustomStringConvertible {\n    case offline, timeout(seconds: Int)\n    var description: String {\n        switch self {\n        case .offline: return "no connection"\n        case .timeout(let s): return "timed out after \\(s)s"\n        }\n    }\n}\nfunc load(_ k: Int) throws -> String {\n    switch k {\n    case 0: throw NetError.offline\n    case 1: throw NetError.timeout(seconds: 5)\n    case 2: throw ValidationError(reason: "bad input")\n    default: return "data\\(k)"\n    }\n}\nfor k in 0...3 {\n    do {\n        let r = try load(k)\n        print("ok", r)\n    } catch let e as NetError {\n        print("net:", e)\n    } catch let e as ValidationError {\n        print("invalid:", e.reason)\n    } catch {\n        print("other")\n    }\n}\nfunc wrapper() throws -> String { try load(1) }\ndo { _ = try wrapper() } catch { print("wrapped:", error) }\nprint((try? load(3)) ?? "none", (try? load(0)) ?? "none")',
     'net: no connection\nnet: timed out after 5s\ninvalid: bad input\nok data3\nwrapped: timed out after 5s\ndata3 none'),
    ('func steps() {\n    defer { print("first defer runs last") }\n    defer { print("second defer runs first") }\n    print("body")\n}\nsteps()\nfunc early(_ x: Int) -> String {\n    defer { print("leaving", x) }\n    if x > 0 { return "positive" }\n    return "not"\n}\nprint(early(1))\nprint(early(-1))',
     'body\nsecond defer runs first\nfirst defer runs last\nleaving 1\npositive\nleaving -1\nnot'),
    ('class Temp {\n    var c: Double = 0 {\n        willSet { print("about to set \\(newValue)") }\n        didSet { if c > 100 { c = 100 }; print("set from \\(oldValue)") }\n    }\n    lazy var label: String = { print("computing"); return "T" }()\n}\nlet tt = Temp()\ntt.c = 150\nprint(tt.c)\nprint(tt.label, tt.label)',
     'about to set 150.0\nset from 0.0\n100.0\ncomputing\nT T'),
    ('struct Shop {\n    struct Item { let name: String; let price: Double }\n    enum Size { case small, large }\n    var items: [Item] = []\n    mutating func add(_ n: String, _ p: Double) { items.append(Item(name: n, price: p)) }\n    var total: Double { items.reduce(0) { $0 + $1.price } }\n}\nvar shop = Shop()\nshop.add("pen", 1.5)\nshop.add("book", 12.25)\nprint(shop.total, shop.items.map(\\.name), Shop.Size.large)\nlet it = Shop.Item(name: "cup", price: 3)\nprint(it.price)',
     '13.75 ["pen", "book"] large\n3.0'),
    ('var handlers: [() -> Void] = []\nfor i in 1...3 { handlers.append { print("handler", i) } }\nhandlers.forEach { $0() }\nfunc run(_ times: Int, action: () -> Void) { for _ in 0..<times { action() } }\nrun(2) { print("hi") }\nfunc compose(_ f: @escaping (Int) -> Int, _ g: @escaping (Int) -> Int) -> (Int) -> Int { { g(f($0)) } }\nlet incThenDouble = compose({ $0 + 1 }, { $0 * 2 })\nprint(incThenDouble(3))\nvar total = 0\n[1, 2, 3].forEach { total += $0 }\nprint(total)\nlet sortedByLen = ["ccc", "a", "bb"].sorted { (a: String, b: String) -> Bool in a.count < b.count }\nprint(sortedByLen)',
     'handler 1\nhandler 2\nhandler 3\nhi\nhi\n8\n6\n["a", "bb", "ccc"]'),
    ('let people = [("Mo", 4), ("Kiki", 7), ("Zed", 4)]\nlet sortedPeople = people.sorted { $0.1 != $1.1 ? $0.1 > $1.1 : $0.0 < $1.0 }\nfor (name, age) in sortedPeople { print(name, age) }\nprint(people.map { $0.0 }.joined(separator: ", "))\nlet byAge = Dictionary(grouping: people, by: { $0.1 })\nprint(byAge[4]!.count)\nlet maxAge = people.map(\\.1).max()!\nprint(maxAge)',
     'Kiki 7\nMo 4\nZed 4\nMo, Kiki, Zed\n2\n7'),
    ('let set1: Set = ["a", "b", "c"]\nlet set2: Set = ["b", "c", "d"]\nprint(set1.intersection(set2).sorted(), set1.isSubset(of: set1.union(set2)), set1.contains("z"))\nvar seen = Set<Int>()\nfor v in [3, 1, 3, 2, 1] { if !seen.insert(v).inserted { print("dup", v) } }\nprint(seen.count)',
     '["b", "c"] true false\ndup 3\ndup 1\n3'),
    ('let score = 87\nlet grade: String\nif score >= 90 { grade = "A" } else if score >= 80 { grade = "B" } else { grade = "C" }\nprint(grade)\nlet message = switch score {\ncase 90...: "great"\ncase 80..<90: "good"\ndefault: "ok"\n}\nprint(message)\nlet parity = if score % 2 == 0 { "even" } else { "odd" }\nprint(parity)',
     'B\ngood\nodd'),
    ('print("a", "b", "c", separator: "-")\nprint("no newline", terminator: "")\nprint(" then this")\nprint([1, 2], [String: Int](), Set<Int>(), (), separator: " | ")\nlet pi = 3.14159\nprint("Pi is about \\(pi)")\nprint("Rounded: \\((pi * 100).rounded() / 100)")\nprint("Int: \\(Int(pi)) Bool: \\(pi > 3) Arr: \\([1, 2]) Opt: \\(String(describing: Optional("x")))")',
     'a-b-c\nno newline then this\n[1, 2] | [:] | [] | ()\nPi is about 3.14159\nRounded: 3.14\nInt: 3 Bool: true Arr: [1, 2] Opt: Optional("x")'),
    ('let o1: Int?? = 5\nprint(o1 as Any)\nlet o2: Int? = nil\nprint(o2 as Any, [o2])\nprint(["a": [1, 2]], ["k": Optional(1)])\nprint([1: "one"], [true], [1.5, 2])\nprint(Set([42]))\nprint([Character("a"), "b"])\nprint([("x", 1)], [[String: Int]]())\nlet e: [Int] = []\nprint(e, e.first as Any, e.max() as Any)\nprint([0.1, 0.2, 0.3].reduce(0, +))\nprint((1...4).reduce(1, *))',
     'Optional(Optional(5))\nnil [nil]\n["a": [1, 2]] ["k": Optional(1)]\n[1: "one"] [true] [1.5, 2.0]\n[42]\n["a", "b"]\n[("x", 1)] []\n[] nil nil\n0.6000000000000001\n24'),
    ('func f(_ x: Int) -> Int { x }\nprint(f)\nlet c = { (x: Int) in x }\nprint(c)\nprint(type(of: f))',
     '(Function)\n(Function)\n(Int) -> Int'),
    ('let letters = "hello"\nvar counts: [Character: Int] = [:]\nfor ch in letters { counts[ch, default: 0] += 1 }\nfor k in counts.keys.sorted() { print(k, counts[k]!) }\nlet caesar = String(letters.map { ch -> Character in\n    let v = ch.asciiValue! - 97\n    return Character(UnicodeScalar((v + 3) % 26 + 97))\n})\nprint(caesar)\nprint(letters.uppercased().map { String($0) }.joined(separator: "."))\nlet digits = "a1b2c3".compactMap { $0.wholeNumberValue }\nprint(digits, digits.reduce(0, +))\nprint("racecar" == String("racecar".reversed()))\nprint(Array("abc").reversed().map { String($0) }.joined())',
     'e 1\nh 1\nl 2\no 1\nkhoor\nH.E.L.L.O\n[1, 2, 3] 6\ntrue\ncba'),
    ('var matrix = [[1, 2, 3], [4, 5, 6]]\nvar transposed: [[Int]] = Array(repeating: [], count: 3)\nfor row in matrix { for (j, v) in row.enumerated() { transposed[j].append(v) } }\nprint(transposed)\nmatrix[0].append(9)\nprint(matrix, matrix.flatMap { $0 }, matrix.map { $0.reduce(0, +) })',
     '[[1, 4], [2, 5], [3, 6]]\n[[1, 2, 3, 9], [4, 5, 6]] [1, 2, 3, 9, 4, 5, 6] [15, 15]'),
    ('struct Student { let name: String; var grades: [Int]\n    var average: Double { grades.isEmpty ? 0 : Double(grades.reduce(0, +)) / Double(grades.count) } }\nvar roster = [Student(name: "Ana", grades: [90, 80]), Student(name: "Ben", grades: [70])]\nroster[1].grades.append(100)\nfor s in roster.sorted(by: { $0.average > $1.average }) { print(s.name, s.average) }\nprint(roster.map(\\.name), roster.filter { $0.average >= 85 }.count)\nlet best = roster.max { $0.average < $1.average }!\nprint(best.name)',
     'Ana 85.0\nBen 85.0\n["Ana", "Ben"] 2\nAna'),
    ('class BankAccount {\n    private(set) var balance: Double = 0\n    let owner: String\n    static var count = 0\n    init(owner: String) { self.owner = owner; BankAccount.count += 1 }\n    func deposit(_ amt: Double) { guard amt > 0 else { print("invalid"); return }; balance += amt }\n    func withdraw(_ amt: Double) -> Bool {\n        if amt > balance { return false }\n        balance -= amt\n        return true\n    }\n}\nlet acct = BankAccount(owner: "Mo")\nacct.deposit(50)\nacct.deposit(-5)\nprint(acct.withdraw(20), acct.withdraw(100), acct.balance, BankAccount.count)\nlet alias = acct\nalias.deposit(1)\nprint(acct.balance, acct === alias)',
     'invalid\ntrue false 30.0 1\n31.0 true'),
    ('protocol Describable { func describe() -> String }\nextension Describable { func shout() -> String { describe().uppercased() } }\nenum Planet: String, Describable, CaseIterable {\n    case mercury, venus\n    func describe() -> String { "planet \\(rawValue)" }\n}\nprint(Planet.allCases.map { $0.shout() })\nstruct Box<T>: Describable { let v: T; func describe() -> String { "box of \\(v)" } }\nprint(Box(v: 3).describe(), Box(v: "x").shout())\nlet items: [any Describable] = [Planet.venus, Box(v: 1.5)]\nfor i in items { print(i.describe()) }',
     '["PLANET MERCURY", "PLANET VENUS"]\nbox of 3 BOX OF X\nplanet venus\nbox of 1.5'),
    ('var queue = [1, 2, 3]\nwhile !queue.isEmpty {\n    let x = queue.removeFirst()\n    if x < 3 { queue.append(x + 10) }\n    print(x, terminator: " ")\n}\nprint()\nvar stack = [Int]()\nfor t in "3 4 + 2 *".split(separator: " ") {\n    if let n = Int(t) { stack.append(n) } else {\n        let b = stack.removeLast(), a = stack.removeLast()\n        stack.append(t == "+" ? a + b : a * b)\n    }\n}\nprint(stack)',
     '1 2 3 11 12 \n[14]'),
    ('func isPrime(_ n: Int) -> Bool {\n    if n < 2 { return false }\n    var i = 2\n    while i * i <= n { if n % i == 0 { return false }; i += 1 }\n    return true\n}\nprint((1...30).filter(isPrime))\nfunc gcd(_ a: Int, _ b: Int) -> Int { b == 0 ? a : gcd(b, a % b) }\nprint(gcd(48, 18))\nvar fibs = [0, 1]\nwhile fibs.count < 15 { fibs.append(fibs[fibs.count - 1] + fibs[fibs.count - 2]) }\nprint(fibs)\nprint(fibs.last!, fibs.suffix(3).reduce(0, +))\nfunc binarySearch(_ a: [Int], _ t: Int) -> Int? {\n    var lo = 0, hi = a.count - 1\n    while lo <= hi {\n        let mid = (lo + hi) / 2\n        if a[mid] == t { return mid } else if a[mid] < t { lo = mid + 1 } else { hi = mid - 1 }\n    }\n    return nil\n}\nprint(binarySearch(fibs, 21) as Any, binarySearch(fibs, 4) as Any)',
     '[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]\n6\n[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377]\n377 754\nOptional(8) nil'),
    ('for i in 1...15 {\n    switch (i % 3, i % 5) {\n    case (0, 0): print("FizzBuzz")\n    case (0, _): print("Fizz")\n    case (_, 0): print("Buzz")\n    default: print(i)\n    }\n}',
     '1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz'),
    ('let temps = [72.5, 68.0, 75.25]\nlet avg = temps.reduce(0, +) / Double(temps.count)\nprint(avg, temps.map { ($0 - 32) * 5 / 9 })\nprint(temps.map { Int($0) }, temps.sorted().first!, temps.contains(68))\nprint(1e3, 2.5e-3, 1_000.5, Double(3) / 4, 7.0 / 2.0, -0.5 * 2)\nprint(Double(10) / 3 * 3, 100.0 / 3.0)\nprint(Int("007")!, Int("-12")!, Int("+5")!, Double(".5") as Any, Double("5.") as Any)',
     '71.91666666666667 [22.5, 20.0, 24.02777777777778]\n[72, 68, 75] 68.0 true\n1000.0 0.0025 1000.5 0.75 3.5 -1.0\n10.0 33.333333333333336\n7 -12 5 Optional(0.5) Optional(5.0)'),
    ('var count = 0\ncount = 2.5',
     'ERROR'),
    ('let n = 5\nlet half = n / 2.0',
     'ERROR'),
    ('func greet(name: String) -> String {\n    print("Hi \\(name)")\n}\ngreet(name: "Mo")',
     'ERROR'),
    ('func add(_ a: Int, _ b: Int) -> Int { a + b }\nlet r = add(1)',
     'ERROR'),
    ('var s = "abc"\ns[0] = "x"',
     'ERROR'),
    ('let arr = [1, 2, 3]\nfor i in 0...arr.count { print(arr[i]) }',
     'CRASH'),
    ('let x: Int\nprint(x)',
     'ERROR'),
    ('var total: Int = 0\ntotal += 1.5',
     'ERROR'),
    ('let age = 10\nif age > 5\n{\n    print("big")\n}',
     'big'),
    ('var names = ["a"]\nnames.append(5)',
     'ERROR'),
    ('struct Dog { var name: String }\nlet d = Dog()',
     'ERROR'),
    ('struct Dog { var name: String\n    func rename(_ n: String) { name = n } }',
     'ERROR'),
    ('class A { func f() {} }\nclass B: A { func f() {} }',
     'ERROR'),
    ('enum Color { case red, green }\nlet c: Color = .blue',
     'ERROR'),
    ('let v: String = nil',
     'ERROR'),
    ('let words = ["a", "b"]\nprint(words.joined(", "))',
     'ERROR'),
    ('print("a" * 3)',
     'ERROR'),
    ('let t = true\nif t == 1 { print("one") }',
     'ERROR'),
    ('let q = [1, 2, 3]\nlet m = q.map { x in x * 2 }\nprint(m.count())',
     'ERROR'),
    ('print(Int("5") + 1)',
     'ERROR'),
    ('let dict = ["a": 1]\nlet val: Int = dict["a"]',
     'ERROR'),
    ('var e = []',
     'ERROR'),
    ('let score = 80\nswitch score {\ncase 90...100:\n    print("A")\ncase 80..<90:\ndefault:\n    print("C")\n}',
     'ERROR'),
    ('print(undefinedFunction())',
     'ERROR'),
    ('var i = 0\nwhile i < 3 {\n    print(i)\n    i++\n}',
     'ERROR'),
    ('for var j = 0; j < 3; j += 1 { print(j) }',
     'ERROR'),
    ('let num = 3\nprint("Value: " + num)',
     'ERROR'),
    ('let maybe: Int? = 3\nif maybe { print("yes") }',
     'ERROR'),
    ('func f(x: inout Int) { x += 1 }\nvar z = 1\nf(x: z)',
     'ERROR'),
    ('let tuple = (1, 2)\nlet (a, b, c2) = tuple',
     'ERROR'),
    ('struct P { let x: Int }\nvar p = P(x: 1)\np = P(x: 2)\nprint(p.x)',
     '2'),
    ('class K { let v = 1 }\nlet k = K()\nk.v = 2',
     'ERROR'),
    ("let str: String = 'hello'",
     'ERROR'),
    ('print(10 % 3.0)',
     'ERROR'),
    ('let big: Int = 3000000000 * 4000000000',
     'ERROR'),
    ('func g() throws {}\ng()',
     'ERROR'),
    ('let numbers = [3, 1, 2]\nnumbers.sort()',
     'ERROR'),
    ('let ch: Character = "a"\nlet s3 = ch + "b"',
     'ERROR'),
    ('struct Item { var name: String; var qty: Int }\nvar cart = [Item(name: "a", qty: 1), Item(name: "b", qty: 2)]\ncart[0].qty += 5\nfor i in cart.indices { cart[i].qty *= 2 }\nvar copy = cart\ncopy[1].name = "z"\nprint(cart.map { "\\($0.name)x\\($0.qty)" }, copy[1].name)\nprint(cart.first(where: { $0.qty > 10 })?.name ?? "none")',
     '["ax12", "bx4"] z\na'),
    ('class Player { var score = 0; let name: String; init(name: String) { self.name = name } }\nlet team = [Player(name: "A"), Player(name: "B")]\nfor p in team { p.score += 10 }\nteam[1].score += 5\nprint(team.map { $0.score }, team.reduce(0) { $0 + $1.score })\nlet top = team.max(by: { $0.score < $1.score })!\nprint(top.name, top === team[1])',
     '[10, 15] 25\nB true'),
    ('class Shape {\n    let name: String\n    init(name: String) { self.name = name }\n    func area() -> Double { 0 }\n    func describe() -> String { "\\(name) with area \\(area())" }\n}\nclass Circle: Shape {\n    let r: Double\n    init(r: Double) { self.r = r; super.init(name: "circle") }\n    override func area() -> Double { 3.14 * r * r }\n}\nclass Square: Shape {\n    let s: Double\n    init(s: Double) { self.s = s; super.init(name: "square") }\n    override func area() -> Double { s * s }\n}\nlet shapes: [Shape] = [Circle(r: 1), Square(s: 2)]\nfor s in shapes { print(s.describe()) }\nprint(shapes.map { $0.area() }.reduce(0, +))\nlet circles = shapes.compactMap { $0 as? Circle }\nprint(circles.count, shapes.filter { $0 is Square }.count)',
     'circle with area 3.14\nsquare with area 4.0\n7.140000000000001\n1 1'),
    ('let values: [Int?] = [1, nil, 3, nil]\nfor case let v? in values { print(v) }\nvar count = 0\nfor v in values where v != nil { count += 1 }\nprint(count)\nlet mixed: [Any] = [1, "two", 3.0, true]\nfor m in mixed {\n    switch m {\n    case let i as Int: print("int", i)\n    case let s as String: print("string", s)\n    case is Double: print("double")\n    default: print("other")\n    }\n}',
     '1\n3\n2\nint 1\nstring two\ndouble\nother'),
    ('let n = 5\nswitch n {\ncase 5:\n    print("five")\n    fallthrough\ncase 6:\n    print("six-ish")\ndefault:\n    print("other")\n}\nlet pair = (2, "b")\nif case (2, let s) = pair { print("matched", s) }\nguard case let (x, y) = pair else { fatalError() }\nprint(x, y)',
     'five\nsix-ish\nmatched b\n2 b'),
    ('print((1, "b") < (1, "c"), (2, 0) > (1, 9), "apple" < "banana", "Z" < "a")\nprint(max("pear", "apple"), min(3.5, 2), [3, 1, 2].min(by: >)!)\nprint(String(describing: 42), String(describing: [1]), 42.description, true.description)\nprint(String(5) + String(2.5) + String(true) + String("x"))\nprint(Character("A") < Character("B"), "a" == "a")',
     'true true true true\npear 2.0 3\n42 [1] 42 true\n52.5truex\ntrue true'),
    ('for i in stride(from: 10, through: 0, by: -5) { print(i, terminator: " ") }\nprint()\nfor (i, x) in ["a", "b", "c"].enumerated().reversed() { print(i, x, terminator: "|") }\nprint()\nlet z3 = zip(zip([1, 2], ["a", "b"]), [true, false]).map { "\\($0.0)\\($0.1)\\($1)" }\nprint(z3)\nprint(Array(zip([1, 2, 3], [4, 5])))\nprint(Array(stride(from: 0, to: 1, by: 0.25)))',
     '10 5 0 \n2 c|1 b|0 a|\n["1atrue", "2bfalse"]\n[(1, 4), (2, 5)]\n[0.0, 0.25, 0.5, 0.75]'),
    ('enum Op: String, CaseIterable {\n    case add = "+", sub = "-", mul = "*"\n    func apply(_ a: Int, _ b: Int) -> Int {\n        switch self {\n        case .add: return a + b\n        case .sub: return a - b\n        case .mul: return a * b\n        }\n    }\n    static func from(_ s: String) -> Op? { Op(rawValue: s) }\n    var symbol: String { rawValue }\n}\nfor op in Op.allCases { print("3 \\(op.symbol) 4 =", op.apply(3, 4)) }\nprint(Op.from("*")?.apply(6, 7) ?? 0, Op.from("/") == nil)\nprint(Op.add, Op.mul.rawValue, Op.allCases)',
     '3 + 4 = 7\n3 - 4 = -1\n3 * 4 = 12\n42 true\nadd * [main.Op.add, main.Op.sub, main.Op.mul]'),
    ('protocol Container {\n    var items: [Int] { get set }\n    mutating func add(_ x: Int)\n}\nextension Container {\n    mutating func add(_ x: Int) { items.append(x) }\n    var total: Int { items.reduce(0, +) }\n}\nstruct Bag: Container { var items: [Int] = [] }\nvar bag = Bag()\nbag.add(3); bag.add(4)\nprint(bag.items, bag.total)',
     '[3, 4] 7'),
    ('func makeMultiplier(_ m: Int) -> (Int) -> Int { { $0 * m } }\nlet triple = makeMultiplier(3)\nprint(triple(5), makeMultiplier(2)(8))\nvar funcs: [String: (Int, Int) -> Int] = ["+": (+), "max": { max($0, $1) }]\nprint(funcs["+"]!(2, 3), funcs["max"]?(4, 9) ?? 0)\nlet ops: [(Int) -> Int] = [{ $0 + 1 }, { $0 * 10 }]\nprint(ops.reduce(5) { acc, f in f(acc) })',
     '15 16\n5 9\n60'),
    ('var log: [String] = []\nfunc record(_ s: String) { log.append(s) }\nrecord("a"); record("b")\nprint(log, log.count)\nvar grid = [[Int]](repeating: [Int](repeating: 0, count: 3), count: 3)\nfor i in 0..<3 { grid[i][i] = 1 }\nprint(grid)\nfor row in grid { print(row.map(String.init).joined(separator: " ")) }',
     '["a", "b"] 2\n[[1, 0, 0], [0, 1, 0], [0, 0, 1]]\n1 0 0\n0 1 0\n0 0 1'),
    ('let sentence = "the quick brown fox jumps over the lazy dog"\nlet wordsArr = sentence.split(separator: " ").map(String.init)\nvar freq: [String: Int] = [:]\nfor w in wordsArr { freq[w, default: 0] += 1 }\nprint(freq["the"]!, freq.count, wordsArr.max(by: { $0.count < $1.count })!)\nlet caps = wordsArr.map { $0.prefix(1).uppercased() + $0.dropFirst() }.joined(separator: " ")\nprint(caps)\nprint(Set(sentence.filter { $0 != " " }).count)\nprint(sentence.count, sentence.filter { $0 == "o" }.count)',
     '2 8 quick\nThe Quick Brown Fox Jumps Over The Lazy Dog\n26\n43 4'),
    ('var balance = 100\nfunc spend(_ amt: Int) -> Bool {\n    guard amt <= balance else { return false }\n    balance -= amt\n    return true\n}\nprint(spend(30), spend(80), balance)\nlet results = [10, 20, 100].map(spend)\nprint(results, balance)',
     'true false 70\n[true, true, false] 40'),
    ('let maybe: Int? = 4\nswitch maybe {\ncase .some(let v) where v > 3: print("big", v)\ncase .some(let v): print("small", v)\ncase .none: print("nothing")\n}\nlet other: String? = nil\nswitch other {\ncase let s?: print(s)\ncase nil: print("nil!")\n}',
     'big 4\nnil!'),
    ('enum Suit: String, CaseIterable { case hearts = "♥", spades = "♠" }\nstruct Card: Hashable { let rank: Int; let suit: Suit }\nlet deck = Suit.allCases.flatMap { s in (1...2).map { Card(rank: $0, suit: s) } }\nprint(deck.count, deck[1].suit.rawValue, deck.map { "\\($0.rank)\\($0.suit.rawValue)" })\nvar seen: Set<Card> = []\nseen.insert(Card(rank: 1, suit: .hearts))\nseen.insert(Card(rank: 1, suit: .hearts))\nprint(seen.count, seen.contains(Card(rank: 1, suit: .hearts)))\nvar bySuit: [Suit: Int] = [:]\nfor c in deck { bySuit[c.suit, default: 0] += c.rank }\nprint(bySuit[.hearts]!, bySuit[.spades]!)',
     '4 ♥ ["1♥", "2♥", "1♠", "2♠"]\n1 true\n3 3'),
    ('enum Token: Equatable { case num(Int), plus, word(String) }\nlet toks: [Token] = [.num(1), .plus, .num(2)]\nprint(toks.contains(.plus), toks[0] == .num(1), toks[0] == .num(2), toks.firstIndex(of: .num(2))!)\nprint(toks)',
     'true true false 2\n[main.Token.num(1), main.Token.plus, main.Token.num(2)]'),
    ('print("🍌".count, "héllo".count, "👍🏽".count, "🇯🇵".count, Array("a🍌b").count)\nprint("🍌🍌".reversed().count, "ñ".uppercased())',
     '1 5 1 1 3\n2 Ñ'),
    ('let a: Any = 5\nlet n = a as! Int\nprint(n + 1)\nlet s = a as? String\nprint(s as Any)\nlet bad = a as! String\nprint(bad)',
     'CRASH'),
    ('struct Counter { var n = 0; mutating func inc() { n += 1 } }\nfunc bump(_ c: inout Counter, times: Int) { for _ in 0..<times { c.inc() } }\nvar c1 = Counter()\nbump(&c1, times: 3)\nvar c2 = c1\nc2.inc()\nprint(c1.n, c2.n)\nvar arrC = [Counter(), Counter()]\narrC[0].inc()\nbump(&arrC[1], times: 2)\nprint(arrC.map(\\.n))',
     '3 4\n[1, 2]'),
    ('let scores = ["Mo": 82, "Kiki": 95, "Zed": 67]\nlet ranked = scores.sorted { $0.value > $1.value }\nfor (i, entry) in ranked.enumerated() { print(i + 1, entry.key, entry.value) }\nlet passed = scores.filter { $0.value >= 70 }.keys.sorted()\nprint(passed, scores.values.max()!, scores.min { $0.value < $1.value }!.key)\nlet total = scores.values.reduce(0, +)\nprint("Average: \\(Double(total) / Double(scores.count))")\nprint(scores.mapValues { $0 >= 70 ? "pass" : "fail" }["Zed"]!)\nprint(scores.keys.contains("Mo"), scores["Nope", default: 0])',
     '1 Kiki 95\n2 Mo 82\n3 Zed 67\n["Kiki", "Mo"] 95 Zed\nAverage: 81.33333333333333\nfail\ntrue 0'),
    ('class Node2 {\n    let val: Int\n    var children: [Node2] = []\n    init(_ v: Int) { val = v }\n    func add(_ c: Node2) -> Node2 { children.append(c); return self }\n    func sum() -> Int { val + children.reduce(0) { $0 + $1.sum() } }\n    func depth() -> Int { 1 + (children.map { $0.depth() }.max() ?? 0) }\n}\nlet root = Node2(1).add(Node2(2).add(Node2(4))).add(Node2(3))\nprint(root.sum(), root.depth(), root.children.count)',
     '10 3 2'),
    ('var text = "Hello"\ntext.insert("!", at: text.endIndex)\nprint(text)',
     'Hello!'),
    ('let w = "Swift"\nprint(w[w.startIndex], w[w.index(after: w.startIndex)], w[w.index(w.startIndex, offsetBy: 2)])\nprint(w.firstIndex(of: "f").map { w.distance(from: w.startIndex, to: $0) } ?? -1)\nprint(String(w[w.startIndex..<w.index(w.startIndex, offsetBy: 3)]))',
     'S w i\n3\nSwi'),
    ('let nums = [1, 2, 3, 4, 5, 6]\nlet (evens, odds) = nums.reduce(into: ([Int](), [Int]())) { acc, x in\n    if x % 2 == 0 { acc.0.append(x) } else { acc.1.append(x) }\n}\nprint(evens, odds)\nprint(nums.split(whereSeparator: { $0 % 3 == 0 }).map(Array.init))',
     '[2, 4, 6] [1, 3, 5]\n[[1, 2], [4, 5]]'),
    ('let x = [1, 2, 3].lazy.map { $0 * 2 }\nprint(Array(x))',
     '[2, 4, 6]'),
    ('protocol P { associatedtype T; func get() -> T }\nstruct S: P { func get() -> Int { 1 } }\nprint(S().get())',
     '1'),
    ('indirect enum Expr { case num(Int); case add(Expr, Expr) }\nfunc eval(_ e: Expr) -> Int { switch e { case .num(let n): return n; case .add(let a, let b): return eval(a) + eval(b) } }\nprint(eval(.add(.num(1), .add(.num(2), .num(3)))))',
     '6'),
    ('var dict = [String: [String]]()\ndict["a", default: []].append("x")\ndict["a"]?.append("y")\nprint(dict)',
     '["a": ["x", "y"]]'),
    ('let opt: [Int]? = [1, 2]\nprint(opt?.count ?? 0, opt?.first ?? 0, opt?[1] ?? 0)',
     '2 1 2'),
    ('struct P2 { var x: Int; static let origin = P2(x: 0) }\nprint(P2.origin.x)',
     '0'),
    ('let closure: () -> Void = { print("called") }\nclosure()\nlet unused = { (a: Int, b: Int) -> Int in a + b }(2, 3)\nprint(unused)',
     'called\n5'),
    ('func greet(_ names: String...) { for n in names { print("Hi", n) } }\ngreet("a", "b")',
     'Hi a\nHi b'),
    ('let t = (x: 1, y: 2)\nlet (x2, _) = t\nprint(x2, t.y)',
     '1 2'),
    ('var arr = [5, 3]\narr[0...1] = [1, 2]\nprint(arr)',
     '[1, 2]'),
    ('extension Array where Element == Int { func total() -> Int { reduce(0, +) } }\nprint([1, 2, 3].total())',
     '6'),
    ('let s = "abc"\nfor (i, c) in s.enumerated() where i > 0 { print(c) }\nprint(s.map { $0.uppercased() }.joined())',
     'b\nc\nABC'),
    ('var x3 = 0\nwhile x3 < 1_000_000 { x3 += 1 }\nprint(x3)',
     '1000000'),
    ('let numbers = Array(1...10)\nlet sumSq = numbers.map { $0 * $0 }.reduce(0, +)\nprint(sumSq, numbers.filter { $0.isMultiple(of: 3) })',
     '385 [3, 6, 9]'),
    ('func depth(_ n: Int) -> Int { n == 0 ? 0 : 1 + depth(n - 1) }\nprint(depth(1000))\nfunc countDown(_ n: Int) -> Int {\n    if n == 0 { return 0 }\n    return 1 + countDown(n - 1)\n}\nprint(countDown(1000))',
     '1000\n1000'),
    ('struct Walker {\n    func walk(_ n: Int) -> Int {\n        if n == 0 { return 0 }\n        return 1 + walk(n - 1)\n    }\n}\nprint(Walker().walk(1000))',
     '1000'),
    ('func sumTo(_ n: Int) -> Int {\n    guard n > 0 else { return 0 }\n    return n + sumTo(n - 1)\n}\nprint(sumTo(1000))',
     '500500'),
    ('func forever(_ n: Int) -> Int { forever(n + 1) }\nprint(forever(0))',
     'CRASH'),
    ('var spins = 0\nwhile true {\n    spins += 1\n    if spins == 50000 { break }\n}\nprint(spins)',
     '50000'),
    ('func fact(_ n: Int) -> Int { n <= 1 ? 1 : n * fact(n - 1) }\nprint(fact(20))\nprint(fact(21))',
     'CRASH'),
    ('let nums = [10, 20, 30]\nvar i = 0\nwhile i <= nums.count {\n    print(nums[i])\n    i += 1\n}',
     'CRASH'),
    ('let words = ["a": 1]\nlet n = words["b"]!\nprint(n)',
     'CRASH'),
    ('let text = "42x"\nlet value = Int(text)!\nprint(value)',
     'CRASH'),
    ('var stack: [Int] = []\nstack.append(1)\nprint(stack.removeLast())\nprint(stack.removeLast())',
     'CRASH'),
    ('let half = 7 / 2\nlet exact = 7.0 / 2\nlet mixed = Double(7) / 2\nprint(half, exact, mixed, 7 % 2, -7 / 2)\nprint(1 / 3.0, 2.0 / 3, 10.0 / 4, 1e-5, 123456789.0 * 1000)\nprint(0.1 + 0.2, 1.1 * 3, 100.0, Double(1) / 0, -1.0 / 0)\nprint(5.0, 5.5, -0.25, 3.0 * 2, 9.99)',
     '3 3.5 3.5 1 -3\n0.3333333333333333 0.6666666666666666 2.5 1e-05 123456789000.0\n0.30000000000000004 3.3000000000000003 100.0 inf -inf\n5.0 5.5 -0.25 6.0 9.99'),
    ('let temperature = 23.456\nprint((temperature * 10).rounded() / 10, Int(temperature), temperature.rounded())\nimport Foundation\nprint(String(format: "%.1f", temperature), String(format: "%05.2f", 3.14159), String(format: "%d%%", 50))\nprint(String(format: "%.0f", 2.5), String(format: "%.0f", 3.5), String(format: "%6.2f|", 1.5))',
     '23.5 23 23.0\n23.5 03.14 50%\n2 4   1.50|'),
    ('var a = [1, 2, 3]\nvar b = a\nb.append(4)\nprint(a, b)\nvar d1 = ["x": 1]\nvar d2 = d1\nd2["x"] = 9\nprint(d1, d2)',
     '[1, 2, 3] [1, 2, 3, 4]\n["x": 1] ["x": 9]'),
    ('let opt1: String? = "Mo"\nlet opt2: String? = nil\nprint(opt1 ?? "?", opt2 ?? "?", opt1!, opt1 as Any, opt2 as Any)\nprint("\\(opt1 ?? "none") and \\(opt2 ?? "none")")\nif let a = opt1, let b = opt2 { print(a, b) } else { print("one is missing") }\nprint(opt1.map { $0.count } ?? 0, opt2?.isEmpty ?? true)',
     'Mo ? Mo Optional("Mo") nil\nMo and none\none is missing\n2 true'),
    ('print("Hello, Swift!"); print("I can code!")\nprint("Hello, Swift!\\nI can code!")',
     'Hello, Swift!\nI can code!\nHello, Swift!\nI can code!'),
    ('let name = "Mo"\nvar age = 4\nprint(name + " is " + String(age) + " years old")\nprint("\\(name) is \\(age) years old")',
     'Mo is 4 years old\nMo is 4 years old'),
    ('let a = 90\nlet b = 85\nlet c = 80\nlet avg = Double(a + b + c) / 3\nprint(avg)\nprint(Double(a + b + c) / 3.0)\nprint((Double(a) + Double(b) + Double(c)) / 3)',
     '85.0\n85.0\n85.0'),
    ('let n = 14\nprint(n % 2 == 0)\nprint(n.isMultiple(of: 2))\nif n % 2 == 0 { print(true) } else { print(false) }',
     'true\ntrue\ntrue'),
    ('let word = "banana"\nprint(word.uppercased() + "!")\nprint("\\(word.uppercased())!")\nprint(word.count)',
     'BANANA!\nBANANA!\n6'),
    ('let text = "hello world"\nvar vowels = 0\nfor ch in text {\n    if "aeiou".contains(ch) { vowels += 1 }\n}\nprint(vowels)\nprint(text.filter { "aeiou".contains($0) }.count)\nvar v2 = 0\nfor ch in text {\n    switch ch {\n    case "a", "e", "i", "o", "u": v2 += 1\n    default: break\n    }\n}\nprint(v2)',
     '3\n3\n3'),
    ('let score = 72\nif score >= 90 {\n    print("A")\n} else if score >= 80 {\n    print("B")\n} else if score >= 70 {\n    print("C")\n} else {\n    print("Try again")\n}\nswitch score {\ncase 90...: print("A")\ncase 80..<90: print("B")\ncase 70..<80: print("C")\ndefault: print("Try again")\n}',
     'C\nC'),
    ('let height = 130\nlet age2 = 7\nprint(height >= 120 && age2 >= 8 ? "Ride on!" : "Sorry")\nif height >= 120, age2 >= 8 { print("Ride on!") } else { print("Sorry") }',
     'Sorry\nSorry'),
    ('let day = 6\nswitch day {\ncase 6: print("Saturday")\ncase 7: print("Sunday")\ncase 1...5: print("Weekday")\ndefault: print("Not a day")\n}',
     'Saturday'),
    ('for i in (1...5).reversed() { print(i) }\nprint("Liftoff!")\nfor i in stride(from: 5, through: 1, by: -1) { print(i) }\nvar k = 5\nwhile k > 0 { print(k); k -= 1 }\nprint("Liftoff!")',
     '5\n4\n3\n2\n1\nLiftoff!\n5\n4\n3\n2\n1\n5\n4\n3\n2\n1\nLiftoff!'),
    ('let t = 3\nfor i in 1...5 { print("\\(t) x \\(i) = \\(t * i)") }\nfor i in 1...5 { print(t, "x", i, "=", t * i) }',
     '3 x 1 = 3\n3 x 2 = 6\n3 x 3 = 9\n3 x 4 = 12\n3 x 5 = 15\n3 x 1 = 3\n3 x 2 = 6\n3 x 3 = 9\n3 x 4 = 12\n3 x 5 = 15'),
    ('var bananas = 1\nvar days = 0\nwhile bananas < 100 { bananas *= 2; days += 1 }\nprint(days)\nvar b2 = 1, d2 = 0\nrepeat { b2 = b2 * 2; d2 += 1 } while b2 < 100\nprint(d2)',
     '7\n7'),
    ('let limit = 15\nfor i in 1...limit {\n    if i % 15 == 0 { print("FizzBuzz") }\n    else if i % 3 == 0 { print("Fizz") }\n    else if i % 5 == 0 { print("Buzz") }\n    else { print(i) }\n}',
     '1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz'),
    ('for i in 1...15 {\n    var out = ""\n    if i % 3 == 0 { out += "Fizz" }\n    if i % 5 == 0 { out += "Buzz" }\n    print(out.isEmpty ? String(i) : out)\n}',
     '1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz'),
    ('let secret = 7\nlet guesses = [3, 9, 7, 2]\nvar tries = 0\nfor g in guesses {\n    tries += 1\n    if g < secret { print("Too low") }\n    else if g > secret { print("Too high") }\n    else { print("Got it in \\(tries) tries!"); break }\n}\nfor (i, g) in guesses.enumerated() {\n    if g == secret { print("Got it in \\(i + 1) tries!"); break }\n}',
     'Too low\nToo high\nGot it in 3 tries!\nGot it in 3 tries!'),
    ('var guests = ["Ava", "Mo"]\nguests.append("Leo")\nguests += ["Kai"]\nguests.remove(at: 0)\nguests.removeAll { $0 == "Mo" }\nprint(guests.count)\nfor g in guests { print(g) }\nguests.forEach { print($0) }',
     '2\nLeo\nKai\nLeo\nKai'),
    ('let temps = [18, 22, 23]\nlet total = temps.reduce(0, +)\nprint(Double(total) / Double(temps.count))\nvar sum = 0\nfor x in temps { sum += x }\nprint(Double(sum) / Double(temps.count))',
     '21.0\n21.0'),
    ('let words = "ook eek ook ook".split(separator: " ")\nvar counts: [String: Int] = [:]\nfor w in words { counts[String(w), default: 0] += 1 }\nprint("ook: \\(counts["ook"]!)")\nprint("eek: \\(counts["eek"] ?? 0)")\nvar c2 = [Substring: Int]()\nfor w in words { c2[w] = (c2[w] ?? 0) + 1 }\nprint(c2["ook"]!, c2["eek"]!)',
     'ook: 3\neek: 1\n3 1'),
    ('let visits = ["Mo", "Kiki", "Mo", "Bao", "Kiki"]\nlet unique = Set(visits)\nprint(unique.count)\nprint(unique.sorted())\nprint(Array(unique).sorted())',
     '3\n["Bao", "Kiki", "Mo"]\n["Bao", "Kiki", "Mo"]'),
    ('func triple(_ n: Int) -> Int { n * 3 }\nprint(triple(4))\nprint(triple(10))\nfunc triple2(_ n: Int) -> Int {\n    let r = n * 3\n    return r\n}\nprint(triple2(4), triple2(10))',
     '12\n30\n12 30'),
    ('func toFahrenheit(celsius: Double) -> Double { celsius * 9 / 5 + 32 }\nprint(toFahrenheit(celsius: 100))\nprint(toFahrenheit(celsius: -40))\nfunc toF(_ c: Double) -> Double { return c * 9.0 / 5.0 + 32.0 }\nprint(toF(100), toF(-40), toF(37))',
     '212.0\n-40.0\n212.0 -40.0 98.6'),
    ('let prices = [2, 15, 7]\nprint(prices.map { "$\\($0)" })\nprint(prices.map { "$" + String($0) })\nlet tags = prices.map { p in "$\\(p)" }\nprint(tags)',
     '["$2", "$15", "$7"]\n["$2", "$15", "$7"]\n["$2", "$15", "$7"]'),
    ('let scores = [65, 97, 12, 88, 51, 40]\nprint(scores.sorted(by: >).filter { $0 >= 50 })\nprint(scores.filter { $0 >= 50 }.sorted { $0 > $1 })\nprint(scores.sorted().reversed().filter { $0 >= 50 })',
     '[97, 88, 65, 51]\n[97, 88, 65, 51]\n[97, 88, 65, 51]'),
    ('let inputs = ["4", "abc", "10"]\nfor s in inputs {\n    if let n = Int(s) { print(n * 2) } else { print("skip") }\n}\nfor s in inputs {\n    guard let n = Int(s) else { print("skip"); continue }\n    print(n * 2)\n}\nprint(inputs.compactMap { Int($0) }.reduce(0, +))\nprint(inputs.compactMap(Int.init).map { $0 * 2 })',
     '8\nskip\n20\n8\nskip\n20\n14\n[8, 20]'),
    ('struct Rect {\n    var w: Int\n    var h: Int\n    var area: Int { w * h }\n    var perimeter: Int { return 2 * (w + h) }\n}\nlet r = Rect(w: 3, h: 4)\nprint(r.area)\nprint(r.perimeter)',
     '12\n14'),
    ('struct Hero {\n    var hp = 100\n    mutating func hit(_ d: Int) { hp = max(0, hp - d) }\n    mutating func heal(_ a: Int) { hp = min(100, hp + a) }\n}\nvar h = Hero()\nh.hit(30); print(h.hp)\nh.heal(50); print(h.hp)\nh.hit(500); print(h.hp)\nstruct Hero2 {\n    var hp = 100\n    mutating func hit(_ d: Int) { hp -= d; if hp < 0 { hp = 0 } }\n}\nvar h2 = Hero2()\nh2.hit(150)\nprint(h2.hp)',
     '70\n100\n0\n0'),
    ('class Employee {\n    let name: String\n    let salary: Int\n    init(name: String, salary: Int) { self.name = name; self.salary = salary }\n    func pay() -> Int { salary }\n}\nclass Manager: Employee {\n    override func pay() -> Int { super.pay() + 500 }\n}\nlet staff: [Employee] = [Employee(name: "Ava", salary: 3000), Manager(name: "Leo", salary: 4000)]\nfor e in staff { print("\\(e.name): \\(e.pay())") }',
     'Ava: 3000\nLeo: 4500'),
    ('enum Light {\n    case green, yellow, red\n    func next() -> Light {\n        switch self {\n        case .green: .yellow\n        case .yellow: .red\n        case .red: .green\n        }\n    }\n}\nvar l = Light.green\nfor _ in 1...4 { l = l.next(); print(l) }',
     'yellow\nred\ngreen\nyellow'),
    ('enum AgeError: Error { case negative }\nstruct Person {\n    var age = 0\n    mutating func setAge(_ a: Int) throws {\n        guard a >= 0 else { throw AgeError.negative }\n        age = a\n    }\n}\nvar p = Person()\ndo {\n    try p.setAge(12)\n    print("Age set to \\(p.age)")\n    try p.setAge(-1)\n} catch AgeError.negative {\n    print("Age can\'t be negative")\n} catch {\n    print("other")\n}',
     "Age set to 12\nAge can't be negative"),
    ('enum BankError: Error { case notEnoughMoney }\nclass Account {\n    var balance = 50\n    func withdraw(_ amt: Int) throws {\n        if amt > balance { throw BankError.notEnoughMoney }\n        balance -= amt\n    }\n}\nlet acc = Account()\ndo { try acc.withdraw(80) } catch { print("Not enough money") }\ntry? acc.withdraw(30)\nprint(acc.balance)',
     'Not enough money\n20'),
    ('let pets = ["Rex", "Bun", "Mittens"]\nvar list = pets\nif let i = list.firstIndex(of: "Bun") { list.remove(at: i) }\nprint(list, list.contains("Bun"))\nlist.removeAll(where: { $0 == "Rex" })\nprint(list)',
     '["Rex", "Mittens"] false\n["Mittens"]'),
    ('let a = 90, b = 85, c = 80\nprint((a + b + c) / 3)',
     '85'),
    ('let a = 90, b = 85, c = 80\nprint(Double((a + b + c) / 3))',
     '85.0'),
    ('let a = 90\nprint(a / 3.0)',
     'ERROR'),
    ('let word = "banana"\nprint(word.uppercase() + "!")',
     'ERROR'),
    ('let word = "banana"\nprint(word.length)',
     'ERROR'),
    ('let word = "banana"\nprint(word.count())',
     'ERROR'),
    ('let text = "hello"\nprint(text[0])',
     'ERROR'),
    ('var guests = ["Ava"]\nguests.add("Leo")',
     'ERROR'),
    ('var guests = ["Ava"]\nguests.push("Leo")',
     'ERROR'),
    ('let n = 5\nif n % 2 { print("odd") }',
     'ERROR'),
    ('let score = 72\nif score >= 90 print("A")',
     'ERROR'),
    ('func triple(n: Int) -> Int { n * 3 }\nprint(triple(4))',
     'ERROR'),
    ('func triple(_ n: Int) -> Int { n * 3 }\nprint(triple(n: 4))',
     'ERROR'),
    ('func triple(_ n: Int) { return n * 3 }',
     'ERROR'),
    ('let x = 5\nprint("Value: \\(x")',
     'ERROR'),
    ('let names = ["a", "b"]\nfor i in 0...names.count { print(names[i]) }',
     'CRASH'),
    ('var count: Int\ncount += 1',
     'ERROR'),
    ('let s: String = 5',
     'ERROR'),
    ('var arr = [1, 2]\narr[2] = 3',
     'CRASH'),
    ('let d = ["a": 1]\nprint(d["a"] + 1)',
     'ERROR'),
    ('let t = "5"\nprint(t + 5)',
     'ERROR'),
    ('let opt: Int? = 5\nprint(opt * 2)',
     'ERROR'),
    ('struct P { var x: Int }\nlet p = P(x: "one")',
     'ERROR'),
    ('struct P { var x: Int; var y: Int }\nlet p = P(y: 1, x: 2)',
     'ERROR'),
    ('class Dog { var name: String }',
     'ERROR'),
    ('let m = [1, 2, 3].map { $0 * 2 }\nm.append(4)',
     'ERROR'),
    ('print(Int("abc")!)',
     'CRASH'),
    ('let e: [Int] = []\nprint(e[0])',
     'CRASH'),
    ('let e: [Int] = []\nprint(e.first!)',
     'CRASH'),
    ('var x = 1\nvar x = 2',
     'ERROR'),
    ('let pi = 3.14\npi = 3.0',
     'ERROR'),
    ('enum Dir { case up, down }\nlet d = Dir.up\nswitch d {\ncase .up: print("up")\n}',
     'ERROR'),
    ('print("a" == \'a\')',
     'ERROR'),
    ('let price = 9.99\nlet qty = 3\nprint(price * qty)',
     'ERROR'),
    ('let total = 10\nlet avg: Double = total / 4',
     'ERROR'),
    ('let total = 10\nprint(Double(total / 4), Double(total) / 4)',
     '2.0 2.5'),
    ('let names = ["Mo", "Kiki"]\nprint(names.sort())',
     'ERROR'),
    ('var names = ["Mo", "Kiki"]\nnames.sort()\nprint(names)\nlet sorted = names.sorted()\nprint(sorted == names)',
     '["Kiki", "Mo"]\ntrue'),
    ('func f(_ x: Int) -> Int {\n    if x > 0 { return 1 }\n}\nprint(f(1))',
     'ERROR'),
    ('var i = 0\nrepeat { i += 1 } while i < 3\nprint(i)',
     '3'),
    ('for i in 0..<0 { print(i) }\nprint("none")',
     'none'),
    ('let r = 5..<1',
     'CRASH'),
    ('let arr = [3, 1, 2]\nprint(arr.max(), arr.min()!, arr.sorted().first)',
     'Optional(3) 1 Optional(1)'),
]


def load():
    files = ["javascript-units-1-2.js", "swift.js"]
    src = "\n".join((ROOT / "src" / "courses" / f).read_text() for f in files)
    js = src + "\nconsole.log(JSON.stringify(COURSE_SWIFT,(k,v)=>v instanceof RegExp?{re:v.source}:v));"
    return json.loads(subprocess.run(["node", "-"], input=js, capture_output=True, text=True, check=True).stdout)


def run_all(codes):
    script = (ROOT / "src" / "engines" / "swift.js").read_text() + """
const I=JSON.parse(require('fs').readFileSync(0,'utf8'));
console.log(JSON.stringify(I.map(c=>TMSwift.run(c))));"""
    tmp = ROOT / "tests" / ".swift-tmc.js"
    tmp.write_text(script)
    try:
        r = subprocess.run(["node", str(tmp)], input=json.dumps(codes), capture_output=True, text=True)
        if r.returncode:
            print(r.stderr[-3000:])
            sys.exit(1)
        return json.loads(r.stdout)
    finally:
        tmp.unlink()


def lines(out):
    l = str(out).split("\n")
    if l and l[-1] == "":
        l.pop()
    return l


def flat(out):
    return " ".join(x.strip() for x in lines(out) if x.strip())


def js_re(src):
    return re.compile(src.replace("\\/", "/"))


def collect():
    """Every Swift program the course and EXTRA contain, as (where, code, check)."""
    course = load()
    jobs = []  # (where, code, check)
    for unit in course["units"]:
        for l in unit["lessons"]:
            lid = l["id"]
            for code, opts in l.get("pool", []):
                jobs.append((f"{lid} game", code, ("flat", opts[0])))
                if len(set(opts)) != len(opts):
                    print(f"✖ {lid} game: duplicate options {opts}")
            for i, s in enumerate(l["steps"]):
                w = f"{lid} step {i}"
                if s["type"] == "talk" and s.get("demo"):
                    jobs.append((w + " demo", s["demo"], ("crash-ok",) if lid in INTENTIONAL_CRASH else ("runs",)))
                if s["type"] == "quiz" and s.get("code") and "does this print" in s["q"]:
                    jobs.append((w + " quiz", s["code"], ("flat", s["opts"][s["a"]])))
                if s["type"] in ("fill", "order"):
                    code = re.sub(r"\[(\d)\]", lambda m: s["blanks"][int(m.group(1))], s["code"]) if s["type"] == "fill" else "\n".join(s["lines"])
                    jobs.append((w + " " + s["type"], code, ("lines", s["out"].split("\n")) if s.get("out") else ("runs",)))
                if s["type"] == "code":
                    jobs.append((w + " answer", s["hint"], ("lines", s["out"])))
                    jobs.append((w + " starter", s["start"], ("not", s["out"])))
                    for j, (pat, rep, outs) in enumerate(s.get("variants", [])):
                        code, n = js_re(pat["re"]).subn(rep.replace("\\", "\\\\"), s["hint"], count=1)
                        if not n:
                            print(f"✖ {w} variant {j}: pattern doesn't match the answer")
                        jobs.append((f"{w} variant {j}", code, ("lines", outs)))
    for name, cases in (("extra", EXTRA), ("real", REAL)):
        for i, (code, exp) in enumerate(cases):
            jobs.append((f"{name} {i}", code, ("error",) if exp == "ERROR" else ("crash",) if exp == "CRASH" else ("lines", exp.split("\n"))))
    return jobs


def main():
    jobs = collect()
    results = run_all([c for _, c, _ in jobs])
    problems = []
    for (w, code, chk), r in zip(jobs, results):
        out, err = r["out"], r["error"]
        kind = chk[0]
        bad = None
        if kind == "flat":
            if err or flat(out) != chk[1]:
                bad = f"expected {chk[1]!r}, got {flat(out)!r} {err or ''}"
        elif kind == "lines":
            if err or lines(out) != chk[1]:
                bad = f"expected {chk[1]!r}, got {lines(out)!r} {err or ''}"
        elif kind == "runs":
            if err:
                bad = f"error: {err}"
        elif kind == "crash-ok":
            if err and not err.startswith("Fatal error"):
                bad = f"error: {err}"
        elif kind == "not":
            if not err and lines(out) == chk[1]:
                bad = "starter code already passes"
        elif kind == "error":
            if not err or not err.startswith("error"):
                bad = f"should be a compile error, got {lines(out)!r} {err or ''}"
        elif kind == "crash":
            if not err or not err.startswith("Fatal error"):
                bad = f"should crash, got {lines(out)!r} {err or ''}"
        if bad:
            problems.append(f"{w}: {bad}\n    {code[:220]!r}")
        elif VERBOSE:
            print(f"  ok {w}: {flat(out)[:70]!r} {err or ''}")
    for p in problems:
        print("✖", p)
    print(f"Swift: {len(jobs)} checks. {len(problems)} problem(s)")
    sys.exit(1 if problems else 0)


if __name__ == "__main__":
    main()
